### ISSUE TITLE
Add cancellation reason to holds delete endpoint - ksdev/ks-0013-bug-30660-holds-del-endpoint

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#1]
### Siirrettävä ominaisuus

Varauksen peruutuksen syyn lisääminen holds endpointiin.

**Comment by AnneliO** [comment]
Miten tätä voi testata? Onko tämä Koha-Suomen vai pääkäyttäjien testattavissa?

**Comment by ghost** [comment]
Jos varauksen peruutukselle pystyy antamaan syyn niin toimii.

**Comment by pknuuti** [comment]
Missä peruutuksen syyn voi antaa? Minä en hoksaa Vaaran tuotannossa enkä nextillä.

**Comment by ghost** [comment]
Peruutusnapista avautuvasta popupista.

**Comment by AnneliO** [comment]
Syyn valinta ei näy popparissa, jos auktorisoidussa arvossa HOLD_CANCELLATION ei ole yhtään arvoa. Testin vuoksi sinne voi lisätä jonkin arvon, niin alasvetovalikko tulee näkyviin peruutusnapin popuppiin.

**Comment by pknuuti** [comment]
Kiitos Anneli. Kun lisäsin noita arvoja, niin johan löytyi alasvetovalikkokin. Varauksen syyn valitseminen onnistui varausta peruutettaessa.

**Comment by sksandel** [comment]
Vaski-Nextillä testailin. 

Asiakkaan tiedoissa varaukset-välilehdelle tulee varauksen peruutuksen syy valittavaksi. Kun syyn valitsee ja peruu varauksen, varaus poistuu. En oikein ymmärrä mitä tällä toiminnolla tekee, kun varaus katoaa näkyvistä. Näitä syitä sitten katsottaisiin raportilla? En testannut, saako syyn jonnekin näkyviin. Varaus katoaa myös verkkokirjastosta, joten syytä ei sielläkään pysty tarkastelemaan.

Tietueen varaukset-sivulla varauksen poistossa on myös mahdollista valita peruutukselle syy, mutta kun valitsee syyn (tai ei valitse mitään) ja vahvistaa poiston, niin varaus pysyy ennallaan. Virheilmoitusta ei tule. Ei siis toimi oikein, mutta se ei liity peruutuksen syyn valintaan. Poistin tuon HOLD_CANCELLATION arvon ja varausta ei silti voi peruuttaa tietueen varausivulta. Varauksia ei myöskään voi päivittää tietueen varaukset-sivulla. Katson onko tästä jo tiketti, jos ei niin teen.

![Image](https://github.com/user-attachments/assets/17a5ced0-676c-4832-92fc-bd98a181ac06)

**Comment by LeenaKinnunen** [comment]
Lapin nextilä kokeilin, ja toimi toisin päin kuin Vaskissa? Sekä tietueen varaukset -sivulla että asiakkaan varauksissa voi valita varauksen peruutuksen syyn. Tietueen varaussivulla varaus poistuu oikein, mutta jos asiakkaan varauksissa valitsee peruutuksen syyn, varaus ei poistu, eikä tule virheilmoitustakaan. Tuotannossa meillä ei ole HOLD_CANCELLATION-arvoja käytössä. 
![image](https://github.com/user-attachments/assets/bec34c14-687a-45bd-b884-8260dedf949d)

**Comment by AnneliO** [comment]
> Tietueen varaukset-sivulla varauksen poistossa on myös mahdollista valita peruutukselle syy, mutta kun valitsee syyn (tai ei valitse mitään) ja vahvistaa poiston, niin varaus pysyy ennallaan. Virheilmoitusta ei tule. Ei siis toimi oikein, mutta se ei liity peruutuksen syyn valintaan. Poistin tuon HOLD_CANCELLATION arvon ja varausta ei silti voi peruuttaa tietueen varausivulta. Varauksia ei myöskään voi päivittää tietueen varaukset-sivulla. Katson onko tästä jo tiketti, jos ei niin teen.

Tästä on tiketti #111

**Comment by AnneliO** [comment]
> Lapin nextilä kokeilin, ja toimi toisin päin kuin Vaskissa? Sekä tietueen varaukset -sivulla että asiakkaan varauksissa voi valita varauksen peruutuksen syyn. Tietueen varaussivulla varaus poistuu oikein, mutta jos asiakkaan varauksissa valitsee peruutuksen syyn, varaus ei poistu, eikä tule virheilmoitustakaan. Tuotannossa meillä ei ole HOLD_CANCELLATION-arvoja käytössä. ![image](https://private-user-images.githubusercontent.com/99165331/356535516-bec34c14-687a-45bd-b884-8260dedf949d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTU5MzQsIm5iZiI6MTcyMzE5NTYzNCwicGF0aCI6Ii85OTE2NTMzMS8zNTY1MzU1MTYtYmVjMzRjMTQtNjg3YS00NWJkLWI4ODQtODI2MGRlZGY5NDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA5MjcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZjgyOGI5MzBhNmFlZGRhODYzNjVjNmYwNTNjZWM2MmQ0NzA0MWNlZmRlODUxM2NiZjZiMmJkZDAwZTkzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fFJwd-1PfV8QYV72waLtp64vE-A5_4BZiOVpqR2TjlE)

Klikkasitko tietueen varaussivulla Peruuta-nappia vai valitsit rivin ja sitten Peruuta valitut -nappi? Jälkimmäisen kautta varaus ei poistu, mutta ekalla vaihtoehdolla poistuu. Jälkimmäinen liittyy tuohon tikettiin #111.

**Comment by AnneliO** [comment]
Testasin lappi-nextillä tuota asiakkaan tiedoissa varauksen poistamista ja minulla se toimi, kunhan valitsin peruttavan varauksen kohdalta Poista?-valikosta Kyllä ja klikkasin sitten Peruuta valitut varaukset -nappia (ja valitsin syyn sitä ennen).

**Comment by LeenaKinnunen** [comment]
> Testasin lappi-nextillä tuota asiakkaan tiedoissa varauksen poistamista ja minulla se toimi, kunhan valitsin peruttavan varauksen kohdalta Poista?-valikosta Kyllä ja klikkasin sitten Peruuta valitut varaukset -nappia (ja valitsin syyn sitä ennen).

Jep, noinhan se toimii oikein. Eli meillä pystyy perumaan ja jättämään peruutuksen syyn molemmilla tavoilla.

**Comment by Kati-Helle** [comment]
Helle-nextissä varauksen peruminen syyn kera (tai ilman syytä) toimii asiakkaan varauksissa sekä tietueen varauksissa.

**Comment by pirliis** [comment]
OUTIn nextillä myös varauksen poisto syyn kera tai ilman, toimii asiakkaan varauksissa ja tietueen varausjonossa.

**Comment by emta001** [comment]
Vaikuttaisi toimivan, suljen tiketin.
