### ISSUE TITLE
UserJS checksumming ja BorrowerCategoryTimeout - ksdev/ks-0024-K23-14-auth-extra

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#10]
UserJS checksumming on ominaisuus, joka laskee mm. IntranetUserJS-järjestelmäasetuksen sisällölle tarkistussumman. Tietoturvaominaisuus.

BorrowerCategoryTimeout: Asiakastyyppikohtainen timeout, tehty Kohan itsepalvelulainausta (SCO:ta) varten.

**Comment by johannaraisa** [comment]
Tämä on tuotu nexteille, itsepalvelulainauksen aikakatkaisua voisi ainakin testata.

**Comment by pirliis** [comment]
OUTIssa testattu:
- automaatti-asiakastyypillä aikakatkaisua ei tullut työpäivän aikana eli oletettavasti toimii kuin pitääkin
- virkailija-asiakastyypille (superlibrarian) aikakatkaisu tuli noin 30 min kuluttua eli toimii varmaan kuin pitääkin
- lainaus- ja palautustilanteessa aikakatkaisu tuli 20 sekunnin kuluttua, jotka on määritelty SelfCheckTimeout- ja  SelfCheckInTimeout -järjestelmäasetuksissa.

**Comment by johannaraisa** [comment]
Testasin tuon checksummauksen, toimii edelleen. Suljen tiketi.
