### ISSUE TITLE
Pyydetty kuljetus rikkoo tietueen perustiedot-näytön nidelistan

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha-24.05#100]
### Mikä vikana?

Jos tietueella on nide, jolla on pyydetty, mutta lähettämätön kuljetus, jää nidelistan avaaminen jumiin käsitellään..-tilaan, kun kyseisen niteen tietoja yritetään ladata.

Bugzillassa näyttäisi olevan tiketti ja korjauskin jo asiaan: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36984

**Comment by emta001** [comment]
Yhteisön korjaus viety nexteille testattavaksi.

**Comment by emta001** [comment]
Testipläni:
1. Luo kokoelma (Työkalut -> Siirtokokoelmat).
2. Lisää kokoelmaan jokin nide.
3. Siirrä kokoelma.
4. Siirry sen tietueen Perustiedot-näytölle, jonka niteen lisäsit kokoelmaan.
=> Nidelistan tuli aueta normaalisti, kuljetettava olevan niteen Tila-sarakkeessa tulisi olla tieto kuljetuksesta.
![image](https://github.com/user-attachments/assets/4cf37d71-9579-4de5-b677-30a613696a2f)

**Comment by pknuuti** [comment]
Toimii Vaaran nextillä ihan kuten pitääkin.

**Comment by MikkoLiimatainen** [comment]
Toimii myös Vaskin nextillä kuten pitääkin.

Tuon siirtokokoelman lisäksi korjasi aiemmankin tapauksen, jossa kuljetukselta puuttui datesent-arvo. Tämä datesent oli ilmeisesti jäänyt puuttumaan palautuksen käsittelyssä ja sain vastaavan tilan tuotettua palauttamalla kuljetukseen menevän niteen ja sulkemalla välilehden palautuspopupin ollessa vielä auki. Käytännössä siis jätin kuljetuksen kuittaamatta, mutta kuljetusrivi on jo tuossa vaiheessa muodostunut ja jää vajaaksi, jos ei tee mitään valintaa.

**Comment by LeenaKinnunen** [comment]
Toimii oikein Lapin nextillä.

**Comment by emta001** [comment]
Toimii siis, suljen tiketin.
