### ISSUE TITLE
Tietueen niteet-sivun aukeaminen hidasta joissain tietueissa

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha-24.05#101]
### Mikä vikana?

Ainakin tietueen [4177619](https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4177619) niteet-sivun (99 nidettä) aukeaminen kestää pidempään, mitä pitäisi (n. 2 min 40 s) ja tietueen [4298398](https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4298398) niteet-sivu (256 nidettä) ei auennut ollenkaan.

Testasin vertailun vuoksi tietuetta [4271232](https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4271232), jossa on 503 nidettä ja sen niteet-sivun avaus ei kestänyt läheskään yhtä kauan (n. 1 min 30 s).

Ainakaan tietueen nidemäärästä ei siis vaikuttaisi olevan kysymys.

**Comment by emta001** [comment]
Tässä saattaisi olla kyse tietueeseen kohdistuvien aktiivisten lainojen määrästä. Niitä on esimerkki tietueilla seuraavasti:

4177619 = 78
4298398 = 177
4271232 = 37

Johanna tutkaili koodia ja näyttäisi sille, että siellä tehdään nyt useampi haku sisäkkäin mikä tietysti hidastaa hakua.

**Comment by emta001** [comment]
Tässä on varmaankin kaksi osatekijää. Niteitä on oltava paljon plus lainoja on oltava paljon. En saanut hidastelua toistumaan omilla testeillä tietueella, jossa on 30 nidettä ja ne kaikki ovat lainassa. Samoin 100 niteen tietue ilman lainoja aukeaa ongelmitta. Yritän tässä askarella tuohon tietueeseen ison määrän lainoja ja katsoa mitä käy.

**Comment by emta001** [comment]
En saanut tätä toistettua omilla testeillä. Tosin lainasin kyllä kaikki niteet yhdelle ja samalle käyttäjälle, ehkä sillä on vaikutusta.

**Comment by lmstrand** [comment]
Testasin äsken, niin kaksi ekaa tietuetta aukesi melkein välittömästi. Kotivinkkiä en saanut auki ollenkaan. Selaimessa virheitä:

![image](https://github.com/user-attachments/assets/7b56aea0-8588-4fa8-92e8-c1489aca90e6)

**Comment by AnneliO** [comment]
[Kotivinkissä ](https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4271232) minullakin tulee konsoliin virheilmoitus 

Uncaught TypeError: row._strings.item_type_id is undefined

**Comment by MikkoLiimatainen** [comment]
Kotivinkin ongelma löytyi kuvailupohjasta. Siellä oli itemtype.pl-liitännäinen käytössä, kun piti olla itemtypes auktorisoitu arvo.

Valitettavasti tuon korjaaminen ei auttanut latausaikaan. Arvioisin, että latausajat ovat edelleen samaa luokkaa kuin aloituksessa.

**Comment by lmstrand** [comment]
Nyt minulla aukesi Kotivinkki (https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4271232) saman tien parissa sekunnissa.

**Comment by AnneliO** [comment]
Kotivinkki avautuu nyt mulla noin 3 sekunnissa. Kauanko sulla Mikko menee?

**Comment by lmstrand** [comment]
Voisiko selaimen välimuisti/cache aiheuttaa näin kummallisia ongelmia? Mitä jos sen tyhjäämistä kokeilisi?

**Comment by AnneliO** [comment]
Kaikki esimerkkitietueet avautuu minulla parissa sekunnissa.

**Comment by MikkoLiimatainen** [comment]
1min 23 s näytti tällä kertaa menevän Kotivinkin niteet-sivun aukeamiseen. Ja tuon Tatun ja Patun niteet-sivu ei edelleen aukea ollenkaan.

**Comment by AnneliO** [comment]
Pystytkö Mikko kokeilemaan eri selaimilla/koneilla?

**Comment by MikkoLiimatainen** [comment]
Kokeilin chromella ja edgellä. Tulos oli jotakuinkin sama. Täytyy koittaa huomenna jollain toisella koneella.

**Comment by MikkoLiimatainen** [comment]
![Latausaika 2024-08-06 160859](https://github.com/user-attachments/assets/6531e96b-6859-4448-901c-deb962b17c26)
Odotellessa näyttää aikaa kuluvan.

**Comment by emta001** [comment]
@AnneliO @lmstrand testatasitteko siis sitä, että Niteet-näyttö aukeaa hitaasti? Tämä siis:

![image](https://github.com/user-attachments/assets/9ab6133b-d04c-4b0f-a2ac-4dcd5f66b079)

Tietueen Perustiedot-näytöllä oleva nidelistaus aukeaa kyllä nopeasti (kunhan kuvailupohjat on siivottu). Mutta tuo välilehti jää junnamaan.

**Comment by AnneliO** [comment]
Aaaaaaa, testataanpa uudelleen. :D

**Comment by lmstrand** [comment]
No enpä hoksannut tuota testata ja niinpä näkyy kestävän.

**Comment by AnneliO** [comment]
Pennut pelastavat salamatkustajan -tietueessa meni Niteet-välilehden latautumiseen 2,54 min.

**Comment by AnneliO** [comment]
Kokeilin outi-nextillä availla Niteet-välilehteä sellaisilta tietueilta, joissa on paljon niteitä, mutta en saanut toistettua ongelmaa siellä.

Esim. [Kodin kuvalehti 2023](https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/moredetail.pl?biblionumber=2278721&searchid=scs_1723012208658)

**Comment by johannaraisa** [comment]
Kysyin yhteisön Mattermostissa tästä ja tämä alkoi kiinnostaa muutamaa. Tein tiketin [yhteisöön](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37591).

**Comment by johannaraisa** [comment]
Nyt on viety korjaus nexteille, voi kokeilla.

**Comment by MikkoLiimatainen** [comment]
No nyt ei niteet-sivun lataus kestä enää kuin maksimissaan 20 sekuntia. Haeskelin lisää noita uusintoja sisältäviä tietueita ja kaikki näyttäisivät toimivan. Eli en enää saa toistettua ongelmaa.

**Comment by AnneliO** [comment]
[Kotivinkissä](https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/moredetail.pl?biblionumber=4271232) meni nyt n. 19 sekuntia Niteet-osion avautumiseen.

**Comment by johannaraisa** [comment]
Tätä on testattu myös yhteisössä ja menossa versioon 24.11. Suljen tiketin.
