### ISSUE TITLE
Bookings/Ennakkovaraukset -välilehden piilotus

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-24.05#103]
### Mikä vikana?

Lainaus- ja Tiedot -sivuilla on uusi Bookings/Ennakkovaraukset -välilehti, joka lienee turha suurimmalle osalle, joten sen voisi piilottaa.

![kuva](https://github.com/user-attachments/assets/92ff1f24-c8fb-4d5c-a0e8-bc547bce26c6)

**Comment by AnneliO** [comment]
Tällaisella IntranetUserCSS:ään lisättävällä rimpsulla välilehdet saa piiloon. En äkkiseltään hoksaa, että tuota bookings-tab -tunnistetta käytettäisiin muussa yhteydessä, mutta kannattaa vilkuilla, ettei muualla mene mitään ylimääräistä piiloon. Tarvittaessa tuon voi tarkentaa.

```
/* Piilota Bookings/Ennakkovaraukset -välilehti lainauksessa/tiedot-sivulla */
 a#bookings-tab { display: none; }
```

Jos edellinen piilottaa liikaa, niin tämä kohdistaa piilotuksen vain lainaus/tiedot-sivuille.

```
/* Piilota Bookings/Ennakkovaraukset -välilehti lainauksessa/tiedot-sivulla */
body#circ_circulation.circ a#bookings-tab { display: none; }
body#pat_moremember.pat a#bookings-tab { display: none; }
```

**Comment by pknuuti** [comment]
Testattu Vaaran nextillä toimivaksi. En ainakaan hoksannut, että ensimmäinen rimpsu olisi piilottanut mitään muuta kuin mitä pitikin.

**Comment by ajrajala** [comment]
Testattu molemmat rimpsut toimiviksi. Minäkään en keksi, missä ensimmäinen rimpsu olisi voinut piilottaa jotain ylimääräistä.

**Comment by LastuLauriH** [comment]
Sama Lastussa ensimmäisen rimpsun kohdalla, näyttäisi toimivan kuten piti.

**Comment by AnneliO** [comment]
Kiitos testailuista! Piilotus tuntuisi toimivan, joten dokumentoin sen [IntranetUserCSS-wikiin](https://github.com/KohaSuomi/Koha-24.05/wiki/IntranetUserCSS).
