### ISSUE TITLE
Varauksen tilan peruuttaminen siirtää käyttäjän tekemään asiakkaalle uutta varausta jonon hännille

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-24.05#104]
### Mikä vikana?

Jos asiakkaan varaus on kuljetettavana tai noudettavissa ja tilan yrittää perua tietueen Varaukset-sivun kautta, aukeaa käyttäjälle varauksenteko-sivu johon on haettu ko. asiakkaan tiedot valmiiksi. Kun varauksen tästä tallentaa, syntyy asiakkaalle jonon hännille uusi varaus ja alkuperäisen varauksen tila säilyy koskemattomana.

Yhteisön sandboxissa ongelma ei näyttäisi toistuvan.

### Mitä pitäisi tapahtua

Varauksen found-arvon pitäisi muuttua null:ksi ja varauksen siirtyä takaisin jonon ensimmäiseksi ei mihinkään niteeseen kiinnittyneenä.

### Kuinka toistaa ongelma/asia

1. Avaa tietue, jolla on kiinni jääneitä varauksia, esim. https://vaski-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=4303058#
2. Kokeile peruuttaa kuljetustila/odottaa-tila joltakin kiinni jääneeltä varaukselta

**Comment by LastuLauriH** [comment]
Kuvatulla tavalla Lastu-Nextin asetuksilla noudettavissa/odottaa tilan peruutus avaa varauksenteko-sivun kyseisen asiakkaan tiedoilla, ja herjaa että asiakkaalla on liian monta varausta tähän tietueeseen, ja uutta varausta ei voi tallentaa. Odottavalle varaukselle jonka tilaa yritettiin perua ei tapahdu mitään.

**Comment by LeenaKinnunen** [comment]
Lapissa toimii samoin kuin Lastu-Nextillä, eli aukeaa varausikkuna, ei voi tehdä uutta varausa, koska sellainen jo on, ja yritetty kuljetuksen peruutus ei tallennu.

**Comment by emta001** [comment]
Testailin omilla testeilläni, samaa oireilua sielläkin kuin Lapissa ja Lastussa.

**Comment by emta001** [comment]
Tapa jolla noita tiloja perutaan on muuttunut yhteisön puolellakin sen verran, että tilojen peruutus-napin rakennetta on muutettava. Tästä seuraa kuitenkin uusi ongelma, jossa nappi ei osaa napata kiinni koodiin jola peruutus tehdään. Tämä taas on korjattu yhteisön tiketissä [37270](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37270), joka korjaa SQL-raporttien poistamiseen liittyvän ongelman. Testasin tuotakin ja raportteja ei tosiaan pysty tällä hetkellä poistamaan nexteillä. Tehdään siis tämän kanssa niin, että teen raportti ongelmasta tiketin ja tuon siihen korjauksen nexteille. Sen jälkeen teen korjaukset tämän tiketin ongelmaan.

**Comment by emta001** [comment]
Korjaus viety nexteille. Näyttäisi toimivan oikein, varausten prioriteetitkin näyttäis asettuvan oikein kun tilaa muuttaa.

**Comment by AnneliO** [comment]
Testasin siili-nextillä peruuttaa varauksen odottava-tilan ja kuljetettavana-tilan ja nyt ne toimi minusta oikein.

**Comment by sksandel** [comment]
Vaskin Nextillä testasin varauksen odottava-tilan ja kuljetettavana-tilan peruutusta ja ne toimivat oikein. Varaukset muuttuivat aktiivisiksi jonon alkuun.

**Comment by emta001** [comment]
Hienoa, vaikuttaisi taas siis toimivan kuten pitääkin. Suljen tiketin.
