### ISSUE TITLE
Nidehaun monivalintakenttien yhdisteleminen hakee tietokannan kaikki niteet

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-24.05#105]
### Mikä vikana?

Jos nidehaussa hakuehtoihin lisää enemmän kuin yhden kentän ns. "Viivakoodi"-hakuvalikosta, näyttää nidehaun tuloksiin tulevan aina tietokannan kaikki niteet. Testailin vaski-nextillä erinäisillä hakuyhdistelmillä ja operaattoreilla, esimerkiksi liitteen kuvan mukaiset hakuehdot antavat tosiaan 2 559 825 tulosta joka on sama kuin items-taulun rivien määrä. :D Tuotannossa hakuehtojen yhdisteleminen toimii.

### Jotain muuta?

![kuva](https://github.com/user-attachments/assets/532bad6a-3c5a-42b7-9ce0-572173533f6e)

**Comment by LastuLauriH** [comment]
Sama bugi toistuu Lastu-Nextissä.

**Comment by atarnus** [comment]
Sama Outi-nextillä. Vilkaisin vähän, että mitä se sivusto lähettää haun yhteydessä. Näyttäisi olevan kaikki valinnat mukana, mutta sitten jos siellä on useampi, niin ne ei jostain syystä päädy sinne taulukon muodostamiseen oikein. Testasin sekä AND että OR operaattoreilla.

![image](https://github.com/user-attachments/assets/7eef967f-14a3-4dff-9bfc-3e5875bf7e27)

Tai voisiko johtua tuosta noista ylimääräisistä hakasista [] ? Ei näytä ihan oikealta JSONilta.

Testillä toimii haku oikein, ja senkin huomasin, että siellä tieto välitetään requestina, kun taas nextillä näyttää olevan headereissä.

**Comment by emta001** [comment]
Sama toistuu ilman meidän muutoksia, mutta ei enää yhteisön masterissa. Etsitään sieltä korjaus.

**Comment by emta001** [comment]
Korjaus löytyi ja on nyt testattavana nexteillä.

**Comment by AnneliO** [comment]
Tämä tuntuisi nyt siili-nextillä toimivan oikein.

**Comment by MikkoLiimatainen** [comment]
Vaikuttaisi toimivan Vaski-nextilläkin oikein nyt.

**Comment by LastuLauriH** [comment]
Vaikuttaa äkkiseltään toimivan myös Lastu-nextillä.

**Comment by LeenaKinnunen** [comment]
Vaikuttaa toimivan oikein Lapissa.

**Comment by atarnus** [comment]
Toimii Outi-nextilläkin oikein, ja näyttäisi ettei johtunut noista hakasuluista (ne näkyvät edelleen samalla tavalla). Kokeilin myös toisensa poissulkevilla ehdoilla JA-operaattorin kanssa, ja antoi nollatulosta kuten pitääkin.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
