### ISSUE TITLE
Firefoxilla ongelma sivun alas vierittämisessä

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-24.05#106]
### Mikä vikana?

Huomasin asiakkaan Maksut-sivulla Maksa maksuja -välilehdellä, että sivun alas vierittäminen ei onnistu (ainakaan) Firefox 115.12.0esr -versiolla. Esimerkkitapauksella https://vaski-next.koha-suomi.fi/cgi-bin/koha/members/pay.pl?borrowernumber=307898 on maksamattomia maksuja siis sen verran, etteivät maksut mahdu näytölle kerralla.

Avasin saman sivun Chromella ja sillä ongelmaa ei ole. Roosalla käytössä on Firefoxista versio 102.8.0esr ja myöskään sillä ongelma ei toistu, Mikolla sen sijaan sama versio kuin minulla ja ongelma toistuu.

Selaimen Tarkastele-toiminnon käyttöön ottamalla sivun vierittäminen korjaantuu, jos sillä on mitään merkitystä selvittelyn kannalta.

**Comment by AnneliO** [comment]
Miten se siis esiintyy, että vierittäminen ei onnistu? Jos on rullahiiri, niin silläkäänkö ei saa rullattua ruutua alaspäin?

Itselläni on normi-Firefoxin versio 128.0 (64-bittinen) ja siinäkin vieritys toimii normaalisti.

**Comment by ajrajala** [comment]
Eli rullahiirellä tai sivupalkkia hiirellä vetämällä ei saa siirryttyä sivun loppuun, vierityspalkki ikään kuin vilahtaa pikaisesti pohjalla ja keltaiset "Maksa valitut" ym painikkeet vilahtaa näkyvissä, mutta sen jälkeen vierityspalkki pomppaa aina takaisin ylemmäs. Eli käytännössä en pääse näkemään mitään mikä on Yhteensä-rivin alapuolella tuolla sivulla.

Muilla sivuilla en huomannut ongelmaa, esim. jos asiakkaalla on paljon lainoja niin sivun loppuun pääsee kyllä ihan nätisti.

**Comment by AnneliO** [comment]
Jännää! Näkyykö selaimen tarkastele-toiminnolla Konsoli-välilehdellä mitään virheilmoituksia?

**Comment by ajrajala** [comment]
Hyvä kysymys, sielläpä näkyy itse asiassa scrollaukseen liittyviä varoituksia:
![kuva](https://github.com/user-attachments/assets/cf93aaab-1ea6-443b-bc3c-e7a913a18f5c)

**Comment by emta001** [comment]
Sain saman toistettua omilla testeillä asiakkaan lainahistoriassa. Sama virhe tulee konsoliin, tosin sen avaamisen jälkeen rullaus rupes toimimaan.

**Comment by johannaraisa** [comment]
Vaikuttaisi siltä, ettei se Firefoxin "scroll anchor"-ominaisuus nyt pysy perässä isojen listojen kanssa. Tämän kanssa voisi kokeilla, että jos noiden listojen css-elementtiin saisi lisättyä tällaisen:

`overflow-anchor: none;`

**Comment by AnneliO** [comment]
Sain tämän toistettua nyt omalla koneellani Hankinnassa ollessani tilauskorin tiedoissa. Tilauskorissa oli kolme tietuetta, kaksi aktiivista ja yksi poistettu. En päässyt rullaamaan sivun alareunaan nähdäkseni sen yhden peruutetun tiedot kokonaan.

**Comment by johannaraisa** [comment]
En osaa sanoa onko tuo edes hyödyllinen ominaisuus Kohan kanssa. Tässä linkki aiheeseen, https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor/Guide_to_scroll_anchoring

Onko sellaisia tapauksia, että selaimen pitäisi muistaa se kohta missä oltiin scrollaamassa? Muuten tuon koko jutun voisi laittaa body-elementtiin, vaikuttaa sitten koko sivuun.

**Comment by ajrajala** [comment]
Ei oikein Vaskissa keksitty tapauksia, joissa pitäisi muistaa. Mietittiin myös, että jos nyt jollain sivulla kävisi noin, niin silloin voi kuitenkin skrollata takaisin siihen kohtaan jossa oli, mikä on huomattavasti pienempi paha kuin se ettei jossakin toisaalla pääse ollenkaan sivun pohjalle.

**Comment by johannaraisa** [comment]
Tätä pitää varmaan kokeilla nextillä, minä en ole saanut vielä toistettua.

**Comment by johannaraisa** [comment]
Nyt tiedän mikä tuossa on ongelmana, sivun ala laitaan ilmestyy nuoli millä pääsee takaisin ylös. Taulukko avautuu juuri sen verran, että tuon elementin ilmestyminen rikkoo vierityksen. Kyseiselle elementille on varmaan määritelty, että kun ollaan tietyssä vaiheessa sivua, niin se näytetään.

**Comment by johannaraisa** [comment]
Lisäsin Vaskille intranetusercss-asetukseen seuraavan:

`#backtotop {
  position: sticky;
  left: calc(95% + 40px);
}`

Ongelma on, että tuolle backtotop-elementille on määritelty `position:fixed;` mikä saa selaimen nappaamaan elementtiin kiinni vieritystä tehdessä. Tämä on selitetty täällä, https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html

Tuosta voisi tehdä tiketin yhteisöön, testaaminen on sitten hieman vaikeampaa.

**Comment by johannaraisa** [comment]
Kokeilkaa muutkin, tuleeko vielä tätä Vaskissa.

**Comment by iinaniemi** [comment]
Vaski-nextillä edelleenkään ei pääse scrollailemaan sivun loppuun esim tuolla Annin esimerkin maksut-sivulla.

**Comment by AnneliO** [comment]
> Vaski-nextillä edelleenkään ei pääse scrollailemaan sivun loppuun esim tuolla Annin esimerkin maksut-sivulla.

Hmm.. mulla se onnistuu. 🤔

**Comment by johannaraisa** [comment]
Voisko olla välimuistijuttu, ctrl+f5?

**Comment by iinaniemi** [comment]
Näyttää toimivan hieman vaihtelevasti. Ensin kun menin sivulle, se päästi alas asti pientä nykimistä lukuun ottamatta. Sitten tein ctrl+f5 eikä se päästänyt alas enää ollenkaan. Jokusen kerran kokeilin päivittää sivua ja välillä se näyttää toimivan ja välillä ei. Kävi monesti niin, että ensin rullaus näyttää toimivan, mutta yhtäkkiä se päättää, ettei päästäkään enää alas saakka.

**Comment by johannaraisa** [comment]
Jostain syystä tuota css-riviä ei ollut enää nextillä, lisäsin sen uudestaan. Nyt voisi kokeilla taas.

**Comment by iinaniemi** [comment]
Nyt näyttää toimivan!

**Comment by ajrajala** [comment]
Sain ongelman edelleen toistumaan [tällä sivulla](https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4269270&searchid=scs_1726211183916). Tuolla asiakkaan maksuissa ongelma ei enää toistu. Onko tuossa css:ssä vielä jotain säätömahdollisuutta johonkin suuntaan, jolla ongelman saisi paremmin taklattua?

**Comment by ajrajala** [comment]
Sellainen lisähavainto äskeiseen liittyen, että jos vaihdan näytettävien niteiden määrää valikosta joksikin muuksi kuin "20", sivun saa vieritettyä alas ongelmitta. Heti kun vaihdan takaisin 20, ongelma ilmaantuu.

**Comment by Rvallim0** [comment]
Muiden testausten ohella huomasin tämän ongelman aiheutuvan myöskin varauksia tehdessä, esimerkiksi [tässä](https://vaski-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=4333115). Ongelma toistuu vain varauslistan viimeisellä sivulla, ja vain jos taulukossa on alle 18 riviä, jos rivejä on 18 tai enemmän, scrollaus toimii normaalisti.

Selain: Firefox 115.14.0esr

**Comment by pirliis** [comment]
En saanut toistettua tätä OUTIssa Firefoxin 128.3.1esr-versiolla.

**Comment by piiaseme** [comment]
OUTIssa myös versiolla Firefox 115.11.0esr scrollaus toimii.

**Comment by ajrajala** [comment]
Minulla on päivittynyt Firefoxin versio 115.15.0esr enkä nyt saa ongelmia toistumaan (kommentoin css:nkin pois). Mutta löysin yhteisöstä tiketin https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36291, jossa ymmärtääkseni kyse samasta ongelmasta? Tiketissä todetaan, että _"it's tricky to reproduce, it should be some coincidence of data/table size and window size, so this kinda of pixel-hunting sometimes, but it happens,
and it is present and reported by our librarians a lot."_

Joten mietin nyt, että onko tämä niinkään Firefox-versiosta riippuvainen ongelma eli onko siitä hyötyä vaikka kuntia kehottaisi päivittämään Firefoxin esim. 128.x.x esr-versioon ennen versiopäivitystä. 🤔 Pitäisin tärkeänä, että tämä ongelma saataisiin taklattua jollakin tavalla, koska siinä kohtaa kun ongelma tulee asiakaspalvelutilanteessa eteen, on se virkailijalle vähän tenkkapoo.

**Comment by johannaraisa** [comment]
Luulen, että helpon ongelman taklaus on juurikin tuo selaimen päivittäminen jos se uudemmilla versioilla toimii oikein. Tuo englanninkielinen kuvaus on kyllä hyvä, tuossa juuri etsitään pikseleitä ja hankalaa toistaa.

**Comment by ajrajala** [comment]
Törmäsin aamulla ongelmaan [tällä haulla tallennetuista raporteista](https://vaski-next.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?op=list&filter_set=1&filter_keyword=action_logs), käytössä oli edelleen 115.15.0esr. Sain äsken koneelleni uuden Firefox-version 128.3.1esr ja ongelma toistuu edelleen. Saan myös ongelman toistumaan Robertin aiemmin laittamassa [esimerkkitapauksessa](https://vaski-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=4333115&show_holds_now=1) varauslistan viimeisellä sivulla.

Laitoin Johannan css-rimpsun takaisin käyttöön kokeillakseni olisiko sillä vaikutusta nyt havaittuihin tapauksiin, mutta ei ollut.

Kuten yhteisötiketissä todetaan niin selainikkunan kokoa muuttamalla ongelma ei enää toistu, mutta käytännössä asiakaspalvelussa tilanne tulee varmaan olemaan se ettei ongelmaa osata kiertää (paitsi varmaan sitten, kun siihen on jo aiemmin kertaalleen törmännyt ja kuullut ratkaisun). Mutta pystyykö tähän tosiaan mitään väliaikaista korjausta kehittämään vai täytyykö odotella mitä yhteisötiketissä tapahtuu?

**Comment by johannaraisa** [comment]
Jos vain poistaisi sen nuolen, siihen se minusta nappaa kiinni? En tiedä onko se nyt niin hyvä ominaisuus, hiirellä voi rullata myös ylös.

**Comment by ajrajala** [comment]
No mietin samaa, minusta pienempi paha luopua nuolesta kun ennenkin pärjätty ilman.

**Comment by AnneliO** [comment]
Mien luopuisi nuolesta, se on minusta tosi hyödyllinen pitkillä sivuilla (silloin, kun ei ole tuota vieritysongelmaa).

**Comment by johannaraisa** [comment]
@ajrajala Jos kokeilen css:llä piilottaa sen nuolen, ni katsotko miten toimii?

**Comment by johannaraisa** [comment]
> @ajrajala Jos kokeilen css:llä piilottaa sen nuolen, ni katsotko miten toimii?

Nyt se on piilotettu, kokeile nappaako vielä kiinni.

**Comment by ajrajala** [comment]
[Tallennetuissa raporteissa tehdyssä haussa](https://vaski-next.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?op=list&filter_set=1&filter_keyword=action_logs) ongelma toistuu edelleen. Sen sijaan [varauksenteko-sivulla viimeisellä välilehdellä](https://vaski-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=4333115&show_holds_now=1) ollut ongelma poistui.

**Comment by piiaseme** [comment]
MInulla on Firefox 115.11.0esr eikä ole aiemmin ollut skrollausongelmia, mutta nyt varauksentekosivulla en pääse sivun pohjalle asti. Varauksia on tietueella yht. 10 ja skrollaus alaspäin toimii ilman nykimistä siihen asti kunnes nuoli tulee esiin. 

Olin tämän niteen varauksissa: https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2323081
Pääsin oikean alanurkan nuolinäppäimellä alemmas, mutten ihan alas asti.
![kuva](https://github.com/user-attachments/assets/bae39269-40ad-4f3a-978e-b12267ba63a7)

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 28.10.2024: Pitäisikö kokeilla vielä poistaa napin luova javascript?

**Comment by ajrajala** [comment]
> Koha-Suomen palaveri 28.10.2024: Pitäisikö kokeilla vielä poistaa napin luova javascript?

Kannattaisin sitä, että kokeillaan.

**Comment by pirliis** [comment]
Kannatan myös kokeilua, jos selausongelmat johtuvat napista.

**Comment by johannaraisa** [comment]
Eka voi kokeilla poistaa tuon koko napin javascriptillä, ei tarvitse sitten koodia muokata.
Laittakaa intranetuserjs:ään tämä:

```
$(document).ready(function() {
  $("#backtotop").remove();
});
```

**Comment by ajrajala** [comment]
Lisäsin javascriptin, [tallennetuissa raporteissa tehdyssä haussa](https://vaski-next.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?op=list&filter_set=1&filter_keyword=action_logs) saan sivun uudelleenlatauksen jälkeenkin toistumaan scrollausongelman, samoin ongelma toistuu jos varaukset-sivulla varauksia on 10 niin kuin pirliis tuolla ylempänä kommentoikin.

Sellainen jännä havainto, että tuolla raporteissa pystyn aika vaivattomasti sivupalkista raahaamalla siirtymään sivun alareunaan vaikka palkki ongelmakohdassa tekeekin tanssiliikkeitä, mutta sitten tuolla varauksissa en saa millään sivupalkistakaan raahattua itseäni sivun alareunaan. :D

**Comment by johannaraisa** [comment]
Minua alkaa epäilyttää, että onkohan se tuo nappi sittenkään. Kun tuolla koodilla se pitäisi hävitä koko koodista. Kommentoin omassa ympäristössä nuo koodit pois ja silti tulee selaimeen tällainen:
"This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features!"

**Comment by johannaraisa** [comment]
Tää saattaa liittyä noihin datatables-taulukoihin, tapahtuuko tuota sellaisella sivulla missä tuota taulukkoa ei ole?

**Comment by ajrajala** [comment]
> Tää saattaa liittyä noihin datatables-taulukoihin, tapahtuuko tuota sellaisella sivulla missä tuota taulukkoa ei ole?

Kuulostaisi pätevältä epäilykseltä. Kaikki tilanteet, joissa meillä on ongelmaan törmätty, on olleet sivuja joissa on joku taulukko (maksut-sivu, varaukset-sivu, tietueen perustiedot, tallennetut raportit).

**Comment by johannaraisa** [comment]
Voihan se olla jokin yhteisvaikutuskin, sillä näyttää tuota samaa ilmoitusta tulevan testillä myös. Teen nyt sillein, että kommentoin nexteiltä tuon nappitoiminnon kokonaan.

**Comment by johannaraisa** [comment]
Nyt on kommentoitu ne koodit, ladatkaa sivu ctrl+f5:llä niin pitäisi hävitä.

**Comment by johannaraisa** [comment]
> Nyt on kommentoitu ne koodit, ladatkaa sivu ctrl+f5:llä niin pitäisi hävitä.

Ja pitää olla englanninkielinen versio, muuten se koodi on vielä paikoillaan.

**Comment by ajrajala** [comment]
Osittain tuo näyttäisi auttavan. Mikko testasi sen kokoisella näytöllä, millä Varaukset-sivulla ja tallennetuissa raporteissa ongelmaa oli. Suomenkielellä käyttäessä ongelma toistuu, englanninkielisessä versiossa ei.

Mutta sitten isommalla näytöllä saan tuolla tallennetuissa raporteissa edelleen ongelman ilmaantumaan.

**Comment by MikkoLiimatainen** [comment]
Ainakin tuon tallennettujen raporttien action_logs haun kanssa tuon taulukon asettelu muuttuu nyt niin paljon englanninkielisessä versiossa, että siinä ei välttämättä osuta ollenkaan triggeripisteeseen, kun taulukko on paljon lyhyempi. Sanoisin, että tuo voi jo itsessään hävittää ongelman tuolta sivulta, vaikka ongelma olisi yhä olemassa.

**Comment by MikkoLiimatainen** [comment]
Onnistuin tavallaan toistamaan ongelman tallennetuissa raporteissa, mutta se ei ole ollenkaan niin vakava kuin aiemmin. Aiemmin hyppäys näytti vievän taulukon yläreunaan, mutta nyt sitä hädin tuskin huomaa. Täytyy tuijottaa tuota vierityspalkkia huomatakseen sen nopeasti pomppivan, mutta skrollaus etenee silti mielestäni normaalisti.

**Comment by MikkoLiimatainen** [comment]
Varaukset sivulla tietueessa, jossa on 17 varausta, ongelma on kuitenkin edelleen: [https://vaski-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=2805397](https://vaski-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=2805397).

**Comment by ajrajala** [comment]
Noilla sivuilla, missä ongelmaan edelleen törmää (tallennetut raportit ja Mikon laittama linkki), pääsen jännästi ihan satunnaisesti rullaamaan sivun loppuun mutta pääsääntöisesti muuten scrollaus jää jumittamaan samaan kohtaan.

**Comment by johannaraisa** [comment]
Näyttää tuossa datatablesissakin olevan tuota samaa ominaisuutta, varaussivulla nuo napit kiinnittyvät yläreunaan, kun mennään alas päin. Kokeilen siihen jotain korjausta.

**Comment by lmstrand** [comment]
Laitoin vaski-nextille rimpsun intranetUserJs-asetukseen, jolla otetaan tuolla https://vaski-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=2805397 datatablen stickyHeader pois, eli taulukon otsikot eivät seuraa sivua alas kelatessa. Toimiiko tällainen ratkaisu ongelmaan?

**Comment by lmstrand** [comment]
Varmaan voisi kokeilla nuolen kera tuota ratkaisua.

**Comment by johannaraisa** [comment]
Se nuoli on palautettu tuonne.

**Comment by johannaraisa** [comment]
> Laitoin vaski-nextille rimpsun intranetUserJs-asetukseen, jolla otetaan tuolla https://vaski-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=2805397 datatablen stickyHeader pois, eli taulukon otsikot eivät seuraa sivua alas kelatessa. Toimiiko tällainen ratkaisu ongelmaan?

Jos tuo toimii, niin se pitäisi tehdä kaikkiin datatables-taulukoihin.

**Comment by johannaraisa** [comment]
Tuo Larin korjaus koskee nyt vain varaussivua, kokeillaan jos se auttaa niin laajennetaan muualle.

**Comment by ajrajala** [comment]
Hmm, kun avasin sivun ekan kerran, pääsin scrollaamaan sivun loppuun pariin otteeseen (mutta olin havaitsevinani pientä nykimistä sivupalkissa), mutta sen jälkeen jäi taas jumittamaan. Latasin sivun ctrl+f5 uudelleen ja ensin scrollatessa teki taas nykimistä mutta suostui hetken yrittämisen jälkeen menemään sivun loppuun. Sain tämän toistumaan muutaman kerran, sitten taas jumittui taas tilanteeseen jossa sivun loppuun ei pääse scrollaamaan millään.

**Comment by lmstrand** [comment]
Nyt saan minäkin toistettua ongelman, tuo ei siis ollut ratkaisu, että poistaa otsikkojen seuraamisen sivulla. Vielä on yksi kikkakolmonen taskussa. Käyn heittämässä kokeeksi intranetuserJs:ään.

**Comment by lmstrand** [comment]
Tuo olikin CSS-muutos. Tuolla pitäisi nyt näkyä ne otsikot koko ajan sivua vierittäessä, mutta mulla ei näy (vaikka siis pitäisi). Korjasiko CSS-muutos silti teillä ongelman?

**Comment by ajrajala** [comment]
> Tuo olikin CSS-muutos. Tuolla pitäisi nyt näkyä ne otsikot koko ajan sivua vierittäessä, mutta mulla ei näy (vaikka siis pitäisi). Korjasiko CSS-muutos silti teillä ongelman?

Hmm, sivun uudelleenlatauksen jälkeen scrollaus edelleen nykii mutta päästää muutaman kerran kyllä scrollaamaan sivun loppuun kun nykimisestä ei välitä. Muutaman kerran jälkeen scrollaus silti menee taas juntturaan, kuten tuossa edellisessä testauskommentissa tapahtui.

**Comment by lmstrand** [comment]
Kokeilkaas nyt. Työkalunapit eivät enää seuraa, kun sivua vierittää ja datatables-foorumilta löydetty purkkafiksaus on laitettu Vaski-nextin intranetUserCSS:ään. Pitäisi vaikuttaa kaikkialla Kohassa.

**Comment by lmstrand** [comment]
Laitan tähän ylös nuo CSS-muokkaukset, mitä nyt ollaan kokeilemassa:

.dataTable .colSticky {
  /* NOTE: applyStickyColumns will assign a background of 'whitesmoke' if transparent */
  position: sticky !important;
}

.btn-toolbar {
  position:static !important;
}

**Comment by ajrajala** [comment]
> Kokeilkaas nyt. Työkalunapit eivät enää seuraa, kun sivua vierittää ja datatables-foorumilta löydetty purkkafiksaus on laitettu Vaski-nextin intranetUserCSS:ään. Pitäisi vaikuttaa kaikkialla Kohassa.

Tuolla varaussivulla en saa scrollausta enää jumittumaan, joten näyttäisi auttaneen. Mut tallennetut raportit on joku murheenkryyni. 😄 Isommalla näytöllä miulla jumittaa edelleen sivu https://vaski-next.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?op=list&filter_set=1&filter_date=&filter_author=&filter_keyword=action_logs ja pienemmällä näytöllä tallennetuissa raporteissa Lainaus-välilehti (kun on näkyvillä kaikki raportit).

**Comment by johannaraisa** [comment]
Otin nyt kaikista Datatables-taulukoista pois ton ominaisuuden, että ne sarakkeiden nimet seuraa siinä scrollissa. Kokeilkaa auttaako tuo noihin sivuihin. Yhteisö on päivittämässä Datatablesia uudempaan versioon, toivottavasti siinä tulisi apuja tähän ongelmaan.

Lisäsin tämän rivin intranetuserjs:ään.

```
$(document).ready(function() {
  dataTablesDefaults.fixedHeader = false;
});
```

**Comment by MikkoLiimatainen** [comment]
Minusta tämä näyttää korjaavan asian. Ja korjaa samalla ongelman tietueen perustiedot näytöltä, jonka laitoin tähän tikettiin tiedoksi: [https://github.com/KohaSuomi/Koha-24.05/issues/139](https://github.com/KohaSuomi/Koha-24.05/issues/139). Kun nuo otsikkorivit eivät jää sivun yläreunaan enää kiinni, niin tuollakaan nuo suodatukset eivät enää sekoile.

**Comment by ajrajala** [comment]
Minäkään en saa ongelmaa enää toistumaan.

**Comment by piiaseme** [comment]
Lisäsin Johannan rimpsun intranetuserjs:ään. Sen jälkeen ongelma ei toistunut enää OUTIn nextillä.

**Comment by johannaraisa** [comment]
Muokkasin hieman OUTIn nextillä tuota, ettei anna turhia varoituksia selaimen konsoliin.

``` 
$(document).ready(function() {
  if (typeof dataTablesDefaults !== 'undefined') {
  	dataTablesDefaults.fixedHeader = false;
  }
});
```

**Comment by johannaraisa** [comment]
Tämä kannattaa käytä lisäämässä omiin intranetuserjs-asetuksiin. On hyvin todennäköistä, että kaikilta löytyy samankokoisia näyttöjä ja taulukot nappaavat kiinni vierityksen yhteydessä.

**Comment by pknuuti** [comment]
Lisätty Vaaran nextille.

**Comment by AnneliO** [comment]
Lisäsin rimpsun myös [IntranetUserJS-wikiin](https://github.com/KohaSuomi/Koha-24.05/wiki/IntranetUserJS).

**Comment by piiaseme** [comment]
OUTIssa ok - Johanna oli sen jo lisännyt :)

**Comment by AnneliO** [comment]
Seuranta kimpoista:

- [x] Lappi
- [x] OUTI
- [x] Siili
- [x] Vaara
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [x] Lastu
- [x] Vaski
- [x] Täti

**Comment by ajrajala** [comment]
Vaski-nextillä oikea js myöskin paikoillaan.

**Comment by Tuomas-Kyyti** [comment]
Kyytin nextille lisätty.

**Comment by AnneliO** [comment]
Lisätty TäTi-nextille.

**Comment by ElinaUotila** [comment]
Lisätty Kirkes-nextille.

**Comment by Hanna-Lumme** [comment]
Lisätty Lumpukoiden nextille.

**Comment by ReettaSiili** [comment]
Lisätty Siili-nextille

**Comment by LastuJanneS** [comment]
Myös Lastun nextille viety.

**Comment by PiaKusmin** [comment]
Ja Lappiin lisätty myös.

**Comment by Kati-Helle** [comment]
Tämä on jo Helle-nextissä (ja nyt myös testissä). Olen unohtanut kommentoida tähän tikettiin.

**Comment by AnneliO** [comment]
Rimpsu on nyt kaikissa kimpoissa käytössä. Suljetaanko tiketti vai jatketaanko ongelman selvittelyä vielä muuten?

**Comment by johannaraisa** [comment]
Suljetaan tämä, koitetaan jossain välissä katsoa miten datatablesin päivitys on mennyt yhteisössä ja jos sen saa tuotua meille.
