### ISSUE TITLE
Mustan yläpalkin ja hakukentän välissä ylimääräinen väli

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-24.05#107]
### Mikä vikana?

Mustan yläpalkin ja sen alapuolella olevan hakupalkin välissä on ylimääräinen tyhjä väli, jossa näkyy taustaväri:

![kuva](https://github.com/user-attachments/assets/a81aa1e0-7545-4111-aabd-b176dd1f1953)

Yhteisön sandboxissa väliä ei ole:

![kuva](https://github.com/user-attachments/assets/4f4fcd93-a19a-46dd-8d55-4f207ae36d25)

### Mitä pitäisi tapahtua

Mustan palkin alapuolella ei pitäisi olla väliä.

### Kuinka toistaa ongelma/asia

Mene jollekin nextille ja avaa etusivu.

**Comment by emta001** [comment]
Kyseessä on luultavasti ongelma fix-yarnissa. Se ei halua linkittää css-tiedostoja oikeasta paikasta.

**Comment by johannaraisa** [comment]
Siivosin utilityssä olleet ylimääräiset yarnin linkitystiedostot, nyt tuo väli on kadonnut. 

HUOM! utilityyn laitetaan vain koha-tmpl-tiedostot, jotka on määritelty [.gitignoreen](https://github.com/KohaSuomi/Koha-24.05/blob/ks24/.gitignore)

```
koha-tmpl/opac-tmpl/bootstrap/css/maps/
koha-tmpl/opac-tmpl/bootstrap/css/opac.css
koha-tmpl/opac-tmpl/bootstrap/css/opac-rtl.css
koha-tmpl/opac-tmpl/bootstrap/css/print.css
koha-tmpl/opac-tmpl/bootstrap/css/print-rtl.css
koha-tmpl/opac-tmpl/bootstrap/css/sco.css
koha-tmpl/opac-tmpl/bootstrap/css/sco-rtl.css

koha-tmpl/intranet-tmpl/prog/css/maps/
koha-tmpl/intranet-tmpl/prog/css/calendar.css
koha-tmpl/intranet-tmpl/prog/css/holds.css
koha-tmpl/intranet-tmpl/prog/css/installer.css
koha-tmpl/intranet-tmpl/prog/css/mainpage.css
koha-tmpl/intranet-tmpl/prog/css/staff-global.css

koha-tmpl/intranet-tmpl/prog/js/vue/dist/

```

**Comment by AnneliO** [comment]
Jees, niin katosi! Vaati tosin ensin ctrl+f5:lla selaimen päivityksen.
