### ISSUE TITLE
Takaajasuhteisiin tehdyt muutokset mahdollistavat tallentamisen ilman suhdetietoa

### ISSUE THREAD

**Issue by atarnus** [KohaSuomi/Koha-24.05#108]
### Mikä vikana?

Uudessa versiossa takaajasuhteen pakollisuuden hallinta on muuttunut. Vaikka takaajille on määritelty suhdetieto(ja) asetuksissa (borrowerRelationship) niin suhteen valitseminen ei olekaan enää pakollista. Asiakkaan tallentaminen takaajalla, mutta ilman suhdetta aiheuttaa kuitenkin Internal Server Errorin. 
(Asiakas tallentuu kyllä, mutta ilman takaajatietoa.)

Jos laittaa BorrowerMandatoryField-asetukseen päälle 'Suhde (relationship)', niin Koha kohtelee jälleen suhdetietoa pakollisena kenttänä, joskin vihjeteksti kentän pakollisuudesta näkyy väärin tapauksessa, jossa Takaajan tietojen kautta mennään luomaan hänelle uusi Taattava asiakas. (Jos vain luo lapsiasiakkaan, ja lisää hänelle takaajan, niin vihjeteksti näyttää toimivan oikein.)

Kuvassa alla näkyy tilanne kun takaajasuhde ei ole päällä BorrowerMandatoryFieldissä. Kentän otsikko on mustalla, mutta 'Pakollinen tieto' vihjeteksti näkyy kentän perässä.
![image](https://github.com/user-attachments/assets/962bce45-3254-405a-9068-47a7603efec8)

Tässä kuvassa on tilanne kun takaajasuhteen pakotus on päällä. Kentän otsikko on oikein punaisella, mutta 'Pakollinen tieto' teksti puuttuu. Eli tässä tulee nyt tämä vihjeteksti väärin päin. (Jos yrittää tallentaa, niin virhetekstit tulostuvat oikein.)
![image](https://github.com/user-attachments/assets/b8759e7c-b2e5-4279-90b6-241c70d39055)

### Mitä pitäisi tapahtua

Jos takaajasuhteita on määritelty, pitäisi takaajan suhde -kenttä muuttua pakolliseksi.

Takaajan kautta luotavan uuden taattavan asiakaan kohdalla suhdekentän vihjetekstin tulisi noudattaa asetusta.

### Kuinka toistaa ongelma/asia

1. Katso, että 'Suhde (relationship)' ei ole valittuna BorrowerMandatoryField-asetuksissa.
2. Luo uusi taattava asiakas / Luo henkilöasiakkaalle uusi taattava.
3. Katso, että asiakkaalla on takaaja, mutta älä valitse suhdetta pudotusvalikosta.
4. Täytä muut pakolliset kentät.
5. Tallenna asiakas. 
6. Huomaa virheilmoitus.
7. Tarkista asiakastiedot, ja huomaa, että uusi asiakas tallentui virheilmoituksesta huolimatta, joskin ilman takaajatietoa.

**Comment by atarnus** [comment]
Yhteisössä on nyt tullut patch jo 2011 tehtyyyn [tikettiin 7223](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=7223), jossa on ehdotettu borrowerRelationship-asetuksen siirtämistä auktorisoituihin arvoihin. Tämä vaikuttaa hyvältä idealta, mutta aiheuttaa sitten sen, että suhde-kentän pakollisuutta ei ainakaan voi sitoa takaisin tuohon borrowerRelationship-arvoon.

**Comment by atarnus** [comment]
Tein tästä varsinaisesta asiasta nyt tiketin myös yhteisöön: [37528](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37528).

**Comment by johannaraisa** [comment]
En nyt ole täysin varma miten tämä kannattaa fiksata, vai onko vain ominaisuus. Virhe mikä tuosta tulee on, _Invalid relationship passed, '' is not defined._
Tämän virheen saa pois, jos siihen borrowerRelationship-asetukseen laittaa esim. mother|father|. Tuossa tapauksessa tyhjäkin hyväksytään.

**Comment by atarnus** [comment]
No siis jos laittaa noin, niin takaaja joo tallentuu (ei siis putoa pois), mutta ilman suhdetta. Ja edelleen tulee internal server error tallennustilanteessa. Eikä varmaan ole tarkoituksenmukaista että takaajia tallentuisi ilman suhdetta, vaikka erroria ei tulisikaan? Sitäkään en osaa nyt yhtäkkiä arvailla, että miten asia voitaisiin huomioida noilla auktorisoiduilla arvoilla, jos tuon tiketin 7223 muutos tullaan ottamaan käyttöön.

Miksi tuossa pudotusvalikossa on yleensäkään mukana tyhjä arvo? Eikö sen voisi vain poistaa?
Ja vielä huomiona, että takaajasuhdettahan ei voi muokata, vaan takaaja pitää poistaa ja liittää uudestaan. Niin nuo tyhjät suhteet olisivat mahdollisesti siitäkin syystä tympeitä sitten.

**Comment by johannaraisa** [comment]
Laitoin kysymystä tuonne yhteisön Mattermostiin, että miten sen koko kentän kanssa pitäisi toimia. Ainakin itse olettaisin, että jos se borrowerRelationship sisältää jotain, niin sitten se pitäisi aina olla pakollinen. Tuolla on aika paljon epäjohdonmukaisuutta muutenkin, esim. se että "Required" tulee siihen kentän viereen jos lisää lasta huoltajalle, kun sitä koko relationship-arvoa ei ole laitettu BorrowerMandatoryField-asetukseen.

**Comment by johannaraisa** [comment]
Tämä koko takaaja-asia tuntuu olevan ihan hirveä suo, enkä saanut mitään vastausta kysymykseeni Mattermostissa. Tein yhteisöön korjausehdotuksen ja tänään 1.8. kehittäjien palaverissa todettiin, että mielummin odotamme sen menoa läpi yhteisössä. Tämän kuitenkin pystyy kiertämään sillä, että määrittelee sen relationship-kentän pakolliseksi. Onhan siellä se kosmeettinen häiriö sen kentän pakollisuusviestin kanssa, mutta se on kuitenkin pientä.

**Comment by johannaraisa** [comment]
Ainakin tikettiin on tullut testauksia, voisi jopa mennä mainiin.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 28.10.2024: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37528 on Pushed to main -tilassa. Tuotava meille.

**Comment by johannaraisa** [comment]
Tämä on nyt nexteillä testattavana.

**Comment by pirliis** [comment]
En tiedä, testasinko kuin on tarkoitus, mutta laitoin BorrowerMandatoryField-järjestelmäasetuksen Suhde (relationship) kentän paikolliseksi:

- kun luo uuden lapsiasiakkaan, jolle lisätty takaaja ja suhde-kenttään valittu "huoltaja" sekä täydennetty muut pakolliset kentät, tallennus ei toimi. Kun painaa Tallenna-painiketta, ei tapahdu mitään.
- jos lapsiasiakkaalle ei lisää takaajaa, tallennus ei onnistu, mutta ohjelma ei anna ilmoitusta, että pakollinen tieto puuttuu. Pitäisikö?
- kun takaajalle lisää uuden taattavan toiminnolla "Lisää huollettava" ja Suhde-kenttään valitsee huoltajan sekä täydentää muut pakolliset kentät, tallennus ei toimi.

**Comment by Rvallim0** [comment]
Vaski nextillä testattu:
-Kun BorrowerMandatoryField asetuksessa relationship kenttä ei ole pakollinen, tallentaessa taattavaa ilman suhdetta tulee "Seuraavat tiedot ovat väärin. Korjaa tiedot. Guarantor relationship cannot be left blank according to configuration." ilmoitus eikä taattava asiakas tallennu.

-Kun BorrowerMandatoryField asetuksessa relationship kentän määrittää pakolliseksi, Koha ei anna yrittää tallentaa vaan ilmoittaa että pakollisia kenttiä on tyhjänä.

-Kun BorrowerMandatoryField asetuksessa relationship kenttä ei ole pakollinen ja suhteen määrittää taattavalle oikein, tallennus onnistuu ongelmitta.

-Kun BorrowerMandatoryField asetuksessa relationship kenttä on pakollinen ja suhde on määritetty taattavalle oikein, tallennus nappi ei tee mitään.

**Comment by johannaraisa** [comment]
> -Kun BorrowerMandatoryField asetuksessa relationship kenttä on pakollinen ja suhde on määritetty taattavalle oikein, tallennus nappi ei tee mitään.

Tuo viimeinen johtuu siitä, että tuolla on non-patron kentässä relationship, joka on näköjään sekin pakollinen ja jos siihen ei valitse mitään niin tallentaminen ei onnistu. Tämä on piilotettuna näkymästä, joten se ei näy käyttäjälle suoraan.

![image](https://github.com/user-attachments/assets/277be14a-1e61-4dc3-b63d-6d11b3394bd1)

**Comment by johannaraisa** [comment]
Katson, jos tuohon on korjausta. Vähän hassua muutenkin, että pitäisi olla kumpaankin määritelty tuo relationship.

**Comment by johannaraisa** [comment]
Ei ollut valmista korjausta, pitää tehdä itse. https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38373
Melkein valmis, laitan huomenna nexteille.

**Comment by johannaraisa** [comment]
Nyt on nexteillä, ladatkaa lomakesivu ctrl+f5:llä ennen tietojen syöttämistä.

**Comment by pirliis** [comment]
Testattu OUTIn nextillä. BorrowerMandatoryField-järjestelmäasetuksen Suhde (relationship) -kenttä pakollinen.

- kun luo uuden lapsiasiakkaan, jolle lisätty takaaja ja suhde-kenttään valittu "huoltaja" sekä täydennetty muut pakolliset kentät -> nyt tallennus toimii.
-  kun luo uuden lapsiasiakkaan, jolle lisätty takaaja, mutta suhde-kenttä jätetään tyhjäksi, vaikka pakollinen tieto ->  **antaa tallentaa asiakastiedot ilman suhde-tietoa**
- kun luo uuden lapsiasiakkaan, jolle ei lisätä takaajaa -> **antaa tallentaa asiakastiedot ilman takaajatietoa**
- jos poistaa takaajatiedon lapsiasiakkaalta-> **asiakastietojen tallennus onnistuu ilman takaajaa**
- jos lisää toisen takaajan, mutta jättää suhde-kentän tyhjäksi -> **antaa tallentaa asiakastiedon ilman suhde-tietoa**
- jos takaajalle tallentaa uuden taattavan -> **tallennus onnistuu ilman suhde-tietoa**

**Comment by johannaraisa** [comment]
> Testattu OUTIn nextillä. BorrowerMandatoryField-järjestelmäasetuksen Suhde (relationship) -kenttä pakollinen.
> 
>     * kun luo uuden lapsiasiakkaan, jolle lisätty takaaja ja suhde-kenttään valittu "huoltaja" sekä täydennetty muut pakolliset kentät -> nyt tallennus toimii.
> 
>     * kun luo uuden lapsiasiakkaan, jolle lisätty takaaja, mutta suhde-kenttä jätetään tyhjäksi, vaikka pakollinen tieto ->  **antaa tallentaa asiakastiedot ilman suhde-tietoa**
> 
>     * kun luo uuden lapsiasiakkaan, jolle ei lisätä takaajaa -> **antaa tallentaa asiakastiedot ilman takaajatietoa**
> 
>     * jos poistaa takaajatiedon lapsiasiakkaalta-> **asiakastietojen tallennus onnistuu ilman takaajaa**
> 
>     * jos lisää toisen takaajan, mutta jättää suhde-kentän tyhjäksi -> **antaa tallentaa asiakastiedon ilman suhde-tietoa**
> 
>     * jos takaajalle tallentaa uuden taattavan -> **tallennus onnistuu ilman suhde-tietoa**

Teillä on nyt jotain outoa tuossa kenttien validoinnissa, se ei valita mistään tyhjistä kentistä. Voi siis tallentaa tyhjän asiakkaan. Lisäksi katsoin, että teillä on borrowerRelationship asetuksessa sallittu tyhjä suhde, jos viimeinen merkki on tuo putki merkki niin silloin tyhjä suhde sallitaan.

**Comment by pirliis** [comment]
> > Testattu OUTIn nextillä. BorrowerMandatoryField-järjestelmäasetuksen Suhde (relationship) -kenttä pakollinen.
> > ```
> > * kun luo uuden lapsiasiakkaan, jolle lisätty takaaja ja suhde-kenttään valittu "huoltaja" sekä täydennetty muut pakolliset kentät -> nyt tallennus toimii.
> > 
> > * kun luo uuden lapsiasiakkaan, jolle lisätty takaaja, mutta suhde-kenttä jätetään tyhjäksi, vaikka pakollinen tieto ->  **antaa tallentaa asiakastiedot ilman suhde-tietoa**
> > 
> > * kun luo uuden lapsiasiakkaan, jolle ei lisätä takaajaa -> **antaa tallentaa asiakastiedot ilman takaajatietoa**
> > 
> > * jos poistaa takaajatiedon lapsiasiakkaalta-> **asiakastietojen tallennus onnistuu ilman takaajaa**
> > 
> > * jos lisää toisen takaajan, mutta jättää suhde-kentän tyhjäksi -> **antaa tallentaa asiakastiedon ilman suhde-tietoa**
> > 
> > * jos takaajalle tallentaa uuden taattavan -> **tallennus onnistuu ilman suhde-tietoa**
> > ```
> 
> Teillä on nyt jotain outoa tuossa kenttien validoinnissa, se ei valita mistään tyhjistä kentistä. Voi siis tallentaa tyhjän asiakkaan. Lisäksi katsoin, että teillä on borrowerRelationship asetuksessa sallittu tyhjä suhde, jos viimeinen merkki on tuo putki merkki niin silloin tyhjä suhde sallitaan.

Eipä tosiaan herjaa mistään pakollisista kentistä, vaan antaa tallentaa ilman. :( 
Ehkä putkimerkin poisto järjestelmäasetuksesta borrowerRelationship ei korjaa kokonaan tilannetta?

**Comment by johannaraisa** [comment]
> > > Testattu OUTIn nextillä. BorrowerMandatoryField-järjestelmäasetuksen Suhde (relationship) -kenttä pakollinen.
> > > ```
> > > * kun luo uuden lapsiasiakkaan, jolle lisätty takaaja ja suhde-kenttään valittu "huoltaja" sekä täydennetty muut pakolliset kentät -> nyt tallennus toimii.
> > > 
> > > * kun luo uuden lapsiasiakkaan, jolle lisätty takaaja, mutta suhde-kenttä jätetään tyhjäksi, vaikka pakollinen tieto ->  **antaa tallentaa asiakastiedot ilman suhde-tietoa**
> > > 
> > > * kun luo uuden lapsiasiakkaan, jolle ei lisätä takaajaa -> **antaa tallentaa asiakastiedot ilman takaajatietoa**
> > > 
> > > * jos poistaa takaajatiedon lapsiasiakkaalta-> **asiakastietojen tallennus onnistuu ilman takaajaa**
> > > 
> > > * jos lisää toisen takaajan, mutta jättää suhde-kentän tyhjäksi -> **antaa tallentaa asiakastiedon ilman suhde-tietoa**
> > > 
> > > * jos takaajalle tallentaa uuden taattavan -> **tallennus onnistuu ilman suhde-tietoa**
> > > ```
> > 
> > 
> > Teillä on nyt jotain outoa tuossa kenttien validoinnissa, se ei valita mistään tyhjistä kentistä. Voi siis tallentaa tyhjän asiakkaan. Lisäksi katsoin, että teillä on borrowerRelationship asetuksessa sallittu tyhjä suhde, jos viimeinen merkki on tuo putki merkki niin silloin tyhjä suhde sallitaan.
> 
> Eipä tosiaan herjaa mistään pakollisista kentistä, vaan antaa tallentaa ilman. :( Ehkä putkimerkin poisto järjestelmäasetuksesta borrowerRelationship ei korjaa kokonaan tilannetta?

Johtuu vissiin noista piilotuksista, korjaan vielä tuota.

**Comment by pirliis** [comment]
Otin pois Suhde-tiedon pakollisuuden järjestelmäasetuksesta BorrowerMandatoryField, niin nyt herjaa, jos pakollisia kenttiä ei ole täytetty, paitsi takaaja-tiedosta.

**Comment by Rvallim0** [comment]
Vaski nextillä uudelleen testattu:
-Kun BorrowerMandatoryField asetuksessa relationship kenttä ei ole pakollinen, tallentaessa taattavaa ilman suhdetta tulee "Seuraavat tiedot ovat väärin. Korjaa tiedot. Guarantor relationship cannot be left blank according to configuration." ilmoitus eikä taattava asiakas tallennu.

-Kun BorrowerMandatoryField asetuksessa relationship kentän määrittää pakolliseksi, Koha ei anna yrittää tallentaa vaan ilmoittaa että pakollisia kenttiä on tyhjänä.

-Kun BorrowerMandatoryField asetuksessa relationship kenttä ei ole pakollinen ja suhteen määrittää taattavalle oikein, tallennus onnistuu ongelmitta.

-Kun BorrowerMandatoryField asetuksessa relationship kenttä on pakollinen ja suhde on määritetty taattavalle oikein, taattava tallentuu nyt oikein

Eli nyt vaikuttaa toimivan oikein

**Comment by johannaraisa** [comment]
Laitan korjausta vielä tähän. BorrowerUnwantedField-asetus vaikuttaa tähän. OUTIssa kentät on hävitetty tosta ruudulta kokonaan ja Vaskissa ne on siellä vaikkakin piilotettuna.

**Comment by johannaraisa** [comment]
Nyt voisi kokeilla uudestaan, ctrf+f5 ennen lomakkeen täyttöä. Aktivoin OUTIssa sen relationshipin pakolliseksi ja poistin siitä borrowerRelationshipistä viimeisen putken.

**Comment by pirliis** [comment]
Testaukset OUTIn nextillä.

Nyt nämä toimivat kuin pitääkin:
- kun luo uuden lapsiasiakkaan, jolle lisätty takaaja, mutta Suhde-kenttä jätetään tyhjäksi -> ei pysty tallentamaan asiakastietoa, herjaa Suhde-kentän tiedon puuttumisesta. 
- jos lisää toisen takaajan, mutta jättää Suhde-kentän tyhjäksi -> ei pysty tallentamaan asiakastietoa, herjaa Suhde-kentän tiedon puuttumisesta.
- jos takaajalle tallentaa uuden taattavan, mutta jättää Suhde-kentän tyhjäksi -> ei pysty tallentamaan, herjaa Suhde-kentän tiedon puuttumisesta.

Nämä ei toimi:
- kun luo uuden lapsiasiakkaan, jolle ei lisätä takaajaa -> antaa tallentaa asiakastiedot ilman takaajatietoa
- kun käy muokkaamassa lapsiasiakkaan tietoja, jolla ei ole takaajaa -> tallennus vaiheessa ei tule ilmoitusta takaajatiedon puuttumisesta
- jos poistaa takaajatiedon lapsiasiakkaalta-> asiakastietojen tallennus onnistuu ilman takaajaa

**Comment by johannaraisa** [comment]
> Nämä ei toimi:
> 
>     * kun luo uuden lapsiasiakkaan, jolle ei lisätä takaajaa -> antaa tallentaa asiakastiedot ilman takaajatietoa
> 
>     * kun käy muokkaamassa lapsiasiakkaan tietoja, jolla ei ole takaajaa -> tallennus vaiheessa ei tule ilmoitusta takaajatiedon puuttumisesta
> 
>     * jos poistaa takaajatiedon lapsiasiakkaalta-> asiakastietojen tallennus onnistuu ilman takaajaa

Huomasin omissa testauksissa, että teillä ei ollut se ChildNeedsGuarantor päällä. En puuttunut tuohon, ku en ole varma miten sen pitää teillä olla.

**Comment by atarnus** [comment]
Jeps, meillä oli varmaan aiemmilla testeillä jäänyt tuo asetus jostain syystä pois päältä, kiitos!

Nyt tosiaan korjaantuivat nuo kolme kohtaa oikealla asetuksella. Ja testasin että ne Pirliin ylemmät kohdat vielä toimivat myös samaan tapaan kuin ennen.

Vähän jännästi tuossa näyttää olevan kahta erilaista tarkistustapaa takaajasuhteelle käytössä.

Yleensä puuttuva takaajatieto antaa tämän perusvirheen:
![Screenshot 2024-11-08 at 09-57-07 Lisää asiakas (Lapsi omatoimi kielletty) › Asiakkaat › Koha](https://github.com/user-attachments/assets/a6172274-1f3e-4971-8903-e47a618bd425)

Mutta jos virheilmoitusta korjailee, ja onnistuu tekemään lisäksi uuden virheellisen tiedon (tapahtuu esim. kun korjaa puutteellisen takaajatiedon, ja lisää samalla uuden takaajan, jolta puolestaan puuttuu takaajatieto) tulee joskus erilainen virheilmoitus: 
![image](https://github.com/user-attachments/assets/0e9d7d1e-06c1-4407-bd9e-9db49160ae25)

Tämä jälkimmäinen on sitten taas näitä virhetilanteita, joissa sivu latautuu uudestaan, ja viestiasetuksiin tehdyt muutokset häviävät sen yhteydessä. Liittyy tiketteihin: https://github.com/KohaSuomi/Koha/issues/839 ja https://github.com/KohaSuomi/Koha/issues/1474

**Comment by johannaraisa** [comment]
Mutta tämä siis pääsääntöisesti toimii, virheilmoitukset vaan on jänniä? En enää viitsi tehdä paljoa muutoksia tähän, kun päivitys on lähellä. Noita voidaan viilata myöhemminkin.

**Comment by atarnus** [comment]
Joo, minusta tuo viestiasetusten potentiaalinen katoaminen on vähän eri ongelma, eikä tämän sörkkiminen korjaisi samaa ongelmaa noissa toisissa tiketeissä. Eikä tuo tilanne edes todennäköisesti tule vastaan käytännössä juuri koskaan. Eli tämä takaajan tallentaminen ok.

**Comment by johannaraisa** [comment]
Tämä voidaan siis viedä tällaisena, suljen tiketin.
