### ISSUE TITLE
Asiakasta tallentaessa tuplatietovaroituksesta ei onnistu siirtyä muokkaamaan olemassa olevaa asiakasta

### ISSUE THREAD

**Issue by atarnus** [KohaSuomi/Koha-24.05#109]
### Mikä vikana?

Jos yrittää tallentaa uutta asiakasta (joko Uusi asiakas tai Lisää huollettava -toiminnolla), ja Koha herjaa potentiaalisesta duplikaatista, ei olemassa olevan asiakkaan muokkaamiseen pääsekään. 
![image](https://github.com/user-attachments/assets/a174ac2d-4c85-490b-b268-fcd41fea1e1c)

Nappia klikkaamalla tulee seuraava virheilmoitus:
![image](https://github.com/user-attachments/assets/7b195275-c507-4286-b10d-d8003fedbd97)

Testillä näyttäisi siirtyvän ihan mainiosti asiakastietojen muokkaussivulle.

### Kuinka toistaa ongelma/asia

1. Katso jonkin jo järjestelmässä olevan asiakkaan nimi ja syntymäaika.
2. Yritä luoda uusi asiakas samalla nimellä ja syntymäajalla.
3. Valitse 'Kopio asiakastiedot?' -kohdassa 'On tuplatieto. Muokkaa olemassa olevaa asiakasta'
4. Huomaa virheilmoitus.

**Comment by johannaraisa** [comment]
Tämä virhe löytyy yhteisöstäkin, tein siitä tiketin [37523](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37523)

**Comment by johannaraisa** [comment]
Nyt tähän on korjaus, saa testata.

**Comment by pknuuti** [comment]
Testattu Vaaran nextillä. Kun valitsin 'Kopio asiakastiedot?' -kohdassa 'On tuplatieto. Muokkaa olemassa olevaa asiakasta', tuli näytölle tupla-asiakkaan tiedot, kuten pitääkin. Eli korjaus toimii.

**Comment by atarnus** [comment]
Minulla tuli ohimennen testattua myös Outi-nextillä, kun katsoin tuota takaajasuhdeasiaa. Eli toimii nyt.

**Comment by MikkoLiimatainen** [comment]
Vaski-nextilläkin näyttäisi pääsevän olemassa olevan asiakkaan muokkaukseen. Toimii siis.

**Comment by johannaraisa** [comment]
Hyvä, suljen tiketin.
