### ISSUE TITLE
Fix open redirects  - ksdev/ks-0025-bug-37828-validate-before-redirecting-with-referer

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#11]
Fix open redirects in acquisitions. Tietoturvaominaisuus.

**Comment by johannaraisa** [comment]
Tämä on tuotu nexteille, yritän kirjoittaa jonkun testaussuunnitelman.

**Comment by johannaraisa** [comment]
Yhdistin tähän ks-0026 versiohaaran, jotta kumpikin on samassa.

**Comment by johannaraisa** [comment]
Testausohje:

1. Mene asiakkaan tietoihin ja sieltä mene vaihtamaan omaa kirjastopistettä.
2. Vaihda pistettä ja tallenna pisteen vaihdon jälkeen pitäisi latautua se sivu missä olit aikaisemmin.
3. Tee kohta yksi uudestaan.
4. Avaa selaimen hiiren oikealla inspect-näkymä kirjastopistealasvetolaatikon päällä.
5. Etsi kuvan elementti.
![image](https://github.com/user-attachments/assets/fa14245e-4df2-450b-9d27-d5c7822cd516)
6. Vaihda input-kentän value-arvoksi joku muu sivu esim. https://github.com
7. Vaihda kirjastopistettä ja tallenna.
8. Sinun pitäisi päätyä Kohan etusivulle.

**Comment by ajrajala** [comment]
Testausohjeen mukaisesti tekemällä toimii kuten kuvattu eli kohdassa 8 päädyin Kohan etusivulle.

**Comment by johannaraisa** [comment]
Minäkin olen tätä testannut, joten eiköhän tuo ole kunnossa. Suljen tiketin.
