### ISSUE TITLE
"Uusi kaikki"-painike siirtää käyttäjän "Tietojen vienti"-työkaluun

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#110]
### Mikä vikana?

Jos asiakkaan lainojen uusinta kerrat ovat täyttyneet ja käyttäjä painaa "Uusi kaikki"-painiketta, Koha siirtää käyttäjän "Tietojen vienti"-työkaluun.

**Comment by emta001** [comment]
Korjaus viety yhteisöön, odotellaan palautetta ja tuodaan sitten meillekin.

**Comment by emta001** [comment]
Tähän mennessä yhteisöön on tullut yksi sign off. Eiköhän se riitä palautteeksi :D

**Comment by emta001** [comment]
Testipläni:
1. Etsi asiakas, jonka kaikkien lainojen uusimiskerrat ovat täyttyneet.
2. Paina "Uusi kaikki"-painiketta.
=> Näytölle tulisi ilmestyä pop-up, jossa lukee "There are no items to be renewed.".

**Comment by ajrajala** [comment]
Toimii kuten ohjeistettu.

**Comment by ReettaSiili** [comment]
Kyllä vaan, Siili nextillä ilmestyy pop-up There are no items to be renewed.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
