### ISSUE TITLE
Peruuta valitut -napilla perutut varaukset eivät poistu

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-24.05#111]
### Mikä vikana?

Jos tietueen varausjonossa valitsee yhden tai useamman varauksen ja klikkaa sitten Peruuta valitut -nappia ja vahvistaa haluavansa poistaa varaukset, eivät varaukset siltikään poistu. Poistotyö ei mene Taustatöihin.

### Mitä pitäisi tapahtua

Varausten poisto pitäisi mennä Taustatöihin ja varausten pitäisi poistua työn valmistuttua.

### Kuinka toistaa ongelma/asia

1. Hae tietue, jossa on varauksia, esim. https://outi-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=2331312
2. Valitse useampi varaus ja klikkaa sitten Peruuta valitut -nappia.
3. Mene Ylläpitoon Taustatöiden hallintaan ja tarkista, syntyikö poistosta taustatyö.
4. Päivitä tietueen varausjono-sivu ja huomaa, etteivät varaukset poistu.

**Comment by pknuuti** [comment]
Vaaran nextillä testattu, toimii kuten Anneli mainitsi eli poistettavat varaukset eivät mene taustatöihin eivätkä ne poistu. Kokeilin kahdella varauksella nimekkeessä.

**Comment by LastuLauriH** [comment]
Lastu-nextissä ei myöskään tule mitään taustatöihin, ja varaukset jäävät jonoon.

**Comment by LeenaKinnunen** [comment]
Lapissakaan ei toimi oikein, ei poistu varaukset eikä tule taustatöihin.

**Comment by johannaraisa** [comment]
Tähän on korjaus nexteillä, koodi oli muuttunut niin paljon että vaihdoin tuon monen poiston käyttämään myös RESTiä

**Comment by AnneliO** [comment]
Testasin outi-nextillä ja ainakaan siellä varaukset eivät edelleenkään poistuneet Peruuta valitut -napilla poistettaessa.

**Comment by johannaraisa** [comment]
Nextit oli levyjärjestelmärempan jäljiltä vanhassa versiossa, lisäsin nuo kommitit uudestaan ja nyt niiden pitäisi olla taas nexteillä.

**Comment by Kati-Helle** [comment]
Helle-nextin tietueen varauksissa Peruuta varaukset -painikkeella poistuu yksi tai useampi poistettavaksi valittu varaus.

**Comment by johannaraisa** [comment]
Lisäsin tuohon vielä selkeämpää informaatiota siitä, että jotain poistetaan. CTRL+F5, ni saa viimeisimmät muutokset toimimaan.

**Comment by AnneliO** [comment]
Siili-nextillä poistui nyt kaikki valitsemani varaukset ja vahvistuspopparissa näytettiin poistettavien varausten tunnisteet.

**Comment by LeenaKinnunen** [comment]
Lapissa toimii myös oikein, valitut varaukset poistui ja varauspopparissa (joka vilahtaa nopeasti) näkyi varausten tunnisteet.

**Comment by johannaraisa** [comment]
Tämä näyttäisi toimivan, suljen tiketin.
