### ISSUE TITLE
Tietuelähteet -sivu ei avaudu

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-24.05#112]
### Mikä vikana?

Versiossa 24.05 on uusi toiminto Tietuelähteet / Record sources, johon pääsee ylläpidon kautta. Kun sivulle yrittää, tulee Virhe 404. Konsolissa tulee virheilmoitus:

GET
https://outi-next.koha-suomi.fi/cgi-bin/koha/admin/record_sources
[HTTP/1.1 404 Not Found 511ms]

### Mitä pitäisi tapahtua

Sivu pitäisi avautua.

### Kuinka toistaa ongelma/asia

1. Mene Ylläpito -> Tietuelähteet
2. Huomaa, ettei sivu avaudu

**Comment by johannaraisa** [comment]
Tää on taas näitä polkuja jotka luodaan yarnilla. On tuolla utilityssä omassa hakemistossa, mutta ei ilmeisesti ole linkitetty nextillä. @CodoDerDritte oliko sulla joku ajatus tähän?

**Comment by johannaraisa** [comment]
Nyt tämä toimii, vaati Apacheen rewrite-ohjauksen. Käyn lisäämässä muuallekin.

**Comment by AnneliO** [comment]
Kiitos! outi-nextillä toimii nyt. siili-nextillä ei vielä.

**Comment by ajrajala** [comment]
Vaski-nextillä https://vaski-next.koha-suomi.fi/cgi-bin/koha/admin/record_sources aukeaa.

**Comment by johannaraisa** [comment]
Näyttää se nyt avautuvan siili-nextillä.

**Comment by pknuuti** [comment]
Vaaran nextillä sivu https://vaara-next.koha-suomi.fi/cgi-bin/koha/admin/record_sources aukeaa ja tulee tieto "Tietuelähteitä ei ole määritelty". Mitähän siellä pitäisi olla?

**Comment by AnneliO** [comment]
> Vaaran nextillä sivu https://vaara-next.koha-suomi.fi/cgi-bin/koha/admin/record_sources aukeaa ja tulee tieto "Tietuelähteitä ei ole määritelty". Mitähän siellä pitäisi olla?

Ei siellä taida kuulua olla oikeastaan mitään, koska se on täysin uusi ominaisuus. 

[Koha-manuaalissa Tietuelähteiden esittely](https://koha-community.org/manual/24.05/en/html/administration.html#record-sources)

[Uutta Kohan versiossa 24.05 - Tietuelähteet](https://github.com/KohaSuomi/Koha-24.05/wiki/Uutta-versiossa-24.05#tietuel%C3%A4hteet)

Sinne voisi lisätä tietuelähteiden tunnisteita, mutta niitä vastaavia tunnisteita saa lisättyä tällä hetkellä tietueiden biblio_metadata-tauluun vain APIn kautta.

**Comment by AnneliO** [comment]
Tämä toimii nyt, joten suljen tiketin. Kiitos! :)
