### ISSUE TITLE
Varaaminen ei onnistu

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-24.05#113]
### Mikä vikana?

Testasin outi-nextillä ja siili-nextillä ja tällä hetkellä varaaminen ei onnistu varauksen teko -sivulla (esim. https://outi-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=2346970). Kun kirjoittaa/lisää asiakkaan kirjastokortin tai hakee nimellä, siirtyy sivu osoitteeseen https://outi-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl? (ilman biblionumberia) ja asiakashaku jää junnaamaan.

### Kuinka toistaa ongelma/asia

1. Hae jokin tietue, esim. https://outi-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=2346970
2. Klikkaa Varaa teos -nappia tai mene Varaukset-välilehdelle vasemmasta reunasta.
3. Hae asiakasta kirjastokortin numerolla tai nimellä (tai osalla siitä)
4. Huomaa, että sivu siirtyy varaussivulle, jossa ei ole tietoa varattavasta tietueesta ja asiakashaku jää junnaamaan.

**Comment by pknuuti** [comment]
Vaaran nextilläkään tuo ei onnistu. Sensijaan kun lähtee asiakkaasta liikkeelle Hae ja varaa-toiminnolla, varaaminen onnistuu.

**Comment by LeenaKinnunen** [comment]
Ei onnistu Lapissakaan varauksen teko näillä reiteillä.

**Comment by emta001** [comment]
Selaimen konsoliin tulee outi-nextillä error:

>Uncaught TypeError: n.settings()[0].aoColumns[t] is undefined

Vaikuttaisi olevan datatable virhe siis. Jostain syystä en saa tätä omilla testeillä toistumaan.

**Comment by emta001** [comment]
Tulee täällä muutakin kummaa; `"Expected integer - got string.", path: "/biblio_id"`.

**Comment by emta001** [comment]
No nyt toistuu, mutta vain jos painan Hae-nappia asiakashausta.

**Comment by AnneliO** [comment]
Tämä toimii nyt ja ongelma johtui tiketistä #33, joka todettiin tässä yhteydessä tarpeettomaksi, koska yhteisössä on saatu toimimaan asiakastietojen haun tulostaulukossa sarakkeiden piilotus. Muutos liittyi alunperin [tikettiin #571](https://github.com/KohaSuomi/Koha-24.05/wiki/Muistilista-p%C3%A4%C3%A4k%C3%A4ytt%C3%A4jille#piilota-varaussivulla-asiakastulostaulukosta-syntym%C3%A4aika-osoite-ja-puhelinnumero).

**Comment by AnneliO** [comment]
[Pääkäyttäjien muistilistalle](https://github.com/KohaSuomi/Koha-24.05/wiki/Muistilista-p%C3%A4%C3%A4k%C3%A4ytt%C3%A4jille#piilota-varaussivulla-asiakastulostaulukosta-syntym%C3%A4aika-osoite-ja-puhelinnumero) lisätty tieto, miten tiketin #33 piilotukset voi jatkossa tehdä.
