### ISSUE TITLE
Jos käyttäjällä on vain list_borrowers-käyttäjäoikeus, tulee asiakashaussa Internal server error 

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-24.05#114]
### Mikä vikana?

Jos käyttäjällä on vain uusi list_borrowers-käyttäjäoikeus, eikä edit_borrowers-oikeutta, tulee asiakashaussa poppari, joss lukee 500: Internal server error ja pitkä litania syitä

Jotain meni pieleen taulua ladattaessa.
500: Internal Server Error. 
Expected boolean - got null.
Expected boolean - got null.
Expected string - got null.
Expected string - got null.
Expected string - got null.
Expected integer - got null.
Expected integer - got null.
Expected integer - got null.
Expected boolean - got null.
Expected boolean - got null.
Expected string - got null.
Expected boolean - got null.
Expected boolean - got null.
Expected string - got null.
Expected string - got null.
Expected string - got null.
Expected integer - got null.
Expected integer - got null.
Expected integer - got null.
Expected boolean - got null.
Expected boolean - got null.
Expected string - got null.
Expected boolean - got null.
Expected boolean - got null.
Expected string - got null.
Expected string - got null.
Expected string - got null.
Expected integer - got null.
Expected integer - got null.
Expected integer - got null.
Expected boolean - got null.
Expected boolean - got null.
Expected string - got null.

Selaimen konsolissa tulee tällainen virheilmoitus:

XHRGET
https://siili-next.koha-suomi.fi/api/v1/patrons?_page=1&_per_page=20&q=[{"-and":[[{"me.firstname":{"like":"%aa%"}},{"me.middle_name":{"like":"%aa%"}},{"me.surname":{"like":"%aa%"}},{"me.cardnumber":{"like":"%aa%"}},{"me.userid":{"like":"%aa%"}},{"me.mobile":{"like":"%aa%"}}]]},{"-or":[{"me.firstname":{"like":"%aa%"}},{"me.middle_name":{"like":"%aa%"}},{"me.surname":{"like":"%aa%"}},{"me.cardnumber":{"like":"%aa%"}},{"me.userid":{"like":"%aa%"}},{"me.mobile":{"like":"%aa%"}}]},{"-and":[[{"extended_attributes.value":{"like":"%aa%"},"extended_attributes.code":[["AUTOTYPE","HOLDID","SSN","TOIMITTAJA"]]}]]}]&_match=contains&_order_by=+me.surname,+me.firstname,+me.middle_name,+me.othernames,+me.street_number,+me.address,+me.address2,+me.city,+me.state,+me.postal_code,+me.country
[HTTP/1.1 500 Internal Server Error 763ms]

### Mitä pitäisi tapahtua

list_borrowers-käyttäjäoikeuden kuvauksen " Search, list and view patrons" perusteella hakeminen pitäisi onnistua.

### Kuinka toistaa ongelma/asia

1. Mene asiakashakuun ja tee haku esim. aa
2. Saa virheilmoituspoppari

**Comment by johannaraisa** [comment]
Virhe palvelimella, onkohan tuo joku meidän lisäys?
[ERROR] GET /api/v1/patrons: unhandled exception (DBIx::Class::Exception)<<DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::mysql::st execute failed: Unknown column 'extended_attributes.attribute' in 'where clause'

**Comment by johannaraisa** [comment]
Tuo virhe tapahtuu siis myös kun katselee API-osoitetta omilla tunnuksilla. Tuossa hakulauseessa on virhe, mistä tuo on peräisin?

**Comment by johannaraisa** [comment]
tai ei ehkä, mutta miksi se yrittää tunkea jotain sellaista arvoa mitä ei ole olemassa.

**Comment by johannaraisa** [comment]
Tää onki hauska, virhe tulee jos selaimesta yritän samaa GET-osoitetta.

**Comment by johannaraisa** [comment]
Nyt yhteisön korjaus [37378](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37378) on tuotu nexteille.

**Comment by johannaraisa** [comment]
Tämä taisi korjaantua tuolla yhteisön fiksillä, suljen tiketin.

**Comment by johannaraisa** [comment]
Tämä tiketti on kunnossa, suljen sen.
