### ISSUE TITLE
Tietueen varaukset-sivun Päivitä varaukset-toiminnolla virhe 403

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha-24.05#115]
### Mikä vikana?

Tietueen varaukset-sivun Päivitä-varaukset painikkeen käyttäminen johtaa virheilmoitukseen 
![image](https://github.com/user-attachments/assets/5f0b239c-489e-4a93-8403-fca3e4900b5b)
![image](https://github.com/user-attachments/assets/1cb7c373-0440-45e1-afae-91bf82aa7b3a)

**Comment by lmstrand** [comment]
Kun painaa vain nappia lokille tulee:

Programming error - No CSRF token passed for POST https://vaara-next.koha-suomi.fi/intranet/reserve/modrequest.pl (referer: https://vaara-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=11729157) at /home/koha/Koha/Koha/Middleware/CSRF.pm line 82.

**Comment by LeenaKinnunen** [comment]
Sama virhe Lapin nextillä.

**Comment by johannaraisa** [comment]
Otan Vaskin nextiltä hetkeksi pois tuon intranetuserjs:n.

**Comment by johannaraisa** [comment]
> Otan Vaskin nextiltä hetkeksi pois tuon intranetuserjs:n.

Ei johtunut noista javascripteistä, tutkitaan lisää.

**Comment by johannaraisa** [comment]
Tähän on korjaus nexteillä.

**Comment by sksandel** [comment]
Toimii: Päivitä-napista ei tule enää virheilmoitusta.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii myös.

**Comment by johannaraisa** [comment]
Todettakoon, että tämä toimii ja suljetaan tiketti.
