### ISSUE TITLE
Damaged/Vaurioitunut-arvo ei näy perustiedot-näytöllä Tila-sarakkeessa

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-24.05#116]
### Mikä vikana?

Nextillä niteen damaged/vaurioitunut-tila ei näy tietueen perustiedot-näytön Kokoelma-taulukossa Tila-sarakkeessa ollenkaan. Tähän asti se on siinä näkynyt.

Nextillä
![kuva](https://github.com/user-attachments/assets/875047ad-c776-47ad-a124-d71373d0873c)

Testillä
![kuva](https://github.com/user-attachments/assets/fdd4f9be-5b63-47df-a4ae-0f283b8f246c)

### Mitä pitäisi tapahtua

Damaged-tila pitäisi näkyä Tila-sarakkeessa.

### Kuinka toistaa ongelma/asia

1. Mene johonkin tietueeseen
2. Muuta yhden niteen Damaged/Vaurioitunut-tila ja tallenna.
3. Mene tietueen perustiedot-näytölle
4. Huomaa, että muuttamasi niteen Tila-sarakkeessa ei näy, että niteellä on Damaged/Vaurioitunut-tila

**Comment by AnneliO** [comment]
Näköjään tästä on bugzillassa bugi ja korjaus: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37078

**Comment by johannaraisa** [comment]
Nyt pitäisi olla korjaus nexteillä.

**Comment by AnneliO** [comment]
Jees! Ainakin siili-nextillä Tila-sarakkeessa näkyy nyt vaurioitunut/damage-tilan kuvaus. :)

**Comment by LeenaKinnunen** [comment]
Lapin nextilläkin näkyy oikein.

**Comment by Kati-Helle** [comment]
Helle-nextissä Kadonnut näkyvillä perustiedot-näytön Tila-sarakkeessa

![kuva](https://github.com/user-attachments/assets/fa72212c-ffbb-49c8-a185-88b6b28d424d)

**Comment by johannaraisa** [comment]
Juu, eiköhän tämä toimi. Suljen tiketin.
