### ISSUE TITLE
Löytyi virheitä : osakohdevirheitä

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha-24.05#117]
### Mikä vikana?

Valitsin nextillä hakutuloksesta näytetäväksi tietueen biblionumber=1902565. Tietue näkyi oikein, mutta näytön yläosaan tuli ikkuna: Löytyi virheitä Osakohdevirheitä. 
![image](https://github.com/user-attachments/assets/99338f8f-be8b-486b-ad5a-ec6a4bace441)

Tämän jälkeen tiedonhaku lakkasi toimimasta, ja tulee virhe Unable to perform your search. Please try again.

**Comment by CodoDerDritte** [comment]
https://github.com/KohaSuomi/Koha-23x/issues/190

Tämä näkyy olevan ongelmana myös Lapissa. Jotain outoa tuossa nextien elasticsearchissa nyt on.

**Comment by CodoDerDritte** [comment]
Ongelma vaikuttaisi ehkä liittyvän siihen että yhdellä nodella oli liian monta Kohaa käynnissä. Johonkin resurssilimittiin tuo taitaa nyt päänsä iskeä. Siirsin Lapin nextin toiselle nodelle ja nyt haku toimii.

**Comment by LeenaKinnunen** [comment]
Samanlainen virheilmoitus on tullut Lapin tuotannossa  30.8.2024 'klo' 14.31
https://lappi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=11216&searchid=scs_1725015676200

Nyt virhettä ei tule.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 28.10.2024: Suljemme tämän tiketin. Jos ongelma toistuu, avataan sitten uudelleen.
