### ISSUE TITLE
API:t lokittumaan plack-api-error.logiin

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#118]
### Siirrettävä ominaisuus

Vaatii muutoksia log4perliin nexteillä.

**Comment by johannaraisa** [comment]
Nexteillä näyttää muutenkin olevan se log4perl erilainen kuin tuotannossa tai testeillä, voisi yhdenmukaistaa, että löytää lokit samoista paikoista jos niitä tarvitsee.

**Comment by CodoDerDritte** [comment]
Log4perl konfiguraatio nexteille on nyt kopioitu testeiltä ja korefreshit ajettu. Jos tulee ikävä nextien entistä log4perl.conf:ia, niin se löytyy vaski-nextiltä nimeltä log4perl.conf.old.
