### ISSUE TITLE
Uusinnalle asetettua poikkeavaa eräpäivää ei noudateta uusinnassa

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-24.05#119]
### Mikä vikana?

Huomattu vaski-nextillä, että uusinta ei käytä sille asetettua poikkeavaa eräpäivää vaan laina saa uuden eräpäivän normaalien laina-ja maksusääntöjen + eräpäiväkalenterin mukaan.

### Kuinka toistaa ongelma/asia

1. Avaa jonkin asiakkaan tiedot, jolla on uusittavissa oleva laina (esim. https://vaski-next.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=328971)
2. Valitse uusittava laina ja aseta Uusinnan eräpäivä -kenttään esim. huominen päivä
3. Klikkaa "Uusi valitut niteet"
4. Huomaa, että lainalle muodostui eräpäivä nidetyypin mukaan eikä asettamasi eräpäivä

**Comment by pknuuti** [comment]
Vaaran nextillä toimii samalla tavalla väärin eli ei huomioi uusittavalle annettua poikkeavaa eräpäivää vaan uusii normaalin nidetyypin lainasäännön mukaisesti.

**Comment by lmstrand** [comment]
Yhteisössä tiketti https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37332

**Comment by lmstrand** [comment]
Tiketin korjaus viety nexteille.

**Comment by Kati-Helle** [comment]
Helle-nextissä valittu nide uusiutuu kalenterista valitun eräpäivän mukaan. 
Testasin muuttamalla eräpäivän olemassa olevaa eräpäivää myöhemmäksi. Myös eräpäivän muuttaminen olemassa olevaa eräpäivää aikaisemmaksi onnistuu.

**Comment by pknuuti** [comment]
Testasin tätä nyt uudelleen Vaaran nextillä ja toimii kuten pitääkin eli uusinnassa eräpäiväksi tulee se, minkä valitsin niteelle eräpäiväksi (oli se sitten eilen tai viikon päästä tms.).

**Comment by lmstrand** [comment]
Kiitos testeistä. Tämä kunnossa.
