### ISSUE TITLE
Fix open redirect in set-library - ksdev/ks-0026-K23-16-set-library-open-redirect 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#12]
Fix open redirect in selectbranchprinter. Tietoturvaominaisuus.

**Comment by johannaraisa** [comment]
Tämä on tuotu nexteille, kirjoitan jonkunlaisen testaussuunnitelman.

**Comment by johannaraisa** [comment]
Tämän korjaus on siirretty #11, suljen tiketin.
