### ISSUE TITLE
Kyyti: nextillä ilmoittaa monesta tietueesta "Tietuetta X ei ole tietokannassa"

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha-24.05#120]
### Mikä vikana?

Kyytin Nextillä tiedonhaku toimii, mutta haun tuloslistalla on paljon tietueita, joiden perustieto-näytölle ei pääse, vaan Koha ilmoittaa, että "Tietuetta X ei ole tietokannassa". Eivät löydy deletedbiblio-taulustakaan.

Myös Kohan järjestelmätiedoissa on varoitus "328 tietue(tta) puuttuu tietueiden kokonaismäärästä: 1648 indeksissä kyyti-next_biblios."

Hankaloittaa voimakkaasti nextin käyttöä tällä hetkellä.

Jokin indeksiongelma?

### Jotain muuta?

Esim. tietueet: 
1511355
1511349
1497338
1468595

**Comment by emta001** [comment]
Ajoin uudelleenindeksoinnin, toimiiko nyt paremmin?

**Comment by Tuomas-Kyyti** [comment]
Kyllä, nyt toimii. Kiitos
