### ISSUE TITLE
Tarkka tiedonhaku ei toimi nextillä

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-24.05#121]
### Mikä vikana?

OUTIn nextillä ei toimi tarkka tiedonhaku. Tulee virheilmoitus: "Unable to perform your search. Please try again."

Nidehaku näyttäisi toimivan.

**Comment by emta001** [comment]
Lokeilta kattelin, että haku tyssää seuraavaan virheeseen:

>[2024/09/13 11:20:12] [WARN] [Request] ** [http://localhost:9200]-[400] [illegal_argument_exception] Fielddata is disabled on [date-of-publication__sort] in [outi-next_biblios]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [date-of-publication__sort] in order to load field data by uninverting the inverted index. Note that this can use significant memory.

**Comment by emta001** [comment]
Epäiltiin ensin, että tuossa date-of-publication-kentässä olis nyt jotakin vialla ja kokeiltiin muuttaa sen tyyppiä muotoon "vuosi". Mutta siinä vaiheessa Hakukoneen asetukset-sivulla rupesi tulemaan herjaa, että indeksi on tehtävä uudestaan. Nyt uudelleenindeksoinnin jälkeen haku toimii taas ja lokeille ei tule enää herjaa.

**Comment by pirliis** [comment]
Nyt nextin tarkka haku toimii! Kiitos selvityksestä ja korjauksesta!

**Comment by pirliis** [comment]
OUTIn nextillä taas Tarkka haku ja Hae tietokannasta antaa ilmoitusta: _Virhe: Unable to perform your search. Please try again._

**Comment by emta001** [comment]
Jostain syystä Elasticsearch oli päättänyt pistää pillit pussiin ja se oli käytävä potkimassa takaisin käyntiin. Nyt näyttäs haku taas toimivan.

**Comment by pirliis** [comment]
Haku taisi toimi jo välillä, mutta nyt taas ei. Tulee sama ilmoitus: _Virhe: Unable to perform your search. Please try again._ 

Kävisitkö potkaisemassa taas takaisin käyntiin. :D

**Comment by emta001** [comment]
Tällä kertaa ongelmana onkin tämmönen virhe

>Exception 'Koha::Exception' thrown 'Unable to update mappings for index "outi-next_biblios". Reason was: "can't merge a non object mapping [carrier-type-term__suggestion] with an object mapping". Index needs to be recreated and reindexed'

**Comment by emta001** [comment]
Ja nyt toimii taas. Mikähän ihme tuolla oikein on ja miksei muualla tule tämmöstä :sweat_smile:

**Comment by pirliis** [comment]
Kiitos, taas toimii. On vähän kummallista, jos vain OUTIn nexti juntturoi.

**Comment by emta001** [comment]
Nexteille on tehty säätöjä tuohon indeksointiin, toivottavasti se nyt toimii kuten pitää. Ainakaan viikonlopun alasajolla ei näyttäisi olleen enää vaikutusta tähän. Suljen tiketin, avataan uudestaan jos tulee tarve.
