### ISSUE TITLE
SQL-raportteja ei pysty poistamaan

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#122]
### Mikä vikana?

Tiketin #104 yhteydessä huomattiin, ettei SQL-raportteja pysty poistamaan virkailijaliittymän kautta. Poista-painikkeen painaminen ei tee muuta kuin pompauttaa sivun takaisin ylös ja URL:in perään tulee #-merkki. Tähän löytyy yhteisöstä korjaus, [bug 37270](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37270).

### Mitä pitäisi tapahtua

SQL-raporttien poistamisen tulisi onnistua virkailijaliittymästä.

### Kuinka toistaa ongelma/asia

1. Mene sivulle Raportit -> Käytä tallennettua raporttia.
2. Yritä poistaa jokin raportti (tai luo uusi, jonka saa poistaa).
3. Yritä poistaa raportti.
=> Poista-napin painaminen ei tee mitään, sivu hyppää takaisin ylös, mutta raportti ei poistu.

**Comment by pknuuti** [comment]
Vaaran nextillä testattu, että toimii juuri kuten Emmi kuvasi eli raportti ei poistu poista-napista.

**Comment by emta001** [comment]
Nyt on paikka nexteillä.

**Comment by pknuuti** [comment]
Vaaran nextillä testattu paikkaus toimivaksi eli raportti poistuu poista-napista kuten pitääkin.

**Comment by Rvallim0** [comment]
Vaskin nextillä testattu raporttien poistamista "Tallennetut raportit" välilehden kautta, toimii ongelmitta.

Edit: Kun toiminnot sarakkeesta valitsee "muokkaa", "Näytä" tai "Käynnistä", niistä aukeavalta sivulta muokkaa-valikosta poistaminen ei onnistu, samalla tavalla kuin Helle-nextissä

**Comment by Kati-Helle** [comment]
Helle-nextissä 

- raportti poistuu raporttilistauksesta Poista-painikkeella

- raportti ei poistu raporttihaun hakutulosnäytön Muokkaa/Poista-painikkeella 
  ![kuva](https://github.com/user-attachments/assets/72b16fbf-4ca2-444d-9da3-fb6bf07c0a45)

**Comment by emta001** [comment]
Testasin yhteisössä ja siellä sama ongelma jonka Kati hoksasi.

**Comment by emta001** [comment]
> Testasin yhteisössä ja siellä sama ongelma jonka Kati hoksasi.

Yhteisöstä löytyi korjaus, [bug 37328](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37328).

**Comment by emta001** [comment]
Nyt on uusi korjaus tuotu nexteille ja siihen liittyykin lisäksi vielä väliaikainen CSS-rimpsu.

```
.dropdown-menu > li > form > a {
  display: block;
}
```

Näin joudutaan tekemään siis sen vuoksi, että tuossa muutoksessa "Poista"-painikkeen paikka siirtyy lomakkeella hieman, eikä sen muotoilu enää toimi vanhalla CSS-säännöllä. Painikkeessa on toki käytetty luokkaa dropdown-item, mutta sen tyylisääntö ei sisälly vielä versioon 24.05 eikä sen tekeminen suoraan Kohaan ole järkevää, kun kyseessä on kuitenkin väliaikainen paikkaus. Joten mennään nyt tällä.

**Comment by Kati-Helle** [comment]
Helle-nextissä testaus. Lisäsin CSS-rimpsun

- raportti ei poistu hakutulosnäytöltä poistaessa
- raporttilistaussivua alaspäin vierittäessä näyttö värähtelee eikä vierity yhtä sutjakkaasti kuin ilman rimpsua

Lisätietona:
Kohan osoiteriville muodostuu Poista-painikkeella risuaita # osoitteen loppuun

**Comment by Rvallim0** [comment]
Vaskin nextille lisätty CSS-rimpsu, ei korjannut ongelmaa.

**Comment by emta001** [comment]
Nyt pitäisi toimia oikein.

**Comment by Rvallim0** [comment]
Vaskin nextillä nyt testattu, raporttien poistaminen toimii nyt.

**Comment by Kati-Helle** [comment]
Joo, Helle-nextissä poistuu, poiston varmistusviestikin tulee nyt näkyviin
![kuva](https://github.com/user-attachments/assets/e9940f60-5aef-4a74-8cb7-4321702e8094)

Muutoksena on nyt myös se, että Raportit-toiminnon avatessa raportit eivät ole ID-numeron mukaisessa järjestyksessä
![kuva](https://github.com/user-attachments/assets/7044a6f8-2e85-4eb6-8418-2dfef98a7be5)

**Comment by Kati-Helle** [comment]
Lisähuomiona, että raportin hakutuloksen Muokkaa-painikkeesta puuttuu nyt Muokkaa-vaihtoehto
![kuva](https://github.com/user-attachments/assets/60eb9cb4-63f6-45b0-992f-c5d69cc1c9d7)

**Comment by emta001** [comment]
Vilkaisin Katin kommenttien perusteella vielä testiltä. Sielläkään raportit eivät ole ID:n mukaisessa järjestyksessä. Myöskään Muokkaus-sivulla ei ole Muokkaa-vaihtoehtoa, eikä varmasti tarviikaan, koska käyttäjähän on silloin jo Muokkaus-sivulla.

**Comment by Kati-Helle** [comment]
Tosiaan, tuotannossakaan Muokkaa-sivulla ei ole Muokkaa-vaihtoehtoa. Vertasin tilannetta tähän tikettiin aiemmin lisäämääni näyttökuvaan vastaavasta tilanteesta.

**Comment by AnneliO** [comment]
Raporttien taulukon oletusjärjestyksen pystyy valitsemaan Määrittely-napin takaa

![kuva](https://github.com/user-attachments/assets/b482e561-ad00-4e30-98a2-a69aa685f98b)

Kati, aiemmassa kuvassa sulla on lista raporteista, myöhemmässä olet muokkaamassa. :)

**Comment by Kati-Helle** [comment]
Kiitos Anneli tiedosta. Helle-tuotannossa report-id:n mukainen järjestys valittuna, testillä ja nextissä ei.

**Comment by emta001** [comment]
Näiden testien perusteella korjaus toimii. Suljen tiketin.
