### ISSUE TITLE
Myöhässä olevia lainoja -viestin linkki lainoihin ei toimi Nextillä

### ISSUE THREAD

**Issue by iinaniemi** [KohaSuomi/Koha-24.05#123]
### Mikä vikana?

Kun Kohassa asiakkaalla on myöhässä olevia lainoja, tiedot ja lainaus-sivuilla on teksti "Myöhässä olevat lainat: Asiakkaalla on myöhässä olevia lainoja [Katso korostetut kohteet alla]"

Tuotannossa tuo Katso.. -linkki vain vie sivun alareunaan josta voi sitten klikata lainat auki. Nextillä tosin tuo nappi ei näytä sitä tekevän. URL-riville tulee samalla lailla loppuun #checkouts kuten tuotannossakin, mutta nappi ei vie sivun loppuun lainojen kohdalle. Tuskin tuota nappia monikaan käyttää mutta onhan se vähän hassu nappi kun se ei nyt käytännössä tee mitään.

### Mitä pitäisi tapahtua

Linkin pitäisi viedä asiakassivun alareunaan lainojen kohdalle.

**Comment by AnneliO** [comment]
Jos nyt katon oikein, niin tuon lainataulun ankkuri on muuttunut, eikä se ole enää #checkouts vaan #checkouts_panel. Jos klikkaan ensin sitä linkkiä, jolloin osoiteriville tulee loppuun #checkouts ja muutan sen sitten muotoon #checkouts_panel ja painan enteriä, niin sivu siirtyy oikeaan kohtaan.

**Comment by AnneliO** [comment]
Yhteisöstä löytyikin tähän liittyen tiketti: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35987

**Comment by atarnus** [comment]
Jos tämä fiksataan niin suosittelen että lainaustaulu avataan sitten $("#issues-table-load-now-button").click()-tyyliin  koska tuohon nappiin on nyt liitetty se uusintanapin aktivointirimpsu, ja kuvittelisin että tämän linkin klikkaaminen tapahtuisi nimenomaan uusintamielessä aika usein.

**Comment by lmstrand** [comment]
Korjaus tähän on testattavana nexteillä. @atarnus en oo varma mitä tuolla kommentilla meinaat. Rikkooko korjaus jotain? Tein sen siis yhteisötiketin ehdotukseni tapaan.

**Comment by atarnus** [comment]
> Korjaus tähän on testattavana nexteillä. @atarnus en oo varma mitä tuolla kommentilla meinaat. Rikkooko korjaus jotain? Tein sen siis yhteisötiketin ehdotukseni tapaan.

Tein aikoinaan jonkun rimpsun siihen, kun lainat-sivulla ei se uusinta-nappi aktivoitunut viimeisimmän versiopäivityksen myötä. Että tuota #issues-table-load-now-button-nappia painaessa se alkoi tsekkaan milloin lataus on valmis ja tekee uusintanapin aktivoinnin tsekkauksen. Uskon (ja toivon) että tuo ongelma on tähän mennessä korjattu järkevämmin, ja tuon ylläolevan viestini voi jättää huomioimatta.

**Comment by atarnus** [comment]
Testattu Outi-nextillä. Toimii: skrollaa alemmas lainoihin, ja avaa myös lainatiedot näkyviin.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii.

Linkki englanniksi suomenkielisessäkin (ja ruotsinkielisessä) Kohassa
![kuva](https://github.com/user-attachments/assets/a946d9f0-c0b1-413f-8bb2-3194b32b9ef2)

**Comment by lmstrand** [comment]
Suomennos lisätään myöhemmin.
