### ISSUE TITLE
Tallennetuilla raporteilla Tabulaattorein erotellun tekstin lataaminen ei toimi

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha-24.05#124]
### Mikä vikana?

Kun raportin tuloksia yrittää ladata tabulaattorein eroteltuna tekstinä, muodostuu ladattuun tiedostoon vain sarakkeiden otsikot ja tulosmäärää vastaava määrä tyhjiä rivejä.

Korjaus näyttäisi löytyvän tiketistä: [https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37382](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37382)

**Comment by emta001** [comment]
Korjaus viety nexteille.

**Comment by MikkoLiimatainen** [comment]
Nyt sain ladattua tab-tiedoston, jossa on ihan sisältökin paikallaan. Tuo vain vaikuttaa nyt olevan monin verroin hitaampi kuin sama tuotannossa ja myös paljon hitaampi kuin csv:n lataus nextillä. Käytännössä n. 3-4 sekunnin lataus on nyt 40 sekunnin mittainen. Aika äkkiä mennään aikakatkaisun puolelle, jos tuo aika kasvaa käytännössä kymmenkertaiseksi isommillakin raporteilla.

**Comment by emta001** [comment]
> Nyt sain ladattua tab-tiedoston, jossa on ihan sisältökin paikallaan. Tuo vain vaikuttaa nyt olevan monin verroin hitaampi kuin sama tuotannossa ja myös paljon hitaampi kuin csv:n lataus nextillä. Käytännössä n. 3-4 sekunnin lataus on nyt 40 sekunnin mittainen. Aika äkkiä mennään aikakatkaisun puolelle, jos tuo aika kasvaa käytännössä kymmenkertaiseksi isommillakin raporteilla.

Millä raportilla testasit? Testailin ite melko simppelillä rapsalla (id 2320), joka on vielä 200 tuloksellakin suht nopea. Niin mietin, että onkohan tässä joku raja sille, miten iso tulosmäärä saa raportin hidastumaan.

**Comment by emta001** [comment]
Testailin nyt uudestaan vaski-nextillä rapsalla 2319 ja hidastahan tuo on verrattuna saman rapsan lataamiseen testillä.

**Comment by MikkoLiimatainen** [comment]
Testasin tällä raportilla: [2311](https://vaski-next.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?id=2311&op=run)

Teemme tällaisilla raporteilla nidelistoja haravaa varten. Tuo tulosjoukko lienee pienemmästä päästä 8852 rivin kanssa. Joissain tapauksissa olemme ladanneet miljoonan rivin tuloksia haravaa varten ja se ei nyt onnistu.

**Comment by emta001** [comment]
> Testasin tällä raportilla: [2311](https://vaski-next.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?id=2311&op=run)
> 
> Teemme tällaisilla raporteilla nidelistoja haravaa varten. Tuo tulosjoukko lienee pienemmästä päästä 8852 rivin kanssa. Joissain tapauksissa olemme ladanneet miljoonan rivin tuloksia haravaa varten ja se ei nyt onnistu.

Joo, ei ole mistään kotosin tää nopeus. Ja näemmä yhteisössä sama ongelma. Yritän katella tuota nopeammaksi ja varmaan pitää tikettikin tehä yhteisöön.

**Comment by emta001** [comment]
Tein tiketin yhteisöön tuosta hitailusta, [37987](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37987). Tää liittyy jollain tapaa HTML::Scrubber paketin käyttöön, joka siivoaa HTML sisältöä. Se ei kai oikein tykkää tuosta uudesta tavasta käsitellä .tab-tiedostojen sisältöä.

**Comment by emta001** [comment]
Nyt on uutta korjausta nexteillä ja rapsojen pitäs latautua taas nopeesti.

**Comment by MikkoLiimatainen** [comment]
Nyt nopeus vaikuttaisi olevan oikealla tasolla. Pieni rapsa latautui muutamassa sekunnissa ihan kuin csv:kin ja miljoonan rivin rapsa latautui ylipäätään. En huomannut tuota isompaa mitenkään kellottaa, mutta lataus sujui varsin nopeasti, kun aiemmin tuota ei pystynyt ollenkaan saamaan tab-muodossa.

**Comment by AnneliO** [comment]
Testasin outi-nextillä reilun 22 000 rivin tuloksen lataamista tabulaattoreilla erotettuna ja tiedot latautuivat käytännössä samantien.

**Comment by emta001** [comment]
Toimii siis, suljen tiketin.
