### ISSUE TITLE
Kun tekee useamman nidevarauksen samalla kertaa, ne sijoittuvat varausjonon alkuun ja loppuun

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha-24.05#125]
### Mikä vikana?

Tässä versiossa on mahdollista tehdä monta nidevarausta samalla kertaa. Kun valitsee kaksi tai useamman niteen varattavaksi samalla toiminnolla, ne sijoittuvat varausjonoon siten, että yksi menee varausjonon viimeiseksi ja loput varausjonon alkuun. Jos tekee vain yhden nidevarauksen, se sijoittuu varausjonoon viimeiseksi kuten pitääkin. 

Esimerkkeinä testiasiakkaan varaukset
https://vaski-next.koha-suomi.fi/cgi-bin/koha/circ/circulation.pl?borrowernumber=167757

### Mitä pitäisi tapahtua

Kaikkien nidevarusten tulisi sijoittua varausjonossa viimeisiksi. 

### Kuinka toistaa ongelma/asia

Tee useampi nidevaraus kerralla sellaiseen tietueeseen, jossa on jo varausjonoa.

**Comment by AnneliO** [comment]
Tein siilinextillä [tietueeseen](https://siili-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=606417) kolmelle eri asiakkaalle kaikkiin niteisiin nidevarauksen.  Ensin asiakkaalle 40960, sitten 12742 ja viimeisenä 15960.

Varaukset järjestäytyivät näin:

MariaDB [siilinext]> select reserve_id,borrowernumber,priority,itemnumber,enumchron from reserves left join items using (itemnumber) where reserves.biblionumber=606417 order by itemnumber,priority;

| reserve_id | borrowernumber | priority | itemnumber | enumchron |
---|---|---|---|---|
|     166683 |          40960 |        1 |     244943 | 1         |
|     166689 |          12742 |       17 |     244943 | 1         |
|     166695 |          15960 |       18 |     244943 | 1         |
|     166696 |          15960 |        6 |     244944 | 2         |
|     166690 |          12742 |       11 |     244944 | 2         |
|     166684 |          40960 |       16 |     244944 | 2         |
|     166697 |          15960 |        5 |     244945 | 3         |
|     166691 |          12742 |       10 |     244945 | 3         |
|     166685 |          40960 |       15 |     244945 | 3         |
|     166698 |          15960 |        4 |     244946 | 4         |
|     166692 |          12742 |        9 |     244946 | 4         |
|     166686 |          40960 |       14 |     244946 | 4         |
|     166699 |          15960 |        3 |     244947 | 5         |
|     166693 |          12742 |        8 |     244947 | 5         |
|     166687 |          40960 |       13 |     244947 | 5         |
|     166700 |          15960 |        2 |     244948 | 6         |
|     166694 |          12742 |        7 |     244948 | 6         |
|     166688 |          40960 |       12 |     244948 | 6         |

En huomaa tuossa muuta kuin että 1-numerossa ekana on se asiakas, jolle tehtiin ekana varaukset (40960 -> 12742 -> 15960 ). Lopuissa prioriteetti menee 15960 -> 12742 -> 40960 eli ikään kuin nurinkurin ekaan numeroon verrattuna.


Reserve_id:n mukaisessa järjestyksessä vielä sama:

| reserve_id | borrowernumber | priority | itemnumber | enumchron |
---|---|---|---|---|
|     166683 |          40960 |        1 |     244943 | 1         |
|     166684 |          40960 |       16 |     244944 | 2         |
|     166685 |          40960 |       15 |     244945 | 3         |
|     166686 |          40960 |       14 |     244946 | 4         |
|     166687 |          40960 |       13 |     244947 | 5         |
|     166688 |          40960 |       12 |     244948 | 6         |
|     166689 |          12742 |       17 |     244943 | 1         |
|     166690 |          12742 |       11 |     244944 | 2         |
|     166691 |          12742 |       10 |     244945 | 3         |
|     166692 |          12742 |        9 |     244946 | 4         |
|     166693 |          12742 |        8 |     244947 | 5         |
|     166694 |          12742 |        7 |     244948 | 6         |
|     166695 |          15960 |       18 |     244943 | 1         |
|     166696 |          15960 |        6 |     244944 | 2         |
|     166697 |          15960 |        5 |     244945 | 3         |
|     166698 |          15960 |        4 |     244946 | 4         |
|     166699 |          15960 |        3 |     244947 | 5         |
|     166700 |          15960 |        2 |     244948 | 6         |

**Comment by emta001** [comment]
Anneli löysi tähän yhteisöstä korjauksen, [bug 37587](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37587). Tuodaan tää nexteille testailtavaks.

**Comment by emta001** [comment]
Korjaus viety nexteille.

**Comment by AnneliO** [comment]
Testasin siilissä ja kirkesissä ja minusta nidevaraukset menevät nyt oikeaan järjestykseen.

**Comment by Kati-Helle** [comment]
Helle-nextissä nidevaraukset menevät oikeaan järjestykseen. Tekemäni kaksi nidevarausta menivät varausjonon hännille.

**Comment by emta001** [comment]
Toimii siis. Suljen tiketin.
