### ISSUE TITLE
Palautustoiminnon sarakkeen "Nidettä ei palautettu" -teksti antaa virheellistä tietoa

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha-24.05#126]
### Mikä vikana?

Versiossa on tullut ei-toivottu uusi ominaisuus, "Nidettä ei palautettu"-teksti Palautustoiminnon Eräpäivä-sarakkeeseen.

Tämä "Nidettä ei palautettu"-viesti lisätään kaikille alla oleville riveille, jos viimeinen palautustoiminnolla käsitelty nide ei ole ollut lainassa.

![image](https://github.com/user-attachments/assets/09d304fc-aefa-4353-a0dd-988630ea4ccd)

Matrixissa tästä oli keskustelua Versionvaihto-kanavalla to 22. elok. 2024. Teksti haluttaisiin kokonaan pois. 

### Kuinka toistaa ongelma/asia

Palauta lainassa ollut nide tai niteitä ja palauta sen jälkeen (samassa välilehdessä) nide, joka ei ole lainassa.

**Comment by AnneliO** [comment]
Tästä ongelmasta on ollut keskustelua myös tieteellisten Koha-kirjastojen Slackissa. Tarkistan, ovatko he tehneet tähän jonkinlaisen ratkaisun.

**Comment by AnneliO** [comment]
Ei mitään uuttaa heidän keskusteluissa. Ainoastaan linkki tällaiseen [bugiin](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37014), joka korjasi jonkin samantyyppisen ongelman.

**Comment by johannaraisa** [comment]
> Ei mitään uuttaa heidän keskusteluissa. Ainoastaan linkki tällaiseen [bugiin](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37014), joka korjasi jonkin samantyyppisen ongelman.
 
Toin tämän korjauksen nexteille, sen pitäisi estää että tuo "Nidettä ei palautettu"-teksti tulee joka riville, kun palauttaa ei lainassa olevan niteen lainattujen jälkeen.

**Comment by AnneliO** [comment]
Testailin siili-nextillä ja nyt "Nidettä ei palautettu" -teksti näkyy vain sen niteen kohdalla, joka palautettiin ei lainassa -olevana.

![kuva](https://github.com/user-attachments/assets/29580f2f-73b1-43fe-b63e-1bb6ebd5aaf8)

![kuva](https://github.com/user-attachments/assets/54da6aa7-2345-4cbd-9636-fae3b1fe8da8)

**Comment by Kati-Helle** [comment]
Toimii Helle-nextissä. "Nidettä ei palautettu"-teksti tulee Eräpäivä-sarakkeeseen vain niille niteille, jotka on palautettu ei lainassa olleina.

**Comment by piiaseme** [comment]
OUTIssa korjaus toimii.

**Comment by pirliis** [comment]
Käännösmuutos vielä tehty tekstille "Nidettä ei palautettu" muotoon "Nidettä ei palautettu lainasta".
https://github.com/KohaSuomi/Koha-translations/issues/56

**Comment by AnneliO** [comment]
Tämä toimii ja pirliin mainitsema tekstimuutos tehty. Suljen tiketin.

**Comment by pknuuti** [comment]
Saisko edes tuon lihavoinnin pois? Jos vaikka tekstin jättääkin.

**Comment by AnneliO** [comment]
> Saisko edes tuon lihavoinnin pois? Jos vaikka tekstin jättääkin.

Se saa "problem"-merkinnän, jonka perusteella se muotoillaan punaisella ja boldilla. Toki sen voi css:llä muuttaa, mutta sitten kaikki "oikeatkin" ongelmat menettävät muotoilun.

Löysin yhteisöstä tällaisen tiketin: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38117

Jos on tarpeen, niin tuosta voisi tehdä erillisen tiketin ja voimme harkita, kannattaako tuo tuoda meidän versioon. Tällä hetkellä se on viety versioon 24.11., mutta ei vielä versioon 24.05.
