### ISSUE TITLE
Koha-Suomen käännösten luonti

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-24.05#127]
### Mikä vikana?

Kunhan Koha-Suomen omat ominaisuudet on siirretty, pitäisi tehdä meidän omat käännökset eli luoda po-tiedostot.

**Comment by AnneliO** [comment]
Vein Koha-translations-tietovarantoon 24.xx-branchiin maanantaina 21.10.2024 sillä hetkellä viimeisimmät fi- ja sv-käännöstiedostot. Ne pitää ottaa pohjaksi, kun Koha-Suomen omia tiedostoja lähdetään luomaan.

**Comment by AnneliO** [comment]
Tietuenäytön muutokset on nyt tarkistettu muutamassa kimpassa. Käännökset voi minusta tehdä nyt.

**Comment by lmstrand** [comment]
Uudet tiedostot rakennettu koha-translations-repon 24.xx-haaran pohjalta ja toimitettu Annelille elementiin.

**Comment by lmstrand** [comment]
laitan tähän vielä ylös ohjeet:

Käännöstiedostojen päivitys: 1 pulli translations-reposta viimeisimmät käännökset 2 tee buildi kaikkine uusine feature brancheineen (AUTOFETCH), Translations-repon tiedostot pitää olla symlinkattuna Koha/misc/translator/po/ kanssa 3 aja Koha-repossa build-haarassa gulp po:update. Toimita Annelille uudelleen generoituneet po-tiedostot translations-reposta fi/se

**Comment by AnneliO** [comment]
Koha-Suomen versiot suomesta ja ruotsista nyt viety Koha-translations-tietovarantoon. Tulevat näkyville, kun seuraavan kerran tehdään build.

**Comment by AnneliO** [comment]
Emmi teki nexteille buildin, joten käännökset ovat nyt testattavissa.

**Comment by AnneliO** [comment]
Tänne on kirjattu osa Koha-Suomen omista muutoksista: https://github.com/KohaSuomi/Koha-translations/wiki/Koha%E2%80%90Suomen-muutokset-k%C3%A4%C3%A4nn%C3%B6stiedostoihin

**Comment by AnneliO** [comment]
[Tiketin #37](https://github.com/KohaSuomi/Koha-translations/issues/37) suomenkieliset muutokset unohtui tehdä tiedostoihin, kun en ollut kirjannut niitä tuonne yllä mainittuun wikiin. Tein ne nyt ja ne tulevat näkyville seuraavassa buildissä.

**Comment by AnneliO** [comment]
> [Tiketin #37](https://github.com/KohaSuomi/Koha-translations/issues/37) suomenkieliset muutokset unohtui tehdä tiedostoihin, kun en ollut kirjannut niitä tuonne yllä mainittuun wikiin. Tein ne nyt ja ne tulevat näkyville seuraavassa buildissä.

Nämä on nyt näkyvissä, kun Johanna ajoi buildin.

**Comment by AnneliO** [comment]
Tiketissä #46 kirjattuna, että fasetit Material types ja Locations eivät ole kääntyneet.
