### ISSUE TITLE
Kortti kadonnut -rajoitusilmoituksen Muokkaa-nappi: Asiakkaan tiedot-laatikko puuttuu muokkaussivulta, jonka vuoksi tallennus ei onnistu

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-24.05#128]
### Mikä vikana?

[36440](http://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36440) Add edit buttons for patron flags in attention box 

Tämä lisää asiakkaan huomautuksissa Kortti kadonnut -rajoitusilmoituksen kohdalle muokkaa-napin, josta pääsee suoraan muokkaamaan kyseistä tietoa.

Muokkaa-nappia klikkaamalla siirtyy asiakkaan muokkaussivulle, mutta ko. muokkaussivulta puuttuu mm. Sotun tallennukseen ja ohittamiseen liittyvät painikkeet.

Kortti kadonnut -rajoitusilmoituksen Muokkaa-napistä päätyy tämmöiseen näkymään:
![kuva](https://github.com/user-attachments/assets/38f2875d-acdf-4221-90f2-54f580362039)

Muokkaamisen tallennus ei onnistu, kun ei pysty klikkaamaan "Vie sotusiiloon" tai "Ohita" nappeja ja sen vuoksi Tallenna-nappi on harmaana.

OUTIn pääkäyttäjät ehdottavat, että Kortti kadonnut -rajoitusilmoituksen Muokkaa-nappi piilotetaan.

**Comment by AnneliO** [comment]
Hyödynsin aiemmin tehtyä Muokkaa-nappien piilotusta Tiedot-sivulla ja tein saman piilotuksen koskemaan myös Lainaus-sivua. En ainakaan hoksaa, että jotain muuta menisi piiloon, mutta kannattaa testata huolellisesti.

```
/* Piilota asiakkaan Lainaus-sivulla Muokkaa-nappi Kortti kadonnut -ilmoituksen perästä, koska tietoja ei voi sitä kautta tallentaa sotu-avaimen tarkistuksen vuoksi */
body#circ_circulation.circ a[href*="&step="] { display: none; }
```

**Comment by pirliis** [comment]
Piilotus toimii OUTIn nextillä, enkä myöskään huomannut, että jotain muuta olisi mennyt piiloon.

**Comment by pknuuti** [comment]
Vaaran nextilläkin testattu toimivaksi.

**Comment by AnneliO** [comment]
Lisäsin tämän rimpsun [IntranetUserCSS-wikiin Asiakastietojen suositeltaviin](https://github.com/KohaSuomi/Koha-24.05/wiki/IntranetUserCSS#suositeltavat).
