### ISSUE TITLE
Päivämääräkenttien muokkaamisessa outouksia

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-24.05#129]
### Mikä vikana?

Jos muokkaa manuaalisesti päivämääräkenttiä, joissa on käytössä ns. datepicker, saa helposti aikaan todella omituisia päivämääriä. Jos muokkaa esim. kuukaudeksi 07, voi vuodeksi päätyä itsestään 7777. Riippuen vähän, miten lähtee olemassa olevaa päivämäärää muokkaamaan (esim. poistaa ensin tietoa delete-näppäimellä vai backspacella).

Tähän on yhteisössä jonkinlainen korjaus olemassa bugissa https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37371. Sen voisi kokeilla tuoda meillekin ja testata, auttaako se huomatuissa ongelmissa.

**Comment by emta001** [comment]
Korjaus viety nexteille.

**Comment by AnneliO** [comment]
Aika jännästi kyllä toimii edelleen, mutta ei tuo enää tuota vuotta 7777. Jos menen vaikka kuukauden kohdalle ja painan backspacea, niin se poistaa kyllä sen siinä olevan tiedon, mutta laittaa tilalle ykkösen.. ja jos jatkan poistamista, niin päädytään päivämäärään 01.01. Se osaa kyllä sitten täydentään luvun oikein, jos alkaa kirjoittamaan uutta lukua yhden poistetun tilalle.

Jos laitan syntymäajaksi vaikka 06.03.3333 (tai tulevaisuuteen yleensäkin), tyhjenee syntymäaikakenttä. Muissa asiakastietojen päivämääräkentissä hyväksytään myös tulevaisuuden päivät.

Hmm.. minun mielestä tämä toimii nyt kyllä paremmin, mutta kyllä se edelleenkin pakottaa toimimaan tietyllä tavalla. Mutta se lienee ihan tarkoituksellista, ettei esim. syntymäaikakenttiin syötetä mitä sattuu.

**Comment by emta001** [comment]
MIe luulen kanssa, että tuo toimii nyt niinkuin on ollut tarkoituskin toimia. Vähän hassusti, muttei sentään täysin hullusti :smile:

**Comment by Rvallim0** [comment]
Vaski next: Yleisesti ottaen vaikuttaa toimivan ihan hyvin, mutta jos aloittaa esimerkiksi syntymäajan muokkauksen niin noin 30 sekunnin välein kenttä resetoituu siihen arvoon mikä oli muokkauksen aloittaessa mikäli datepickeriä ei sulje välissä. Arvo resetoituu riippumatta siitä onko se virheellinen vai ei, vaikuttaa tulevan siitä mikä arvo datepickerissä on näkyvissä. Tämä välillä ainakin testauksen aikana osui keskelle kirjoittamista jolloin sinne tuli mitä sattuu.

Välillä satunnaisesti tuntuu myös vuoden kohdalta katoavan kaksi numeroa edestä tai lopusta, tämä tosin niin satunnainen että ei pysty toistamaan luotettavasti ja esiintyy vain silloin kun sinne koittaa väkisin saada virheitä aikaiseksi.

**Comment by AnneliO** [comment]
Sain toistettua siili-nextillä tuon päivämäärän resetoitumisen. Oliskohan siinä taustalla jokin "halu" varmistaa, että kentässä olisi edes jokin oikeanlainen päivämäärä, jos käyttäjä unohtuu nukkumaan kenttään? Puoli minuuttia on kyllä aika hankala, kun se ei tunnu edes resetoituvan silloin, kun valikon käyttää kiinni. Eli se aika ei ala aina ns. alusta, kun päivämäärä-pickerin avaa.

En tiedä, kannattaako tuolle tässä vaiheessa tehdä mitään. Pitäisikö seurailla, miten sen kanssa käy tuotannossa? Toki käyttäjillä voi olla hankala huomata, että tieto resetoitui.

Toisaalta, jos käyttäjällä on suomalainen henkilötunnus, koko kenttään ei edes tarvitse mennä, koska syntymäaika kopioidaan henkilötunnuksesta. Ja aika harvoin syntymäaika varsinaisesti muuttuu, jolloin tuota kenttää pitäisi mennä muokkaamaan sellaisilla henkilöillä, joilla ei ole suomalaista henkilötunnusta.

"Resetoiminen" tapahtuu myös uutta asiakasta luotaessa ja kenttä tyhjenee tällöin. Mutta koska syntymäaika on pakollinen kenttä, eikä asiakastietoja saa tallennettua ilman syntymäaikaa, niin se ei jää ainakaan täysin tallentamatta sellaisissa tapauksissa.

**Comment by pirliis** [comment]
OUTIn nextillä toimii yhtä hassusti syntymäaika-kenttä kuin edellisissä testauksissa kuvattu eli jos menee päivämäärän tai kuukauden kohdalle ja käyttää backspacea, muuttuu luvuksi 01. Kenttä resetoituu myös, jos kalenteri on auki ja päivämäärämuutos on jäänyt "kesken".

Tullut asiakkaaksi- ja Vanhenee-kentissä myös backspacen käyttö muuttaa päivän ja kuukauden muotoon 01, mutta kentän resetoitumista ei tapahdu

**Comment by emta001** [comment]
Tämä toimii nyt vähemmän väärin kuin aiemmin, joten eiköhän tämän uskalla sulkea.
