### ISSUE TITLE
Signum- ja pääsanapluginit - ksdev/ks-0027-K22-6-signum-builder-plugins

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#13]
**HUOM! Yhdistetään tässä branchissa kaikki commitit yhteen. Tämä voi auttaa esim. 0114 branchin kanssa ilmenneisiin merge conflict ongelmiin.**

Signumeita ja pääsanoja varten on tehty monenlaisia liitännäisiä:

- [x] 084a_mainheading_branch_loc_signum_builder.pl
- [ ] 084a_mainheading_branchloc_genre_signum_builder.pl
- [ ] 084a_mainheading_branchloc_signum_builder.pl
- [ ] 084a_mainheading_loc_signum_builder.pl
- [x] brancloc_084a_mainheading_signum_builder.pl
- [ ] fi_JSON_084a_signum_builder_subfields.pl
- [ ] fi_JSON_942khm.pl
- [ ] fi_paakirjaus.pl
- [ ] fi_paakirjaus_ohitusind_3merkkia.pl
- [ ] fi_signumbuilder_942k_branchloc_942hm.pl
- [ ] fi_signumbuilder_942k_loc_942hm.pl
- [ ] fi_signumbuilder_942k_loc_ccode_942hm.pl
- [ ] fi_signumbuilder_942khm_branch_loc.pl
- [ ] fi_signumbuilder_942khm_branchloc.pl
- [ ] fi_signumbuilder_942khm_branchloc_genre.pl
- [ ] fi_signumbuilder_942khm_loc.pl
- [x] loc_084a_mainheading_signum_builder.pl
- [x] loc_ccode_084a_mainheading_signum_builder.pl
- [ ] ykl_from_084a.pl

**Comment by emta001** [comment]
Viety testattavaksi. Testatkaa varmistamalla, että käytössä olevat plugarit toimivat kuten pitääkin.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii oikein käytössä oleva 
loc_ccode_084a_mainheading_signum_builder.pl

**Comment by ajrajala** [comment]
Vaskissa käytössä plugari loc_084a_mainheading_signum_builder.pl, testattu nextillä että toimii.

**Comment by pknuuti** [comment]
Vaaran nextillä toimii liitännäinen branchloc_084a_mainheading_signum_builder.pl,

**Comment by pirliis** [comment]
OUTIissa käytössä liitännäinen loc_084a_mainheading_signum_builder.pl. Toimii OUTIn nextillä.

**Comment by AnneliO** [comment]
Siili-nextillä näyttäisi olevan Kirja-kuvailupohjassa käytössä 084a_mainheading_branch_loc_signum_builder.pl, joka tuntuisi myös tuottavan nimensä mukaisia signumeita.

**Comment by LeenaKinnunen** [comment]
Lapissa toimii oikein plugari loc_ccode_084a_mainheading_signum_builder.pl

**Comment by emta001** [comment]
Eiköhän näiden testaamisten perusteella voida sanoa, että tämä on OK. Suljen tiketin.
