### ISSUE TITLE
Asiakkaan lainatietoihin uusinta-sarakkeeseen oletusrasti myös tänään erääntyville lainoille  - ksdev/ks-0138-K23-131-autocheck-renew-for-loans-due-today

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#130]
### Siirrettävä ominaisuus

Kuten otsikossa lukee.

**Comment by emta001** [comment]
Tuotu nexteille testattavaksi. Tarkistakaa, että uusinta-sarake on nyt rastitettu myös tänään erääntyvillä lainoilla.

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä ja tänään erääntyvälle lainalle tuli automaattisesti uusinta-sarakkeeseen ruksi. Eli toimii.

**Comment by Kati-Helle** [comment]
Toimii Helle-nextissä.

**Comment by AnneliO** [comment]
Toimii siili-nextillä.

**Comment by piiaseme** [comment]
Toimii OUTIn nextillä.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
