### ISSUE TITLE
isbn-all -indeksin lisäys Koha-Suomen Elasticsearch-mäppäystiedostoon

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-24.05#132]
### Mikä vikana?

Yhteisössä on lisätty Elasticsearchin indekseihin uusi indeksi isbn-all, johon viedään tiedot MARC-kentistä 020$a ja 020$z. Tämä pitäisi lisätä myös Koha-Suomen mäppäystiedostoon/indekseihin.

Indeksejä pystyy kyllä nykyään lisäämään käyttöliittymänkin kautta, mutta olisiko lisäys helpompi tehdä mappings.yaml-tiedoston kautta?

**Comment by lmstrand** [comment]
Tekisin ehkä tiedostoon. Jää myös versiohistoriaan jälki muutoksesta ja sen ajankohdasta. Vaatii uudelleenindeksoinnin.

**Comment by lmstrand** [comment]
Muutos tehty /koha-suomi-utility/etc/elasticsearch-mappings-next.yaml -tiedostoon. Outi-next on uudelleenindeksoitu uudella mäppäyksellä.

**Comment by AnneliO** [comment]
Testasin outi-nextillä ja uusi indeksi näkyy Hakukoneen asetukset -sivulla. Etsin myös SQL-kyselyllä tietueita, joihin on merkitty virheellinen isbn 020z-kenttään ja koitin sitten hakea tietueesta löytyvällä isbn-numerolla isbn-all -indeksistä. 

SQL-kysely:

```
SELECT biblionumber, ExtractValue(bm.metadata, '//datafield[@tag="020"]/subfield[@code="z"]') as '020z'
FROM biblio_metadata bm
WHERE ExtractValue(bm.metadata, '//datafield[@tag="020"]/subfield[@code="z"]') != ''
```

Haku sitten pikahaku-kentässä esim. isbn-all:925-469-406-9

**Comment by lmstrand** [comment]
Uudelleenindeksoitu myös Kyyti, Helle, Siili, Vaara, Lumme, Kirkes

**Comment by AnneliO** [comment]
Testasin vielä siili-nextillä hakemalla sekä aktiivisia että virheellisiä isbn-numeroita niin, että poistin isbn:stä hakulauseessa väliviivat. Haku toimi silti.

Tähän pitäisi vaikuttaa [SearchWithISBNVariations](https://koha-community.org/manual/23.11/en/html/searchingpreferences.html#searchwithisbnvariations)-järjestelmäasetus, mutta ainakaan lennossa tuon vaihtaminen ei vaikuttanut mitään. Väliviivattomalla versiolla hakeminen toimi silti, vaikka asetuksen otti pois päältä.

**Comment by ElinaUotila** [comment]
Kirkes-nextillä testattu sekä aktiivisten että virheellisten isbn-numeroiden hakua, niin väliviivoilla kuin ilmankin. Toimi kaikissa tapauksissa.

**Comment by Kati-Helle** [comment]
Toimi testatessani Helle-nextissä Hae tietokannasta -toiminnolla:
- tietueen kenttä-arvon 020a haku toimii arvon väliviivojen kera sekä ilman väliviivoja (testaustietueessa 020a=978-952-04-5647-4)
- tietueen kenttä-arvon 020z haku toimii arvon väliviivojen kera sekä ilman väliviivoja (testaustietueessa 020z= 978-952-5185-52-4)

Asetuksen  SearchWithISBNVariations eri vaihtoehtoja en kokeillut. Helle-nextissä asetukseen on valittuna: hae

**Comment by piiaseme** [comment]
OUTIN nextillä testattu aktiivisella ja virheellisellä ISBN-numeroilla, viivoilla ja ilman viivoja. Näyttäisi toimivan oikein.

**Comment by AnneliO** [comment]
Tämä toimii, joten suljen tiketin. Tieto päivitetty myös Kohan ohje suomeksi -sivulle Elasticsearchin indekseihin.
