### ISSUE TITLE
Eräpäivien siirto eräajona -työkalu ei toimi

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-24.05#133]
### Mikä vikana?

Eräpäivien siirto eräajonoa -työkalu ei toimi.

Hakuehtojen syöttämisen/valitsemisen ja Jatka-painikkeen klikkauksen jälkeen näkymänä tämä, kun valitsin esikatsele tuloksia
![kuva](https://github.com/user-attachments/assets/2ad8a6de-d2f9-4e02-887e-4c45cfe4df55)

Koha-yhteisön tiketti
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37483

**Comment by Kati-Helle** [comment]
Näkymä sama ilman esikatseluakin.

**Comment by emta001** [comment]
Korjaus viety nexteille.

**Comment by pknuuti** [comment]
Vaaran nextillä testattu, toimii. Eräpäivä muuttuu valituille niteille.

**Comment by Kati-Helle** [comment]
Toimii Helle-nextissä.

**Comment by emta001** [comment]
Hienoa! Suljen tiketin.
