### ISSUE TITLE
OUTI: IntranetUserJS-rimpsu "othername-kentän piilotus määritetyiltä asiakastyypeiltä"

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-24.05#134]
### Mikä vikana?

OUTIssa käytössä ollut JS-rimpsu ei toimi nextillä oikein kaikilta osin.

Valituilla asiakastyypeillä:
- Uutta asiakasta lisätessä Othername-kentän piilotusrimpsu toimii oikein eikä kenttää näy.
- Asiakastiedon kopioinnissa Othername-kentän piilotusrimpsu toimii oikein eikä kenttää näy.

- Jo olemassa olevaa asiakasta muokatessa Othername-kenttä näkyy ja on muokattavissa.

Onko uuteen versioon tullut jokin muutos, joka riikkoo rimpsun "modify"-kohdan?

### Mitä pitäisi tapahtua

Valituilla asiakastyypeillä olevia asiakkaita muokatessa Othername-kentän ei tulisi näkyä eikä olla muokattavissa.

### Jotain muuta?

OUTIn käyttämä JS-rimpsu:

/// ALKU ///
// Piilottaa 'Other names' kentän valituille asiakastyypeille (categorycode) muokkauslomakkeilla (add, modify, duplicate)
$(document).ready(function () {
if ( window.location.pathname == '/cgi-bin/koha/members/memberentry.pl' ) {
var categories = ["YHTEISO", "KAUKOLAINA", "AUTOM", "EITILASTO", "VIRKAILIJA", "API"];
if ( ( window.location.search.includes('?op=add') && categories.some(cat => window.location.search.includes(cat)) ) || ( ( window.location.search.includes('?op=modify') || window.location.search.includes('?op=duplicate') ) && categories.some(cat => $('.patroncategory')[0].innerHTML.includes(cat)) ) ) {
$('#othernames').attr('disabled', 'disabled');
// Piilottaa li-elementin, jonka sisällä on label ja input
$('#othernames').parent().hide();
}
}
});
/// LOPPU ///

Othername-rimpsua ei ole https://github.com/KohaSuomi/Koha-24.05/wiki/IntranetUserJS -listalla. Lisätäänkö se samalla sinne vai onko rimpsun osalle mietitty jotain muuta vahtoehtoa?

Liittyy tikettiin: https://github.com/KohaSuomi/Koha/issues/956

**Comment by atarnus** [comment]
Näköjään modify on muuttunut edit_formiksi, pitäisi toimia tällä (ja poistin tuon kentän disabloinnin, jonka ei pitäisi olla tarpeen kun se menee piiloon):

```
/// ALKU ///
// Piilottaa 'Other names' kentän valituille asiakastyypeille (categorycode) muokkauslomakkeilla (lisää, muokkaa, kopioi)
$(document).ready(function () {
    if ( window.location.pathname == '/cgi-bin/koha/members/memberentry.pl' ) {
        var categories = ["YHTEISO", "KAUKOLAINA", "AUTOM", "EITILASTO", "VIRKAILIJA", "API"];
        if ( ( window.location.search.includes('?op=add') && categories.some(cat => window.location.search.includes(cat)) ) || ( ( window.location.search.includes('?op=edit_form') || window.location.search.includes('?op=duplicate') ) && categories.some(cat => $('.patroncategory')[0].innerHTML.includes(cat)) ) ) {
            // Piilottaa li-elementin, jonka sisällä on label ja input
            $('#othernames').parent().hide();
        }
    }
});
/// LOPPU ///
```

**Comment by AnneliO** [comment]
Jos tuo nyt toimii, niin sen voi lisätä Piian mainitsemaan https://github.com/KohaSuomi/Koha-24.05/wiki/IntranetUserJS -wikiin. Sinne on tarkoitus kerätä kaikki ne, joita ei plugarisoida, jotta ne olisivat edes jossain keskitetysti ylhäällä. :)

**Comment by piiaseme** [comment]
Korjaus toimii ja korjattu rimpsu on viety 24.05 IntranetUserJS-wikiin. Suljen tiketin.
