### ISSUE TITLE
Varausjonon toiminto 'aseta alin sija varausjonossa' ei toimi

### ISSUE THREAD

**Issue by atarnus** [KohaSuomi/Koha-24.05#135]
### Mikä vikana?

Tietueen varausjononäkymässä oleva sarake, jossa tuplanuoli alaspäin (ks. ao. kuva), pitäisi toimia niin, että klikatessa ko. varaus siirtyy pysyvästi jonon hännille (set lowest priority), mutta nextillä ohjaakin tekemään uutta varausta. (En tiedä käyttääkö kukaan tätä toimintoa mutta tuotannossa se kuitenkin toimii, ja uudessa versiossa on rikki.)

![image](https://github.com/user-attachments/assets/9743fa45-f39d-4ab6-aa8c-69dda37179c2)

Mahdollisesti samanlainen ongelma kuin https://github.com/KohaSuomi/Koha-24.05/issues/104

**Comment by emta001** [comment]
Korjaus viety nexteille.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii. (Myös muut varaussijan siirtopainikkeet toimivat.)

**Comment by Rvallim0** [comment]
Vaski nextillä toimii.

**Comment by AnneliO** [comment]
Koitin testata siili-nextillä, mutta se ei onnistunut, koska varaukset eivät näy.

![kuva](https://github.com/user-attachments/assets/61bc0c3a-1c5c-4769-b348-95e5bfb5ed8f)

**Comment by pirliis** [comment]
OUTIn nextillä toimii.

**Comment by emta001** [comment]
> Koitin testata siili-nextillä, mutta se ei onnistunut, koska varaukset eivät näy.
> 
> ![kuva](https://private-user-images.githubusercontent.com/33121325/377435606-61bc0c3a-1c5c-4769-b348-95e5bfb5ed8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMjgxODYsIm5iZiI6MTcyOTIyNzg4NiwicGF0aCI6Ii8zMzEyMTMyNS8zNzc0MzU2MDYtNjFiYzBjM2EtMWM1Yy00NzY5LWIzNDgtOTVlNWJmYjVlZDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA1MDQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYTBkYWZlZWFkM2I5Mjg5NTY4MzI4YzdiMzliODI0YzQ5YjljYTRiNmQzMTNhOTAyYTliZDZhYzIyMjRhYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._0Zl-MU7y4Gc2jvLbvbUI8hmDapcQhO0FJEKogCxVRU)

Johtuu varmaan siitä Larin tekemästä korjauksesta siihen yhteen namiskaan :sweat_smile: Mutta muiden testauksien perusteella tämä toimii kuten pitää, suljen tiketin.
