### ISSUE TITLE
OUTI: Finnassa tehty tietojen muutospyyntö ei siirry Kohaan

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-24.05#136]
### Mikä vikana?

Asiakkaan tiedoissa Finnassa muutin ensin varaustunnisteen ja lähetin pyynnön, se ei tullut Kohaan. Sen jälkeen muutin asiakkaan katuosoitteen ja lähetin pyynnön. Sekään ei tullut perille.

Finnassa asiakkaan tiedoissa luki, että muutospyynnöt on lähetetty eteenpäin.

Käyttämäni Finnan osoite oli versionvaihto Wikistä: https://outi.finna-pre.fi/next
Ja Kohan Nextille pyyntöjä odotin.

**Comment by lmstrand** [comment]
Vaaran nextillä toimii osoitteesta vaara.finna-pre.fi/next:
![image](https://github.com/user-attachments/assets/9991cec8-b7de-4ef1-a897-ea9a233100bc)

**Comment by ajrajala** [comment]
Testasin tätä äsken meillä, ei näytä tulevan vaski-nextillekään muutospyyntö läpi.

**Comment by lmstrand** [comment]
Ongelma ei ainakaan ole Kohan pään rajapinnassa.

**Comment by AnneliO** [comment]
Testasin nyt outi-nextillä ja toimi. Testaan vielä vaski-nextillä myös.

**Comment by AnneliO** [comment]
Ja toimi myös vaski-nextillä.

**Comment by ajrajala** [comment]
> Ja toimi myös vaski-nextillä.

Hyvä hyvä. Aloin just epäillä että olinko sittenkin testissä kiinni olevassa Finna-näkymässä, vaikka olin kyllä avaanivani nextin... Liikaa välilehtiä. :D

**Comment by piiaseme** [comment]
Vissiin Vaskin ja OUTIn hikka on ohi, kiitos kaikille, suljen tiketin :)
