### ISSUE TITLE
SQL-raportin muokkaussivulla 'Päivitä ja aja'-nappi ei toimi kuten muut raportin ajamiset

### ISSUE THREAD

**Issue by atarnus** [KohaSuomi/Koha-24.05#137]
### Mikä vikana?

Kun raportin ajaa 'Päivitä ja aja'-napista, niin ylävalikosta katoaa 'Muokkaa'-vaihtoehto 'Muokkaa'-valikon alta (hirveän selkeää, että siellä on Muokkaa-Muokkaa, mutta näin se on.) Itse raportin tulokset kuitenkin tulevat näkyviin, mutta muokkaamiseen takaisin siirtyminen ei nyt onnistu oikein muuten kuin selaimen takaisin-napista.

![image](https://github.com/user-attachments/assets/240d7d7c-055c-4658-bd92-3f2e082389e7)

Raportin ajamisen URL on yleensä muotoa '../guided_reports.pl?id=773&op=run' mutta 'Päivitä ja aja'-nappi näyttää siivoavan tuolta parametrit pois, URL on pelkkä guide_reports.pl

Raportti jää ikään kuin muokkaussivulle edelleen. Tulosten perään jää muokkauslaatikko, mutta se ei kuitenkaan toimi niin kuin pitäisi. Tästä oli yhteisötiketti: [#37763](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37763)

![image](https://github.com/user-attachments/assets/99ffefc3-3022-4e4c-948e-10c0623afa35)

**Comment by lmstrand** [comment]
Tiketti yhteisössä: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37763

**Comment by emta001** [comment]
Viety nexteille testattavaksi.

**Comment by AnneliO** [comment]
Tulostaulukon alapuolelle jää vielä jostain syystä tieto "Raporttisi x on tallennettu". Se tosin katoaa näkyvistä, kun näytöllä klikkaa mihin tahansa kohtaan. :D
![kuva](https://github.com/user-attachments/assets/dbd2160a-58d1-49b4-9def-babc20700b7a)

Muokkaa-valikon asettelu on epätasainen:
![kuva](https://github.com/user-attachments/assets/3fff6ae6-3ace-4d12-9371-1fd3c09a5b45)

Testillä vastaava:
![kuva](https://github.com/user-attachments/assets/6bfcfd88-9898-4383-adda-f0e458f280c7)

En nyt äkkiseltään muuta hoksannut.

**Comment by emta001** [comment]
Tuo ilmotushan tulee aina kun rapsaa muokataan ja tallennetaan, se on varmaan tarkotuksella siellä. Tuo asettelu menee höpsis nyt jostain muusta syystä, toisen tiketin yhteydessä taidettiin tehdä joku CSS-rimpsu joka ehkä vaikuttaa tuohon. Pitää tutkia.

**Comment by AnneliO** [comment]
> Tuo ilmotushan tulee aina kun rapsaa muokataan ja tallennetaan, se on varmaan tarkotuksella siellä. 

Näkyy joo, mutta yläreunassa. Jos tuloksia on paljon niin tuo nykyinen asettelu on vähän höpö, kun se voi jäädä näytön ulkopuolelle. Mutta tuo ei sinänsä siis ole mikään showstopperi. Outo vain. :)

**Comment by emta001** [comment]
Njaa, ongelma olikin se että sitä CSS-rimpsua ei ollut outi-nextillä.

```
.dropdown-menu > li > form > a {
  display: block;
}
```

Tuo taitaa toimia oikein yhteisössä? Siellä olis varmaan tuohon oikeakin korjaus, mutta kannattaako sitä tuoda meille, kun rimpsullakin pärjää?

**Comment by AnneliO** [comment]
> Njaa, ongelma olikin se että sitä CSS-rimpsua ei ollut outi-nextillä.
> 
> ```
> .dropdown-menu > li > form > a {
>   display: block;
> }
> ```

Tuo rimpsu on ilmeisesti jäänyt dokumentoimatta joskus, koska sitä ei ole IntranetUserCSS-wikissä ollenkaan. Lisäsin sen [Muita-osion suositeltuihin.](https://github.com/KohaSuomi/Koha-24.05/wiki/IntranetUserCSS#suositellut)
> 
> Tuo taitaa toimia oikein yhteisössä? Siellä olis varmaan tuohon oikeakin korjaus, mutta kannattaako sitä tuoda meille, kun rimpsullakin pärjää?

Ainakin sandboxissa asettuvat nätisti. Ei ehkä ole niin kriittinen, joten eiköhän pärjätä toistaiseksi rimpsulla.

**Comment by emta001** [comment]
> > Njaa, ongelma olikin se että sitä CSS-rimpsua ei ollut outi-nextillä.
> > ```
> > .dropdown-menu > li > form > a {
> >   display: block;
> > }
> > ```
> 
> Tuo rimpsu on ilmeisesti jäänyt dokumentoimatta joskus, koska sitä ei ole IntranetUserCSS-wikissä ollenkaan. Lisäsin sen [Muita-osion suositeltuihin.](https://github.com/KohaSuomi/Koha-24.05/wiki/IntranetUserCSS#suositellut)
> 
> > Tuo taitaa toimia oikein yhteisössä? Siellä olis varmaan tuohon oikeakin korjaus, mutta kannattaako sitä tuoda meille, kun rimpsullakin pärjää?
> 
> Ainakin sandboxissa asettuvat nätisti. Ei ehkä ole niin kriittinen, joten eiköhän pärjätä toistaiseksi rimpsulla.

Tuo rimpsu on tullutkin tehtyä vasta tässä hiljattain tikettiin #122, niin ei ihme ettei sitä vielä ole dokumentoitu :smile: Mutta joo, eiköhän tällä pärjätä seuraavaan versioon asti :+1:

**Comment by Rvallim0** [comment]
Vaski nextillä testattu, toimii.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
