### ISSUE TITLE
Asiakkaan Kirjastotiedot-osiossa väärä osoite-tieto, vaikka toiminto ei olisi käytössä

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha-24.05#138]
### Mikä vikana?

BorrowerUnwantedField-asetuksella on valittavissa näytetäänkö "Tarkista osoite (gonenoaddress)" -toiminto asiakkaan muokkauslomakkeella. Ilmeisesti tässä versiossa uutena ominaisuutena on tullut kyseisen arvon näyttäminen Kirjastotiedot-osiossa. 

Vaikka Tarkista osoite-toiminto olisi piilotettuna, niin Kirjastotiedoissa näytetään tuon kentän arvo. Se pitäisi saada piiloon, koska tuo tieto voi olla virheellinen.
![image](https://github.com/user-attachments/assets/d39944c2-9fd5-4f95-b63b-f88848c679b4)

**Comment by AnneliO** [comment]
Nämä tuntuisi ainakin siili-nextillä piilottavan nuo Kortti kadonnut ja Väärä osoite -rivit:

```
/* Piilota Väärä osoite ja Kortti kadonnut -rivit asiakkaan Tiedot-sivulta oikealta Kirjastotiedot-laatikosta */
body#pat_moremember.pat li#patron-flags-gonenoaddress { display:none; }
body#pat_moremember.pat li#patron-flags-lostcard { display:none; }
```

**Comment by AnneliO** [comment]
Tuosta voisi melkein tehdän yhteisöön tiketin, että nuokin kentät piilotettaisiin, jos ne on piilotettu borrowerunwantedfields-järjestelmäasetuksella.

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä, tuolla css-rimpsulla piilotus onnistuu.

**Comment by AnneliO** [comment]
Lisäsin nämä rimpsut IntranetUserCSS-wikiin [asiakastietojen vapaaehtoisiin](https://github.com/KohaSuomi/Koha-24.05/wiki/IntranetUserCSS#vapaaehtoiset).

**Comment by Kati-Helle** [comment]
Kiitos rimpsuista. Toimivat myös Helle-nextissä.

**Comment by AnneliO** [comment]
Jos vaskilaiset testaavat vielä ja toteavat toimivaksi, niin tiketin voinee sitten sulkea. :)

**Comment by sksandel** [comment]
Toimii.
