### ISSUE TITLE
Näytä rajaukset -toiminto tietueen Perustiedot sivulla muuttaa holdings-taulukon sarakeleveyksiä

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-24.05#139]
### Mikä vikana?

Kun tietueen Perustiedot-sivulla klikkaa "Näytä rajaukset" -linkkiä, tuo se näkyville sarakkeiseen suodatusvaihtoehdot. Nidetyyppi, Nykyinen kirjasto ja Kotikirjasto -sarakkeissa suodatukseen käytetään pudotusvalikkoja ja näissä valikoissa nimet ovat niin pitkiä, että sarakkeet muuttuvat todella leveiksi. Tila-sarake sen sijaan kapenee ja koska se sisältää yleensä paljon tekstiä, rivittyy teksti monelle riville tehden yhdestä tulosrivistä melko korkean. Lopputuloksena holdings-taulukko ei ole kovinkaan nätin näköinen ja käyttäjä joutuu scrollaamaan sivua oikealle nähdäkseen kaikki sarakkeet.

Saisiko sarakkeita pakotettua tietyn levyiseksi ja valinnat rivittymään, esim. samaan tapaan css:llä mitä on tehty [Lisää viesti -modaalin alasvetovalikolle](https://koha-suomi.fi/dokumentaatio/intranetusercss/#s%C3%A4%C3%A4d%C3%A4-lis%C3%A4%C3%A4-viesti--popparin-alasvetovalikon-leveytt%C3%A4)?

### Jotain muuta?

![kuva](https://github.com/user-attachments/assets/b8e176c0-344b-4402-8c25-d83893a17adb)

**Comment by AnneliO** [comment]
Lisäsin vaski-nextille tällaisen css-rimpsun ylimmäiseksi IntranetUserCSS-asetukseen:

```
/* Säädä Kokoelmat-taulukossa alasvetovalikoiden leveys kapeammaksi. Valikot tulevat näkyville, kun klikkaa Näytä rajaukset -linkkiä */
body#catalog_detail.catalog select.dt-select-filter { max-width: 200px; }
```

Minun silmään ja testeissä tuo toimisi siedettävästi. Testailetteko muutkin? :)

**Comment by AnneliO** [comment]
Matrix-juttelujen perusteella lisäsin vaski-nextille myös tila-sarakkeelle tällaisen minimileveyspakotuksen:

```
body#catalog_detail.catalog th#holdings_status.status.sorting_disabled { min-width: 250px; }
body#catalog_detail.catalog th#otherholdings_status.status.sorting_disabled { min-width: 250px; }
```

Tuo tosin sitten kaventaa muiden sarakkeiden leveyttä väkisin, koska taulukon leveys on rajattu. Kannattaa harkita, voiko tuota ottaa käyttöön ja voisiko mahdollisesti vähentää oletuksena näkyvillä olevien sarakkeiden määrää.

**Comment by ajrajala** [comment]
CSS parantaa tosiaan tilannetta. Tila-sarakkeen kapeus aiheutti tosiaan tulosrivin korkeuden kasvamisen, riveistä tuli helposti korkeita kun nide on vaikkapa kuljetettavana varausta varten.

Vaskissa olisi varmaan mahdollista vähentää oletuksena näytettäviä sarakkeita, koska niitä näytetään nyt aika paljon. Jatkamme siis pohdintaa ja mietimme jätetäänkö tuota jälkimmäistä css:ää käyttöön.

**Comment by pirliis** [comment]
Lisäsin OUTIn nextille molemmat rimpsut ja mielestäni nyt näyttää paremmalle, kun Tila-sarake on leveämpi, vaikka muut sarakkeet vähän kaventuivat.

**Comment by pknuuti** [comment]
Laitoin Vaaran nextillekin nuo määritykset, ihan hyvältä näyttää.

**Comment by AnneliO** [comment]
Lisäsin nämä rimpsut myös version 24.05 [IntranetUserCSS-wikiin Tiedonhaun vapaaehtoisiin](https://github.com/KohaSuomi/Koha-24.05/wiki/IntranetUserCSS#vapaaehtoiset-4).

**Comment by MikkoLiimatainen** [comment]
Tuon tila-sarakkeen leveyden säätö näyttää näillä koodeilla tipahtavan pois siinä vaiheessa, jos rajausten ollessa näkyvillä vierittää sivua alas siihen asti, että otsikkorivit kiinnittyvät sivun yläreunaan. Tuo vaikuttaisi johtuvan siitä, että nuo otsikkojen id:t siirretään noihin toisiin elementteihin, jotka kiinnittyvät tuohon sivun yläreunaan varsinaisen taulun päälle. Erikoinen ratkaisu minusta, mutta näin se näyttää toimivan.

Jos nuo id:t poistaa rimpsuista tai korvaa rimpsut tällä rimpsulla, joka siirtää koon muokkauksen otsikoista taulun varsinaisiin riveihin, niin samaa ongelmaa ei ole.
```
body#catalog_detail.catalog td.status { min-width: 250px;}
```

**Comment by AnneliO** [comment]
> Tuon tila-sarakkeen leveyden säätö näyttää näillä koodeilla tipahtavan pois siinä vaiheessa, jos rajausten ollessa näkyvillä vierittää sivua alas siihen asti, että otsikkorivit kiinnittyvät sivun yläreunaan. Tuo vaikuttaisi johtuvan siitä, että nuo otsikkojen id:t siirretään noihin toisiin elementteihin, jotka kiinnittyvät tuohon sivun yläreunaan varsinaisen taulun päälle. Erikoinen ratkaisu minusta, mutta näin se näyttää toimivan.
> 
> Jos nuo id:t poistaa rimpsuista tai korvaa rimpsut tällä rimpsulla, joka siirtää koon muokkauksen otsikoista taulun varsinaisiin riveihin, niin samaa ongelmaa ei ole.
> 
> ```
> body#catalog_detail.catalog td.status { min-width: 250px;}
> ```

Hyvä, kun huomasit! Jos joku muukin vielä testaisi tällä Mikon versiolla, niin kopsaan sitten tämän wikiin. :)

**Comment by pknuuti** [comment]
Testasin Mikon versiota Vaaran nextillä eikä siellä (pienellä näytöllä) tilanne parantunut. Ihmettelen, eikö tuota Nidetyyppi-saraketta saisi paljon kapeammaksi, nyt siellä on tilaa aivan liikaa. Sarakkeen leveys perustilanteessa on ihan kätevän levyinen.

**Comment by pirliis** [comment]
Testasin myös jo aiemmin Mikon versiota, mutta en havainnut parannusta, joten ajattelin, etten vain nyt tajua pointtia. :D

**Comment by AnneliO** [comment]
> Testasin Mikon versiota Vaaran nextillä eikä siellä (pienellä näytöllä) tilanne parantunut. Ihmettelen, eikö tuota Nidetyyppi-saraketta saisi paljon kapeammaksi, nyt siellä on tilaa aivan liikaa. Sarakkeen leveys perustilanteessa on ihan kätevän levyinen.

Vaara-nextillä ei ollut tätä tästä tiketistä ylempänä olevaa rimpsua:

```
/* Säädä Kokoelmat-taulukossa alasvetovalikoiden leveys kapeammaksi. Valikot tulevat näkyville, kun klikkaa Näytä rajaukset -linkkiä */
body#catalog_detail.catalog select.dt-select-filter { max-width: 200px; }
```

Lisäsin sen nyt vaara-nextillä niin, että määritin max-leveydeksi 150px. Kyllä tuo minusta näyttäisi kapenevan Nidetyyppi-sarakekin.

Lisäsin tuohon rimpsuun myös kokeeksi tällaiset lisämääritykset, jotka määrittävät nidetyyppi-sarakkeenn 100px:n levyiseksi:

```
body#catalog_detail.catalog th#holdings_itype { max-width: 100px; }
body#catalog_detail.catalog th#holdings_itype select.dt-select-filter { max-width: 100px; }
```

Tuo kyllä tuntuisi toimivan, mutta sitten pidempien nidetyyppien kuvaukset joutuvat ahtautumaan aika pieneen tilaan. Esim. https://vaara-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=11683591

![kuva](https://github.com/user-attachments/assets/4ed7348c-ea56-4835-ba1b-08fe62b4488f)

**Comment by AnneliO** [comment]
> Testasin myös jo aiemmin Mikon versiota, mutta en havainnut parannusta, joten ajattelin, etten vain nyt tajua pointtia. :D

Minun versiolla käy näin, kun taulukkoa vierittää alaspäin suodattimien ollessa näkyvissä. Eli otsikkorivin sarakkeet ovat leveämpiä kuin muun taulukon.

![kuva](https://github.com/user-attachments/assets/b15bab01-1936-4089-ba1d-139fb9c2e9c7)

Mikon versiolla otsikkotasot ja sarakkeet pysyvät suunnilleen saman levyisinä:

![kuva](https://github.com/user-attachments/assets/d253fd19-4e59-4205-b709-810777844c5e)

**Comment by pknuuti** [comment]
Kiitos Anneli, en ollut ymmärtänyt oikein tuota lisäämistä vaan käsitin, että se pitää korvata. Ja mitä tulee noihin pitkiin nidetyyppeihin, niitä on niin pienessä määrässä niteitä, että tilanne on varmasti harvinainen piilotuksen kannalta. Tämä on nyt hyvä.

**Comment by pirliis** [comment]
Tein myös kuin Päivi eli korvasin Annelin rimpsut Mikon rimpsuilla. Ilmankos ei saatu toimimaan. :D 
Lisäsin Mikon rimpsun nyt Annelin rimpsujen lisäksi. Nyt näyttää hyvältä. :)

**Comment by AnneliO** [comment]
Tässä tiketissä on jo kolmea eri tarkoitusta varten olevaa css-säätöä, joten ei ihme, jos menee vähän sekaisin. Koitan laittaa nämä tuonne wikiin jotenkin selkeämmin. :D

**Comment by AnneliO** [comment]
Voiko tämän tiketin jo sulkea?

**Comment by ajrajala** [comment]
Eiköhän voi, kun kerta css-rimpsuja on testattu ja ne on dokumentoitu. Suljen.

**Comment by MikkoLiimatainen** [comment]
Nämä muokkaukset eivät toimi aina oikein, jos kokoelmat on jaettu eri välilehdille.

Huomasin ongelman näistä koodeista, koska niissä ei otettu huomioon otherholdings_itype id:tä:
```
body#catalog_detail.catalog th#holdings_itype { max-width: 100px; }
body#catalog_detail.catalog th#holdings_itype select.dt-select-filter { max-width: 100px; }
``` 
Kun koitin saada tuota toimimaan myös muiden kokoelmien välilehdellä, niin huomasin, etteivät nämä kokomuutokset toimi oikein, jos rajaukset näytetään epäaktiivisen välilehden puolella ja selaa sivua alas niin, että otsikkorivit jäävät kiinni sivun yläreunaan ja käytössä olevalla välilehdellä rajauksia ei näytetä. Tämä johtuu siitä, että nuo rajaukset ovat tässä tilanteessa väärältä välilehdeltä.

Tässä esimerkiksi Muut kokoelmat välilehden puolella näkyy Turku, Pääkirjasto kokoelmat välilehden rajaukset, kun sillä välilehdellä rajaukset ovat päällä, mutta tällä aktiivisella välilehdellä ei:
![Suodatukset väärän kokoelman puolella 2024-11-01 124701](https://github.com/user-attachments/assets/9c148bec-7d66-4aa3-b638-9903f2285b53)


Jos tuosta nyt suodattaisi esimerkiksi nidetyypin mukaan, niin rajaus tapahtuisi toisen välilehden puolella. Sama ongelma on itse asiassa myös tuotannossa, mutta siellä se on hankalammin havaittavissa. Kyseessä on siis isompikin bugi, josta tarvinnee tehdä oma tikettinsä. Mutta tähän tikettiin liittyen näistä kokomuokkauksista voi tulla haittaa, jos kokoelma on jaettu.
