### ISSUE TITLE
list_borrowers-oikeuden lisääminen

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-24.05#140]
### Mikä vikana?

Jos käyttäjällä on edit_borrowers tai view_borrower_infos_from_any_libraries -oikeudet, pitää hänelle lisätä versionvaihdossa käyttäjäoikeus list_borrowers.

Liittyy tikettiin #26 ja siihen, mitä oikeuksia käyttäjä tarvitsee, jotta tietoja voidaan hakea API:n kautta näkyville.

**Comment by AnneliO** [comment]
Pääkäyttäjäpalaverin 22.10.2024 keskustelujen ja pohdintojen jälkeen tulimme siihen tulokseen, että tämä pitääkin tehdä näin:

Jos käyttäjällä on edit_borrowers-oikeus -> lisätään list_borrowers-oikeus
Jos käyttäjällä on edit_borrowers ja view_borrower_infos_from_any_libraries -oikeudet -> lisätään list_borrowers-oikeus

Jos käyttäjällä on vain view_borrower_infos_from_any_libraries-oikeus -> EI lisätä list_borrowers-oikeutta

**Comment by AnneliO** [comment]
Vaskissa on käytössä ns. kevyttunnuksia, joilla on vain tuo view_borrower_infos_from_any_libraries-oikeus ja niillä tunnuksilla ei haluta päästää käyttäjää asiakkaan tiedot-välilehdelle. Nyt list_borrowers-oikeus sallii päädyn tiedot-välilehdelle, jos sinne mennään esim. varaussivun linkistä.

**Comment by emta001** [comment]
Skriptiä on nyt muutettu niin kuin pääkäyttäjäpalaverissa sovittiin. Ajoin sen omaan testiympäristööni ja se näyttäisi toimivan kuten pitääkin. Kävin ajamassa kaikille nexteille saman ajon.

**Comment by emta001** [comment]
Tähän tikettiin voisi ilmoitella, jos huomaa jotain jännää noissa oikissa. Tai jos kaikki on OK :smile:

**Comment by MikkoLiimatainen** [comment]
Vaski-nextillä kaikki näyttäisi olevan kunnossa. En ainakaan huomannut kuin pari poikkeavuutta, jotka näyttävät olevan ihan omaa tekoamme.

**Comment by pirliis** [comment]
Tsekkailin OUTIn nextillä borrowers-käyttäjäoikeuksia. Aiemmissa Koha-versioissa, vaikka ruksitti kaikki borrowers-käyttäjäoikeuden alaiset oikeudet käyttäjälle, ohjelma ei automaattisesti lisännyt päätason oikeustäppää. Ainakin nyt käytössä olevassa versossa näin tapahtuu ja on voinut tapahtua jo edellisissä versioissa.

Eli OUTIn tuotannossa on nyt samoilla oikeuksilla olevilla käyttäjillä kahdenlaista ruksitusta:
![Image](https://github.com/user-attachments/assets/ae50161b-f6e3-41e9-b8ca-72c3390a23f9)
![Image](https://github.com/user-attachments/assets/157b6852-dfe9-4687-b5ee-2b89dfdef095)

Nyt nextillä osalla käyttäjillä on tietenkin kaikki borrowers-käyttäjäoikeuden alaiset oikeudet päällä ja osalla ei:
![Image](https://github.com/user-attachments/assets/37bf951c-f570-475d-9261-7c23782c7c5e)
![Image](https://github.com/user-attachments/assets/f9f7d4d5-51e7-4524-a97a-f71aa28b57a2)

OUTIssa ei olla vielä päätetty, otetaanko 24.05 version uutta ominaisuutta käyttöön, jossa käyttäjällä olisi mahdollista lähettää "Lisää viesti" -toiminnolla s-postiviesti asiakkaalle. Tämä toiminto vaatisi käyttäjälle "send_messages_to_borrowers" -oikeuden. Jos toimintoa ei oteta käyttöön, osalla käyttäjillä on turhaan oikeus päällä. Ehkä ne voisi poistaa sitten ajona tarpeettomana pois.

Toki, jos näitä poistettavia ei olisi suurta määrää, voisimme poistaa ne manuaalisesti.

**Comment by emta001** [comment]
Tuo OUTIn ongelma liittynee nyt siihen, että käyttöoikeuksien asettaminen ei toimi mitenkään (paremman sanan puutteessa) älykkäästi  :sweat_smile: Ensiksi, tuotannossa noiden oikeuksien ruksitukset menee eri tavalla eri käyttäjille siksi, että joillakin käyttäjillä ei ole aiemmin ollut päällä kaikki borrowers-oikeudet. Kun oikeuksia lisätään automaattisesti tietokanta-ajona, ne lisätään aina yksittäisenä oikeutena eikä ajossa katsota sitä, onko käyttäjällä nyt täydet oikat vai ei. Jos katsottaisiin, silloin pitäisi laskea käyttäjälle uusi flags-arvo, asettaa se käyttäjälle ja poistaa user_permissions-taulusta yksittäiset oikeudet. Tällöin myös käyttöliittymässä oleva ruksitus menisi oikein.

Tuo toinen ongelma "send_messages_to_borrowers" -oikeuden kanssa liittynee taas siihen, että käyttäjällä on aiemmin ollut päällä täydet borrowers-oikat. Kun se on lisätty tietokantaan, se menee automaattisesti päälle kaikille käyttäjille joilla täydet oikat on olleet päällä. Pitäisi siis tehdä erikseen ajo, jossa näiltä käyttäjiltä otetaan pois tuo kyseinen oikeus ja asetetaan sitten yksitellen päälle muut borrowers-oikeudet. Miusta se voisi olla oman tikettinsä arvoinen homma ja siihen voisi kukin kimppa käydä kommentoimassa tarvitseeko tuommosta ajoa tehdä, niin tiedetään tehdäänkö versionvaihdossa kantojen päivityksen yhteydessä kaikille vai sitten jälkiajona vain tietyille kimpoille.

**Comment by pirliis** [comment]
#145 Send_messages_to_borrowers -oikeuden tarpeellisuus kimpassa

**Comment by atarnus** [comment]
Outi-nextillä katsoin rapsalla, että kaikilla käyttäjillä, joilla on edit_borrowers oikeus on myös list_borrowers oikeus. Eli meidän puolesta tämä mennyt ihan oikein. Meillä ei ole käytössä tunnuksia, joilla olisi vain view_borrower_infos_from_any_libraries-oikeus.

**Comment by ElinaUotila** [comment]
Kirkes-nextillä list_borrowers-oikeus näyttää menneen oikeille käyttäjille.

**Comment by ReettaSiili** [comment]
Siilin nextillä list_borrowers-oikeus on oikein eli koko henkilökunnalla. Meillä ei ole mitään kevyttunnuksia ja jos onkin, käyn muokkaamassa niitä käsin.

**Comment by atarnus** [comment]
Tein OUTI:n käyttäjäoikeustoiveista oman tiketin https://github.com/KohaSuomi/Koha-24.05/issues/180, niin meidän puolesta tämän voi sulkea.
