### ISSUE TITLE
Lehtien saapumisvalvonta: Luo seuraava -nappi ei muodosta lehdelle uutta numeroa

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-24.05#142]
### Mikä vikana?

Kun menee saapumisvalvonnan Numerohistorian kautta 
![kuva](https://github.com/user-attachments/assets/7aca01f7-7b36-4f9e-b1bc-a8377074b632)
lehden tietoihin ei Luo seuraava -nappi toimi.
![kuva](https://github.com/user-attachments/assets/c5cc2c36-6de5-4689-ad9b-8759f30d031e)

Numerot ennen ja jälkeen napin painalluksen:
![kuva](https://github.com/user-attachments/assets/b6137f68-f4f4-4f50-801e-29eb442eff5b)

### Mitä pitäisi tapahtua

Napin painalluksen jälkeen tulisi lehdelle muodostua uusi numero:
![kuva](https://github.com/user-attachments/assets/844a262d-af5e-4d89-8165-5c6d1c5f8ce7)
(sain muodostettua lehden no 5 siten, että klikkasin "Ohita numerot ja luo seuraava" ja annoin ohitettavaksi määräksi 0)

**Comment by AnneliO** [comment]
Millä kausijulkaisutilauksella testasit? :)

**Comment by piiaseme** [comment]
[Viva! 2024.](https://outi-next.koha-suomi.fi/cgi-bin/koha/serials/subscription-detail.pl?subscriptionid=26987)

**Comment by AnneliO** [comment]
Testasin myös nyt tuolla Vivalla ja lisäksi vaski-nextillä [Aarre](https://vaski-next.koha-suomi.fi/cgi-bin/koha/serials/serials-collection.pl?op=gennext&subscriptionid=7) -lehden tilauksella.

Uutta numeroa ei tosiaan synny. Selaimen konsolissa ei näy mitään virheilmoituksia.

**Comment by AnneliO** [comment]
Testaan vielä sandboxissa.

**Comment by AnneliO** [comment]
Sandboxissa (versio 24.06) toimi oikein.

Testasin vielä niin, että lisäsin vaski-nextille uuden kausijulkaisutilauksen ja koitin siihen luoda seuraavan numeron. Ei onnistunut silloinkaan.

**Comment by emta001** [comment]
Näinnäisestihän selaimen päästä tuo näyttäisi toimivan kuten pitääkin, kutsu palauttaa 200 viestin. Palvelimen lokeilla tuleekin sitten pari herjaa:

> [2024/10/24 08:22:24] [WARN] Use of uninitialized value in string eq at /home/koha/Koha/serials/serials-collection.pl line 183.
> [2024/10/24 08:22:24] [WARN] Use of uninitialized value in concatenation (.) or string at /home/koha/Koha/serials/serials-collection.pl line 187.

Luultavasti jotain oleellista jää nyt matkasta. Yritin löytää tälle yhteisöstä tikettiä, mutten ole semmosta vielä löytänyt.

**Comment by emta001** [comment]
Tiketti löytyikin:

[Bug 37294](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37294) - Generate next button in serials not working

Kokeillaan tuoda meillekin.

**Comment by emta001** [comment]
Korjaus viety nexteille.

**Comment by piiaseme** [comment]
OUTIssa korjaus toimii.

**Comment by Rvallim0** [comment]
Vaskin nextillä testattu, uuden numeron luonti "Luo seuraava"-napin kautta toimii.

**Comment by AnneliO** [comment]
Testasin vaara-nextillä ja Luo seuraava -nappula toimi oikein.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
