### ISSUE TITLE
Korin kaikki ominaisuudet eivät toimi

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-24.05#143]
### Mikä vikana?

Kaikki korissa olevat toiminnot eivät toimi kuten pitäisi.

Kun klikkaa korissa valintoja: Lisää tietoja, Lähetä, Tulosta ja Tyhjennä ja sulje, niin kori tyhjenee ja kori menee "lukkoon" eli ruutuun saa nimekkeet takaisin näkyville sulkemalla ruudun ja avaamalla korin uudelleen.
![kuva](https://github.com/user-attachments/assets/203c58b0-fba9-4f67-8636-29ce35e9d71f)

Kun klikkaa valintoja: Lataa, Poista, Lisää listalle, Varaa, Erämuokkaus ja Eräpoisto, niin mitään ei tapahdu. 
Myöskään  nuolinäppäin ei toimi.
![kuva](https://github.com/user-attachments/assets/677f81c7-e157-47d4-bb95-a11157513c6d)

Ainoat toiminnot, jotka toimivat ovat: Piilota ikkuna sekä Valitse kaikki ja Tyhjennä kaikki.

**Comment by AnneliO** [comment]
Jos selaimen tarkastele-toiminnolla katselee korissa konsoliin tulevia ilmoituksia, niin siellä on kaksi virheilmoitusta:

Uncaught TypeError: $(...).dataTable is not a function
    <anonymous> https://siili-next.koha-suomi.fi/intranet-tmpl/prog/js/cart_24.0501000.js:86
    jQuery 13
cart_24.0501000.js:86:18

ja

Uncaught TypeError: antiClickjack is null
    <anonymous> https://siili-next.koha-suomi.fi/cgi-bin/koha/basket/basket.pl:1086
basket.pl:1086:12

**Comment by AnneliO** [comment]
IntranetUserJS-järjestelmäasetuksen tyhjentäminen ei vaikuttanut toimintaan.

**Comment by AnneliO** [comment]
Eikä myöskään IntranetUserCSS:n tyhjentäminen.

**Comment by lmstrand** [comment]
En löytänyt yhteisöstä korjausta/tikettiä aiheesta.

**Comment by AnneliO** [comment]
Testasin vielä PTFS Europen sandboxissa (24.06) ja siellä toimii samalla tavalla eli oudosti.

**Comment by emta001** [comment]
Vaikuttais tosiaan sille, ettei tätä ole yhteisössä korjattu tai tiketöity. Teettekö tiketin, niin kattellaan saisko tän korjattua vielä ennen versionvaihtoa.

**Comment by emta001** [comment]
Okei vika ainakin löytyi. Jostain syystä [tämän bugin](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37033) muutos rikkoo tuon korin.

**Comment by emta001** [comment]
Väsäilen tiketin.

**Comment by emta001** [comment]
Tiketti tehty, [bug 38257](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38257).

**Comment by emta001** [comment]
Korjaus tehty yhteisöön ja tuotu myös nexteille testattavaksi.

**Comment by piiaseme** [comment]
Testasin OUTIssa ja vaikutti kaikki korin toiminnot toimivan kuten pitää.

**Comment by Rvallim0** [comment]
Vaskin nextillä testattu ja kaikki paitsi "Lataa"-pudotusvalikko toimii. Pudotusvalikon saa auki jos painaa ensin "Lisää tietoja" ja sen jälkeen klikkailee "Lataa"-nappia, jolloin pudotusvalikko aukeaa jos klikkaus osuu siihen hetkeen kun näkymä vaihtuu, jos näkymä ehtii latautumaan kokonaan ei valikkoa saa enää auki.

**Comment by piiaseme** [comment]
Jäiköhän tuo Lataa minulla testaamatta, sillä pudotusvalikko ei toimi OUTIssakaan. Kokelin Vaskin testaamalla tavalla, mutta en onnistunut lataamaan korin sisältöä.

**Comment by emta001** [comment]
Juu-u, ei toimi lataus vielä kuten pitää.

**Comment by emta001** [comment]
Lataus toimii kyllä 24.05-versiossa jossa ei ole miedän muutoksia käytössä. Tuo muutos, joka rikkoi muut ominaisuudet, näyttäisi edelleen rikkovan tuon latauksenkin.

**Comment by emta001** [comment]
Lataus ei toimi, koska intranet-bottom.inc filu sisältää myös rivin `[% INCLUDE js_includes.inc %]`. Näköjään jos tuota js_includes.inc filua yrittää ajaa kahdesta eri paikasta samalle sivulle, homma menee rikki.

**Comment by emta001** [comment]
Korjaus viety nexteille.

**Comment by piiaseme** [comment]
Testasin OUTIssa lataamista ja lataaminen näyttäisi nyt toimivan.

**Comment by Kati-Helle** [comment]
Helle-nextissä Korin ominaisuudet toimivat, myös lataaminen.

**Comment by AnneliO** [comment]
Testasin siili-nextillä ja sielläkin toimi kaikki korin yläreunan toiminnallisuudet.

**Comment by emta001** [comment]
Toimii siis, suljen tiketin.
