### ISSUE TITLE
Nextien cronien yhtenäistäminen

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#144]
### Siirrettävä ominaisuus

Ainakin update_holds_to_pull-ajon voisi säätää kaikilla nexteillä ajettavaksi samoilla aikaväleillä (esim. 5 minuutin välein klo 7-18).

**Comment by lmstrand** [comment]
muutettu:

  */1 07-18 * * *    $TRIGGER cronjobs/holds/build_holds_queue.pl
  */5 07-18 * * *    $TRIGGER cronjobs/holds/update-holds-to-pull.pl

Tätissä molemmat kommentoitu pois.

**Comment by emta001** [comment]
Puhuttiinkin tästä eilen hieman, että muiden cronien kohdalla säätäminen ei ehkä ole tarpeellista, nuo ovat ne raskaimmat. Suljen tiketin tältä erää, avataan uudestaan jos tarvii.
