### ISSUE TITLE
Send_messages_to_borrowers -oikeuden tarpeellisuus kimpassa

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-24.05#145]
### Mikä vikana?

Jos käyttäjällä on tuotannossa täydet borrowers-oikeudet, versiopäivityksessä hänelle tulee automaattisesti päälle uusi käyttäjäoikeus send_messages_to_borrowers. Oikeus pitää olla päällä, jos käyttäjällä on oikeus lähettää asiakkaalle s-postiviesti ”Lisää viesti” -toiminnolla.

Kimpat kommentoivat tähän tikettiin, jos haluavat, että oikeus otetaan käyttäjiltä pois jälkiajona versiopäivityksen jälkeen.

SELECT COUNT(*) FROM borrowers WHERE MOD(flags DIV 16, 2); -kyselyllä voi tarkistaa, kuinka monelle käyttäjälle oikeus tulee.

**Comment by AnneliO** [comment]
Kommenttien pohjalta lisätään tähän listaan ne kimpat, jotka haluavat ajon tehtävän:

- [ ] kimppa

**Comment by atarnus** [comment]
Tästä tehdään Outissa päätös ensi keskiviikkona.

**Comment by pirliis** [comment]
OUTIssa toiminto otetaan käyttöön, joten kaikille käyttäjille saa ajaa send_messages_to_borrowers -oikeuden päälle.

**Comment by ElinaUotila** [comment]
Kirkesissä toiminto otetaan myös käyttöön, eli uusi oikeus saa tulla kaikille, joilla on täydet borrowers-oikeudet. (Tarkistettu 19.11. että meille tämä on tullut kaikille, jotka sen tarvitsevatkin, eli Kirkesissä ei tarvita toimenpiteitä).

**Comment by pirliis** [comment]
Tarvittavasta ajosta OUTIssa on toinen tiketti #180. Ajo on tehty ja haluttu oikeus on nyt käyttäjillä.
Suljen tämän tiketin.
