### ISSUE TITLE
Osakohteen tiedoissa oleva emoon vievä linkki vie Hakutulokset-sivulle eikä emon perustiedot-näytölle

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-24.05#146]
### Mikä vikana?

Kun klikkaa osakohteen tiedoissa olevaa emoon vievää linkkiä, se vie Hakutulokset-sivulle eikä suoraan emon perustiedot-näytölle. Tämä tapahtuu klikatessa linkkiä Hakutulokset-sivulla ja osakohteen perustiedot-näytöllä.

Tuotannossa linkit vievät emon perustiedot-näytölle.

### Mitä pitäisi tapahtua

Kun klikkaa osakohteessa olevaa emoon vievää linkkiä, linkin tulisi viedä emon perustiedot-näytölle.

**Comment by pknuuti** [comment]
Vaaran nextillä osakohteessa oleva emon linkki vie emon perustiedot-näytölle.

**Comment by AnneliO** [comment]
Vaikuttaisko tähän uusi järjestelmäasetus RedirectToSoleResult, jossa OUTIssa on valittuna Älä ohjaa? Linkki emokohteeseen on käytännössä linkki hakuun, jossa haetaan emon tietoja control-number- ja cni-indekseistä, esim. Control-number,ext:"7459133" AND cni,ext:"FI-BTJ". Se ei siis ole suora linkki emoon.

Nyt tuossa järjestelmäasetuksessa on valittuna, että jos hakutuloksia on vain yksi, niin ei ohjata suoraan kyseiseen tietueeseen vaan näytetään hakutuloslistaus.

**Comment by piiaseme** [comment]
RedirectToSoleResult oli juurikin se asetus, joka ohjautumiseen vaikuttaa. Kiitos, en hoksannut tuota.
Suljen tiketin :)
