### ISSUE TITLE
Asiakastietueen voi tallentaa ilman varaustunnusta, mutta aiheuttaa virheen

### ISSUE THREAD

**Issue by LastuJanneS** [KohaSuomi/Koha-24.05#147]
### Mikä vikana?

Jos asiakastietueen yrittää tallentaa ilman varaustunnusta, asiakastietue kyllä tallentuu mutta Koha antaa "internal server error"-virheen.

### Mitä pitäisi tapahtua

Varaustunnus on pakollinen kenttä, joten Kohan ei lähtökohtaisesti pitäisi antaa tallentaa asiakastietuetta ilman sitä. Eli pitäisi tulla ilmoitus, että lomakkeella on pakollisia kenttiä jotka on täytettävä.

### Kuinka toistaa ongelma/asia

1. Avaa jonkin testiasiakastietueen muokkaus
2. Pyyhi varaustunnus pois ja koita tallentaa asiakastietue

**Comment by pknuuti** [comment]
Vaaran nextillä testattu: uusi asiakas tallentuu ilman varaustunnusta, kun sen tyhjentää lomakkeelta ennen asiakastietojen tallennusta. Virheilmoitus tulee ja näytölle jää "pyörimään" jotain, mutta kun näytöltä poistuu ja hakee tämän uuden asiakkaan sukunimellä, se yllättävästi tulee hakutulokseen. Ei sen näin todellakaan pitäisi mennä. Pakollisen kentän puuttumisesta pitää tulla ilmoitus tietoja tallennettaessa.

**Comment by emta001** [comment]
Tää on kyllä hämmentävä ongelma. Testailin omilla testeilläni ja tää vaikuttais johtuvan tiketin #39 muutoksista. Luultavasti tuo muutos aiheuttaa sen, että varaustunnus-kentän validointi ohitetaan. Mutta sitten kun siitä päästään tallentamaan asiakasta, Kohan muut tsekkaukset tulee väliin ja heittää 500 virhettä. Lokeille tuleekin sitten "Missing mandatory extended attribute (type=HOLDID)" virhe.

Mutta nexteillä tää näkyy eri tavalla. Siellä tulee valkoinen ruutu ja "Internal server error" virhe ja lokeille tulee seuraavaa:
>[2024/10/30 14:34:15] [WARN] Programming error - op 'cud-insert' must not start with 'cud-' for GET https://lastu-next.koha-suomi.fi/intraneterrors/500.pl (referer: https://lastu-next.koha-suomi.fi/cgi-bin/koha/members/memberentry.pl?op=add_form&categorycode=HENKILO) at /home/koha/Koha/Koha/Middleware/CSRF.pm line 82.

Sama koodihan molemmissa ympäristöissä pitäis olla, joten en oikein hiffaa miksi toisessa valitetaan yhtä ja toisessa toista.

**Comment by emta001** [comment]
Vein korjauksen nexteille, näyttäisi toimivan kuten pitääkin.

**Comment by LastuJanneS** [comment]
Testattu Lastun nextillä ja toimii nyt kuten pitääkin, ei anna tallentaa asiakastietuetta ilman varaustunnusta.

**Comment by pknuuti** [comment]
Testattu Vaaran nextillä, antaa virheilmoituksen kun yrittää tallentaa tyhjän varaustunnuksen. Toimii siis kuten pitääkin.

**Comment by emta001** [comment]
Jesh, toimii siis. Suljen tiketin, avataan uudestaan jos tämän kanssa tulee vielä ongelmia.

**Comment by Rvallim0** [comment]
Vaski nextillä testattu, jos varaustunnus kenttä on tyhjä Koha ilmoittaa kentän olevan pakollinen ja estää tallennuksen.

**Comment by piiaseme** [comment]
OUTIssa testattu eikä tallentaminen onnistu, kun varaustunnus-kenttä on tyhjä.

**Comment by emta001** [comment]
Hmm, oliko näiden uusien testauskommenttien tarkoitus mennä tikettiin #150? Tää on jo suljettu ja tuossa toisessa on tiketöity se uusi ongelma :smile:

**Comment by piiaseme** [comment]
> Hmm, oliko näiden uusien testauskommenttien tarkoitus mennä tikettiin #150? Tää on jo suljettu ja tuossa toisessa on tiketöity se uusi ongelma 😄
Tähän tikettiin oli tää minun testauskommentti - vähä myöhässä ..
