### ISSUE TITLE
Tietueen niteiden sivutus: Oletusmäärän muokkausmahdollisuus versioon 24.05

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-24.05#148]
### Mikä vikana?

Uutena ominaisuutena tulee tietueen niteiden sivutus ja niteet jakautuvat oletuksena 20 nidettä /sivu. Voisiko saada oletusmäärän muokattavaksi? 

Bugzillassa tiketti: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35191 Voisiko sen tuoda versioon 24.05?

### Jotain muuta?

![kuva](https://github.com/user-attachments/assets/e9e03387-857f-4bb9-aab5-76b3f1a27949)

**Comment by piiaseme** [comment]
Sivutuksen oletuksen muutos toimii nyt OUTI-nextillä.

**Comment by AnneliO** [comment]
Sellainen huomio, että jos tauluille laittaa oletukseksi "Kaikki", tulee haku-laatikko tällöin aina näkyville. Riippumatta siitä, kuinka paljon on niteitä ja tuleeko näkyviin Muut kokoelmat -välilehti. Liittyen tikettiin KohaSuomi/Koha#1541.

**Comment by lmstrand** [comment]
Yhteisön patch vietävä omaan feature branchiin.

**Comment by lmstrand** [comment]
viety nexteille branchissa ksdev/ks-0200-bug-35191-per-page-configurable-for-items-table

**Comment by pknuuti** [comment]
Vaaran nextillä testattu oletusmäärän muutos. Se toimii. Valitsin 20:n sijaan 50.

**Comment by LastuJanneS** [comment]
Lastun nextillä testattu myös oletusmäärän muutos toimivaksi. Meillä valittuna 20:n sijaan "Kaikki".

**Comment by Kati-Helle** [comment]
Helle-nextissäkin oletusmäärän muutos toimii. Vaihtoehto 'Kaikki' sovittu Helle-käyttöön.

**Comment by AnneliO** [comment]
Lisäsin [pääkäyttäjien muistilistalle](https://github.com/KohaSuomi/Koha-24.05/wiki/Muistilista-p%C3%A4%C3%A4k%C3%A4ytt%C3%A4jille#k%C3%A4y-tarvittaessa-muuttamassa-kokoelmat-taulukossa-n%C3%A4ytett%C3%A4vien-niteiden-m%C3%A4%C3%A4r%C3%A4n-oletusarvo), että tämäkin taulumääritys pitää tarvittaessa käydä tekemässä tuotannossa versionvaihdon jälkeen.

**Comment by piiaseme** [comment]
Suljen tiketin.
