### ISSUE TITLE
Hankinnassa tilauksen siirtäminen toiselle toimittajalle ei toimi

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-24.05#149]
### Mikä vikana?

Tilauksen siirto toiselle toimittajalle ei toimi ts. kun lähtee siirtämään tilausta tilauskortissa Muokkaa-sarakkeen Siirto-linkistä avautuu Siirrä tilaus -näyttö, jossa on Toimittaja-hakukenttä. Kun hakukentällä hakee toimittajaa, jolle siirto halutaan tehdä, haku ei anna mitään tulosta tai kerro, ettei haku tuottanut tulosta.

OUTIn next:
![image](https://github.com/user-attachments/assets/af890cf8-9429-4282-a8e7-ff8645ef827f)

OUTIn testi, jossa haku toimii:
![image](https://github.com/user-attachments/assets/ce029cb3-0255-42b4-a2cb-505d959578b5)

**Comment by AnneliO** [comment]
Konsoliin ei tule virheilmoituksia ja IntranetUserCSS:n tyhjentäminen ei tuonut osiota esille, joten mikään CSS niitä ei ainakaan piilota.

**Comment by johannaraisa** [comment]
Yhteisön bugi, https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37343
Pitää tuoda korjaus.

**Comment by johannaraisa** [comment]
Nyt tämä on nexteillä.

**Comment by pirliis** [comment]
Tilauksen siirtäminen toiselle toimittajalle nyt toimii. Kiitos!
Suljen tiketin samantien.
