### ISSUE TITLE
GDPR logging improvements - ksdev/ks-0032-K22-29-gdpr-logging-improvements

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#15]
GDPR logging improvements.

Pitäisi siis lokittua seuraavat:

Jos BorrowersLog-järjestelmäasetus on päällä:

- asiakastietojen muokkaus ja muokkausyritys (Patron/Modification.pm)

Jos BorrowersViewLog-järjestelmäasetus on päällä:

- käsittelyä odottavien asiakastietojen muutosten katselu (Patron/Modifications.pm)
-asiakashaku ja asiakasvalinta (REST/V1/Patrons.pm)
- lainausten katselu (circ/circulation.pl)
-asiakkaan tietojen katselu (members/moremember.pl)
- ilmoitusten katselu (members/notices.pl)
-maksujen katselu (members/pay.pl)
- hankintaehdotusten katselu (members/purchase-suggestions.pl)
- kiertolistojen katselu (members/routing-lists.pl)
- tilastojen katselu (members/statistics.pl)
- lokitietojen katselu tai vienti csv:ksi (tools/viewlog.pl)

**Comment by ajrajala** [comment]
> asiakastietojen muokkaus ja muokkausyritys (Patron/Modification.pm)

-> Tietojen muokkaus lokittui. [Viime kevään tiketin kommentin perusteella](https://github.com/KohaSuomi/Koha-23x/issues/20#issuecomment-2022144568) muokkausyritys lokittuu vain, jos muokkausta yrittää ilman muokkausoikeutta. En nyt keksi miten tuollaisen tilanteen saisi tehtyä, joten muokkausyrityksen lokittuminen jäi tarkistamatta.

> käsittelyä odottavien asiakastietojen muutosten katselu (Patron/Modifications.pm)

-> OK

> asiakashaku ja asiakasvalinta (REST/V1/Patrons.pm)

-> Molemmat OK

> lainausten katselu (circ/circulation.pl)
> asiakkaan tietojen katselu (members/moremember.pl)
> ilmoitusten katselu (members/notices.pl)
> maksujen katselu (members/pay.pl)
> hankintaehdotusten katselu (members/purchase-suggestions.pl)
> kiertolistojen katselu (members/routing-lists.pl)
> tilastojen katselu (members/statistics.pl)

-> OK

> lokitietojen katselu tai vienti csv:ksi (tools/viewlog.pl)

Lokitietojen katselu lokittuu, mutta vienti csv:ksi tai tulosta-toiminnon käyttö ei minusta tee erillistä lokimerkintää. Mutta näin on ollut viime keväänkin versiopäivityksen testauksessa ([tiketti 20](https://github.com/KohaSuomi/Koha-23x/issues/20)).

**Comment by piiaseme** [comment]
OUTIssa näyttäisi lokittuvan kaikki muu ok, paitsi:

asiakastietojen muokkausyritys (Patron/Modification.pm)
- koetin siten, että normivirkailijaoikeuksilla koetin muuttaa toisen virkailijan tietoja. Ei lokittunut vaikka kuin härpin.

vienti csv:ksi (tools/viewlog.pl)
- ei lokitu

käsittelyä odottavien asiakastietojen muutosten katselu (Patron/Modifications.pm)

- tätä en saanut kokeiltua, kun asiakkaan muutospyyntöä en saanut Finnasta NextiKohaan. _EDIT: Nyt muutospyyntö tuli perille -> lokittuu katselu_

**Comment by emta001** [comment]
Testasin tuota vientiä csv:ksi (tools/viewlog.pl) ja se näyttäisi lokittuvan sekä omalla testillä että OUTIn nextillä:

`| 208775334 | 2024-10-28 13:38:17 | 281018 | MEMBERS | VIEW        | 281018 | Exporting logs to csv  | intranet  | NULL   | NULL  | NULL | `

Täähän vaatii  BorrowersViewLog asetuksen, mutta käsittääkseni sen pitäs olla kaikilla päällä.

**Comment by emta001** [comment]
@piiaseme onko asiakastietojen muokkausyritys (Patron/Modification.pm) siis semmonen mitä yritit Finnan kautta? Koodista kun kattelen niin tuota Modification.pm moduulia ei käytetä kuin opacin puolella tai sitten Finna-plugarista.

**Comment by piiaseme** [comment]
> @piiaseme onko asiakastietojen muokkausyritys (Patron/Modification.pm) siis semmonen mitä yritit Finnan kautta? Koodista kun kattelen niin tuota Modification.pm moduulia ei käytetä kuin opacin puolella tai sitten Finna-plugarista.

Tätä en yrittänyt Finnan kautta. Eli olen testannut sitä väärin. Testaan uudelleen.

**Comment by ajrajala** [comment]
> Testasin tuota vientiä csv:ksi (tools/viewlog.pl) ja se näyttäisi lokittuvan sekä omalla testillä että OUTIn nextillä:
> 
> `| 208775334 | 2024-10-28 13:38:17 | 281018 | MEMBERS | VIEW | 281018 | Exporting logs to csv | intranet | NULL | NULL | NULL | `
> 
> Täähän vaatii BorrowersViewLog asetuksen, mutta käsittääkseni sen pitäs olla kaikilla päällä.

Asetus on meillä päällä, mutta en näe että lokin vienti csv:ksi kirjaisi meillä erikseen lokimerkinnän. Muutoslokin katselusta kirjautuu kyllä VIEW-rivi, mutta esim. tuossa kuvan tapauksessa vein lokin csv:ksi 11:59 ja sellaista riviä ei näy lokien katselussa. 🤔 Mutta onko tuossa nyt vaan jotain mitä en hoksaa?

![kuva](https://github.com/user-attachments/assets/991b1e6e-2192-45c2-891c-76836717327d)

**Comment by AnneliO** [comment]
Mie luulen, että tässä Anni koittaa viedä tiedot CSV-tiedostoksi tästä taulukon yläpuolelta löytyvistä toiminnoista:

![kuva](https://github.com/user-attachments/assets/32d98c17-aba4-452b-b3f1-6e7aa68ff752)


Kun tuo kirjaus tulee vain silloin, kun tiedot viedään tiedostoksi tästä kohdasta:
![kuva](https://github.com/user-attachments/assets/f7b93f75-99d4-4c58-afda-0a8ac9c6f19b)

**Comment by emta001** [comment]
Joo, eihän noita lokiteta, ne on datatablesin ominaisuuksia. Äkkiseltään sanoisin, että niihin ei edes saa lokitusta kiinni.

**Comment by ajrajala** [comment]
Aivan, en tajunnut tosiaan tuota. Eli siinä tapauksessa toimii vaski-nextilläkin.

**Comment by AnneliO** [comment]
Kokeilin itsekin tuosta datatablesin ominaisuuksista.. en edes ensin huomannut tuota toista vaihtoehtoa. :D

**Comment by piiaseme** [comment]
Asiakastietojen muokkausyritys (Patron/Modification.pm) nyt testattu OUTIssa uudelleen -> Lokittuu

**Comment by piiaseme** [comment]
OUTIssa lokittuu myös vienti csv:ksi (tools/viewlog.pl). Kiitos testivinkeistä :)

**Comment by ElinaUotila** [comment]
Testattu Kirkes-Nextillä: 

asiakastietojen muokkaus ja muokkausyritys (Patron/Modification.pm) 

> lokittuu

käsittelyä odottavien asiakastietojen muutosten katselu (Patron/Modifications.pm) 
-asiakashaku ja asiakasvalinta (REST/V1/Patrons.pm)
lainausten katselu (circ/circulation.pl) 
-asiakkaan tietojen katselu (members/moremember.pl)
ilmoitusten katselu (members/notices.pl)
-maksujen katselu (members/pay.pl)
hankintaehdotusten katselu (members/purchase-suggestions.pl)
kiertolistojen katselu (members/routing-lists.pl)
tilastojen katselu (members/statistics.pl)

> kaikki muut testattu paitsi kiertolistat ja hankintaehdotukset, joita meillä ei ole käytössä. Kaikki testatut lokittuvat

lokitietojen katselu tai vienti csv:ksi (tools/viewlog.pl)

> molemmat lokittuvat

**Comment by emta001** [comment]
Tätä on nyt testailtu kolmesta kimpasta ja vaikuttaisi toimivan kuten pitääkin. Suljen tiketin.
