### ISSUE TITLE
Asiakastyypille pakolliseksi määritelty asiakasmääre estää muiden asiakastyyppien tallentamisen

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-24.05#150]
### Mikä vikana?

Vaski-nextillä huomattiin, ettei asiakkaan tietoja saa tallennettua vaan _Muut määreet ja tunnukset_ -osioon tulee kuvassa näkyvä virheilmoitus. Ongelma vaikuttaisi johtuvan Automaatti-asiakastyypille pakolliseksi määritellyistä asiakasmääreistä, sillä kun poistin niistä pakollisuuden, tallentaminen onnistui.

Tämä ongelma on ollut esillä aiemminkin: https://github.com/KohaSuomi/Bugiton/issues/1#issuecomment-1786503326
Onkohan jokin muutos tuonut ongelman nyt takaisin vaski-nextillä, sillä väittäisin että aiemmin syksyllä tätä ei ole esiintynyt? 🤔 

Vaski-nextillä on tällä hetkellä asiakasmääreet AUTOMALLI, AUTOTYPE ja TOIMITTAJA pakollisia + määreet ovat käytössä vain asiakastyypillä Automaatti.

### Jotain muuta?

![kuva](https://github.com/user-attachments/assets/779eff96-c045-4bd9-b039-fa87e9b18fcf)

**Comment by emta001** [comment]
Liittynee tiketissä #147 tehtyyn korjaukseen. Korjataan.

**Comment by emta001** [comment]
Ei liittynutkään tuohon tikettiin, vaan siihen ettei asiakasmääre AUTOMALLI:lla ole class-attribuuttia. Validointi tai sen ohitus perustuu siis siihen, että tietyille elementeille lisätään class-attribuuttiin "ignore_validation". Mutta näköjään sitä ei synny, jos asiakasmääreeseen ei ole liitetty auktorisoitua arvoa ja siksi tuota validointi luokkaa ei pysty lisäämään.

**Comment by emta001** [comment]
Korjaus nexteillä. Ongelmana olikin se, että olin ottanut edellisen korjauksen yhteydessä pois koodinpätkän, jonka arvelin omien testieni perusteella olleen korjauksen kanssa tarpeeton. Mutta edellisessä kommentissa kuvaamassani tapauksessa se olikin vielä tarpeellinen. Nyt se on lisätty takaisin koodiin ja validointi vaikuttaisi toimivan kuten pitääkin.

**Comment by ajrajala** [comment]
Vaski-nextillä testattu, nyt onnistuu muiden asiakaslajien tallennus ja automaatti-asiakaslajia ei pysty tallentamaan, jos sille pakollinen asiakasmääre puuttuu. Toimii siis kuten pitää.

**Comment by ajrajala** [comment]
Tätä ei ole ehtineet muut testata, joten ehtiiköhän tämä korjaus mukaan versiopäivitykseen? Mietin lähinnä sitä, että tartteeko meidän tilapäisesti muuttaa automaattien asiakasmääreet ei-pakollisiksi?

**Comment by pknuuti** [comment]
Vaaran nextillä testattu. En tiedä ymmärsinkö ihan oikein mitä tässä haetaan. Vaarassa on merkitty pakolliseksi asiakasmääreeksi vain HOLDID ja esim. automaattitunnuksen tallentaminen onnistuu ilman ongelmia.

**Comment by atarnus** [comment]
Testasin Outissa laittamalla automaattien AUTOTYPE-arvon pakolliseksi, eikä estänyt asiakastietojen tallentamista. Ihan vähän jäi nyt epäselväksi, että millaiset asetukset siellä piti olla, että tämä virhe alunperin edes tapahtui?

Meillä on tietysti myös HOLDID pakollinen, se on yksilöivä ja sillä ei ole asiakastyyppirajausta. Tuo AUTOTYPE nyt ei ollut yksilöivä, mutta sillä on asiakastyyppirajoite, ja ei tuota Luokka-tietoa. Onko tämä riittävä testi vai pitäisikö vielä kokeilla jollain luokallisella arvolla? Tai asiakastyyppirajatulla arvolla, joka ei ole kytketty auktorisoituun arvoon?

Testasin itse asiassa nyt vielä lisäämällä Yhteisöasiakkaiden Y-tunnus pakolliseksi. Tämä ei ole kytketty auktorisoituihin arvoihin, eikä ole luokkaa. Ja asiakkaiden tallentaminen onnistuu.

**Comment by ajrajala** [comment]
> Testasin Outissa laittamalla automaattien AUTOTYPE-arvon pakolliseksi, eikä estänyt asiakastietojen tallentamista. Ihan vähän jäi nyt epäselväksi, että millaiset asetukset siellä piti olla, että tämä virhe alunperin edes tapahtui?
> 
> Meillä on tietysti myös HOLDID pakollinen, se on yksilöivä ja sillä ei ole asiakastyyppirajausta. Tuo AUTOTYPE nyt ei ollut yksilöivä, mutta sillä on asiakastyyppirajoite, ja ei tuota Luokka-tietoa. Onko tämä riittävä testi vai pitäisikö vielä kokeilla jollain luokallisella arvolla? Tai asiakastyyppirajatulla arvolla, joka ei ole kytketty auktorisoituun arvoon?
> 
> Testasin itse asiassa nyt vielä lisäämällä Yhteisöasiakkaiden Y-tunnus pakolliseksi. Tämä ei ole kytketty auktorisoituihin arvoihin, eikä ole luokkaa. Ja asiakkaiden tallentaminen onnistuu.

On minusta testattu kuten pitikin. Ongelma tosiaan oli siinä, että kun esim. automaatti-asiakaslajin käyttöön rajattu asiakasmääre AUTOTYPE oli pakollinen, niin tuo pakollisuus esti tallentamasta minkään muun asiakaslajinkaan tietoja.

**Comment by emta001** [comment]
Eiköhän tää toimi. Suljen tiketin.
