### ISSUE TITLE
Useampaa varausta peruttaessa vahvistuspopparissa ei ole tietoa mitkä varaukset ollaan poistamassa

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha-24.05#151]
### Mikä vikana?

Onkohan tämä Koha-Suomi muutos useamman varauksen samanaikainen peruutus-vahvistuspoppariin vielä toteuttamatta? Liittyy siis tähän: https://github.com/KohaSuomi/Koha-24.05/wiki/Uutta-versiossa-24.05#selke%C3%A4mpi-ilmoitus-useampaa-varausta-peruuttaessa 

Vaski-Nextillä useampaa varausta peruttaessa vahvistuspopparissa ei ollut lueteltu, mitkä varaukset poistetaan. Oli vain tieto "Haluatko varmasti peruuttaa tämän varauksen?". 

![image](https://github.com/user-attachments/assets/4792c736-4925-4a3c-a35a-71bfe03b2e07)

### Mitä pitäisi tapahtua

Vahvistuspoppariin pitäisi tulla peruttavien varausten ID:t.

**Comment by AnneliO** [comment]
Lista peruutettavista tulee näkyville sitä mukaa, kun niitä poistetaan sen jälkeen, kun olet valinnut _Vahvista poisto_:

![kuva](https://github.com/user-attachments/assets/614cd2d0-de3e-4ce0-a615-5099f198ceb7)

**Comment by AnneliO** [comment]
Toimintatapa mainitaan tuolla linkkaamallasi sivulla, mutta vasta kuvan jälkeen, joten se jää helposti huomaamatta:
![kuva](https://github.com/user-attachments/assets/c1730190-1120-400f-893e-6736880671a4)

**Comment by sksandel** [comment]
No näinhän se tosiaankin toimii.
