### ISSUE TITLE
Korjauksia tietueen muokkaus-sivuun

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-24.05#152]
### Mikä vikana?

Yhteisöstä bongattu [bugi 38211](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38211), jonka kuvaus on seuraavanlainen:

Prior to the patch from [bug 37947](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37947), there was the unnoticed [bug 38168](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38168) - if you created a biblio in the framework SR and then edited it again, the Settings menu would say you were in the Audio Cassettes, CDs framework, but the fields and tags would say you were in Default (easy check in MARC21 is that 001 and 003 are hidden in frameworks other than Default, so if you see them in the editor you are in Default). With the patch from [bug 37947](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37947), the first time you edit a newly-created record, the editor opens in Default and the Settings menu says it is in Default, then every time after that the editor opens in the correct framework and the Settings menu agrees.

Tuodaan korjaus meidänkin versioon.

EDIT.

Tiketin alkuperäinen nimi: "Jos muulla kuin oletuspohjalla luotua tietuetta muokkaa, tulee käyttöön huomaamatta oletuskuvailupohja". Tämän korjauksen yhteydessä tuodaan myös muutama muu korjaus, joista yhteisön tiketti on riippuvainen.

**Comment by emta001** [comment]
Tästä tulikin sitten isompi homma. Tän korjaaminen vaatii useamman yhteisöpatchin mukaan ottamisen, yksi niistä vaikuttaisi korjaavan jopa tietueen muokkaus-sivun tyhjenemisen. Korjaan tiketin nimen yleisempään muotoon, niin ei sitten jatkossa ihnmetellä mistä tässä oikein oli kysymys :smile:

**Comment by emta001** [comment]
Koska tässä on nyt 4 yhteisön tikettiä samassa syssyssä, niin testattavaakin on reippaammin (testiplänit on kopioitu tiketeistä ja suomennettu vapaasti):

[Bug 37429](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37429) - Can't edit bibliographic records anymore (empty form)

Tietueen muokkaus-lomake saattoi joskus jäädä tyhjäksi eikä tietueen tietoja haettu ennen kuin plack käynnistettiin uusiksi. Tämä johtui globaaleista muuttujista, joka sai arvonsa edellisestä lomakkeeseen tehdystä kutsusta, jolloin lomakkeella ei näkynyt muokattavan tietueen tietoja. Korjattu asettamalla muuttujiin oletusarvot.

1. Avaa jokin olemassa oleva tietue.
2. Muokkaa tietuetta.
3. Vaihda kuvailupohjaa (ei tarvitse tehdä muutoksia)
4. Vaihda kuvailupohja alkuperäiseen (ei tarvitse tallentaa)
5. Palaa tietueen tiedot-sivulle (detail.pl)
6. Avaa taas tietueen muokkaus.
=> Tietueen tietojen tulisi olla niillä kuuluvilla paikoillaan.

[Bug 37947](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37947) - Import from Z39.50 doesn't open the record in editor

Edellisestä tiketistä johtuen tietueen tuominen Z39.50 hakutuloksista ei enää avannut tietueen muokkaus-lomaketta. 

1. Mene Kuvailu-moduuliin.
2. Klikkaa "Uusi Z39.50/SRU-haku".
3. Tee haku esim. Melindaan jollakin hakuehdolla.
4. Valitse yksi tuloksista ja paina "Tuo".
=> Lisää MARC-tietue sivun tuli aueta ja tietueen tietojen tulisi olla täytettyhnä kenttiin.

**HOX! Kaikilla ei ole pikakuvailu käytössä, skipatkaa tämä jos näin on kimpassanne.**
[Bug 38076](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38076) - Librarians with only fast add permission can no longer edit or create fast add records

Virkailijat, joilla oli pelkkä fast_cataloging-oikeus, eivät pystyneet tekemään pikakuvailua. 

1. Kirjaudu sissän käyttäjänä, jolla on fast_cataloging oikeus, mutta ei muita editcatalogue-oikeuksia.
2. Siirry sivulle Kuvailu->Pikakuvailu
=> Lisää MARC-tietue lomakkeen tulisi aueta normaalisti.

[Bug 38211](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38211) - New bibliographic record in non-default framework opens in default on first edit

Jälleen globaali muuttuja ongelma, joka aiheutti väärän kuvailupohjan käytön tilanteissa jossa tietuetta muokataan ensimmäisen kerran.

1. Luo uusi tietue.
2. Täytä lomakkeelle vaaditut kentät ja tallenna tietue.
3. Muokkaa tietuetta.
=> Käytössä tulisi olla oikea kuvailupohja eikä lomakkeella näy sinne kuulumattomia kenttiä.

**Comment by ajrajala** [comment]
Vaski-nextillä testattu kaikki muu paitsi pikakuvailu, jota ei ole käytössä. Kaikki näyttäisi toimivan.

**Comment by piiaseme** [comment]
[Bug 37429](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37429) - Can't edit bibliographic records anymore (empty form)
- OUTIn nextillä ja testillä näyttäisi toimivan oikein.

[Bug 37947](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37947) - Import from Z39.50 doesn't open the record in editor
- Toimii OUTIn nextillä ja testillä.

[Bug 38211](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38211) - New bibliographic record in non-default framework opens in default on first edit
- OUTIn testillä ja nextillä testattu. Toimii oikein.

OUTIssa ei ole pikakuvailua käytössä.

**Comment by AnneliO** [comment]
Testasin täti-nextillä kaikki neljä kohtaa ja ne toimivat.

**Comment by AnneliO** [comment]
Tämän voinee sulkea. :)
