### ISSUE TITLE
Erä- ja noutopäiväkalenteriin ilmestyy ylimääräisiä sulkupäiviä

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-24.05#153]
### Mikä vikana?

Nextillä, kun kirjastolle lisää sulkupäiviä, voi kalenteriin yllättäen ilmestyä sulkupäiviä sellaisille päiville, joissa ylityksiä ei tulisi olla.

Koskelan kirjaston joulukuu ennen kalenterin muokkausta:
![kuva](https://github.com/user-attachments/assets/0c8a3ece-a014-43a3-90a6-8004c3d8fe69)

Lisäsin kirjastolle Helatorstai-ylityksen 28.-29.5.2024, 
![kuva](https://github.com/user-attachments/assets/67797e1c-5ddb-44ac-a8aa-1a4e435f5661)
niin kirjastolle ilmestyi myös joulun välipäiville "Helatorstai"-ylityksiä. 
![kuva](https://github.com/user-attachments/assets/ce8b83dc-0f1f-43f5-b692-ec2ab2250d49)

Helatorstai oli ilmestynyt myös juhannukselle:
![kuva](https://github.com/user-attachments/assets/1f8c6821-0e65-4109-abf8-2c077083220f)

Olin muille kirjastoille, ennen Koskelan kirjaston kalenterin muokkaamista, lisännyt juhannusylityksiä ja joululoma-ylityksiä. Ihan kuin kalenteri muistaisi aiemmat ylitykset ja vei samoille päiville myös Koskelalle mm. joululomaylitykset.

Kun tätä testasin muillakin kirjastoilla, niin kaikille ei ylimääräisiä ylityksiä tallentunut vaan ylimääräiset sulut tulivat ihan randomisti. 

Toinen esimerkki Ritaharjun kirjasto. Sille tallensin juhannus-ylityksen, niin se tallensi Ritaharjulle samalla myös Helatorstai-ylityksen vaikka sitä ei Ritaharjuun ollut tarkoitus tallentaa eikä sitä sinne oltu tallennettu.
![kuva](https://github.com/user-attachments/assets/cbea0f5d-1919-4671-a03a-2504dc5d9a89)

### Mitä pitäisi tapahtua

Kalenteriylitysten tulisi tallentua vain niille kiirjastoille ja päiville, jotka virkailja valitsee. 
Ylimääräisiä ylityksiä ei saisi kalenteriin ilmestyä itsekseen.

### Jotain muuta?

Aiemmin tästä on ollut Redmine-tiketti vuonna 2021:
https://github.com/KohaSuomi/RedGrave/blob/main/Palaute%20-%20Koha-Suomi/2021/%235084%20OUTI%3A%20Kohan%20kalenterii%20ilmestyy%20itsest%C3%A4%C3%A4n%20yksitt%C3%A4isi%C3%A4%20kiinniolop%C3%A4ivi%C3%A4.md

**Comment by emta001** [comment]
Tää voisi hyvinkin johtua (jälleen) plackista. Luultavasti sen välimuistiin on jäänyt noita kalenteriin tehtyjä muutoksia ja se poimii päivämäärät sieltä. Onko tilanne korjaantunut nyt kun plack on yöllä käynnistynyt uudestaan.

**Comment by piiaseme** [comment]
Pikaisella testailulla sain sen edelleen laittamaan itsekseen sulkupäiviä. 
![kuva](https://github.com/user-attachments/assets/2c241ec3-5a56-4722-a3de-a3c1075afc48)
Laitoin Kaijolle (yllä) syyslomaksi 13.-19.10. ja Karjasillalle 6.-12.10, niin kalenteri tallensi Karjasillalle syyslomaviikoiksi molemmat viikot (kuva alla).
![kuva](https://github.com/user-attachments/assets/5b3554ad-5c31-4465-b06a-92db36812f9c)

**Comment by piiaseme** [comment]
Lisäyksenä vielä, että Koskelan ja Ritaharjun kirjastoilta oli kadonnut ne ylimääräiset randomit ylitykset.

**Comment by LastuLauriH** [comment]
Meinasin jo kirjoittaa etten saa toistettua, mutta aikani kun tein etenkin eri aikaväleille ja käytin samaa nimeä asettaessa sulkuja, rupesi niitä edellisiä sulkuja tulemaan mukaan kuten Piialla yllä. En kyllä saanut toistettua sitä luotettavasti niin että sillä sulun nimellä olisi tuntunut olevan mitään väliä. Välillä tuli jopa kaksi aiempaa eri kirjastoille asetettua sulkua uuden mukana, ja sitten lopetti taas niiden monistamisen, sit taas jatkuu jne. Vaikea saada kiinni.

**Comment by piiaseme** [comment]
Juu, ylitysten nimellä ei näytä olevan vaikutusta.

Tein tästä bugzilla-tiketin: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38357 Toivottavasti siitä saa selkoa :D

**Comment by emta001** [comment]
Korjaus viety nexteille. Testipläni:

1. Lisää eri kirjastoille eri sulkupäiviä.
2. Varmista etteivät sulkupäivät kopioidu muille kirjastoille.

**Comment by piiaseme** [comment]
OUTIn nextillä korjaus toimii. Sulkupäivät eivät kopioidu muille kirjastoille itsekseen.

**Comment by ajrajala** [comment]
Vaski-nextillä lisäsin n. 10 kirjastolle yksittäisiä sulkupäiviä ja sulkujaksoja. Näissä testailuissa ei tapahtunut virheellistä kopioitumista.

**Comment by LastuLauriH** [comment]
En saanut enää toistettua ylimääräisiä sulkupäivien muodostumisia Lastu-Nextillä, kokeilin useita kertoja aikaväli- että yksittäisiä sulkuja yli viidelle eri kirjastolle.

**Comment by emta001** [comment]
Jesh, eiköhän tämä toimi. Suljen tiketin.
