### ISSUE TITLE
Tallennettujen raporttien Lataa-toiminnossa eivät toimi pienempi ja suurempi kuin merkit

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha-24.05#154]
### Mikä vikana?

Kun ajaa tallennetun raportin ja lataa tuloksen missä tahansa muodossa, korvaantuvat tuloksessa olevat < ja > merkit tiedostossa `&lt;` ja `&gt;` merkkijonoilla.

**Comment by AnneliO** [comment]
Oisko sulla esimerkkiä tällaisesta raportista?

**Comment by MikkoLiimatainen** [comment]
No, en tiedä onko varsinaista raporttia, jossa tämä ongelma tulee vastaan. Tällä hetkellä testiraportillani voi kokeilla tätä ongelmaa: [https://vaski-next.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?id=2140&op=run](https://vaski-next.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?id=2140&op=run).

Satuin huomaamaan asian, kun nappasin syspreffit tuotannosta ja nextiltä vertailtavaksi ja siellä olivat nuo merkit väärin.

En myöskään ole löytänyt muita virheellisesti muodostuvia merkkejä, vaikka yritin niitä hiukan hakeakin.

**Comment by AnneliO** [comment]
Aa, ne muuttuu muotoon "&lt" ja "&gt". Github ilmeisesti kääntää ne automaattisesti < ja > -muotoon, jolloin näyttää, että olet kirjoittanut kaksi kertaa lauseeseen "< ja >".

**Comment by MikkoLiimatainen** [comment]
No niinpä näköjään tekee :D En edes huomannut.

**Comment by AnneliO** [comment]
Voiskohan tämä liittyä tähän uuteen ominaisuuteen: https://github.com/KohaSuomi/Koha-24.05/wiki/Uutta-versiossa-24.05#htmln-poisto-kun-raportti-ladataan-csv-muotoisena

Kovasti kyllä väittävät tiketissä, että tuo koskee vain CSV-muotoista lataamista, mutta ei se varmaan olis eka kerta, kun väitteet ei pitäisi paikkansa.

**Comment by johannaraisa** [comment]
> Voiskohan tämä liittyä tähän uuteen ominaisuuteen: https://github.com/KohaSuomi/Koha-24.05/wiki/Uutta-versiossa-24.05#htmln-poisto-kun-raportti-ladataan-csv-muotoisena
> 
> Kovasti kyllä väittävät tiketissä, että tuo koskee vain CSV-muotoista lataamista, mutta ei se varmaan olis eka kerta, kun väitteet ei pitäisi paikkansa.

On se tuosta kiinni ja kyllä sitä käytetään muissakin formaateissa. Kokeilin kommentoida itseltä koodista tuon pois ja merkit ei muuttuneet.

**Comment by AnneliO** [comment]
Laitoin yhteisön tikettiin https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=5920 kommentin, että HTML:n poisto tapahtuu kaikissa latausmuodoissa, ei vain CSV:ssä, kuten release notesit väittää.

Nyt varmaan sitten pitänee pohtia, onko tuosta < ja > -merkkien muuttumisesta haittaa, koska tämä on tarkoituksellinen muutos. Jos on, niin siitä pitänee sitten tehdä yhteisöön tiketti.

**Comment by MikkoLiimatainen** [comment]
Meillä ei ainakaan tullut mieleen, että Vaskissa olisi yhtäkään raporttia, johon tämä tällä hetkellä vaikuttaisi. Jos jossakin raportin tuloksessa näitä merkkejä on, niin se ehkä on todennäköisemmin virhe tiedoissa, kuin oikeasti tarpeellinen asia. Minusta tämä voi nyt jäädä tänne tiedoksi ja avataan asia sitten uudelleen, jos tästä löytyy oikea haitta.

**Comment by AnneliO** [comment]
Ok. Suljen tiketin tältä erää ja avataan uudelleen, jos se tulee tarpeen. :)
