### ISSUE TITLE
Aikakauslehtien julkaisutiheyden muokkaaminen ei onnistu

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-24.05#156]
### Mikä vikana?

OUTIn nextillä ei aikakauslehtien julkaisutiheyden muokkaaminen ja poistaminen onnistu. Uuden julkaisutiheyden luominen onnistuu, mutta ei olemassa olevien poistaminen eikä muokkaaminen.

Kausijulkaisut -> Muokkaa ilmestymistiheyksiä
Poista-napista ei tapahdu mitään.
Muokkaus-sivulle pääsee ja muokkaaminen onnistuu, mutta muutos ei tallennu.

**Comment by AnneliO** [comment]
Jos ilmestymistiheyttä muokkaa, ei tule näkyville nykyiset tiedot, vaan tyhjät kentät:
![kuva](https://github.com/user-attachments/assets/8b541827-21e5-4777-8f10-f76f2987b1fb)

Testillä kentät ovat esitäytetty:
![kuva](https://github.com/user-attachments/assets/338e0121-4264-4cb7-af72-174dbe589295)

**Comment by lmstrand** [comment]
Yhteisössä editointi korjattu: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37165 (testattu kehitysympäristössä toimivaksi).
Tämä ei korjaa poistoa, enkä löytänyt yhteisöstä tikettiä asiasta.

**Comment by lmstrand** [comment]
Poisto on rikkoutunut tässä serials/subscription-frequencies.pl-tiedoston commitissa rivin 91 muutoksen myötä samaan tapaan, kuin editointi:
https://github.com/KohaSuomi/Koha-24.05/commit/18e808240febf817544f21eb84020a270761c9a5#diff-29e76c8fa76e45e0b37a796849de5566ef8ba8be3d45ad43fb5be7f012aac8f3

**Comment by lmstrand** [comment]
tiketti yhteisössä poisto-ongelmasta: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38378

**Comment by AnneliO** [comment]
Koska versionvaihtoon on seitsemisen työpäivää ja tämä ongelma ei estä lainaus- ja palautustoimintoja, niin ehdotan, että nämä korjaukset tuodaan tarvittaessa meidän versioon vasta versionpäivityksen jälkeen. :)

**Comment by lmstrand** [comment]
Korjaukset editointiin ja poistoon viety nexteille testattavaksi. Branchissa ksdev/ks-0204-K24-G138-fix-subscription-frequencies-editing.

**Comment by piiaseme** [comment]
OUTIn nextillä ilmestymistiheyden muokkaus ja poisto onnistuvat nyt.

**Comment by Rvallim0** [comment]
Vaski nextillä testattu, ilmestymistiheyden lisääminen ja olemassa olevan ilmestymistiheyden muokkaaminen ja poistaminen toimivat.

**Comment by lmstrand** [comment]
Poistamiseen tehty korjaus on poistettu branchista, koska ei ollut yhteisön mieleen. Tehdään tämä korjaus yhteisön mallin mukaan ja otetaan vasta sitten matkaan, kun tiketti  https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38378 siis menee yhteisössä läpi. Jätän tiketin siksi aikaa työn alla-tilaan.

**Comment by lmstrand** [comment]
Eikun tehdäänkin niin, että suljetaan tämä tiketti. Teetkö @piiaseme uuden tiketin tuosta pelkästä poisto-ongelmasta. Pysytään paremmin kärryillä sitten tuon poisto-ongelman tilasta.

**Comment by piiaseme** [comment]
Uusi tiketti poisto-ongelmasta: https://github.com/KohaSuomi/Koha-24.05/issues/159
Suljen tämän tiketin.
