### ISSUE TITLE
Ilmoitusten ja kuittien muokkauksessa Lisää/Insert-nappi ei toimi

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha-24.05#157]
### Mikä vikana?

Nexteillä ei ilmoitusten ja kuittien muokkauksessa pysty lisäämään viestiin siitä vasemmalta sitä dataa tietokantatauluista. _Lisää_-napin painallus ei tee mitään.

Kokeilin tyhjentää intranetusercss:n ja -js:n, muttei auttanut. Sandoxissa tämä toimii.

**Comment by johannaraisa** [comment]
Yhteisössä on korjaus asiaan, https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37059

**Comment by johannaraisa** [comment]
Tämä on tuotu nexteille, ladatkaa sivu ctrl+f5:llä.

**Comment by Tuomas-Kyyti** [comment]
Nyt nappi toimii.

**Comment by atarnus** [comment]
Outi-nextillä toimii myös.

**Comment by atarnus** [comment]
Ohimennen huomattiin tässä, että ilmoituksiin on tullut tällainen oletuskielimerkintä:
![image](https://github.com/user-attachments/assets/769dff00-fdc9-4e51-99c1-fff2703ca706)

Jostain syystä se oli Outissa alunperin Svenska. Vaihtui suomeksi kun OPACLanguages järjestystä muutti niin, että suomi oli ylimpänä. Ei mitään hajua vaikuttaako tuo mihinkään ja miksi meidän järjestys oli tämmöinen. Mutta kirjaan nyt johonkin ylös. :D

**Comment by Kati-Helle** [comment]
Helle-nextissäkin Lisää-painike toimii siirtäen valitun tietokantataulun arvon viestipohjaan.

**Comment by johannaraisa** [comment]
Toimii, suljen tiketin.
