### ISSUE TITLE
Aikakauslehtien julkaisutiheyden poistaminen ei onnistu

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-24.05#159]
### Mikä vikana?

OUTIn nextillä ei aikakauslehtien julkaisutiheyden poistaminen onnistu. Uuden julkaisutiheyden luominen ja muokkaaminen onnistuvat, mutta ei olemassa olevien poistaminen.

Kausijulkaisut -> Muokkaa ilmestymistiheyksiä
Poista-napista ei tapahdu mitään.

Tiketti yhteisössä poisto-ongelmasta: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38378

### Jotain muuta?

Julkaisutiheyden poiston epäonnistumisesta oli alunperin tiketissä: https://github.com/KohaSuomi/Koha-24.05/issues/156

**Comment by lmstrand** [comment]
Yhteisön tiketti tilassa Passed QA ja sign offattu pariin otteeseen, joten toin yhteisön korjauksen branchiin ksdev/ks-0204-K24-G138-fix-subscription-frequencies-editing.

**Comment by lmstrand** [comment]
testataan versionvaihdon jälkeen.

**Comment by lmstrand** [comment]
Tämän korjaus on viety testeille testattavaksi.

**Comment by piiaseme** [comment]
OUTIn testillä poistaminen nyt onnistuu.

**Comment by ajrajala** [comment]
Vaski-testillä ilmestymistiheyden poistaminen onnistui myös.

**Comment by johannaraisa** [comment]
Tämä on tuotannossa jo.

**Comment by johannaraisa** [comment]
Ei olekaan vielä, tuodaan huomenna.

**Comment by piiaseme** [comment]
Aikakauslehtien julkaisutiheyden poistaminen onnistuu nyt tuotannossa, joten suljen tiketin.
