### ISSUE TITLE
Luokitusoppaissa omia järjestelysääntö-plugineja - ksdev/ks-0033-K23-8-cn_sort-routines 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#16]
Kohan luokitusoppaisiin on lisätty omia järjestelysääntö-plugineja.

Koha-yhteisön tapa muodostaa niteiden signum poikkeaa suomalaisten yleisten kirjastojen tavasta. Niteen itemcallnumber-sarakkeen tieto kopioidaan niteen cn-sort-sarakkeeseen siten, että cn-sort-sarakkeeseen tieto tulee muodossa "luokka - pääsana", eli mahdolliset kirjasto- ja hyllypaikkalyhenteet tiputetaan pois. cn-sort-sarakkeen tietoa käytetään mm. tiedonhaussa luokan mukaan järjestämiseen. Jos sarakkeeseen tallennetussa tiedossa on alussa muuta kuin luokkatieto, tiedot eivät järjesty oikein.

Jotta tiedot saadaan vietyä oikein, luotiin sitä varten Kohan luokitusoppaisiin kaksi uutta järjestelysääntöä "OUTI" ja "LUMME".

**Comment by johannaraisa** [comment]
Tämä on nyt lisätty nexteille, testausta vaille valmista.

**Comment by AnneliO** [comment]
Testasin siili-nextillä, jossa on käytössä LUMME-versio ja tulos oli näin:

itemcallnumber | cn_sort
---|---
84.2 LEP PK A  | 84.2 LEP PK A 

Sitten testasin outi-nextillä, jossa on käytössä OUTI-versio ja siellä tulos oli näin:

itemcallnumber | cn_sort
---|---
AIK 70.92 BER  | 70.92 BER

Eli minusta nämä toimivat oikein.

**Comment by johannaraisa** [comment]
Hyvä, eiköhän tuo ole riittävä testaus. Suljen tiketin.
