### ISSUE TITLE
OUTI ja Vaara: Asiakasviestinnän käynnistäminen ti 19.11.2024 klo 12

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-24.05#160]
### Mikä vikana?

OUTIssa asiakasviestinnän saa käynnistää ti 19.11. klo 12.

**Comment by pknuuti** [comment]
Vaarassa samalla kaavalla eli ti 19.11. klo 12 asiakasviestit liikkeelle.

**Comment by piiaseme** [comment]
OUTIssa viestit kulkevat. Jos Vaarassakin viestitys pelaa, niin tämän tiketin voi sulkea :)

**Comment by pknuuti** [comment]
Vaarassa viestit pelaa.
