### ISSUE TITLE
Helle: Asiakasviestinnän käynnistämisaika keskiviikkona 20.11.2024

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-24.05#161]
### Mikä vikana?

Käynnistättekö Hellen asiakasviestien lähetyksen ke 20.11.2024 klo 9.30.

**Comment by johannaraisa** [comment]
Kytketty päälle, aloittavat normaaliin aikaan eli klo 9.30

**Comment by Kati-Helle** [comment]
Kiitos, viestit liikkuvat.
