### ISSUE TITLE
Lumme: asiakasviestinnän käynnistäminen ke 20.11.

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha-24.05#162]
### Mikä vikana?

Lumpeissa asiakasviestinnän saa käynnistää ke 20.11.

**Comment by johannaraisa** [comment]
Kytketty päälle, aloittavat normaaliin aikaan klo 9.30

**Comment by Hanna-Lumme** [comment]
Viestit ovat lähteneet, kiitoksia!
