### ISSUE TITLE
Vaski: asiakasviestinnän käynnistäminen ti 19.11. klo 12 

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha-24.05#167]
### Mikä vikana?

Vaskissa asiakasviestinnän saa käynnistää ti 19.11.2024 klo 12.

**Comment by sksandel** [comment]
Kaikki muut viestit kunnossa, mutta Vaskin kirjelähetykset (print) ovat edelleen pending-tilassa (muodostuneet 17.-20.11.).

**Comment by ajrajala** [comment]
Suljen tämän tiketin, tarkistettu että pending-tilaan keskiviikkona jääneet kirjeet muuttuivat lähetetyiksi.
