### ISSUE TITLE
Lastu: asiakasviestinnän käynnistäminen ti 19.11. klo 12

### ISSUE THREAD

**Issue by LastuJanneS** [KohaSuomi/Koha-24.05#168]
### Mikä vikana?

Lastussa voi asiakasviestinnän käynnistää tiistaina 19.11. klo 12

**Comment by LastuJanneS** [comment]
Täällä aloiteltiin tuotantokäyttö jo aamulla, eli meidän puolesta voi asiakasviestinnän käynnistää jo aikaisemminkin mikäli sopiva hetki ilmaantuu.

**Comment by johannaraisa** [comment]
Laitan ne päälle nyt, aloittavat sitten normaaliin aikaan eli klo 9.30.

**Comment by LastuJanneS** [comment]
Kiitos, hyvin toimii. Suljen tiketin.
