### ISSUE TITLE
Tekstiviestirajapinnat, message_id arvon lisääminen viestienlähetysfunktioon - ksdev/ks-0034-K23-22-SMS

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#17]
Tekstiviestirajapinnat, message_id arvon lisääminen viestienlähetysfunktioon.

**Comment by johannaraisa** [comment]
Tämä on lisätty nextille, ei ollut ristiriitoja joten uskon toimivan edelleen.
