### ISSUE TITLE
Lisätään bib-level arvot d osakohdehakuun - ksdev/ks-0189-KOHA-1419-add-bib-levels 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#170]
### Siirrettävä ominaisuus

Alkuperäinen tiketti 

> [Osakohteiden näkymisessä emokohteessa ongelmia, jos osakohteen taso on d #1419](https://github.com/KohaSuomi/Koha/issues/1419)
> 
> Lastussa on hieman reilu 300 000 osakohdetta, joilla on bib-level:d. Nämä ilmeisesti linkittyvät emokohteisiin, mutta eivät tule näkyviin emokohteen tietueessa "Osakohteet"-välilehdellä. Tämä johtuu ilmeisesti siitä, että d-taso on rajattu pois haussa jossa Koha hakee osakohteet mukaan.
> 
> Koha-Suomen kehittäjät ovat tästä keskustelleet, ja tavoite korjata tämä tekemällä pieni koodimuutos Kohaan.

Eli testattava niin, että näkyvätkö sellaiset osakohteet emon "Osakohteet"-välilehdellä, joilla on bib-level:d. Koskenee erityisesti Lastua.

**Comment by LastuJanneS** [comment]
Testien perusteella näkyvät Lastussa oikein emonsa "Osakohteet"-välilehdellä.

**Comment by emta001** [comment]
Käsittääkseni ongelma on tosiaan vain Lastussa, joten eiköhän riitä että siellä on testattu ja todettu toimivaksi. Suljen tiketin.
