### ISSUE TITLE
Lisää muuttujien nimet raportista jos niitä ei laiteta raporttia kutsuessa - ksdev/ks-0195-bug-32413-fix-param-names-for-json-report

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#171]
### Siirrettävä ominaisuus

Jos raportilla oli kahteen kertaan kutsu samaan parametriin, esim. UNION-lauseessa toisen SELECT-kyselyn tulokset jäivät puuttumaan tuloksista.

Testaa näin:
1) Luo raportti:
    SELECT count(\*) from items where homebranch = \<\<Branchcode>>
    UNION ALL
    SELECT count(\*) from deleteditems where homebranch = \<\<Branchcode>>
2) Aja raportti JSONina, eli esimerkiksi  https://vaski-next.koha-suomi.fi/cgi-bin/koha/svc/report?id=\<\<RAPORTIN ID TÄHÄN!>>&sql_params=\<\<KIRJASTOPISTEEN TUNNUS TÄHÄN>>
3) Tarkista, että saat raportilla 2 tulosta ja ne ovat oikein

**Comment by MikkoLiimatainen** [comment]
Testattu Vaskin nextillä ja toimii oikein.

**Comment by LeenaKinnunen** [comment]
Mitä tarkoittaa Aja raportti JSONina? En saa Lapin nextillä tulosta?

**Comment by AnneliO** [comment]
Tein siili-nextille raportin nro 125 ja "ajoin" sen JSONina lisäämällä selaimen välilehdelle osoitteeksi https://siili-next.koha-suomi.fi/cgi-bin/koha/svc/report?id=125sql_params=SII_PK

Se antaa kyllä tuloksia, mutta tulokset ovat 0. Pitäisi olla 933 ja 4. Onko minun osoitteessa virhe?

**Comment by MikkoLiimatainen** [comment]
ennen sql_params tulee olla &-merkki

**Comment by atarnus** [comment]
Outissa toimii, mutta voisiko tälle syöttää useampia parametrejä vielä ja testata toimiiko niiden kanssa?

**Comment by AnneliO** [comment]
> ennen sql_params tulee olla &-merkki

Kiitos, nyt toimi siili-nextilläkin https://siili-next.koha-suomi.fi/cgi-bin/koha/svc/report?id=125&sql_params=SII_PK

**Comment by MikkoLiimatainen** [comment]
> Outissa toimii, mutta voisiko tälle syöttää useampia parametrejä vielä ja testata toimiiko niiden kanssa?

Testasin tätä kahdella eri parametrillä ja näytti toimivan.

**Comment by atarnus** [comment]
> > Outissa toimii, mutta voisiko tälle syöttää useampia parametrejä vielä ja testata toimiiko niiden kanssa?
> 
> Testasin tätä kahdella eri parametrillä ja näytti toimivan.

Miten kannattaa kaksi eri parametria syöttää tuolle, minulla ne tunkeutuu vain yhteen kun en hokaa, että miten eritellään toisistaan.

**Comment by MikkoLiimatainen** [comment]
Itse ajoin tuon näin: [https://vaski-next.koha-suomi.fi/cgi-bin/koha/svc/report?id=2078&sql_params=tupk&sql_params=20](https://vaski-next.koha-suomi.fi/cgi-bin/koha/svc/report?id=2078&sql_params=tupk&sql_params=20)
Toisena parametrinä käytin items.issues > <<määrä>>

**Comment by atarnus** [comment]
Näyttäisi nyt toimivan minullakin. Kokeilin aiemmin tuota ja sekin tuntui vain pistävän ne annetut parametrit pötköön, mutta olisiko kuitenkin ollut vain joku kirjoitusvirhe vielä siinä. Eli kokeilin rajata homebranchin lisäksi itypellä, ja toimii.
https://outi-next.koha-suomi.fi/cgi-bin/koha/svc/report?id=785&sql_params=OUPK&sql_params=28VRK

**Comment by ElinaUotila** [comment]
Kirkes-nextillä toimii ja tulee oikea tulos.

**Comment by emta001** [comment]
Toimii siis, suljen tiketin.
