### ISSUE TITLE
Automaatilla uusinnassa ei näy uusi eräpäivä

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-24.05#172]
### Mikä vikana?

Vaskin tuotannossa testatiin lainausautomaatilla lainan uusintaa ja näyttäisi, että [tämä muutos](https://github.com/KohaSuomi/Koha-24.05/commit/fd63776e926c6308a94693d0fe034009723c84fa) ei olisi tuotannossa mukana. Uusinnan jälkeen automaatin näytöllä sekä kiuitilla näkyi siis vanha eräpäivä. Eräpäivä päivittyi vasta, kun lainojen tiedot avasi automaatille uudelleen.

**Comment by pknuuti** [comment]
Vaarassa sama huomio eli lainausautomaatin näytöllä ja kuitilla näkyy uusinnan jälkeen vanha eräpäivä.

**Comment by AnneliO** [comment]
Koitetaan käynnistää sipit ja plackit uudelleen.

**Comment by ajrajala** [comment]
Pääkäyttäjäpalaverissa oli epäilys että sipit ja plackit oli jo käynnistetty uudelleen, joten testattiin tätä (ja tikettiä #174) uudelleen mutta ei näyttäisi edelleenkään toimivan. Mutta olikohan uudelleenkäynnistystä sitten kuitenkaan vielä tehty, testattiinko ennenaikaisesti?

**Comment by ElinaUotila** [comment]
Kirkesissä testattiin juuri, ja täälläkään ei näy uusi eräpäivä.

**Comment by lmstrand** [comment]
SIP-palvelimeen tehdyt muutokset olivat tippuneet jostain syystä pois kyydistä tuotannossa (ja nextillä). Päivitin tuotannot ja nyt kaikki muutokset ovat mukana, mukaanlukien tämä ja pitäisi toimia taas oikein.

**Comment by ReettaSiili** [comment]
Uusi eräpäivä näkyy nyt oikein ruudulla ja kuitilla ainakin Siilin Mikro-Väylän automaateilla.

**Comment by piiaseme** [comment]
Uusi eräpäivä näkyy näytöllä ja kuitilla OUTIn Lyngsoen automaatilla.

**Comment by ajrajala** [comment]
Jeps, toimii! Suljen tiketin.
