### ISSUE TITLE
Väärät Elasticsearchin mäppäykset käytössä tuotannossa

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-24.05#173]
### Mikä vikana?

Tuotannoissa on käytössä väärät Elasticsearchin mäppäykset, josta johtuen esim. faseteilla on väärä otsikot ja puuttuu uudet isbn-all ja issn-all -indeksit.

**Comment by emta001** [comment]
Kaikki kimpat on nyt päivittymässä.

**Comment by AnneliO** [comment]
Tämä on nyt ok. Suljen tiketin, kiitos!
