### ISSUE TITLE
Automaatilla ei saa lainattua toisella asiakkaalla lainassa olevaa nidettä

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-24.05#174]
### Mikä vikana?

Vaskin tuotannossa testattiin lainausautomaatilla sellaisen niteen lainaamista, joka on toisella asiakkaalla lainassa. Vaikuttaisi, että [tämä muutoas](https://github.com/KohaSuomi/Koha-24.05/commit/01e84f20969fa7cfec24651554eac19f7159ad5b) ei olisi tuotannossa mukana?

**Comment by AnneliO** [comment]
Koitetaan käynnistää sipit ja plackit uudelleen.

**Comment by lmstrand** [comment]
SIP-palvelimeen tehdyt muutokset olivat kaikki tippuneet pois branchista. Päivitin tuotannot muutosten kera ja käynnistin sip-palvelimet uudelleen. Nyt pitäisi toimia.

**Comment by piiaseme** [comment]
OUTIssa on testattu ja todettu toimivaksi.

**Comment by ajrajala** [comment]
Meillä myös testattu ja nyt tosiaan kunnossa, suljen tiketin.
