### ISSUE TITLE
Itsepalvelulainauksessa kohdistin siirtyy palautuksen jälkeen lainauskenttään

### ISSUE THREAD

**Issue by atarnus** [KohaSuomi/Koha-24.05#176]
### Mikä vikana?

Itsepalvelulainauksessa on nyt pieni epäkäytännöllisyys palautuksen yhteydessä. Kun palauttaa niteen, niin fokus siirtyy automaattisesti lainauskenttään. Eli siis useamman niteen palauttaminen peräkkäin vaatii aina kohdistamaan erikseen palautuskenttään jokaisen palautuksen välissä. Tämän voi toistaa ihan silläkin, että painaa OK tyhjässä palautuskentässä.

![image](https://github.com/user-attachments/assets/74ec5c61-3452-4e84-99fc-56368d6a2333)
 

### Asiasanat/tagit

itsepalvelulainaus

**Comment by emta001** [comment]
Vika löytyi, tuo viivakoodi-kenttä ei enää saanut focus-classia mistään. Se lisättiin aiemmin palautuksen yhteydessä, kun sivulle palautettiin palautetun niteen tiedot checkinmessage-parametrissä. Se oli ihan Koha-Suomen omaa koodia, jonka sijaan siirryttiin käyttämään yhteisön mukaista palautus viestiä. Enpä sitten hoksannut riisua tuolta sivulta kaikkia checkinmessage-parametriä käyttäviä koodinpätkiä ja vaihtaa tuohon barcode-kenttään ehtoa, jolla focus-class lisätään :sweat_smile: Korjailen tuon ja laitan testeille eka testattavaks.

**Comment by emta001** [comment]
Viety testeille.

**Comment by pirliis** [comment]
OUTIssa fokus hyppää niteen palautuksen jälkeen vielä Lainaus-kenttään.

**Comment by emta001** [comment]
> OUTIssa fokus hyppää niteen palautuksen jälkeen vielä Lainaus-kenttään.

Hmm, sain kyllä toimimaan tuon. Testasitko siis testillä vai tuotannossa? Tää on vasta testillä.

**Comment by pirliis** [comment]
> > OUTIssa fokus hyppää niteen palautuksen jälkeen vielä Lainaus-kenttään.
> 
> Hmm, sain kyllä toimimaan tuon. Testasitko siis testillä vai tuotannossa? Tää on vasta testillä.

Testillä testasin, mutta niteet eivät olleet lainassa.

**Comment by atarnus** [comment]
Jos painaa tyhjänä Palautuksen OK:ta tai palauttaa niteen, joka ei ole lainassa, niin edelleen hyppää Lainauskenttään. Ainakin tuossa tapauksessa, että palauttaa niteen, joka ei ole lainassa, niin mielellään saisi silloinkin pysyä vielä palautuskentässä. Noita kuitenkin tulee.

**Comment by emta001** [comment]
> Jos painaa tyhjänä Palautuksen OK:ta tai palauttaa niteen, joka ei ole lainassa, niin edelleen hyppää Lainauskenttään. Ainakin tuossa tapauksessa, että palauttaa niteen, joka ei ole lainassa, niin mielellään saisi silloinkin pysyä vielä palautuskentässä. Noita kuitenkin tulee.

No pitää vielä huomenna katella. Ihan en kyllä hoksaa, miten tuo on aiemmin sitten pysynyt tossa Palautus-kentässä näissäkin tapauksissa, kun eihän näissä generoida checkinmessagea lainkaan :thinking: Mutta ehkä multa nyt vaan jää jotain oleellista hoksaamatta :sweat_smile:

**Comment by emta001** [comment]
No nyt fokuksen pitäs säilyä myös kun tarjotaan nidettä, joka ei ole joko lainassa tai olemassa lainkaan, sekä silloin jos lähetellään tyhjää kenttää eteenpäin.

**Comment by pirliis** [comment]
> No nyt fokuksen pitäs säilyä myös kun tarjotaan nidettä, joka ei ole joko lainassa tai olemassa lainkaan, sekä silloin jos lähetellään tyhjää kenttää eteenpäin.

Onko tämä jo tuotannossa vai vielä testillä?

**Comment by emta001** [comment]
> > No nyt fokuksen pitäs säilyä myös kun tarjotaan nidettä, joka ei ole joko lainassa tai olemassa lainkaan, sekä silloin jos lähetellään tyhjää kenttää eteenpäin.
> 
> Onko tämä jo tuotannossa vai vielä testillä?

Testillä, koska ei kannata tässä vaiheessa päivittää tuotantoja. Tehdään sinne päivitys huomenaamulla, jos tän todetaan olevan ok.

**Comment by pirliis** [comment]
Testattu OUTIn tesillä. Kursoriongelma on korjaantunut eli jos palauttaa useamman "ei lainassa" olleen niteen peräkkäin, kursori pysyy Palautus-kentässä. Tosin ohjelma antaa ilmoituksen: "Nidettä ei palautettu: ole hyvä ja ota yhteyttä kirjaston henkilökuntaan", vaikka niteen palautus onnistui.

Myös lainassa olleiden niteiden palauttaminen peräkkäin toimii eli kursori pysyy Palautus-kentässä.

**Comment by emta001** [comment]
> Testattu OUTIn tesillä. Kursoriongelma on korjaantunut eli jos palauttaa useamman "ei lainassa" olleen niteen peräkkäin, kursori pysyy Palautus-kentässä. Tosin ohjelma antaa ilmoituksen: "Nidettä ei palautettu: ole hyvä ja ota yhteyttä kirjaston henkilökuntaan", vaikka niteen palautus onnistui.
> 
> Myös lainassa olleiden niteiden palauttaminen peräkkäin toimii eli kursori pysyy Palautus-kentässä.

No ei sen kyllä tuommosia pitäs höpistä, kun palautus onnistuu :smile:

**Comment by emta001** [comment]
![image](https://github.com/user-attachments/assets/8afdd5cf-5b0c-4875-a088-8d6247cc6922)
Hmm, kyllä tää ihan oikein näyttäs toimivan :thinking:

**Comment by pirliis** [comment]
Joo, kun palautetaan nide, joka oli lainassa, palautetun niteen tiedot tulevat aivan oikein (kuin sinun kuvassa), mutta tarkoitin, jos palauttaa niteen, joka ei ollut lainassa, ohjelma ilmoittaa "Nidettä ei palautettu...".

**Comment by emta001** [comment]
> Joo, kun palautetaan nide, joka oli lainassa, palautetun niteen tiedot tulevat aivan oikein (kuin sinun kuvassa), mutta tarkoitin, jos palauttaa niteen, joka ei ollut lainassa, ohjelma ilmoittaa "Nidettä ei palautettu...".

Niin joo tämä. Aiemmin ei käytetty noita Kohan omia ilmoituksia ja Anneli muisteli, että silloin palautettiin "Palautettu xxxx nide...." viesti. Mikä on kyllä minusta aivan väärin, miksi väittää asiakkaalle, että on palautettu jotain mikä ei edes ole lainassa :sweat_smile: Muistelisin myös, että tuota pohdittiin sillon kun tätä rukattiin uuteen kuosiin ja todettiin, että annetaan olla noin.

**Comment by pirliis** [comment]
> > Joo, kun palautetaan nide, joka oli lainassa, palautetun niteen tiedot tulevat aivan oikein (kuin sinun kuvassa), mutta tarkoitin, jos palauttaa niteen, joka ei ollut lainassa, ohjelma ilmoittaa "Nidettä ei palautettu...".
> 
> Niin joo tämä. Aiemmin ei käytetty noita Kohan omia ilmoituksia ja Anneli muisteli, että silloin palautettiin "Palautettu xxxx nide...." viesti. Mikä on kyllä minusta aivan väärin, miksi väittää asiakkaalle, että on palautettu jotain mikä ei edes ole lainassa 😅 Muistelisin myös, että tuota pohdittiin sillon kun tätä rukattiin uuteen kuosiin ja todettiin, että annetaan olla noin.

Varmaan harvoin itsepalvelutoiminnolla palautetaan "ei lainassa" olevia, joten ei varmaan tule ongelmaa.

**Comment by emta001** [comment]
Tuodaan tämä huomenna tuotantoon.

**Comment by piiaseme** [comment]
OUTIssa testattu tuotannossa ja kursori pysyy nyt palautuskentässä, kun palauttaa "ei lainassa" olleen niteen.

**Comment by johannaraisa** [comment]
Suljetaan tämä tiketti.
