### ISSUE TITLE
Asiakasviesteissä ja kuiteissa ei voi enää käyttää <<arvoja>> Template Toolkit -tagien sisällä

### ISSUE THREAD

**Issue by atarnus** [KohaSuomi/Koha-24.05#178]
Anneli mainitsi tiketin https://github.com/KohaSuomi/Koha/issues/1953 yhteydessä:
>Katselen tässä [Bywater Solutionsin esittelyvideota versioiden 23.11 ja 24.05](https://youtu.be/lib3VJbwf5Y?si=wvrnQUJ8TJD-ODVG&t=3757) ominaisuuksista ja siellä sanotaan, että uusissa viestipohjissa ei toimi <<>>-tägit, koska ne tukee vain Template Toolkitia. Ja että vanhat viestipohjat tukee hauenleukoja.

Tästä tuli heti mieleeni Kohan tervetuloviesti ja sen 
`[% IF "<<borrowers.categorycode>>" == "VIRKAILIJA" %]`
Kävin testillä luomassa uuden virkailijan, ja tosiaan tuo asiakatyypin tarkistus ei enää toiminut. Sen sijaan viestipohja hyväksyi 
`[% IF borrower.categorycode == "VIRKAILIJA" %]`
huom. borrower ilman s-kirjainta lopussa.

Tämä toimimattomuus koskee nyt vain näitä kulmasulkeissa olevia arvoja, jotka ovat Template Toolkit tagien [% %] sisällä.
Tekstin osina nuo arvot toimivat edelleen oikein. Esim.
```
Hei[% IF ( borrower.othernames ) %] <<borrowers.othernames>>!
[% ELSIF ( borrower.firstname ) %] <<borrowers.firstname>>!
[% ELSE %] <<borrowers.surname>>! 
[% END %] 
```

OUTIssa näkyvi olevan noita [% IF "<<borrowers.categorycode>>" == "VIRKAILIJA" %] -tyyppisiä lausekkeita seuraavissa viestipohjissa:
WELCOME
MEMBERSHIP_EXPIRY
PASSWORD_CHANGE
CHECKINSLIP

Palautuskuitin tapauksessa riittää koko ehdon poisto, sillä anonymisoidulle asiakkaalle ei voi enää tulostaa palautuskuittia ollenkaan, ks. https://github.com/KohaSuomi/Koha/issues/1503

**Comment by AnneliO** [comment]
Nämä on nyt korjattu Ilmoitukset ja kuitit -sivulle. Suljen tiketin. :)
