### ISSUE TITLE
Do not allow script-tags in systempreferences - ksdev/ks-0035-K22-9-script-tags-sysprefs

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#18]
**HUOM! Tutkittava voiko tämän tiputtaa!**

Do not allow script-tags in systempreferences. Tietoturvapäivitys.

**Comment by johannaraisa** [comment]
Tämä on nyt nexteillä testattavana.

Testaussuunnitelma:

1. Lisää johonkin järjestelmäasetuksen tekstikenttään tämä: <script>alert("hello");</script>
2. Huomaa, että sivu ilmoittaa: 
![image](https://github.com/user-attachments/assets/ad656875-da95-41e4-b9f1-ab301a46420f)

**Comment by pknuuti** [comment]
Näin toimii Vaaran nextillä eli tulee kuvan mukainen huomautus.

**Comment by MikkoLiimatainen** [comment]
Vaskinkin nextillä tulee virheviesti, jos yrittää tallentaa skriptiä järjestelmäasetuksiin. Kokeilin jokseenkin sattumanvaraisesti eri asetuksiin ja aina tuli virheilmoitus.

**Comment by pirliis** [comment]
Myös OUTIn testillä tuli virheilmoitus: Error: Internal Server Error

**Comment by johannaraisa** [comment]
Todetaan toimivaksi, suljen tiketin.
