### ISSUE TITLE
OUTI: Käyttäjäoikeuksien ajo

### ISSUE THREAD

**Issue by atarnus** [KohaSuomi/Koha-24.05#180]
OUTIssa suurimmalle osalle virkailijatunnuksista kuuluisi koko borrowers-osion oikeudet, eli flag 4. Tuo flag ei ole kuitenkaan tullut automaattisesti kaikille virkailijoille, joilla on valittuina kaikki osion oikeudet, eli meillä on nyt virkailjoita samoilla oikeuksilla flagin kanssa ja ilman.

Toiveemme olisi nyt saada ajettua tuo flag 4 kaikille virkailijatunnuksille, joilta löytyy _delete_borrowers_-oikeus (237 tunnusta). Vähän kysymysmerkiksi jäi tässä se, että poistaako flagin ajaminen sitten user_permissions taulusta nuo yksittäiset oikeudet, vai pitäisikö ne erikseen vielä siivota.

Sen jälkeen kun flag 4 olisi paikoillaan kaikilla virkailijatunnuksilla, joille se kuuluu, tarvisi vielä ajaa _list_borrowers_- ja _send_messages_to_borrowers_-oikeudet kaikille virkailijoille, joilla on _edit_borrowers_-oikeus (näitä pitäisi olla sitten jäljellä 217 tunnusta. Tällä hetkellä nämä oikeudet ovat käytössä flag4-omaavien lisäksi vain 44 virkailijatunnuksella, joilta käsin poistin tarpeettoman delete_borrowers-oikeuden ja samalla lisäsin nämä uudet, eli puuttuu 173:lta.)

**Comment by emta001** [comment]
Tein nyt ensin tästä koeajon testeille. Otin vanhat käyttäjäoikeudet ja asiakkaat, joita tuo flagsin asetus koskee, talteen aputauluun. Tässä testikannasta 10 ensimmäistä asiakasta, joilta löytyi delete_borrowers-oikka:

```
+----------------+
| borrowernumber |
+----------------+
|         185067 |
|         185070 |
|         185071 |
|         185073 |
|         185077 |
|         185079 |
|         185080 |
|         185082 |
|         185085 |
|         185088 |
+----------------+
```

Ja tässä sitten jäljelle jääneet asiakkaat, joilla oli edit_borrowers-oikeus:

```
+----------------+
| borrowernumber |
+----------------+
|         186485 |
|         186486 |
|         186497 |
|         186498 |
|         186499 |
|         186500 |
|         186501 |
|         186502 |
|         186503 |
|         186504 |
+----------------+
```

Tarkistin muutaman näistä käyttäjistä ja vaikuttaisi sille, että ajot meni kuten pitikin.

**Comment by emta001** [comment]
Ajot tehty myös tuotantoon seuraavilla loitsuilla:

`CREATE TABLE ks_20241120_user_permissions_KS24180 SELECT * FROM user_permissions;`

`CREATE TABLE ks_20241120_borrowers_KS24180 SELECT * FROM borrowers WHERE borrowernumber IN(SELECT borrowernumber FROM user_permissions WHERE code = "delete_borrowers");`

`UPDATE borrowers SET flags = flags + (1<<4) WHERE borrowernumber IN(SELECT borrowernumber FROM user_permissions WHERE code = "delete_borrowers");`

`DELETE FROM user_permissions WHERE borrowernumber IN(SELECT borrowernumber FROM borrowers WHERE flags = flags | (1<<4)) AND module_bit = 4;`

`SELECT CONCAT('INSERT INTO user_permissions (borrowernumber, module_bit, code) VALUES (',borrowernumber,', 4, "list_borrowers");') FROM user_permissions WHERE code = "edit_borrowers";`

`SELECT CONCAT('INSERT INTO user_permissions (borrowernumber, module_bit, code) VALUES (',borrowernumber,', 4, "send_messages_to_borrowers");') FROM user_permissions WHERE code = "edit_borrowers";`

Kahdessa jälkimmäisessä ajo koski kylläkin 268 käyttäjää.

**Comment by atarnus** [comment]
Minä taisin vähentää tuon 44 sieltä kahdesti. :)
Olen tarkennellut nyt meidän raportteja myös ja löytänyt muutamia poikkeuksia vielä jotka oli hyvä käsin korjata. Pieniä epäjohdonmukaisuuksia selitti nämä jotkut yksittäiset poikkeukset sekä se, että oikeuksia oli myös API-tunnuksilla, ja VIRKAILIJA-rajaus oli mukana joissain minun raporteissa ja toisissa ei.

Ihan oikealta näyttää, kiitos!
