### ISSUE TITLE
Hankinnan muokkaa-napin toimimattomuus

### ISSUE THREAD

**Issue by helasann** [KohaSuomi/Koha-24.05#181]
### Mikä vikana?

Hankinnan muokkaa -nappi ei toimi niteen vastaanotossa.

### Mitä pitäisi tapahtua

Pitäisi siirtyä eteenpäin.

**Comment by AnneliO** [comment]
Voitko laittaa kuvakaappauksen tai osoitteen, missä tämä tapahtuu? :)

**Comment by ajrajala** [comment]
Olisikohan kyse tästä? Meille tuli eilen ilmoitus, ettei tuosta Muokkaa-linkistä pääse eteenpäin. Kun Muokkaa-linkkiä klikkaa, latautuu hetken aikaa uusi välilehti, mutta sitten se sulkeutuu ja käyttäjä on takaisin vastaanottonäkymässä.
![Vastaanotto muokkaa](https://github.com/user-attachments/assets/90f82473-f37b-42fd-9d55-2bdbde8cabd4)

**Comment by helasann** [comment]
Sain juuri kuvakaappauksen tähän liittyen ja kyse on tuosta ylempänä mainitusta asiasta.

**Comment by piiaseme** [comment]
OUTIssa saimme juuri viestin samasta ongelmasta.

**Comment by AnneliO** [comment]
Testasin tätä Bywaterin sandboxissa ja siellä muokkaus onnistuu. Tosin siellä näkymä on hieman erilainen. Edit-sana ei näytä linkiltä, mutta sitä klikatessa avautuu niteen muokkaus toiseen välilehteen.

![kuva](https://github.com/user-attachments/assets/1de1d5ca-d8c0-453a-a4d5-772a977f1058)

**Comment by AnneliO** [comment]
Koitin etsiä tästä tikettiä Bugzillasta ja kysellä myös yhteisön Mattermostista, mutta mitään ei löytynyt.

**Comment by johannaraisa** [comment]
Tarvitsen polun miten tuolle näytölle pääsee, en muista näitä ulkoa.

**Comment by helasann** [comment]
> Tarvitsen polun miten tuolle näytölle pääsee, en muista näitä ulkoa.

Auttaisiko tämä:
Hankinnat > hae toimittaja > vastaanota tilauksia (lue laskun numero) > hae vastaanotettava nide > vastaanota > muokkaa (ei toimi)

**Comment by johannaraisa** [comment]
Löytyi korjaus yhteisöstä, https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37536
Tuon testeille.

**Comment by johannaraisa** [comment]
Tämä on tuotu testeille.

Testausohje:
1. Käy ensin niteiden muokkausnäytöllä tekemässä ctrl+f5. (Liittyy tuohon additem sivuun).
2. Tämän jälkeen kokeile Muokkaus-nappia vastaanotossa.

**Comment by helasann** [comment]
> Tämä on tuotu testeille.
> 
> Testausohje:
> 
> 1. Käy ensin niteiden muokkausnäytöllä tekemässä ctrl+f5. (Liittyy tuohon additem sivuun).
> 2. Tämän jälkeen kokeile Muokkaus-nappia vastaanotossa.

Kirkes-testillä toimii. Meidän puolesta voi laittaa tuotantoon.

**Comment by piiaseme** [comment]
OUTIn testillä Muokkaa-linkki toimii nyt.

**Comment by helasann** [comment]
Päivitystä pyydetään kiirehdittävän. Saadaanko tiistaille, vai meneekö kuukausihuoltoon?

**Comment by AnneliO** [comment]
> Päivitystä pyydetään kiirehdittävän. Saadaanko tiistaille, vai meneekö kuukausihuoltoon?

Tämä on tulossa huomiseen päivitykseen.
