### ISSUE TITLE
Kirkes: Lapsiasiakkaalle ei voi tallentaa huoltajatietoa

### ISSUE THREAD

**Issue by helasann** [KohaSuomi/Koha-24.05#183]
### Mikä vikana?

Lapsiasiakkaalle ei voi tallentaa huoltajatietoa, koska valikko puuttuu.

### Mitä pitäisi tapahtua

Valikko, josta huoltajatiedon voi valita, on näkyvissä.

### Kuinka toistaa ongelma/asia

Lisää lapsiasiakas
Täytä tarvittavat lapsen tiedot
Lisää takaaja
Tallenna

### Jotain muuta?

![kuva](https://github.com/user-attachments/assets/a3d4976c-db5b-40ba-9dfe-f509522dab94)

**Comment by ElinaUotila** [comment]
Ongelma löytyi borrowerunwantedfield-asetuksesta.
