### ISSUE TITLE
Signumplugari ei toimi "Niteiden muokkaus eräajona" -toiminnossa

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-24.05#184]
### Mikä vikana?

Kun niteitä muokkaa eräajotoiminnossa ja painaa "Kohan koko signum" -kentän kolmea pistettä, kenttä menee vain lukkoon ja jää tyhjäksi, eikä signumia muodostu. OUTIssa käytössä plugari "loc_084a_mainheading_signum_builder.pl".

Yksittäisen niteen muokkausnäytöllä signum muodostuu oikein plugarilla.

**Comment by atarnus** [comment]
Voisiko noissa buildereissa olla yleisestikin jotain hitautta? Minusta se automaattisen nidetyypin valintakin on aika hidas, menee n. 10 sek.

**Comment by AnneliO** [comment]
Testasin viemällä teoksen https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2330941 Muut kokoelmat -välilehden niteet niteiden erämuokkaukseen ja klikkasin Kohan koko signum -kentän liitännäistä. Signumi muodostui oikein ja suht nopeasti.

Mitä kautta lähdit tekemään muokkausta?

**Comment by AnneliO** [comment]
Jos vein nidehaun kautta monen eri tietueen niteitä erämuokkaukseen ja yritin generoida signumin, niin silloin kenttä lukittui. Mutta ei se tuossa tapauksessa voikaan osata muodostaa signumia, koska sivulla ei ole silloin tiedoissa tietueiden biblionumbereita, joista poimia tarvittavat luokka- ja pääsanatiedot. Eikä ne olisi kaikille edes samat.

**Comment by pirliis** [comment]
Vein niteet nidehaun kautta erämuokkaukseen. Kaikki niteet olivat samasta tietueesta.

**Comment by AnneliO** [comment]
Biblionumber välittyy niteiden erämuokkaukseen vain silloin, kun niteet viedään erämuokkaukseen tietueen perustiedot-näytöltä. Olemme kumpikin Emmin kanssa testanneet sen eri yhteyksissä, että se toimii noin.

Eli nidehaun kautta vietäessä signumin generointi ei voi toimia, koska tosiaan mukaan ei tule tietueen biblionumberia.

**Comment by pirliis** [comment]
Kiitos tiedosta! Kävin myös Oulun hankinnassa kysymässä, mitä kautta olivat vieneet niteet erämuokkaukseen. Siellä niteet oli viety perustiedot-näytöltä ja ongelmana todellisuudessa siellä olikin tämän hetkinen erämuokkauksen hitaus, mutta sieltä raportoitiin, että signumin muodostaminen erämuokkauksessa ei toimi. Eli tämä ongelma on ratkennut. Suljen tiketin.
