### ISSUE TITLE
Pseudonymize statistic ajo aiheuttaa viivettä taustatöihin

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-24.05#185]
### Mikä vikana?

OUTIssa ja Vaskissa ilmeni viivettä taustatöissä 19.11. ja eräajot valmistuivat todella hitaasti.

Aamulla 20.11. tehtiin päivitys, jossa tipautettiin yksi taustatöihin liittyvä branchi. Päivitys auttoi, mutta Vaskissa ja OUTIssa Pseudonymize statistic ajo ruuhkauttaa edelleen taustatöitä.

**Comment by emta001** [comment]
Kaikilla muilla kimpoilla paitsi Siilillä nostettiin taustatyöajojen max-processes-asetuksen määrää. Katsotaan auttoiko tämä.

**Comment by emta001** [comment]
Muutos näyttäisi auttaneen, jonot lähtivät purkautumaan OUTIssa ja Vaskissakin työt näyttäisivät valmistuvan suht ripeästi.

Tässä on kuitenkin riskinä se, että rinnakkaiset työt voivat tehdä muutoksia samoille niteille ja tästä voi seurata jonkinlaista ristiriitaa.

**Comment by ajrajala** [comment]
Muutos tosiaan on tasannut tilanteen hyvin ja todettiin että tuo Emmin mainitsema riski on kuitenkin suhteellisen pieni. Vaskin puolesta tiketin saa siis sulkea.

**Comment by AnneliO** [comment]
@piiaseme jos outissa tilanne on myös rauhoittunut, niin suljetko tämän tiketin? :)

**Comment by piiaseme** [comment]
OUTIssakin tilanne näyttää rauhoittuneen, joten suljen tiketin.
