### ISSUE TITLE
Lainauksen Määrittele eräpäivä -toiminnon ominaisuus Muista istunnolle 

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-24.05#186]
### Mikä vikana?

Lainauksen Määrittele eräpäivä -toiminto vaikuttaa muuttuneen uudessa versiossa. 
Toimintoon valittu eräpäivä katoaa näkyvistä ensimmäisen lainatun niteen jälkeen. Valittuna eräpäivä 13.12.2024 (lainauspäivä 20.11.2024). Muista istunnolle -täppä pysyy edelleen valittuna.
![kuva](https://github.com/user-attachments/assets/1d67f079-3bcd-4ec0-9780-dff55b260599)

- kun avaa toiminnon kalenterin, aukeaa kalenteri joulukuulle, Kalenterissa ei ole korostettuna valittua eräpäivää
- kalenteriin valittu eräpäivä muodostuu myös asiakkaan seuraavien lainojen eräpäiväksi
- Muista valinta -täppä on päällä seuraavalle/uudelle lainaajalle ja lainan/lainojen eräpäiväksi tulee toimintoon valittu eräpäivä. Valittu eräpäivä ei edelleenkään näy toiminnossa.

**Comment by AnneliO** [comment]
Tämä kuulostais samalta ongelmalta: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37345

**Comment by lmstrand** [comment]
Toin yhteisötiketin korjauksen testattavaksi testeille.

**Comment by Kati-Helle** [comment]
Helle-testissä valittu päivämäärä on nyt lainauksessa näkyvillä, kun valittuna on Muista istunnolle
- ennen lainausta
- lainauksen jälkeen
- lainaavan asiakkaan vaihtuessa
- uudessa selainikkunassa Lainaus-toiminnossa

![kuva](https://github.com/user-attachments/assets/0d066029-97a5-49a7-b573-bd084244c66b)

Mutta: 
- en onnistunut poistamaan ominaisuutta käytöstä

**Comment by AnneliO** [comment]
> Mutta:
> 
>     * en onnistunut poistamaan ominaisuutta käytöstä

Jos laittaa rastin kohtaan Muista istunnolle, niin se tieto säilyy niin kauan, että kirjaudut ulos Kohasta. Kentän saa väliaikaisesti muutettua toiseksi tai tyhjennettyä, mutta muistiin asetettu tieto palaa aina takaisin.

Kokeiletko vielä niin, että kirjaudut ulos? Tuleeko istunnolle muistettu eräpäivän vielä senkin jälkeen?

**Comment by Kati-Helle** [comment]
Tosiaan, kyse on Muista istunnolle -ominaisuudesta :)

Helle-testissä on valittuna Muista istunnolle -ominaisuus. Kirjaudun Kohasta ulos ja kirjaudun Kohaan uudestaan: Muista istunnolle -ominaisuus ei ole enää päällä/valittuna.

**Comment by piiaseme** [comment]
OUTIssa korjaus toimii.

**Comment by Tuomas-Kyyti** [comment]
Testattu Kyytin testillä toimivaksi.

**Comment by Kati-Helle** [comment]
Korjaus on päivitetty tänä aamuna 3.12.2024 Koha-tuotantoon.
Testasin. Toimii oikein.

Suljen tiketin.
