### ISSUE TITLE
Varausta tehdessä kohdistin menee väärään kenttään

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha-24.05#187]
### Mikä vikana?

Varausta tehdessä kohdistin menee yläpalkin lainauskenttään eikä siihen, josta varaava asiakas haetaan korttinumerolla tai nimellä. Jos sitä ei huomaa, kortin lukee väärään kenttään ja Koha hyppää lainausnäkymään. 
![image](https://github.com/user-attachments/assets/2d236000-3375-41ff-9581-55b05b5e7e27)

**Comment by AnneliO** [comment]
Tästä löytyi yhteisöstä bugi ja korjaus: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37373

**Comment by ReettaSiili** [comment]
Sama vika Siilinjärvellä

**Comment by johannaraisa** [comment]
Tämä on tuotu testeille.

**Comment by pknuuti** [comment]
Toimii Vaaran testillä, kursori menee oikeaan paikkaan eli kenttään, johon luetaan tai kirjoitetaan asiakkaan kortti/nimi.

**Comment by ElinaUotila** [comment]
Toimii myös Kirkesin testillä.

**Comment by ElinaUotila** [comment]
Toimii tuotannossakin.
