### ISSUE TITLE
Hyllytarkenne - ksdev/ks-0040-bug-34142-items_sublocation

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#19]
items-tauluun on lisätty sub_location-sarake, johon tallennetaan Hyllytarkenne. Se näkyy tietueen perustiedot-näytöllä nidetaulussa Kotikirjasto-sarakkeessa hyllypaikan jälkeen sulkeissa ja palautuksessa omana sarakkeenaan.

**Comment by emta001** [comment]
Tätä voi testata nexteillä. Testauspläni:

- Varmista, että hyllytarkenne näkyy tietueen perustiedot-näytöllä nidetaulussa Kotikirjasto-sarakkeessa hyllypaikan jälkeen sulkeissa

![image](https://github.com/KohaSuomi/Koha-24.05/assets/37581745/8ae3ff05-94fb-4374-8ddf-d75a924d7ab3)

- Varmista, että hyllytarkenne näkyy palautuksessa omana sarakkeenaan:

![image](https://github.com/KohaSuomi/Koha-24.05/assets/37581745/aec7a1c4-37a0-484f-bfe3-3ff627a4b498)

**Comment by ReettaSiili** [comment]
Siilin nextillä:
Näkyy perustiedoissa nidenäkymässä Kotikirjasto-sarakkeessa. Pieni kauneusvirhe vain: _Aikuisten osasto(Joulukirjat)_ välilyönti puuttuu.
Näkyy palautusnäytöllä kuten esimerkissä yläpuolella, Hyllypaikka-sarakkeessa, hyllypaikan perässä.

**Comment by Kati-Helle** [comment]
Helle-nextissä Hyllytarkenne Pikalaina näkyvillä palautusnäytöllä Hyllypaikka-sarakkeessa
![kuva](https://github.com/KohaSuomi/Koha-24.05/assets/99952449/6b6af326-d91e-4ba6-b6b7-de32f7267224)

sekä tietueen Perustiedot-välilehdellä Kotikirjasto-sarakkeessa
![kuva](https://github.com/KohaSuomi/Koha-24.05/assets/99952449/4c6481c5-4590-4800-b34b-051397ea7a19)

**Comment by MikkoLiimatainen** [comment]
Vaski-nextillä hyllytarkenne näkyy tietueen perustiedoissa, sekä palautuksessa. Välilyönti olisi hyvä saada tietueen perustiedot näytön listaan.

**Comment by Kati-Helle** [comment]
Helle-Nextissä on välilyönti hyllypaikka-arvon ja hyllytarkenne-arvon välissä
![kuva](https://github.com/KohaSuomi/Koha-24.05/assets/99952449/bafcefd3-15e5-4d06-8f85-2e21c4188873)

**Comment by emta001** [comment]
Välilyönti lisätty, näyttääkö nyt oikeamalle?

**Comment by pirliis** [comment]
OUTIn nextillä hyllytarkenne näkyy tietueen perustiedot- ja palautus -sivuilla oikein välilyönteineen.

**Comment by MikkoLiimatainen** [comment]
Vaskin nextillä näkyy myös oikein välilyönteineen.

**Comment by emta001** [comment]
Testattu ja toimii. Suljen tiketin.
