### ISSUE TITLE
Viivakoodin generointi niteelle -  ksdev/ks-0005-bug-30328-gen-barcode

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#2]
### Siirrettävä ominaisuus

Koha-Suomessa toteutetut viivakoodien generoinnin muutokset.

**Comment by emta001** [comment]
Viety nexteille testattavaksi.

**Comment by emta001** [comment]
Nappasi tähän branchiin mukaan myös tiketin [772](https://github.com/KohaSuomi/Koha/issues/772) muutoksen, eli viivakoodiin generoituu myös sekunnit ja niiden perään juokseva numerointi.

**Comment by Kati-Helle** [comment]
Helle-nextissä niteen viivakoodi generoituu.
Nidetunnukset muodostettu 08.07.2024 n. klo 10.42

434N2407081042201

434N2407081042481

**Comment by ajrajala** [comment]
Myös Vaski-nextillä viivakoodiin generoituu sekunnit + juokseva numero.

**Comment by pknuuti** [comment]
Vaaran nextillä tänään generoituu tällainen viivakoodi Vaara2407121237251.

**Comment by emta001** [comment]
Testattu ja todettu toimivaksi. Suljen tiketin.
