### ISSUE TITLE
Tietuenäytön muutokset - ksdev/ks-0041-k22-13-ks-xslt

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#20]
Tietuenäytön xslt-muutokset.

**Comment by lmstrand** [comment]
Viety nexteille testattavaksi.

**Comment by lmstrand** [comment]
https://github.com/KohaSuomi/Koha-23x/issues/29

**Comment by Kati-Helle** [comment]
Muutama Hellen tuotannon ja nextin tietueen Perustiedot-näyttövertailuja

Kirja - tiedot vastaavat toisiaan
![kuva](https://github.com/user-attachments/assets/f249fd86-0344-44ea-a384-bab3180bc991)

CD - suomenkielisessä (ja ruotsinkielisessä) nextissä englanninkielisiä otsikkoja
Associated place  - Liittyvä paikka
Creation time - Luontiaika
Performance medium - Esityskokoonpano

![kuva](https://github.com/user-attachments/assets/1ee2fc20-df32-465d-9f36-ceb0a7f318d9)

**Comment by AnneliO** [comment]
[Koha-Suomen käännökset](https://github.com/KohaSuomi/Koha-24.05/issues/20) tehdään, kunhan tämän tiketin muutokset on testattu toimiviksi.

**Comment by MikkoLiimatainen** [comment]
Vaskissa näyttää olevan ok.

**Comment by ElinaUotila** [comment]
Kirkesissä Nextin ja tuotannon tiedot vastaavat toisiaan muutamia Hellen jo mainitsemia englanninkielisiä otsikkoja lukuunottamatta.

**Comment by piiaseme** [comment]
OUTIssa näyttäisi olevan ok.

**Comment by LastuLauriH** [comment]
Lastussa näyttäisi olevan ok.

**Comment by AnneliO** [comment]
Tämä näyttäisi olevan ok, joten suljen tiketin.
