### ISSUE TITLE
SIP muutos - ksdev/ks-0043-K23-15-SIP2

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#21]
SIP-muutos.

**Comment by lmstrand** [comment]
Tuotu puuttuvat commitit kyseiseen branchiin ja fetchattu vaski-nextille.

**Comment by lmstrand** [comment]
Huom. sisältää yhteisöcommitin Bug 18317: Allow check out of already checked out items through SIP joka ei ollut päätynyt vielä ks24-branchiin, pudotetaan seuraavassa versionvaihdossa.

**Comment by lmstrand** [comment]
sis. commitit:

[Bug 37016: Invalid due date in SIP renew response](https://github.com/KohaSuomi/Koha-24.05/commit/fd63776e926c6308a94693d0fe034009723c84fa)
[Bug 18317: Allow check out of already checked out items through SIP](https://github.com/KohaSuomi/Koha-24.05/commit/01e84f20969fa7cfec24651554eac19f7159ad5b)
[G900 Add account locked info to 64 resp and handle message geneneration as expired](https://github.com/KohaSuomi/Koha-24.05/commit/0c918be975dd46e1221167d4313d3080cd622a27)
[KD-2608 Handle notforloan status changes on checkin with SIP](https://github.com/KohaSuomi/Koha-24.05/commit/d3c85103b89119bede3c422678b07c9c0c3d4e8b)
[KD-913 Add SIP2 response message preference for alert](https://github.com/KohaSuomi/Koha-24.05/commit/99fa3af02c8a081ce828d54af4ffd15b1dc1146d)
[KD-4572 Add ss (self service) block support for sip2 63-64 reply](https://github.com/KohaSuomi/Koha-24.05/commit/e40c955b0303af99b3abf49d7027550338dab04c)

**Comment by ajrajala** [comment]
Matrixissa oli kyselty testaajaa, Vaskissa onnistuisi ainakin.

**Comment by ajrajala** [comment]
[Bug 37016: Invalid due date in SIP renew response](https://github.com/KohaSuomi/Koha-24.05/commit/fd63776e926c6308a94693d0fe034009723c84fa) -> Tämä ei näytä toimivan oikein, automaatin näytöllä sekä automaattikuitissa näkyi uusimisen jälkeen edelleen vanha eräpäivä vaikka Koha olikin uusinut niteen.

[Bug 18317: Allow check out of already checked out items through SIP](https://github.com/KohaSuomi/Koha-24.05/commit/01e84f20969fa7cfec24651554eac19f7159ad5b) -> Tämä ok, laina palautui edelliseltä asiakkaalta ja meni lainaan uudelle asiakkaalle.

[G900 Add account locked info to 64 resp and handle message geneneration as expired](https://github.com/KohaSuomi/Koha-24.05/commit/0c918be975dd46e1221167d4313d3080cd622a27) -> Yritin tunnistautua automaatilla kortilla, jolla "Tili on lukittu" -merkintä. Automaatin lokeissa 64-kentässä pelkästään tieto "Invalid password". Tuotannossa vastaavassa tilanteessa lokissa tieto "ACCOUNT LOCKED -- Invalid password" eli ei nyt toimi nextillä samalla tavalla.

[KD-2608 Handle notforloan status changes on checkin with SIP](https://github.com/KohaSuomi/Koha-24.05/commit/d3c85103b89119bede3c422678b07c9c0c3d4e8b) -> Niteellä oleva notforloan-tila poistuu/säilyy automaatilla palauttaessa sen mukaisesti mitä UpdateNotForLoanStatusOnCheckin-järjestelmäasetukseen on Kohassa määritelty eli tämä ok. Jostain syystä tosin ensimmäistä kertaa palauttaessa nidettä, jolla oli palautuksessa säilyvä notforloan-tila, sain virheilmoituksen eikä nide palautunut lainasta. Mutta en onnistunut toistamaan samaa virhettä enää uudelleen eikä siitä näyttänyt jääneen automaatin lokiin merkintää, joten menee ehkä jonkin hetkellisen häiriön piikkiin. 🤔

[KD-913 Add SIP2 response message preference for alert](https://github.com/KohaSuomi/Koha-24.05/commit/99fa3af02c8a081ce828d54af4ffd15b1dc1146d)
[KD-4572 Add ss (self service) block support for sip2 63-64 reply](https://github.com/KohaSuomi/Koha-24.05/commit/e40c955b0303af99b3abf49d7027550338dab04c)
-> Näitä kahta en tiennyt miten testata. Ss blockit ei kai Vaskissa käytössä joten jäänyt minulle vieraaksi, raportilla ei ainakaan borrower_ss_blocks-taulusta mitään löydy.

**Comment by lmstrand** [comment]
Kiitos testailusta. Käyn tutkimassa nuo ongelmatapaukset, että mikä niissä voi olla. Tuo omatoimen esto pitäisi lisätä meidän devaajien käyttäjätunnukselle tuonne borrower_ss_blocks-tauluun. Tuo alert liittyi jotenkin niihin laskutettujen? niteiden lajitteluun.

**Comment by lmstrand** [comment]
Voitteko testata uusiksi noita ongelmallisia ominaisuuksia. Lokeille ei ole tullut mitään, kun lokitustaso on ollut liian korkealla. Tarkistin, että tarvittavat commitit ovat kyydissä ja käynnistin sip-palvelimen uusiksi lokitusten kera.

**Comment by ajrajala** [comment]
[Bug 37016: Invalid due date in SIP renew response](https://github.com/KohaSuomi/Koha-24.05/commit/fd63776e926c6308a94693d0fe034009723c84fa) -> Tämä toimii nyt oikein, näytölle ja kuitille päivittyi heti uusi eräpäivä.

[G900 Add account locked info to 64 resp and handle message geneneration as expired](https://github.com/KohaSuomi/Koha-24.05/commit/0c918be975dd46e1221167d4313d3080cd622a27) -> Automaatin lokiin tulee edelleen pelkästään tieto Invalid password eli tuotannossa lokilla näkyvä ACCOUNT LOCKED -tieto puuttuu:

`30.08.2024 09:24:03	64              00020240830    092402000000000000000000000000AOTUPK|AA***121|AE***|BLY|CQN|BV0|CC14.99|BD***|BE***|PB***|PC***|PIY|AFGreetings from Koha.  -- Invalid password|PA1|AY7AZB3C9 `

Kaivelin Matrixista [keskustelua](https://matrix.to/#/!YyLfbjvTmipmsZDCFG:matrix.org/$iWCUk50uAW0du5k-mgDnrIO_M-uB1MLOaVKcD5xzJxU?via=matrix.org), joka taisi liittyä tuohon alert-statukseen, keskustelussa oli puhetta siitä että tieto lisättäisiin CL-kenttään. Sellaista ei laskutetulla niteellä ainakaan MV automaatin lokissa näy, laitan nyt tähän vielä kuitenkin miltä lokissa näyttää. Vaskin kaikilla automaateilla laskutettujen niteiden erottelu tapahtuu CV53 perusteella, muulle ei meillä ole ollut tarvetta.

`30.08.2024 09:31:51	101YNN20240830    093150AOTUPK|ABLVASK24010900403|AQTAPK|AJYökoulu ja kaamea kosto /|AA***484|CK001|CSLAP 84.2 NOR|CTTAPK|CRHEL|CV53|AY1AZD708`

**Comment by lmstrand** [comment]
Tein muutoksen, jossa tilin lukossa ollessa lisätään tieto sanomaan aina ja sanoma muodostuu samoin, kuin tili olisi vanhentunut. Voitteko kokeilla mitä nyt tapahtuu, jos tili on myös vanhentunut? En ole ihan varma tuosta logiikasta :D

**Comment by ajrajala** [comment]
> Tein muutoksen, jossa tilin lukossa ollessa lisätään tieto sanomaan aina ja sanoma muodostuu samoin, kuin tili olisi vanhentunut. Voitteko kokeilla mitä nyt tapahtuu, jos tili on myös vanhentunut? En ole ihan varma tuosta logiikasta :D

Muutin lukitun kortin vanhentuneeksi, nyt tulee sanomassa näin:
`AFGreetings from Koha.  Your account has expired as of 29.08.2024 ACCOUNT LOCKED -- Invalid password`

**Comment by lmstrand** [comment]
Ok nuo molemmat tapaukset ovat sitten kaiketi kunnossa erikseen ja yhdessä. Pyydän vielä OUTIlaisia testaamaan Lyngsoen vehkeillä ainakin nuo vanhenemisen/lukituksen erikseen ja yhdessä varmuuden vuoksi.

**Comment by AnneliO** [comment]
Onkohan tähän tulossa vielä testauksia vai voisiko tiketin sulkea?

**Comment by piiaseme** [comment]
Siirrän OUTIn automaatti-gurujen testaustulokset Matrixista tänne:

Testailutuloksia:

Bug 37016, Invalid due date in SIP renew response: uusintapäivämäärä näkyy näytöllä ja kuitilla oikein

Bug 18317, Allow check out of already checked out items through SIP: Ei voinut lainata jo lainassa olevaa. AFItem already checked out to another patron. Please return item for check-in

G900, Add account locked info to 64 resp and handle message geneneration as expired: Ei näy Locked-sanaa jos tili lukittuna, pelkästään Invalid password. Jos kortti vanhentunut, näkyy Your account has expired. Jos lukittu ja vanhentunut yhtäaikaa, näkyy Account expired viesti ja invalid password, mutta ei lukittu sanaa vieläkään.

KD-2608 Handle notforloan status changes on checkin with SIP : Saapunut-tilassa oleva kirja muuttui Saatavilla-tilaan palauttaessa automaatilla niin kuin pitikin.

**Comment by lmstrand** [comment]
Ilmeisesti tuo G900-tiketti pitää avata uusiksi. Suljen tämän.
