### ISSUE TITLE
Verkkokirjastossa tehdyt uusinnat kirjautuu Finna-api-käyttäjän kotikirjaston mukaan - ksdev/ks-0047-K23-17-api-OpacRenewalBranch

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#22]
Verkkokirjastossa tehdyt uusinnat kirjautuu Finna-api-käyttäjän kotikirjaston mukaan.

Lari teki verkkokirjastouusintoihin korjauksen, että se seuraa OpacRenewalBranch-järjestelmäasetusta statistics-taulun osalta. Korjaus viedään tuotantoon maanantaina. Kaikkien kannattaa käydä tarkistamassa, että tuossa asetuksessa on nyt se valinta, jonka mukaan haluatte verkkokirjastouusintojen tilastoituvan.

Sen sijaan verkkokirjasto seuraa eräpäiväkalenteria valitessaan circcontrol- ja HomeorHoldingbranch-järjestelmäasetuksia. Ne kannattaa säätää siten, kuin haluatte uusintojen seuraavan. Esim. OUTIssa halutaan uusinnan seuraavan lainanneen kirjaston eräpäiväkalenteria, jolloin valitsemme asetuksiin seuraavat:

circcontrol: the library where the item is from
homeorholdingbranch: holdingbranch

HomeOrHoldingbranch-asetuksessa määritetään, käytetäänkö niteen koti- vai sijaintikirjastoa. Kun nide lainataan eri kirjastossa kuin sen kotikirjastossa, on sen sijaintikirjasto lainaava kirjasto, jolloin asetukseen valitaan sijaintikirjasto, mikäli halutaan uusinnan seuraavan lainannutta kirjastoa.

**Comment by AnneliO** [comment]
Kohaan on tullut uusi järjestelmäasetus RESTAPIRenewalBranch, toimiiko se suoraan tämän muutoksen korvaajana?

**Comment by lmstrand** [comment]
Finna-pluginin koodissa ei ole mainintaa tuosta sysprefistä. Testataan kuitenkin nexteillä tiputtamalla branch pois buildista ja kokeillaan, vaikuttaako asetus.

**Comment by AnneliO** [comment]
Testasin outi-nextillä ja sitä vastaavalla Finna-nextillä tätä niin, että valitsin ensin RESTAPIRenewalBranch vaihtoehdon _niteen lainannut kirjasto_ ja statistics-tauluun kirjautui branch-sarakkeeseen OUUL, kuten pitääkin:

2024-08-14 11:59:20 	OUUL 	0 	renew 		28VRKLN 	LN 		HENKILO 	api

Sitten vaihdoin siihen _API-käyttäjän kotikirjasto_, joka oli OUPK:

2024-08-14 12:01:12 	OUPK 	0 	renew 		28VRKLN 	LN 		HENKILO 	api

Sitten vielä _niteen kotikirjasto_, joka oli KEPK:

2024-08-14 12:02:00 	KEPK 	0 	renew 		28VRKLN 	LN 		HENKILO 	api

Eli nähdäkseni tämä toimii, mutta ei haittaa, vaikka joku muukin vielä testaisi tätä tekemällä uusintoja Finnan kautta eri vaihtoehtoja käyttäen järjestelmäasetuksessa.

**Comment by AnneliO** [comment]
Käytin tällaista kyselyä:

```
select * from statistics where borrowernumber=xxxx
```

branch-sarakkeen tieto muuttui sen mukaan, mitä valitsin järjestelmäasetukseen.

**Comment by AnneliO** [comment]
[Linkit Finna-nexteihin](https://github.com/KohaSuomi/Koha-24.05/wiki/Finna%E2%80%90nextit)

**Comment by lmstrand** [comment]
Viimeisin commit Revert Log successful credentials validation as login event tiputettu tuotannoista testauksen ajaksi.

**Comment by Rvallim0** [comment]
Vaskissa testattu samanlaisilla tapauksilla, asetukset toimivat oletusten mukaisesti.
