### ISSUE TITLE
GetSuomiFiMessages - ksdev/ks-0054-K23-38-get-suomifi-messages

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#23]
KSMessaging, jolla hallinnoidaan viestien lähetystä mm. suomi.fi viesteihin ja ekirjepalveluihin.

**Comment by johannaraisa** [comment]
Tämä on lisätty nexteille ja ei ollut ongelmia, joten uskon toimivan edelleen.
