### ISSUE TITLE
Raporttien vienti Finnan ymmärtämään JSON-muotoon - ksdev/ks-0066-K23-66-finna-json

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#24]
### Siirrettävä ominaisuus

Plugin hook ja finnaprefix-järjestelmäasetus.

**Comment by emta001** [comment]
Viety nexteille, testaile tälleen:
1. Aja jokin raportti.
2. Lataa raportin tulokset, valitsen alasvetovalikosta vaihtoehto "Finna JSON".
=> Raportin tulisi latautua JSON-muodossa .

**Comment by pknuuti** [comment]
Tein Vaaran nextillä raportit lainatuimmista ja varatuimmista ja latasin ne json-muotoon Finnaa varten. Kun vien raportit Finnaan, niiden sisältö ei kuitenkaan näy oikein. Toisessa raportissa näkyy 1, varatuimmissa 0 nimekettä, vaikka oikeasti niitä on enemmän. Eli ei toimi kuten pitää, vaikka raportti sinänsä latautuu JSON-muotoon.

**Comment by AnneliO** [comment]
Onko FinnaBaseUrl-järjestelmäasetukssa (Paikalliset-osiossa) oikea osoite ja tunnisteet Finnaan? Tai jos yrität viedä listan tuotannon Finnaan, niin näkyvätkö tiedot oikein? Nextillä on todennäköisesti määritetty tuotannon Finnan osoite.

**Comment by AnneliO** [comment]
Höpötinköhän mie omiani? 😅 Järjestelmäasetus taiskin olla finnaprefix. Löytyy myös Paikalliset tiedot.

**Comment by emta001** [comment]
Juu, asetus on finnaprefix. Olin siinä käsityksessä, että se on vain koha-conf.xml:stä löytyvä asetus, joka taitaa nexteillä olla unknown tjsp. Pitäsköhän jonnekin käydä vaihtamassa se, niin voidaan testata tuota varsinaista viemistäkin eikä vain generointia.

**Comment by pknuuti** [comment]
Tuotannon Finnaan nextillä ajetut raportit voidaan tuoda JSON-muodossa ja ne näyttää oikean määrän nimekkeitä. Yritin vaihtaa nextin Finnan osoitteen asetukseen, mutta siltikään tuonti sinne ei onnistu kuin tyhjänä.
Finnaprefix on vaarakirjastot. Mitenkähän tuo pitäisi muuttaa?

**Comment by AnneliO** [comment]
> Juu, asetus on finnaprefix. Olin siinä käsityksessä, että se on vain koha-conf.xml:stä löytyvä asetus, joka taitaa nexteillä olla unknown tjsp. Pitäsköhän jonnekin käydä vaihtamassa se, niin voidaan testata tuota varsinaista viemistäkin eikä vain generointia.

Kyllä tuolla asetuksella on vaikutusta tiedoston muodostumiseen. Vaihdoin outi-nextillä finnaprefix-asetukseen _outi_next._ ja latasin raportin uudelleen tiedostoksi (testasin siis jo ennen muutosta ladata saman raportin). Tunnus oli muuttunut.

**Comment by emta001** [comment]
> Tuotannon Finnaan nextillä ajetut raportit voidaan tuoda JSON-muodossa ja ne näyttää oikean määrän nimekkeitä. Yritin vaihtaa nextin Finnan osoitteen asetukseen, mutta siltikään tuonti sinne ei onnistu kuin tyhjänä. Finnaprefix on vaarakirjastot. Mitenkähän tuo pitäisi muuttaa?

Kävin vaihtamassa vaara-nextille koha-conf.xml:ään finnprefix-asetuksen arvoksi vaarakirjastot. Toimisko nytten?

**Comment by AnneliO** [comment]
> Tuotannon Finnaan nextillä ajetut raportit voidaan tuoda JSON-muodossa ja ne näyttää oikean määrän nimekkeitä. Yritin vaihtaa nextin Finnan osoitteen asetukseen, mutta siltikään tuonti sinne ei onnistu kuin tyhjänä. Finnaprefix on vaarakirjastot. Mitenkähän tuo pitäisi muuttaa?

Vaara-nextillä tunniste näyttäisi olevan vaarakirjastot_next

https://vaara.finna-pre.fi/next/Record/vaarakirjastot_next.11726879

**Comment by pknuuti** [comment]
No nyt pelittää eli nextille tulee JSON-muodossa tallennettu raportti listaksi. Emmin konffin jälkeen ajoin raportit uudelleen ja toin Finna-nextille.

**Comment by emta001** [comment]
> > Juu, asetus on finnaprefix. Olin siinä käsityksessä, että se on vain koha-conf.xml:stä löytyvä asetus, joka taitaa nexteillä olla unknown tjsp. Pitäsköhän jonnekin käydä vaihtamassa se, niin voidaan testata tuota varsinaista viemistäkin eikä vain generointia.
> 
> Kyllä tuolla asetuksella on vaikutusta tiedoston muodostumiseen. Vaihdoin outi-nextillä finnaprefix-asetukseen _outi_next._ ja latasin raportin uudelleen tiedostoksi (testasin siis jo ennen muutosta ladata saman raportin). Tunnus oli muuttunut.

Jaahas, kumpihan noista on sitten enemmän oikein :thinking: Koodissa ei ole ainakaan semmosta paikkaa jossa luotaisiin tuommoinen syspref.

**Comment by emta001** [comment]
Tutkittiin tätä vielä lisää. Meillä on ilmeisesti tehty joskus päätös (tai ainakin keskusteltu), että finnaprefix-asetus siirtyy koha-conf.xml:ään. Mutta vanhaa järjestelmäasetusta, joka on Paikallisissa asetuksissa, ei ole koskaan poistettu eikä koodia ole muutettu niin, että asetus haettaisiin konfista ei ole tehty. Näköjään vaara-nextille onkin laitettu Kohan asetukseen tuo "vaarakirjastot-next." arvo, siksi raporttien vieminen rupesi toimimaan. 

Tästä pitänee käydä vielä hieman keskustelua kumpi asetus säilytetään ja kummasta luovutaan. Molempia ei ole järkeä ylläpitää.

**Comment by pknuuti** [comment]
Minähän sen asetuksen muutin eilen Annelin antaman tiedon perusteella ja sen jälkeen se toimi. Mutta olisi tietysti kiva, jos se toimisi ilman moneen paikkaan tehtävää muutosta.

**Comment by LeenaKinnunen** [comment]
Kokeilin tätä Lapin nextillä, molemmilla finnaprefixeillä (lapinkirjasto. ja lapinkirjasto_next.), ei toiminut. Odotellaan, mitä päätetään.

**Comment by AnneliO** [comment]
> Kokeilin tätä Lapin nextillä, molemmilla finnaprefixeillä (lapinkirjasto. ja lapinkirjasto_next.), ei toiminut. Odotellaan, mitä päätetään.

Kokeilin laittaa finnaprefix-järjestelmäasetukseen lapinkirjasto_next. ja vein kyselyn 

```
SELECT
  b.biblionumber AS 'biblionumber',
  count(h.reservedate) AS 'Varauksia' 
FROM biblio b 
LEFT JOIN biblio_metadata m USING (biblionumber) 
LEFT JOIN reserves h ON (b.biblionumber=h.biblionumber) 
GROUP BY b.biblionumber 
ORDER BY Varauksia DESC
LIMIT 25
```

tulokset Finna JSON -muotoon. Sitten vein tiedoston Lapin Finna-nextille Omissa tiedoissa _Tuo suosikit ja haut_ -toiminnolla Finnaan. Suosikkilista muodostui ihan oikein.

Miksiköhän Leena sulla ei toiminut. 🤔

**Comment by LeenaKinnunen** [comment]
Nyt toimi, lista siirtyi. Finnaprefixissä oli lapinkirjasto_next. , jolla testasin jo aiemmin.

**Comment by emta001** [comment]
Tästä oli tehty 12.8.2024 palaverissa päätös, että koha-confissa olevasta asetuksesta luovutaan ja se siivotaan versionvaihdon yhteydessä pois käytöstä kaikilta kimpoilta. Käytetään tämän kanssa jatkossakin siis paikallisista asetuksista löytyvää finnaprefix-asetusta. 

Testauksien perusteella tämä vaikuttaisi toimivan, suljen tiketin.
