### ISSUE TITLE
Aineistotyyppi näkyviin asiakkaan lainoihin ja palautustoimintoon - ksdev/ks-0074-K23-40-checkouts-and-returns-itemtype

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#25]
### Siirrettävä ominaisuus

Aineistotyyppi näkyviin asiakkaan lainoihin ja palautustoimintoon.

**Comment by emta001** [comment]
Testattavana nexteillä.

**Comment by Kati-Helle** [comment]
Kävinpä kurkkaamassa uutta Helle-Nextiä ja testaamassa tämän tiketin.

Asiakkaan lainoissa näkyy aineistotyypin kuvaus Aineistotyyppi-sarakkeessa
![kuva](https://github.com/KohaSuomi/Koha-24.05/assets/99952449/f43bb4a1-1246-4861-b6c5-9714e1e7efe6)

Palautuksessakin Aineistotyyppi-sarakkeessa aineistotyypin kuvaus näkyvillä
![kuva](https://github.com/KohaSuomi/Koha-24.05/assets/99952449/5ca26958-2ddf-4f8d-b73f-bd93870ad6a4)

**Comment by MikkoLiimatainen** [comment]
Aineistotyypit näkyvät palautuksessa, sekä asiakkaan lainoissa Vaski-nextilläkin

**Comment by LastuLauriH** [comment]
Samoin näkyvät molemmissa Lastu-Nextilläkin.

**Comment by pknuuti** [comment]
Vaaran nextillä myös oikein.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
