### ISSUE TITLE
Tietueen Varaukset-sivulla asiakas-sarakkeen tietoja ei ladata jos käyttäjältä puuttuu edit_borrowers-oikeus - ksdev/ks-0080-bug-32502-api-holds-permission

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#26]
### Siirrettävä ominaisuus

Jos käyttäjällä ei ole edit_borrowers-oikeutta, mitään asiakas-sarakkeessa olevia tietoja ei ladata. APIa muutettu niin, että tiedot ladataan kun käyttäjällä on view_borrower_infos_from_any_libraries-oikeus.

**Comment by ghost** [comment]
Testattava riittääkö yhteisössä lisätty list_borrowers -oikeus.

**Comment by AnneliO** [comment]
Testasin siili-nextillä sellaisella käyttäjätunnuksella, jolla oli vain list_borrowers-oikeus borrowers-osiosta. Menin tietueen Varaukset-välilehdelle ja varausten kohdalla näkyi asiakkaiden kirjastokortin numerot ja linkistä pääsi siirtymään asiakkaan tietoihin.

**Comment by LeenaKinnunen** [comment]
Toimii Lapin nextillä samoin kuin Annelin testillä Siilissä.

**Comment by iinaniemi** [comment]
Samoin Vaski-nextillä

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii, kun tunnuksella on nämä oikeudet borrowers-osiosta: list_borrowers JA view_borrower_infos_from_any_libraries

Kun oikeutena on borrowers-osiosta vain list_borrowers, käy näin eli asiakastiedot ovat haussa eikä haku valmistu (kirjautumistunnus-kirjastona Porvoon pääkirjasto)
![kuva](https://github.com/user-attachments/assets/7a5d9d5b-d203-4392-8df6-56ce27d72eca)

**Comment by AnneliO** [comment]
Jaahas, mikähän on muuttunut, koska nyt tapahtuu siili-nextilläkin noin kuten Kati laittoi.

**Comment by johannaraisa** [comment]
Toimiikohan tämä nyt oikein? Kaiken ocfs-säädön ja nextien uudelleen buildin jäljiltä nexteille livahti kommitti mikä sinne ei kuulunut.

**Comment by AnneliO** [comment]
Minusta siili-nextillä toimii taas oikein. :)

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii nyt, kun Kohaan kirjautuneen tunnuksella on borrowers-osiosta vain list_borrowers-oikeus. 
Asiakas-sarakkeen arvot latautuvat ja arvojen linkit toimivat.

**Comment by ajrajala** [comment]
Onkohan vaski-nextillä jotain eri tavalla? Testasin tuolla Katin kuvaamalla tavalla, minulla kirjastokorttitunnukset ei lataudu näkyville eikä sivun uudelleenlatauskaan auta.

**Comment by AnneliO** [comment]
Testasin nyt kans vaski-nextillä ja mulla kävi niin, että jos varauksia oli paljon, niin osalle varauksista näkyi kirjastokortin numero ja osalle se jäi hakemaan tietoa. Esim. tietueessa https://vaski-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=4341268

Konsoliin tulee virheilmoituksia "not found":

![kuva](https://github.com/user-attachments/assets/772c150c-99b3-48c2-8a1f-26a0c92cf3b1)

**Comment by AnneliO** [comment]
Jos koitan mennä esim. tuon ekana [listatun asiakkaan tietoihin](https://vaski-next.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=271790), niin tulee ilmotus, ettei ole oikeutta nähdä valitun asiakkaan tietoja.

**Comment by AnneliO** [comment]
Jos vaihdan käyttämäni tunnuksen kotikirjastoksi saman kuin asiakkaan kotikirjasto on, niin pääse katsomaan asiakkaan tietoja ja varauksen tiedoissa näkyy kirjastokortin numero.

**Comment by AnneliO** [comment]
Lisäsin käyttäjätunnukselle view_borrower_infos_from_any_libraries-käyttäjäoikeuden ja kaikki varaukset latautuu. Eli jostain syystä se tosiaan taas vaatii tuon oikeuden, vaikka ei pitäisi.

**Comment by johannaraisa** [comment]
Ei tuota versiohaara ole nexteillä. Yritän katsoa tuleeko se jostain välimuistista.

**Comment by johannaraisa** [comment]
Ei ole tuosta kiinni, joku muu kohta nyt vaikuttaa.

**Comment by johannaraisa** [comment]
Jos ei olisi oikeuttaa niin antaisi Forbiddenin, miksi antaa Not Found?

**Comment by johannaraisa** [comment]
Mikä on tuon testikäyttäjän borrowernumber, en saa tätä toistettu omalla koneella?

**Comment by AnneliO** [comment]
> Mikä on tuon testikäyttäjän borrowernumber, en saa tätä toistettu omalla koneella?

https://vaski-next.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=402846

**Comment by AnneliO** [comment]
> > Mikä on tuon testikäyttäjän borrowernumber, en saa tätä toistettu omalla koneella?
> 
> https://vaski-next.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=402846

Otin tältä käyttäjältä pois view_borrower_infos_from_any_libraries -oikeuden.

**Comment by johannaraisa** [comment]
Taitaa olla johtua tämän korjauksesta: https://github.com/KohaSuomi/Koha-24.05/issues/114

**Comment by johannaraisa** [comment]
Tässä kohtaa tuo oikeusjuttu menee syvemmälle, itse REST-rajapinnan oikeudet ovat kunnossa. Kun asiakkaan tietoja haetaan, niin käyttäjältä tarkastetaan tämä 

```
=head3 libraries_where_can_see_patrons

my $libraries = $patron->libraries_where_can_see_patrons;

Return the list of branchcodes(!) of libraries the patron is allowed to see other patron's infos.
The branchcodes are arbitrarily returned sorted.
We are supposing here that the object is related to the logged in patron (use of C4::Context::only_my_library)

An empty array means no restriction, the patron can see patron's infos from any libraries.

=cut

sub libraries_where_can_see_patrons {
    my ($self) = @_;

    return $self->libraries_where_can_see_things(
        {
            permission    => 'borrowers',
            subpermission => 'view_borrower_infos_from_any_libraries',
            group_feature => 'ft_hide_patron_info',
        }
    );
}
```
Yhteisön varaussivuversiossa asia on hoidettu niin, että asiakkaan tietoihin ei tule linkkiä, vaan tieto asiakkaan kirjastosta.

![image](https://github.com/user-attachments/assets/6a057c4a-ab36-4e2f-9081-6ef746cafc86)

Tuohan vaikuttaa muuallakin, kuten siinä että käyttäjä voi katsella asiakkaan tietoja toisesta kirjastopisteestä. En tiedä onko meillä tarvetta rajoittaa tietojen katselemista muista yksiköistä, joten lisäisin vain kyseisen asetuksen kaikille virkailijoille.

**Comment by ajrajala** [comment]
Vaskissa ei ainakaan tarvetta rajoittaa tietojen katselemista muista yksiköistä, joten meille view_borrower_infos_from_any_libraries-käyttöoikeuden käyttäminen on ok.

**Comment by johannaraisa** [comment]
Lisäsin tuohon ilmoituksen, ettei hyrrät jää pyörimään. 

![image](https://github.com/user-attachments/assets/5033664b-9e18-463a-9538-fc2cadad7502)

**Comment by johannaraisa** [comment]
Yritin kysellä yhteisöstä, että näkeekö muut tässä ristiriidan. Ainakin asia on APIa käyttävälle epäselvä ja käytännössä vaatii jonkun katsomaan koodia, jotta voi tietää miksi jotkut tiedot ei näy. Tuskin siihen mitään vastausta saa, joten näillä mennään.

**Comment by johannaraisa** [comment]
Tähän ei ole tullut vastauksia. Mennään siis sillä, että jos haluaa nähdä kaikki asiakkaat listalla, niin tarvitaan se view_borrower_infos_from_any_libraries-oikeus.

**Comment by johannaraisa** [comment]
Suljen tämän tiketin.
