### ISSUE TITLE
Raporttien kyselyiden siirtäminen tietokantaslavelle - ksdev/ks-0083-K23-44-use-altdbh-for-reports

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#28]
### Siirrettävä ominaisuus

Siirretään Koha raporttien käsittely tietokantaslavelle.

**Comment by johannaraisa** [comment]
Tämä on lisätty nexteille, voisi kokeilla hakea raporttia ja katsoa mitä tapahtuu.

**Comment by lmstrand** [comment]
Raportin ajaminen Vaara-nextillä lokittaa Using alt dbh to 10.0.36.43. ONLY SELECTS ALLOWED, NEVER WRITE TO DB THROUGH THIS HANDLE! at /home/koha/Koha/C4/KohaSuomi/Tweaks.pm line 39 lokeille joten toimii kuten pitää.

**Comment by johannaraisa** [comment]
Näyttäisi toimivan, suljen tiketin.
