### ISSUE TITLE
Taustatöiden työlistalla "Only include jobs started in the last hour" -valinta toimii väärin - ksdev/ks-0095-bug-36217-fix-background-jobs-filters

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#29]
### Siirrettävä ominaisuus

Taustatöiden listalla taas jos ottaa täpän pois kohdasta Only include jobs started in the last hour, katoaa listalta työt lähitunneilta/lähiajalta kokonaan.

**Comment by johannaraisa** [comment]
Nyt on tämä nexteillä, testausta vailla valmista.

**Comment by ajrajala** [comment]
Testasin tätä vaski-nextillä niin, että minulla oli joitakin viimeisen tunnin sisällä aloitettuja taustatöitä. Kun kohdassa "Sisällytä vain taustatyöt, jotka on aloitettu viimeisen tunnin aikana" oli rasti, näin ainoastaan kyseiset taustatyöt ja kun rastin otti pois, latautui näkyville kaikki taustatyöt.

(Huom. taustatyöt on järjestetty niin, että keskeneräiset työt näkyvät ensimmäisenä. Nuo omat viimeisen tunnin aikana aloittamani työt eivät siis näkyneet listan kärjessä rastin pois otettuani, mistä ensin hiukan hämäännyin. Tuoreimmat taustatyöt kuitenkin löytyvät edelleen kun järjestää listan päivämäärän mukaan.)

**Comment by johannaraisa** [comment]
> Testasin tätä vaski-nextillä niin, että minulla oli joitakin viimeisen tunnin sisällä aloitettuja taustatöitä. Kun kohdassa "Sisällytä vain taustatyöt, jotka on aloitettu viimeisen tunnin aikana" oli rasti, näin ainoastaan kyseiset taustatyöt ja kun rastin otti pois, latautui näkyville kaikki taustatyöt.
> 
> (Huom. taustatyöt on järjestetty niin, että keskeneräiset työt näkyvät ensimmäisenä. Nuo omat viimeisen tunnin aikana aloittamani työt eivät siis näkyneet listan kärjessä rastin pois otettuani, mistä ensin hiukan hämäännyin. Tuoreimmat taustatyöt kuitenkin löytyvät edelleen kun järjestää listan päivämäärän mukaan.)

Okei, vaikuttaa siis muuten toimivan, mutta listan järjestys vaihtelee? Pitää siis hieman viilata. Tein tämän yhteisöönkin ja siellä näyttävät olevan innoissaan. https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36217

**Comment by ajrajala** [comment]
Lista on kyllä koko ajan järjestetty Tila-sarakkeen mukaan (myös tuotannossa), mutta kun tuoreissa töissä ei keskeneräisiä taustatöitä ollut, niin kuvittelin virheellisesti että työt olisivat aikajärjestyksessä ja siksi hämäännyin kun rastin pois otettua listalle ilmestyikin vanhoja keskeneräisiksi jääneitä taustatöitä. Éli listan järjestyksessä ei varsinaisesti liene viilattavaa, itselle olisi vain ollut loogisempaa järjestää työt oletuksena uusimmasta vanhimpaan.

**Comment by AnneliO** [comment]
Testasin tätä siili-nextillä ja minustakin tämä toimi oikein.

**Comment by johannaraisa** [comment]
Vaikuttaisi toimivan, suljen tiketin.
