### ISSUE TITLE
Able to update more hold parameters via REST API - ksdev/ks-0014-bug-30661-holds-update-params

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#3]
Varauslistan sivutukseen tarvittava endpoint.

**Comment by AnneliO** [comment]
Miten tätä voi testata? Onko tämä Koha-Suomen vai pääkäyttäjien testattavissa?

**Comment by ghost** [comment]
Toimii jos varauksen vanhenemispäivää pystyy muuttamaan varaussivulta.

**Comment by pknuuti** [comment]
Vaaran nextillä varasin asiakkaalle teoksen. Varauksen vanhenemispäivää pystyi muuttamaan eli toimii.

**Comment by sksandel** [comment]
Vaskin nextillä varauksen vanhenemispäivää pystyy muuttamaan tietueen Varaukset-sivulla.

**Comment by LeenaKinnunen** [comment]
Myös Lapissa varauksen vanhenemispäivän vaihto onnistuu tietueen Varaukset-sivulla.

**Comment by Kati-Helle** [comment]
Toimii Helle-nextissä.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
