### ISSUE TITLE
Finto-plugit - ksdev/ks-0099-K23-50-Finto-value-builders 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#31]
### Siirrettävä ominaisuus

Finto-plugit.

**Comment by johannaraisa** [comment]
Tämä on lisätty nexteille, testausta vaille valmista.

**Comment by ajrajala** [comment]
Meillä kuvailija ei ehtinyt nyt testata, mutta testasin näitä täti-nextillä [viime kevään testausohjeen](https://github.com/KohaSuomi/Koha-23x/issues/50#issuecomment-1990949162) mukaisesti ja pluginit toimivat mainituissa kentissä.

**Comment by johannaraisa** [comment]
Lisään tuon edellisen testaussuunnitelman tähän, samalla mennään.

1. Tee kuvailutietue tati-nextille.
2. Kokeile toimiiko Finto-plugit kentissä:
    1. 100$a, finto_finaf.pl           
    2. 382$a, finto_seko_nouri_noind.pl
    3. 655$a, finto_slm-local.pl       
    4. 648$a, finto_yso-aika_noind.pl  
    5. 388$a, finto_yso-aika.pl        
    6. 385$a, finto_yso-kauno_noind.pl 
    7. 650$a, finto_yso-kauno.pl       
    8. 257$a, finto_ysopaikat_noind.pl 
    9. 651$a, finto_ysopaikat.pl

**Comment by pknuuti** [comment]
Testasin Täti-nextillä noita plugareita ja kaikissa kentissä näytti toimivan.

**Comment by johannaraisa** [comment]
Hyvä, näyttää toimivan, suljen tiketin.
