### ISSUE TITLE
Turhien asiakastietojen piilotus - ks-0107-KD-G571-hide-table-borrowers-unwanted-fields 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#33]
### Siirrettävä ominaisuus

Otetaan pois nykyinen hakutulostaulukon piilotus ja piilotetaan taulukosta syntymäaika, osoite ja puhelinnumero.

**Comment by AnneliO** [comment]
Tätä muutosta ei enää tarvita, koska yhteisössä on saatu toimimaan sarakkeiden piilotus oikein. Tämä muutos liittyy alunperin [tikettiin #571](https://github.com/KohaSuomi/Koha/issues/571).

[Pääkäyttäjien muistilistalle](https://github.com/KohaSuomi/Koha-24.05/wiki/Muistilista-p%C3%A4%C3%A4k%C3%A4ytt%C3%A4jille#piilota-varaussivulla-asiakastulostaulukosta-syntym%C3%A4aika-osoite-ja-puhelinnumero) lisätty tieto, miten piilotuksen voi tehdä taulujen asetukset -sivulla.

Emmi poisti tämän branchin käytöstä.
