### ISSUE TITLE
Niteiden muokkaukseen/lisäykseen nidetyypin automaattinen valinta - ksdev/ks-0114-K22-336-autoitemtype

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#34]
### Siirrettävä ominaisuus

**HUOM! Tämän alle on tuotava korjattu 0027-branch.**

Niteiden muokkaukseen/lisäykseen tarvitaan toiminnallisuus (plugin/value builder), joka valitsee automaattisesti niteelle oikean nidetyypin hyllypaikan ja/tai kokoelmakoodin mukaan.

**Comment by emta001** [comment]
Viety testattavaksi. Testatkaa varmistamalla, että käytössä olevat plugarit toimivat kuten pitääkin.

**Comment by emta001** [comment]
> Viety testattavaksi. Testatkaa varmistamalla, että käytössä olevat plugarit toimivat kuten pitääkin.

Ja väärään tikettiin tuli tää kommentti :smile: 

Testipläni tälle:

**Kokeile erilaisia yhdistelmiä seuraavilla hakuehdoilla:**
- Aineistolaji
- Hyllypaikka
- Hyllytarkenne
- Kokoelmakoodi

Haussa käytetään aina vähintään aineistolajia. Muita kolmea ehtoa käytetään, jos ne on täytetty niteen tietoihin tallennuslomakkeella. Jos ehdoilla ei löydy ehdotettavaa nidetyyppiä, nidetyyppi-kenttä jää tyhjäksi. Alla vielä SQL-lauseke, jolla voi tarkistaa, mitä kannasta tarjotaan tietyillä ehdoilla:

SELECT i.itype, count(*) AS count FROM items i
LEFT JOIN biblioitems bi on(i.biblionumber = bi.biblionumber)
WHERE bi.itemtype = ?
AND i.location = ?
AND i.sub_location = ?
AND i.ccode = ?
GROUP BY i.itype
ORDER BY count DESC;

HUOM! Toiminnallisuuden käyttöönotto vaatii muokkauksen MARC-kuvailupohjiin. Eli kenttään 952y tulee ottaa käyttöön plugin itemtype.pl. EDIT. Kentästä on poistettava myös auth values-arvo.

**Olemattoman nidetyypin testaus:**
- syötä itemtype-kenttään höpöhöpö arvo tai jätä se tyhjäksi
- yritä tallentaa
-> näytölle pitäisi ilmestyä pop-up, jossa ilmoitetaan että nidetyyppi ei ole validi ja lista valideista nidetyypeistä

**Comment by ajrajala** [comment]
Vaski-nextillä testailtu eri yhdistelmillä ja näyttäisi tarjoavan oikeaa nidetyyppiä. Jos täytetyillä ehdoilla ei löydy niteitä, jäi kenttä tyhjäksi.

Testattu myös, että olemattoman nidetyypin testaus ok, näytölle tulee testausohjeessa mainittu pop-up.

**Comment by emta001** [comment]
Tiketissä #90 huomattiin, ettei tätä generointia voida käyttää sillä se rikkoo nidetaulukon tietueen Perustiedot-näytöllä. Tarkempi kuvaus ongelmasta löytyy tästä tiketin [kommentista](https://github.com/KohaSuomi/Koha-24.05/issues/90#issuecomment-2205799726).

Yritän keksi tähän jonkin ratkaisun, jolla ongelma voitaisiin kiertää.

**Comment by emta001** [comment]
> Tiketissä #90 huomattiin, ettei tätä generointia voida käyttää sillä se rikkoo nidetaulukon tietueen Perustiedot-näytöllä. Tarkempi kuvaus ongelmasta löytyy tästä tiketin [kommentista](https://github.com/KohaSuomi/Koha-24.05/issues/90#issuecomment-2205799726).
> 
> Yritän keksi tähän jonkin ratkaisun, jolla ongelma voitaisiin kiertää.

Tähän löytyi ratkaisu yhteisöstä, [bug 37375](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37375). Korjaus aiheuttaa kuitenkin sen, että jos MARC-kuvailupohjassa ei ole käytetty auktorisoitua arvoa esim. nidetyyppi-kentässä, nidetaulukossa näytetään vain nidetyypin tunnus (14VRUU tms.).

**Comment by emta001** [comment]
Nyt on korjaus viety nexteille ja tätä voi taas testata.

**Comment by Tuomas-Kyyti** [comment]
> Tähän löytyi ratkaisu yhteisöstä, [bug 37375](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37375). Korjaus aiheuttaa kuitenkin sen, että jos MARC-kuvailupohjassa ei ole käytetty auktorisoitua arvoa esim. nidetyyppi-kentässä, nidetaulukossa näytetään vain nidetyypin tunnus (14VRUU tms.).

Niin ja tässä toiminnallisuudessa auktorisoitu arvo ei voi olla käytössä, joten perusnäytöllä näkyy aina vain nidetyypin tunnus.

Tämä on kyllä ongelma. Olimme juuri ottamassa ensi viikolla tätä toimintoa käyttöön tuotannossa, mutta kun kerran tulevassa versiossa toimii näin, niin pitääkin miettiä uudelleen. Tämä koko nidetyypin käsite on ollut henkilökunnalle vähän vaikea ja jos ne muuttuisivat niiksi lyhenteiksi, niin hankalaa voisi olla.

Onko sitä nidetyypin kuvausta mitään toivoa saada näkymään perustiedot-sivulla?

**Comment by emta001** [comment]
> > Tähän löytyi ratkaisu yhteisöstä, [bug 37375](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37375). Korjaus aiheuttaa kuitenkin sen, että jos MARC-kuvailupohjassa ei ole käytetty auktorisoitua arvoa esim. nidetyyppi-kentässä, nidetaulukossa näytetään vain nidetyypin tunnus (14VRUU tms.).
> 
> Niin ja tässä toiminnallisuudessa auktorisoitu arvo ei voi olla käytössä, joten perusnäytöllä näkyy aina vain nidetyypin tunnus.
> 
> Tämä on kyllä ongelma. Olimme juuri ottamassa ensi viikolla tätä toimintoa käyttöön tuotannossa, mutta kun kerran tulevassa versiossa toimii näin, niin pitääkin miettiä uudelleen. Tämä koko nidetyypin käsite on ollut henkilökunnalle vähän vaikea ja jos ne muuttuisivat niiksi lyhenteiksi, niin hankalaa voisi olla.
> 
> Onko sitä nidetyypin kuvausta mitään toivoa saada näkymään perustiedot-sivulla?

Valitettavasti ei oikein ole. Kyseessä on ominaisuus, jonka muuttaminen olisi tehtävä yhteisön kautta, ei pelkästään meidän omana muutoksena. Yhteisössä kuitenkin näytettäisiin olevan ennemmin sitä mieltä, että tietyissä kuvailupohjan kentissä tulisi nimenomaan käyttää auktorisoitua arvoa (tämä koskenee myös nidetyyppi-kenttää). Joten en oikein luottaisi siihen, että muutos menisi yhteisössä läpi.

**Comment by Kati-Helle** [comment]
Testasin Helle-nextissä. Toimii.

**Comment by pirliis** [comment]
Testasin OUTIn nextillä. Muutoin näytti toimivan, mutta jos niteelle laittoi hyllytarkenteen, nidetyypin automaattista valintaa en saanut toimimaan.

**Comment by emta001** [comment]
> Testasin OUTIn nextillä. Muutoin näytti toimivan, mutta jos niteelle laittoi hyllytarkenteen, nidetyypin automaattista valintaa en saanut toimimaan.

Onko tuo plugari kiinni jossain tietyssä kuvailupohjassa? Ainakaan default-pohjassa se ei näyttäs toimivan?

**Comment by pirliis** [comment]
> > Testasin OUTIn nextillä. Muutoin näytti toimivan, mutta jos niteelle laittoi hyllytarkenteen, nidetyypin automaattista valintaa en saanut toimimaan.
> 
> Onko tuo plugari kiinni jossain tietyssä kuvailupohjassa? Ainakaan default-pohjassa se ei näyttäs toimivan?

Laiton nyt päälle kuvailupohjalle "kirja". Otin plugarin aamulla pois, kun meillä henkilökunta aloittaa tänään myös testaukset.

**Comment by emta001** [comment]
Testailin ja ongelma on varmaankin siinä, ettei valituilla ehdoilla löydy toista vastaanvanlaista nidettä. Kun laitan pelkäksi hyllytarkenteeksi "Alakylän koulu", saan ehdotuksena 28VRKLN. Jos lisään vielä hyllypaikaksi "Aikuiset", niin en enää saa yhtään ehdotusta. Nexteillähän on muutenkin vähemmän aineistoa kuin tuotannossa, niin sekin voi vaikuttaa noihin ehdotuksiin.

**Comment by pirliis** [comment]
> Testailin ja ongelma on varmaankin siinä, ettei valituilla ehdoilla löydy toista vastaanvanlaista nidettä. Kun laitan pelkäksi hyllytarkenteeksi "Alakylän koulu", saan ehdotuksena 28VRKLN. Jos lisään vielä hyllypaikaksi "Aikuiset", niin en enää saa yhtään ehdotusta. Nexteillähän on muutenkin vähemmän aineistoa kuin tuotannossa, niin sekin voi vaikuttaa noihin ehdotuksiin.

Sori. Testasin koulukirjastojen aineistoja niin, että laitoin hyllypaikaksi "Lapset ja nuoret", kun olisi pitänyt laittaa "Koulukirjasto". :D  Plugari näyttäisi siis toimivan myös OUTIssa hyllytarkenteella (kun testaaja osaa vain testata oikein. ;)).

**Comment by emta001** [comment]
Tämä toimii kuten pitääkin vaikka hieman höpsösti yhteisön muutoksien vuoksi. Suljen tiketin.
