### ISSUE TITLE
Veloitusaika muuttuu automaattisesti laina- ja maksusäännöissä muita saman rivin sääntöjä muokatessa  - ksdev/ks-0116-bug-34585-circrule-whentocharge-column 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#35]
### Siirrettävä ominaisuus

Kun laina- ja maksusäännöissä alkaa muokata jotain yksittäistä sääntöä, ko. nidetyypin Veloitusajankohta-sarakkeessa pudotusvalikon valinta hyppää oletuksena kohtaan "Aikavälin loppupäivä".

**Comment by emta001** [comment]
Testaussuunnitelma:
1. Tarkista, että sääntöä muokatessa Veloitusajankohta-sarakkeeseen ei valikoidu oletuksena "Aikavälin loppupäivä".
2. Tarkista, että kun tyhjennät muokattavan säännön kentät "Tyhjennä"-painikkeella, alasvetovalikoihin tulevat oletus valinnat.

**Comment by ajrajala** [comment]
Testaussuunnitelman 1. ja 2. kohta on ok, mutta huomasin testauksen yhteydessä, että mikäli muokkaan uutta, juuri tekemääni sääntöriviä, muokkausriville Asiakastyyppi-sarakkeeseen ei siirry säännölle valittu asiakastyyppi vaan valikossa on valittuna Kaikki. Ja jos asiakastyyppiä ei korjaa, tallentuu tästä tietysti kokonaan uusi sääntörivi eikä muokkauksia alkuperäiseen valittuun sääntöön.

![kuva](https://github.com/user-attachments/assets/d8eb649f-9a1f-417e-9173-0430d09cf329)

En saanut ongelmaa toistettua vaski-testillä, joten liittyyki bugi tähän korjaukseen vai onko ihan erillinen ongelma, josta pitäisi tehdä oma tiketti?

**Comment by emta001** [comment]
Luultavasti liittyy ihan tähän korjaukseen, yhteisöön oli tullut jo toinen korjaus liittyen näihin ja jouduin karsimaan koodia hieman. Ehkäpä se yhteisön korjaus ei korjannut sitten kaikkea tai karsin liikaa.

**Comment by emta001** [comment]
Testasin vielä vaski-testillä tätä ja huomasin lähes saman ongelman. Rupesin siis muokkamaan olemassa olevaa sääntöä ja sitten yritin tyhjentää muokkausrivin. Alasvetovalikot eivät tyhjentyneet sielläkään. Tässä on nyt sitten jokin vika.

**Comment by emta001** [comment]
Yhteisössä on siis 3 tikettiä, joista jokainen korjaa yhden laina-ja maksusääntöihin liittyvän ongelman.

[Bug 34585](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34585) - "When to charge" columns value not copied when editing circulation rule -> tämä on siis meidän 0116-branchissa
[Bug 36527](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36527) - Patron category or item type not changing when editing another circulation rule -> tämän korjasin 0116-branchiin ylemmän bugin yhteydessä ja tämä oli mukana myös yhteisön tiketissä, kunnes siitä tehtiin tämä uusi tiketti
[Bug 37254](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37254) - Dropdown values not cleared after pressing clear in circulation rules -> uusi tiketti ongelmasta, jota en huomannut aiemmin

Eli vähän nyt on sekavaa ja selkeyden vuoksi, eriytän nää kaikki omiksi tiketeikseen ja brancheikseen.

**Comment by emta001** [comment]
Nyt on uudet tiketit valmiit, #98 ja #99.

**Comment by emta001** [comment]
Nyt on uusi versio testattavana, samoin kuin nuo uusien tikettien korjaukset.

**Comment by ajrajala** [comment]
Kommentoin noihin erillisiin tiketteihin, mutta koontina tähän vielä: nyt äsken luodun sääntörivin ottaminen muokkaukseen säilyttää asiakastyypin ja nidetyypin eli tässä tiketissä aiemmin raportoitu ongelma on poistunut. Veloitusaika-sarakkeessa säilyy myös edelleen säännölle tehty valinta, kun sääntörivin ottaa muokkaukseen.

**Comment by LeenaKinnunen** [comment]
Lapissa sääntöjen muuttaminen toimii, ja valinnat pysyvät.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
