### ISSUE TITLE
Asiakkaan Lainaus- ja Tiedot- välilehdelle näkyviin kaikkien maksujen summa - ksdev/ks-0122-on-0032-KD-G762-include-all-charges-for-totals-in-intranet 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#37]
### Siirrettävä ominaisuus

Virkailijaliittymään halutaan näkyviin Lainaus- ja Tiedot- välilehdille asiakkaan kaikkien maksujen summa (julkisoikeudelliset + ei-julkisoikeudelliset). Tällä hetkellä vain julkisoikeudelliset maksut näkyvät kyseisissä näkymissä.

**Comment by Kati-Helle** [comment]
Helle-nextissä näkyvät vain julkisoikeudelliset maksut.

AsiakasID = 22707

Asiakkaan maksut
![kuva](https://github.com/user-attachments/assets/99f15673-0377-436c-adc4-004d7a9f9f7d)

Maksut asiakkaan Lainaus-välilehdellä
![kuva](https://github.com/user-attachments/assets/5966d1ef-a9a6-48af-a8fe-9e72c5c764b8)

Maksut asiakkaan Tiedot-välilehdellä
![kuva](https://github.com/user-attachments/assets/e71400a9-b734-4bd5-8566-bd338f6f90bc)

**Comment by lmstrand** [comment]
Jotain syystä koodi ei tullut mukaan nextien päivityksessä. Nyt näyttäisi toimivan, kun koodi on paikallaan.

**Comment by Kati-Helle** [comment]
Joo, nyt asiakkaan kaikkien maksujen määrä näkyvissä.

Lainaus-välilehdellä
![kuva](https://github.com/user-attachments/assets/1aa6521b-a02e-4085-9840-610eb84938ec)

Tiedot-välilehdellä
![kuva](https://github.com/user-attachments/assets/ea538ad8-185c-4fae-96c2-ebc6a24f50ce)

**Comment by ReettaSiili** [comment]
Myös Siili-nextillä maksut näkyvät oikein eroteltuna lainakieltoa aiheuttaviin sekä kokonaissumma, kuten Hellessä, englanniksi.

**Comment by Rvallim0** [comment]
Vaskin nextillä testattu myös, toimii odotetusti, mutta teksti englanniksi.

**Comment by lmstrand** [comment]
Odottaa vielä käännöksien tekoa, mutta tämä muuten ok. Suljen tiketin.
