### ISSUE TITLE
Asiakkaan lisääminen onnistunut ilman osoitetietoja - ksdev/ks-0125-bug-34671-fieldset-collapse-error

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#39]
### Siirrettävä ominaisuus

Asiakkaan pystyy tallentamaan ilman vaadittuja tietoja, jos niiden fieldset on piilotettu.

**Comment by emta001** [comment]
Tämä on testattavana nexteillä.

**Comment by Kati-Helle** [comment]
Helle-nextissä uuden asiakastiedon tallennus ei onnistu ilman osoitetietoja. Uuden asiakastiedon tallennusyrityksestä tämä:
![kuva](https://github.com/KohaSuomi/Koha-24.05/assets/99952449/23140048-d94f-4f80-b432-52c71a0b1717)

**Comment by MikkoLiimatainen** [comment]
Vaski-nextissäkään tallennus ilman pakollisia tietoja ei onnistunut, vaikka fieldset oli piilotettuna.

**Comment by pknuuti** [comment]
Ei onnistu tallentaa ilman osoitetietoja myöskään Vaaran nextillä.

**Comment by atarnus** [comment]
Outi-nextillä myös vaatii täyttämään kentät:

![Image](https://github.com/user-attachments/assets/0add294e-9210-48e5-9254-07cf91812efe)

**Comment by emta001** [comment]
Toimii, suljen tiketin.
