### ISSUE TITLE
Sivutus tietueen Varaukset-sivulle - ksdev/ks-0015-K23-7-holds-page-REST

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#4]
Koha-Suomen oma versio Varaukset-sivusta.

**Comment by AnneliO** [comment]
Testailin varaussivun sivutusta ja kaikki muu, mitä hoksasin testailla (järjestyksen vaihto, peruuta-nappi, keskeytys, keskeytyksen jatko) tuntui toimivan. Ainoa, mikä ei toiminut, oli Peruuta valitut -nappi. Tein siitä erillisen tiketin #111.

**Comment by ajrajala** [comment]
Tiedoksi mahdollisesti sivutukseen liittyen tiketti #104

**Comment by sksandel** [comment]
Vaskin Nextillä testattu. Varaussivun sivutuksessa en huomannut ongelmia. Testasin eri sivumäärät, kaikki varaukset, varausten selailu sivu kerrallaan, siirtymä ensimmäiseen ja viimeiseen varaussivuun tai valitulle varaussivulle.

**Comment by atarnus** [comment]
Sivutus toimii Outi-nextillä, testasin eri rivimääriä ja siirtmistä sivulla toiselle, jonossa nostoja/laskuja ym. Yksittäisen varauksen peruuttaminen Peruuta-napista antoi kyllä peruutusviestin "Hold cancelled" moneen kertaan, 3-8 riviä putkeen tuli samaa viestiä useammalla poistolla, välillä kuitenkin vain yksi. Joka kerta poistui kuitenkin vain se yksi varaus.

**Comment by atarnus** [comment]
Tämä nuolikohta on rikki, mutta ei liittyne sivutukseen. Käyttäytyy samankaltaisesti kuin yllämainittu #104. Eli sen sijaan, että varaukselle tulisi matalin prioriteetti, tulee uuden varauksen ikkuna. En tiedä käyttääkö tätä toiminnallisuutta kukaan ikinä, tehdäänkö tästä tikettiä? (Tuotannossa tämä nyt kuitenkin tuntuu toimivan.)
![image](https://github.com/user-attachments/assets/d98fb51c-a68d-4be2-a70c-09bc69ec1840)

**Comment by emta001** [comment]
> Tämä nuolikohta on rikki, mutta ei liittyne sivutukseen. Käyttäytyy samankaltaisesti kuin yllämainittu #104. Eli sen sijaan, että varaukselle tulisi matalin prioriteetti, tulee uuden varauksen ikkuna. En tiedä käyttääkö tätä toiminnallisuutta kukaan ikinä, tehdäänkö tästä tikettiä? (Tuotannossa tämä nyt kuitenkin tuntuu toimivan.) ![image](https://private-user-images.githubusercontent.com/63994411/368523655-d98fb51c-a68d-4be2-a70c-09bc69ec1840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODM3NTcsIm5iZiI6MTcyODM4MzQ1NywicGF0aCI6Ii82Mzk5NDQxMS8zNjg1MjM2NTUtZDk4ZmI1MWMtYTY4ZC00YmUyLWE3MGMtMDliYzY5ZWMxODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEwMzA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZjU3ODJiYWZlMGE1YzBmNzFjMjcxMjc1M2FiNDhiYTYwMWNkMjZhZGU2YTgxM2Q1Y2E4YzZlZTI2MDNkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CghPyayel4vWKg4KGAe8X7B_SaUGEaZuhi6TvOzMPPQ)

Luultavasti tässä on tosiaan sama ongelma kyseessä kuin tiketissä #104. Pitää käydä muokkaamassa tuon linkin rakennetta.

**Comment by emta001** [comment]
@atarnus kehtaako tehdä tuosta Set lowest priority-nuolesta oman tikettinsä?

**Comment by atarnus** [comment]
> @atarnus kehtaako tehdä tuosta Set lowest priority-nuolesta oman tikettinsä?

Tässäpä olisi: https://github.com/KohaSuomi/Koha-24.05/issues/135

**Comment by emta001** [comment]
Sivutuksen osalta varaukset toimii, joten suljen tämän tiketin. Muista ongelmista vois sitten tehdä omat tiketit.
