### ISSUE TITLE
Rajaukseen käytetty fasettivalinta "Nykyinen paikka" säilyy, vaikka hakutulosnäytöllä tehdään uusi haku - ksdev/ks-0131-KOHA-667-selecting-facet-changes-library 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#40]
### Siirrettävä ominaisuus

Hae tietokannasta -haku muistaa tarpeettomasti aiemmassa haussa käytetyn fasettirajauksen Nykyinen paikka, kun Haun tulokset -näytöllä tehdään uusi haku.

**Comment by johannaraisa** [comment]
Nyt tämä on nexteillä, testausta vailla valmista.

**Comment by ajrajala** [comment]
Vaski-nextillä toimii kuten pitää; "Nykyinen paikka" -fasettivalinta poistuu, kun tekee fasetilla rajaamisen jälkeen uuden haun Hae tietokannasta -kentän kautta.

**Comment by AnneliO** [comment]
Siili-nextillä testattuna toimii oikein.

**Comment by atarnus** [comment]
Testattu Outi-nextillä, ja fasettivalinnat eivät tosiaan muuta pudotusvalikon kirjastovalintaa, eikä kirjastovalinta jää voimaan tuleville hauille.

Muistelisin, että aiemmin ongelma koski myös Kotikirjasto (homebranch) fasettia. Ja tosiaan myöskään Nykyinen paikka (holdingbranch) fasettivalinta ei vaihda pudotusvalikon kirjastoa. Hakutuloksessa näkyy, että pudotusvalikon rajausehto on tuo välilyönnillä oleva ehto ja fasettivalinta on ilman väliä. Tällä tavalla voi saada aikaan vähän tällaisia hassuja tuplaehtoja, mutta lienee parempi kuin fasetin "päälle jääminen" vahingossa.

`'((holdingbranch: "OUJA")) AND (holdingbranch:("HAIPK")) AND (homebranch:("HAIPK"))'`

Huomiona myös, että jos hakutuloksia on vain yksi, niin pudotusvalikostakin tehty kirjastovalinta nollaantuu (olettaisin johtuvan siitä, että siirrytään hakutulossivulta tietueen sivulle). Muuten pudotusvalikon valinta säilyy.

**Comment by johannaraisa** [comment]
Tulkitsenko oikein, että tämä on kunnossa ja tiketin voi sulkea?

**Comment by LeenaKinnunen** [comment]
Lapissa toimii oikein, eli fasettivalinnat eivät säily, kun tekee uuden haun.

**Comment by johannaraisa** [comment]
Hyvä juttu, suljen tiketin.
