### ISSUE TITLE
Taululukon vaihtaminen proccessing-tilaan viestiä luodessa - ksdev/ks-0134-bug-35734-message-queue-table-lock

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#41]
### Siirrettävä ominaisuus

Koha-Suomessa tehty parannus viestien käsittelyyn. Estää taulunlukon syntymisen message_queue-tauluun, joka voi aiheuttaa koko Kohan.

**Comment by johannaraisa** [comment]
Tämä on lisätty nexteille, testauta vaille valmista.

**Comment by johannaraisa** [comment]
Testaussuunnitelma:

1. Laita asiakkaalle päälle lainakuitti.
2. Lainaa nide
3. Vahvista, että lainaus onnistui ja asiakkaalle on muodostunut viesti.

**Comment by johannaraisa** [comment]
Testasin itse vaski-nextillä, kaikki meni kuten piti.

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä, toimii oikein.

**Comment by LeenaKinnunen** [comment]
Toimii oikein Lapilla, sekä lainaus- että palautuskuitti-sähköpostit muodostuvat odottamaan lähetystä.

**Comment by johannaraisa** [comment]
Hyvä, suljen tiketin.
