### ISSUE TITLE
Tietueen kuvailun virheilmoituksen Mene kenttään -linkin korjaus - ksdev/ks-0135-K22-580-fix-error-links-in-cataloguing

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#42]
### Siirrettävä ominaisuus

**HUOM! Tutkittava voiko tämän tiputtaa.**

Kuvailu-toiminto ilmoittaa tietuetta tallentaessa, kun tietueelta puuttuu esim. pakollisen kentän arvo.
Ilmoituksessa on mainittuun puuttuvaan kenttään Mene kenttään -linkki, joka ei nyt vie ilmoituksessa mainittuun kenttään eikä muuallekaan.

**Comment by johannaraisa** [comment]
Ei näytä olevan parannusta, tuodaan tämä.

**Comment by johannaraisa** [comment]
Tämä on nyt nexteillä, testausta vaille valmista.

**Comment by pknuuti** [comment]
Testattu Vaaran nextillä, toimii.

**Comment by LeenaKinnunen** [comment]
Lapin nextillä toimii.

**Comment by sksandel** [comment]
Vaskin nextillä toimii. Valittaa puuttuvista kentistä ja "mene kenttään" vie täyttämään tietoja oikeaan kohtaan.

**Comment by johannaraisa** [comment]
Hyvä juttu, suljen tiketin.
