### ISSUE TITLE
"Piilota kaikki sarakkeet" valinta ei säily sivun päivittyessä niteiden eräpoistossa/erämuokkauksessa - ksdev/ks-0137-bug-36129-batch-mod-hideall-checkbox

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#43]
### Siirrettävä ominaisuus

Kun niteiden eräpoistossa/erämuokkauksessa sivulla valitsee "Piilota kaikki sarakkeet" valinnan, valinta ei enää säily kun sivun lataa uudelleen. Sarakkeet piilottuvat oikein.

**Comment by emta001** [comment]
Viety nexteille testattavaksi. Testailkaa tälleen:

1. Mene niteiden erämuokkaukseen ja syötä muokkattavien niteiden viivakoodit kenttään.
2. Olessasi muokkaussivulla, paina valintaa "Piilota kaikki sarakkeet".
3. Poistu sivulta ja palaa sille uudelleen tai päivitä sivu.
=> "Piilota kaikki sarakkeet" tulisi olla edelleen valittuna ja sarakkeet on piilotettu oikein.

**Comment by LeenaKinnunen** [comment]
Lapin nextillä testattu, toimii oikein: sarakkeet pysyvät piilossa niin valittuna.

**Comment by sksandel** [comment]
Vaskin Nextillää testattu. Toimii. Halutut sarakkeet pysyvät piilossa kun sivun päivittää.

**Comment by Kati-Helle** [comment]
Helle-nextissä piilotetut sarakkeet pysyvät piilossa, kun sivun päivittää TAI kun poistuu sivulta. ja palaa takaisin.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
