### ISSUE TITLE
Log changes to borrower message preferences to action logs - ksdev/ks-0140-K23-G241-messaging-prefs-actionlog

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#45]
### Siirrettävä ominaisuus

Asiakkaan viestiasetusten muutokset eivät tallennu lokiin.

**Comment by johannaraisa** [comment]
Nyt tämä on nexteillä, testausta vailla valmista.

**Comment by ajrajala** [comment]
Tein jonkin muutoksen asiakkaan kaikkiin viestiasetuksiin Kohassa. Jokaisen viestiasetuksen muutoksesta tallentui oma lokirivi tähän tyyliin:

`Messaging preference: after: [{"days_in_advance":4, "message_name":"Advance_Notice", "message_transport_type":"email", "wants_digest":1}] before: [{"days_in_advance":3, "message_name":"Advance_Notice", "message_transport_type":"email", "wants_digest":1}] `

Nähdäkseni toimii siis kuten pitää.

**Comment by AnneliO** [comment]
Kokeilin siili-nextillä niin, että 

* poistin puhelinnumeron, jolloin triggeröityi viestiasetusten poisto. Muutos lokittui.
*  lisäsin yhden sähköpostiviestivalinnan. Muutos lokittui.

Minusta tämä toimii.

**Comment by pknuuti** [comment]
Vaaran nextilläkin lokittuu muutokset viestiasetuksissa.

**Comment by johannaraisa** [comment]
Eiköhän ole kunnossa sitten, suljetaan tiketti.
