### ISSUE TITLE
MTYPE fasetoitavaksi ja fasetti MTYPE:lle - ksdev/ks-0142-K23-132-facet-for-mtype

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#46]
### Siirrettävä ominaisuus

**HUOM! Tutkittava voiko tämän tiputtaa.**

Aineistotyypit-fasetti mtype-indeksistä.

**Comment by johannaraisa** [comment]
Korjatkaa jos olen väärässä, näyttäisi toimivan, mutta fasettien nimet ovat koodeja eikä selkeä kieltä?

**Comment by johannaraisa** [comment]
Näköjään pitää muokata mappings-tiedoston labeleita, että alkaa näkymään.

**Comment by johannaraisa** [comment]
Indeksoitu uudelleen ja testattavissa:

- [x] Vaara
- [x] Vaski
- [x] Lumme
- [x] Kyyti
- [x] OUTI
- [x] Kirkes
- [x] Lappi
- [ ] Lastu
- [x] Siili
- [x] Täti
- [x] Helle

**Comment by johannaraisa** [comment]
"Material types"-otsikko vaatii käännöksen ja nyt listassa näkyy avainarvo eikä auktorisoitujen arvojen kuvaus. Kuvauksesta pitää tehdä tiketti yhteisöön, sillä tällä hetkellä esim. ccode on kovakoodattu. Kaikki nuo pitäisi hakea automaattisesti, eikä kovakoodauksella.

**Comment by AnneliO** [comment]
Material types -otsikolle saadaan todennäköisesti tehtyä käännös, kun luodaan Koha-Suomen omat po-tiedostot.

Testeillä listassa näkyy arvon kuvaus, mitenköhän se sinne on toteutettu?

![Image](https://github.com/user-attachments/assets/acb4c9bd-082a-46f3-8dcb-1548e64b81cd)


Tosin, 24.05:ssa on mukana yhteisön muutokset fasettien lisäämisestä ylläpidossa, joten pitäisikö tämä yrittää tehdä jotenkin eri tavalla kuin versioon 23.11?

[Fasetit konfiguroitavaksi liittymän kautta](https://github.com/KohaSuomi/Koha-24.05/wiki/Uutta-versiossa-24.05#fasetit-konfiguroitavaksi-k%C3%A4ytt%C3%B6liittym%C3%A4n-kautta)

ja 

[Fasetin kytkeminen auktorisoituun arvoon](https://github.com/KohaSuomi/Koha-24.05/wiki/Uutta-versiossa-24.05#fasetin-kytkeminen-auktorisoituun-arvoon)

**Comment by AnneliO** [comment]
Haa, kävin siili-nextillä valitsemassa mtype-fasetille auktorisoiduksi arvoksi MTYPE:n, niin tiedonhaussa fasetissa rupesi näkymään kuvaus tunnisteen sijaan.


Fasettien asetukset
![Image](https://github.com/user-attachments/assets/33a67511-cd59-42c8-b1e3-0d3419a58fa7)


Fasetti tiedonhaussa
![Image](https://github.com/user-attachments/assets/ea08eaa6-f953-40a5-8de3-3ce1dfdf7b01)

**Comment by lmstrand** [comment]
Niin tämä oli toteutettu edellisessä versiossa branchiin ksdev/ks-0142-K23-132-facet-for-mtype joka on nyt siis turha tuoda 24:een.

**Comment by LeenaKinnunen** [comment]
En tiedä pitikö testata, mutta tein kuten Anneli (hih) ja sain toimimaan Lapin nextillä eli material types-fasetissa näkyy kuvailu eli toimii.

**Comment by johannaraisa** [comment]
Tähän tarvitaan siis enää käännös, suljen tämän tiketin.

**Comment by AnneliO** [comment]
Pistin varalta ylös [Muistilistalle](https://github.com/KohaSuomi/Koha-24.05/wiki/Muistilista#valitse-mtype-indeksille-auktorisoitu-arvo), että versionvaihdon jälkeen pitää käydä valitsemassa mtype-indeksille auktorisoitu arvo.

**Comment by AnneliO** [comment]
Ilmeisesti Material type -fasetti ei käänny. Avaan tiketin uudelleen.

**Comment by AnneliO** [comment]
Tässä on muutosta aiempaan fasetin nimenkin osalta. Tiketin [Koha-23.xx #132](https://github.com/KohaSuomi/Koha-23x/issues/132) mukaan fasetin nimi on nykyään Record-level item types. Nexteillä se on Material types. Aiemmin termi laitettiin noudattamaan muualla Kohassa käytössä olevaa termistöä. Pitäisikö jatkossakin noudattaa samaa linjaa?

Kävin läpi fi-FI-staff-prog.po-tiedoston ja etsin kaikki käännökset, joissa on mainittu facets.inc. Siellä ei ollut mukana Material types eikä toista puuttuvaa käännöstä Locations.

Arvailua, mutta voiko tähän vaikuttaa jotenkin se, mikä mäppäystiedosto on käytössä siinä tietokannassa, minkä pohjalta käännökset tehdään? Mitkä termit siellä on ollut käytössä noiden indeksien kuvauksina, kun käännöstiedostot luotiin?

Koitan vielä selailla Bugzillaa, löytyiskö sieltä jotain tähän aiheeseen liittyvää.

**Comment by AnneliO** [comment]
En löytänyt oikein mitään juuri fasetin käännettävyyteen liittyvää bugzillasta.

Kokeilin myös siili-nextillä vaihtaa mtype-indeksin Labelin muotoon "Record-level item type", jolle löytyy staff-progista käännös muita sivuja varten. Otsikko kyllä muuttui faseteissa, mutta käännös ei siihen lennossa tarttunut (en kyllä oikeastaan odottanutkaan sen toimivan :D).

**Comment by AnneliO** [comment]
Aukaisin fasettien kääntymättömyydestä [uuden tiketin](https://github.com/KohaSuomi/Koha/issues/1542). Suljen tämän.
