### ISSUE TITLE
Kaikkien asiakastietojen haun esto - ksdev/ks-0143-KOHA-467-prevent-search-for-all-patrons

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#47]
### Siirrettävä ominaisuus

Täällä pyritään estämään se, että virkailija ei vahingossa hae tietokannan kaikkia asiakastietoja listalle, jolloin kaikille listalla oleville tehdään muutoslokiin merkintä asiakastietojen katselusta.

**Comment by emta001** [comment]
Viety nexteille testattavaksi.

**Comment by ajrajala** [comment]
Vaski-nextillä näyttää toimivan, tyhjä haku antaa punaisen virhetekstin:
![kuva](https://github.com/user-attachments/assets/62cc8f02-923b-495c-b36b-0097531916c4)

Jos haku-kenttään laittaa %-merkin, haku onnistuu (kuten tuotannossakin).

**Comment by atarnus** [comment]
Toimii myös Outi-nextillä.

(Aikoinaan kun tätä tehtiin, niin päätettiin jättää tuo %-haun mahdollisuus päälle. Sen voisi sieltä estää kyllä tekemällä regexp tarkistuksen, että eihän hakutermi muodostu pelkästään %-, *- ja välimerkeistä, jos katsotaan tarpeelliseksi. Pelkillä välilyönneillä hakeminen ei onnistu. Jostain syystä *-merkillä hakeminen oli kait välillä onnistunut.)

**Comment by ajrajala** [comment]
> Toimii myös Outi-nextillä.
> 
> (Aikoinaan kun tätä tehtiin, niin päätettiin jättää tuo %-haun mahdollisuus päälle. Sen voisi sieltä estää kyllä tekemällä regexp tarkistuksen, että eihän hakutermi muodostu pelkästään %-, *- ja välimerkeistä, jos katsotaan tarpeelliseksi. Pelkillä välilyönneillä hakeminen ei onnistu. Jostain syystä *-merkillä hakeminen oli kait välillä onnistunut.)

Vaskilla olisi toiveena, että mahdollisuus %-hakuun säilyisi. Siitä on hyötyä esim. esihenkilöille, kun käyvät läpi oman kirjastonsa virkailijatunnuksia (onko poistettavia/uusittavia tunnuksia).

**Comment by pknuuti** [comment]
Vaaran toive ihan sama kuin Vaskilla ja syykin on sama :)

**Comment by AnneliO** [comment]
Toimii siili-nextillä. Käännös puuttuu vielä ohjetekstistä, mutta se tulee todennäköisesti sitten, kun tehdään Koha-Suomen omat po-tiedostot.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
