### ISSUE TITLE
Nidehaun monivalintakenttiin mahdollisuus hakea suurempi tai pienempi kuin -operaattoreilla - ksdev/ks-0146-KOHA-447-more-operators-for-item-search

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#48]
### Siirrettävä ominaisuus

Otsikko lienee tarpeeksi selittävä.

**Comment by emta001** [comment]
Viety nexteille testattavaksi.

**Comment by ajrajala** [comment]
Tiedoksi tähän tikettiin liittyen bugi #105

**Comment by AnneliO** [comment]
Minusta tämä toimii siili-nextillä oikein.

**Comment by LeenaKinnunen** [comment]
Vaikuttaa toimivan Lapissa oikein.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
