### ISSUE TITLE
Floatrules - ksdev/ks-0018-K23-8-floatrules

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#5]
Koha-Suomen kellutussäännöille tehty asetus.

**Comment by emta001** [comment]
Tämä on testattavissa nexteillä. Testaa varmistamalla, että kellutus toimii Floatrules-asetuksessa olevien sääntöjen mukaan.

**Comment by Kati-Helle** [comment]
Helle-nextissä kellutus toimii Floatrules-asetuksen sääntöjen mukaan.

**Comment by ajrajala** [comment]
Vaski-nextillä testattu eri tyyppisiä FloatRules-sääntöjä, kellutus näyttäisi toimivan kuten pitää.

**Comment by pirliis** [comment]
OUTIn nextillä testattu. FloatRulesin kellutussäännöt näyttäisivät toimivan myös OUTIssa

**Comment by emta001** [comment]
Toimii. Suljen tiketin.
