### ISSUE TITLE
normalize-and-uc-facet-sorting - ksdev/ks-0152-K23-G1238-normalize-and-uc-facet-sorting

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#50]
### Siirrettävä ominaisuus

Nimet aakkostuvat faseteissa väärin, jos ne sisältävät erikoismerkkejä, esim. Šostakovitš, Dmitri menee viimeiseksi.

**Comment by lmstrand** [comment]
Tuotu nexteille testattavaksi.

**Comment by AnneliO** [comment]
FacetOrder-järjestelmäasetuksessa pitää olla valittuna "aakkosjärjestyksessä", jotta tätä voi testata.

**Comment by Rvallim0** [comment]
Vaski nextillä testattu, toimii oikein.

**Comment by pirliis** [comment]
OUTIn nextillä näyttäisi aakkostuvan oikein.

**Comment by lmstrand** [comment]
Tämä ok. Kiitos testailusta.
