### ISSUE TITLE
Poistaa tyhjän 942-kentän, jos cn_sort on poistanut 6-osakentän - ksdev/ks-0156-KOHA-G1255-remove-empty-942-field

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#51]
### Siirrettävä ominaisuus

Jos 942-kentässä on vain 6-osakenttä, niin kantaan tallentuu tyhjä 942-kenttä. Tämä aiheuttaa 500-virheen tietuenäytöllä.

**Comment by johannaraisa** [comment]
Tämä on viety nexteille. Koodi näyttää samalle kuin nykyään, joten uskoisin toimivan edelleen.
