### ISSUE TITLE
Järjestelmäasetus millä voi määritellä mitä kenttiä emosta kopioidaan osakohteeseen - ksdev/ks-0157-bug-37061-prepare-host-field-system-reference 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#52]
### Siirrettävä ominaisuus

Otsikko kertonee tarpeeksi.

Järjestelmäasetuksen nimi on PrepareHostField

**Comment by johannaraisa** [comment]
Tämä on lisätty nexteille, testausta vaille valmista.

**Comment by ajrajala** [comment]
Järjestelmäasetus näyttäisi toimivan, lisäsin parille tietueelle uuden osakohteen ja 773-osakentissä näkyy kuvailueditorissa järjestelmäasetukseen määritellyt emotietueen kenttien tiedot.

**Comment by pknuuti** [comment]
Vaaran nextillä en pysty tekemään osakohdetta tietueelle. Tallennuksen jälkeen tulee virheilmoitus:
"Virhe!
Virhe 500
Tämä viesti johtuu jostain seuraavasta syystä:

    Ulkoinen lähde on ohjannut sinut nimekkeeseen, jota ei ole enää olemassa
    Seurasit vanhaa linkkiä esim. hakukoneesta tai kirjanmerkeistä
    Yritit päästä sivulle, jonne pitää kirjautua.
    Linkki oli virheellinen ja sivua ei ole olemassa

Mitä seuraavaksi?

    Käytä ylävalikkoa siirtyäksesi toiseen Kohan osioon.
    Raportoidaksesi toimimattoman linkin tai muun ongelman, ota yhteys ylläpitoon. [Lähetä sähköposti](mailto:noreply%40koha-suomi.fi)"

Laitoin ensin järjestelmäasetuksen  PrepareHostField käyttöön, vaikuttaako se nyt jotenkin asiaan?

**Comment by johannaraisa** [comment]
> Vaaran nextillä en pysty tekemään osakohdetta tietueelle. Tallennuksen jälkeen tulee virheilmoitus: "Virhe! Virhe 500 Tämä viesti johtuu jostain seuraavasta syystä:
> 
> ```
> Ulkoinen lähde on ohjannut sinut nimekkeeseen, jota ei ole enää olemassa
> Seurasit vanhaa linkkiä esim. hakukoneesta tai kirjanmerkeistä
> Yritit päästä sivulle, jonne pitää kirjautua.
> Linkki oli virheellinen ja sivua ei ole olemassa
> ```
> 
> Mitä seuraavaksi?
> 
> ```
> Käytä ylävalikkoa siirtyäksesi toiseen Kohan osioon.
> Raportoidaksesi toimimattoman linkin tai muun ongelman, ota yhteys ylläpitoon. [Lähetä sähköposti](mailto:noreply%40koha-suomi.fi)"
> ```
> 
> Laitoin ensin järjestelmäasetuksen PrepareHostField käyttöön, vaikuttaako se nyt jotenkin asiaan?

Taitaa johtua noista tietokantatriggereistä, siellä on väärä käyttäjä. Korjaan sen, ni katsotan uudestaan.

**Comment by pknuuti** [comment]
Otin pois tuon järjestelmäasetuksen, mutta edelleenkään en saa tallennettua osakohdetta nextillä.

**Comment by johannaraisa** [comment]
Nyt voi kokeilla uudestaan, muutin tietokantatriggerien käyttäjän.

**Comment by pknuuti** [comment]
Kiitos, nyt onnistuu tallentaminen.

**Comment by pknuuti** [comment]
Osakohteen tallentaminen onnistuu, mutta ihmettelen miksi kaikki määrittelemäni kentät eivät tule osakohteeseen, vaikka emossa on tietoja ko. kentässä. 
Tässä emon tietoja:

![Image](https://github.com/user-attachments/assets/b5a81125-ea25-41a7-8908-2d29f71b5d0b)

osakohteen 773-kentät:

![Image](https://github.com/user-attachments/assets/de4d649a-4c31-434c-b029-0ef81d4b3bc8)

Järjestelmäasetus:

![Image](https://github.com/user-attachments/assets/c44e4e95-5a20-4f1e-a404-fb8cc2bb5b3b)

**Comment by pknuuti** [comment]
Nyt tuon järjestelmäasetuksen muokkaaminen nextillä ei onnistu. Tallentamisessa tulee virheilmoitus Forbidden.

**Comment by johannaraisa** [comment]
> Nyt tuon järjestelmäasetuksen muokkaaminen nextillä ei onnistu. Tallentamisessa tulee virheilmoitus Forbidden.

Minä muokkasin sitä äsken, kun siinä oli tuo ylimääräinen viimeinen rivi. Pitääv varmaan ladata uudestaan sivu, että on ajan tasalla.

**Comment by pknuuti** [comment]
Yritin muokata uuden version kokonaan, mutta aina vaan tuli virheilmoitus. Nyt vihdoin tallentui muokattu versio.

**Comment by pknuuti** [comment]
Tein uuden testin Vaaran nextillä. Järjestelmäasetuksessa samat arvot kuin TäTissä:

![Image](https://github.com/user-attachments/assets/8a165c21-5550-4343-b8cf-5df8b9f89e71)

Tulos: 

![Image](https://github.com/user-attachments/assets/d81e2449-844a-40fd-a55a-2d9a593a1634)

Emon tietueessa kenttä 2xx:

![Image](https://github.com/user-attachments/assets/bc59244b-2a69-4586-8c60-02c7024dfe3c)

Eli miksi ei edelleenkään tule kaikki määritellyt kentät osakohteelle? Vai enkö hoksaa nyt jotain olennaista?

**Comment by johannaraisa** [comment]
Hmm, voisikohan liittyä tuohon, että tuo 773$d on määritelty kahdesti. Pitääpä testata.

**Comment by johannaraisa** [comment]
Nyt toimii Vaarassakin, vaati plackin uudelleen käynnistyksen.

**Comment by pknuuti** [comment]
Kiitos, nyt toimii kuten pitääkin. Olipas se mielenkiintoinen testaus :) Eli siis testaus on onnistunut, toiminto toimii kuten pitääkin.

**Comment by ajrajala** [comment]
> > Vaaran nextillä en pysty tekemään osakohdetta tietueelle. Tallennuksen jälkeen tulee virheilmoitus: "Virhe! Virhe 500 Tämä viesti johtuu jostain seuraavasta syystä:
> > ```
> > Ulkoinen lähde on ohjannut sinut nimekkeeseen, jota ei ole enää olemassa
> > Seurasit vanhaa linkkiä esim. hakukoneesta tai kirjanmerkeistä
> > Yritit päästä sivulle, jonne pitää kirjautua.
> > Linkki oli virheellinen ja sivua ei ole olemassa
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Mitä seuraavaksi?
> > ```
> > Käytä ylävalikkoa siirtyäksesi toiseen Kohan osioon.
> > Raportoidaksesi toimimattoman linkin tai muun ongelman, ota yhteys ylläpitoon. [Lähetä sähköposti](mailto:noreply%40koha-suomi.fi)"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Laitoin ensin järjestelmäasetuksen PrepareHostField käyttöön, vaikuttaako se nyt jotenkin asiaan?
> 
> Taitaa johtua noista tietokantatriggereistä, siellä on väärä käyttäjä. Korjaan sen, ni katsotan uudestaan.

Onkohan vaski-nextilläkin väärä käyttäjä? En eilen tallentanut osakohdetta vaan katselin vain mitkä tiedot kopioitui lomakkeelle. Nyt koitin tallentaa tietuetta niin tulee virhe 500 -ilmoitus,

**Comment by johannaraisa** [comment]
> > > Vaaran nextillä en pysty tekemään osakohdetta tietueelle. Tallennuksen jälkeen tulee virheilmoitus: "Virhe! Virhe 500 Tämä viesti johtuu jostain seuraavasta syystä:
> > > ```
> > > Ulkoinen lähde on ohjannut sinut nimekkeeseen, jota ei ole enää olemassa
> > > Seurasit vanhaa linkkiä esim. hakukoneesta tai kirjanmerkeistä
> > > Yritit päästä sivulle, jonne pitää kirjautua.
> > > Linkki oli virheellinen ja sivua ei ole olemassa
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Mitä seuraavaksi?
> > > ```
> > > Käytä ylävalikkoa siirtyäksesi toiseen Kohan osioon.
> > > Raportoidaksesi toimimattoman linkin tai muun ongelman, ota yhteys ylläpitoon. [Lähetä sähköposti](mailto:noreply%40koha-suomi.fi)"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Laitoin ensin järjestelmäasetuksen PrepareHostField käyttöön, vaikuttaako se nyt jotenkin asiaan?
> > 
> > 
> > Taitaa johtua noista tietokantatriggereistä, siellä on väärä käyttäjä. Korjaan sen, ni katsotan uudestaan.
> 
> Onkohan vaski-nextilläkin väärä käyttäjä? En eilen tallentanut osakohdetta vaan katselin vain mitkä tiedot kopioitui lomakkeelle. Nyt koitin tallentaa tietuetta niin tulee virhe 500 -ilmoitus,

Joo, ne oli siellä väärin. Korjasin, nyt voi kokeilla.

**Comment by AnneliO** [comment]
Testailin tätä siili-nextillä ja minusta kentät siirtyivät asetuksen mukaisesti emosta osakohteen 773-kenttään.

**Comment by LeenaKinnunen** [comment]
Lapissa ei ole tässä asetuksessa mitään tietoja, laitetaanko siihen siis samat kuin Vaarassa?

**Comment by pknuuti** [comment]
> Lapissa ei ole tässä asetuksessa mitään tietoja, laitetaanko siihen siis samat kuin Vaarassa?

Kannattaa laittaa, niin osakohteille tulee aineistotyypit.

**Comment by AnneliO** [comment]
Miepä pistän tähän vielä tekstinä tuon asetuksen sisällön:

```
001: 773$w
020$a: 773$z
022$a: 773$x
028$ba: 773$o
245$abnpc: 773$t
260$ab: 773$d
264$abc: 773$d
300$ae: 773$h
```

**Comment by AnneliO** [comment]
Dokumentoin asetuksen ja sen sisällön myös [Järjestelmäasetukset-sivulle](https://koha-suomi.fi/dokumentaatio/jarjestelmaasetukset/#preparehostfield).

**Comment by johannaraisa** [comment]
Tämä vaikuttaisi toimivan nexteillä, suljen tiketin.
