### ISSUE TITLE
Varauksen lainaaminen ei aina päivitä timestampia reserves-taulussa - ksdev/ks-0158-bug-37023-update-timestamp-when-filling-a-hold

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#53]
### Siirrettävä ominaisuus

Päivittää aikaleiman kun varaus nappaa kiinni ja siirtyy old_reserves-tauluun.

**Comment by johannaraisa** [comment]
Tämä on lisätty nexteille, testausta vaille valmista.

**Comment by ajrajala** [comment]
Tarkistettu vaski-nextillä, kun varaus lainattiin ja se siirtyi old_reserves-tauluun päivittyi sinne timestampiksi lainausajankohta.

**Comment by AnneliO** [comment]
Testaussuunnitelma:

1. Tee varaus ja palauta tietueeseen liittyvä nide, jotta varaus jää kiinni.
2. Tarkista raportilla, mikä on varauksen aikaleima: select timestamp from reserves where itemnumber=xxx and borrowernumber=xxx (itemnumber löytyy esim. osoiteriviltä, kun nidettä muokkaa. Asiakkaan borrowernumber löytyy osoiteriviltä, kun menee asiakkaan tietoihin.)
3. Lainaa nide asiakkaalle, jolle se on noudettavissa.
4. Tarkista raportilla, mikä on varauksen aikaleima: select timestamp from old_reserves where itemnumber=xxxx and borrowernumber=xxxx
5. Jos aikaleima on muuttunut varauksen lainausajankohdaksi, toimii korjaus.

**Comment by pknuuti** [comment]
Aikaleima päivittyy, kun testaa Annelin ohjeen mukaan.

**Comment by atarnus** [comment]
Testasin Outi-nextillä 5 niteellä, kaikkiin tuli old_reserves taulussa timestampiksi lainausajankohta.

**Comment by johannaraisa** [comment]
Hyvä juttu, suljen tiketin.
