### ISSUE TITLE
KSU - koha-suomi-utility

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#54]
### Siirrettävä ominaisuus

Testattava toimivatko utilityssä olevat työkalut uudessa ympäristössä.

**Comment by johannaraisa** [comment]
Tarkastetaan, että käytössä olevat cronit toimii. Muut hoidetaan kuntoon, kun niitä tarvitaan.

- [x] excess_login_attempts.pl
- [x] drop_borrower_ss_block.pl
- [x] manage_expired_accounts.pl
- [x] overdue_notices.pl
- [x] reset_failed_logins.pl
- [x] set_expirationdate_for_holds.pl
- [x] expire_holds.sh
- [x] remove_hold_fees.pl
- [x] cleanup-scripts/*

**Comment by johannaraisa** [comment]
Skriptit näyttäisivät toimivan kuten pitää, suljen tiketin.
