### ISSUE TITLE
KPOKM - koha-plugin-OKM-stats

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#56]
### Siirrettävä ominaisuus

Tilastoliitännäinen.

**Comment by emta001** [comment]
Testailin tätä omilla testeillä ja Siilissä. Vaikuttaisi toimivan oikein, ajelen kuitenkin kaikille bde-taulut ja tilastot muutaman tilaston, niin voitte testailla.

- [x] Siili
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [ ] Lastu
- [x] Vaara
- [x] Lappi
- [x] OUTI
- [x] Vaski

**Comment by emta001** [comment]
Taulut päivitetty ja rapsat ajettu (Vaskissa olikin vanhat tallella). Testailkaa, että aukeavat ja että rapsojen sisältö näyttää suht oikealta. 

Lastussa ei ollutkaan missään kannassa vielä asetuksia tälle plugarille tallennettuna, niin en pystynyt sinne ajamaan rapsoja. Jos haluatte testailla tätä, niin [täältä](https://koha-suomi.fi/dokumentaatio/raportit/#93-okm-tilastot) löytyy ohjeet käyttöönottoon. Miulta voi kysellä neuvoa jos tarvis.

**Comment by ajrajala** [comment]
Vaski-nextillä aukeaa ja luvut näyttää oikealta.

**Comment by pknuuti** [comment]
Vaaran nextillä raportti aukeaa, mutta numeroista en osaa sanoa mitään, kun kanta on redusoitu ja kesäkuussa ei varmaankaan kukaan ole testannut lainaamista.

**Comment by AnneliO** [comment]
Testailin siili-nextillä ja kaikki liitännäisen toiminnot tuntuisivat toimivan. Luvuista en minäkään osaa sanoa, ovatko ne oikein.

**Comment by emta001** [comment]
Toimii siis, suljen tiketin.
