### ISSUE TITLE
KPODUE - koha-plugin-overdue-tool

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#57]
### Siirrettävä ominaisuus

Laskutusliitännäinen.

**Comment by emta001** [comment]
Testailin omilla testeillä sekä vilkaisin hieman outi-nextillä tätä ja vaikuttaisi toimivan kuten pitää ilman muutoksia. Tässä kuitenkin testaamisen muistilista:
1. Pystyykö asetuksia tallentamaan ja säilyvätkö tallennetut asetukset?
2. Hakeeko työkalu laskutettavien listalle oikeat asiakkaat ja lainat?
3. Ovatko edellisten tiedot oikein?
4. Toimivatko filtterit (aikavälillä rajaus, asiakastyypillä rajaus jne.)?
5. Toimiiko Jäljennös-toiminnallisuus?
6. Onnistuuko laskun luominen OK?

**Comment by ajrajala** [comment]
1. OK, testasin yleisiä ja ryhmäasetuksia.
2. OK, hain TUPK:n laskutettavat ja availin parinkymmenen tiedot, kaikissa eräpäivät täsmäsivät laskutusväliin.
3. OK, eräpäivät, nidetunnus, nimeketiedot ja korvaushinta täsmäävät.
4. OK (aikavälirajaus, näytä laskutetut, asiakastyypillä rajaus, minimisumma).
5. OK, tiedot oikein, myös muutettu korvaushinta päivittyy jäljennökseen.
6. OK, sekä Luo Finvoice että Luo pdf-lasku muodostaa asiakkaalle (+takaajalle jos huollettava) rajoitteen, Ilmoitukset-välilehdellä näkyy muodostettu lasku ja siinä tiedot oikein.

**Comment by piiaseme** [comment]
OUTIssa kaikki kohdat testattu ja toimivat ongelmitta.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
