### ISSUE TITLE
KPREP - koha-plugin-report-services

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#58]
### Siirrettävä ominaisuus

Raportointipalvelu.

**Comment by emta001** [comment]
Liitännäiseen tehty [smartmatch-korjaus](https://github.com/KohaSuomi/koha-plugin-report-services/issues/5) ja viety nexteille testattavaksi.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii. Tällä hetkellä hakutuloksessa kolme tarkasteltavaa raporttia. Raporteista jokaisen saa avattua ja vietyä Exceliin.
![kuva](https://github.com/user-attachments/assets/a7f88920-c6ac-4f28-a71d-812162080275)

**Comment by LeenaKinnunen** [comment]
Toimii myös Lapissa : kolme raporttia, jotka saa auki ja vietyä Exceliin.

**Comment by lmstrand** [comment]
Kiitos testeistä, tämä ok.

**Comment by emta001** [comment]
Tässä on nyt taidettu testata OKM-plugarin toimivuutta? Siitä on ollut oma tikettinsä #56. Tämä tiketti koskee rajapintaa, jolla voi lähettää Koha raportteja esim. PowerBI:hin ja tätä ei ole vielä testattu sen kummemmin. Avaan tiketin uudestaan.

**Comment by lmstrand** [comment]
Testattu Vaski-nextillä ok.
