### ISSUE TITLE
Kohan itsepalvelun palautus-toiminto - ksdev/ks-0020-K22-57-SCOreturns

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#6]
Koha-Suomen versio itsepalvelun palautus-toiminnosta.

**Comment by AnneliO** [comment]
Yritin palauttaa niteen 564N23299971 outi-nextillä (https://outi-next.koha-suomi.fi/cgi-bin/koha/sco/sco-main.pl), mutta sain virheilmoituksen 

Sorry, the requested page is not available
Error 403

This message can have the following reason(s):

    An unexpected error occurred while processing your request.

**Comment by AnneliO** [comment]
Huomioita:

Kumpikin boksi on nyt saman värinen, vaikka ne on määritetty SCOUserCSS-asetuksessa aiemmin eri värisiksi:
![kuva](https://github.com/user-attachments/assets/4a5bf9fa-7a78-4d50-80b4-90f6e4cf257d)
Ilmeisesti niillä on nyt sama "tunniste".

Aloitussivu tyhjeni aiemmin ehkäpä n. 20 s kuluttua viimeisimmästä palautuksesta, jotta sivulle ei jäänyt näkyviin edellisen asiakkaan palautukset (tietoturva-asia). Nyt se ei tuntuisi sitä enää tekevän, vaan näkyville jää tällainen näkymä:

![kuva](https://github.com/user-attachments/assets/e64419bd-851c-45c4-93fa-cda0e429e276)

Noin muuten palautus tuntuisi toimivan ja mitä vilkaisin nopeasti lainauspuolelle, niin sielläkin näytti toimivan

**Comment by emta001** [comment]
Tiedon palautuksesta tulisi nyt tyhjentyä oikein, olin käyttänyt väärää muuttujaa ehtolauseessa ja tyhjennyksestä vastaava funktio ei käynnistynyt.

Laatikoihin on nyt lisätty molempiin omat id:t, **_sco_entry_checkin_** ja **_sco_entry_checkout_**. Jotta värit tms. toimisi oikein, pitää itesepalvelun CSS-rimpsuun tehdä muutoksia.

**Comment by AnneliO** [comment]
Tiedot tyhjenee nyt oikein.

Uudet id:tkin sain toimimaan, mutta ne on lipsahtanut nyt väärin päin. Checkin on id:nä checkout ja Checkout on id:nä checkin. Ihmettelin tovin, miksi värit menevät nyt jotenkin hassusti, kunnes hoksasin tarkistaa tuon. :D

Näillä saa värit taas paikoilleen:
```
div#sco_entry_checkout.sco_entry.col {
  max-width: 500px;
  background-color: #b8eaff;
  margin: 25px 25px 55px 55px;
  padding: 25px 25px 25px 25px;
  -webkit-border-radius: 10px;
-moz-border-radius: 10px;
border-radius: 10px;
-webkit-box-shadow: 5px 5px 7px 0px rgba(0,0,0,0.35); 
box-shadow: 5px 5px 7px 0px rgba(0,0,0,0.35);
}


div#sco_entry_checkin.sco_entry.col {
  max-width: 500px;
  background-color: #8fe67e;
  margin: 25px 25px 55px 55px;
  padding: 25px 25px 25px 25px;
  -webkit-border-radius: 10px;
-moz-border-radius: 10px;
border-radius: 10px;
-webkit-box-shadow: 5px 5px 7px 0px rgba(0,0,0,0.35); 
box-shadow: 5px 5px 7px 0px rgba(0,0,0,0.35);
}
```
Toinen h4-otsikkotason fonttikoon määritys on jatkossa tarpeeton ja tämä riittää:
```
.sco_entry.col h4 {
 font-size: 25px;
 color: black;
}
```

**Comment by emta001** [comment]
Höm, kävin korjaamassa nuo id:t oikeille paikoilleen. Ihme aivopiereskelyä taas ilmassa :sweat_smile:

**Comment by Kati-Helle** [comment]
Helle-nextissä Lainaus-toiminnon kirjautumiskentät asettuvat nyt näin
![kuva](https://github.com/user-attachments/assets/566e3451-0fd8-4136-a716-d6304d7e2433)


Tuotannossa kaikkien kieliversioiden tyylinä tämä
![kuva](https://github.com/user-attachments/assets/ee1ba2f8-a2a6-411e-9bfb-aa09ed642438)

**Comment by AnneliO** [comment]
Säätelin outi-nextillä, vaara-nextillä ja helle-nextillä SCOUserCSS-asetusta juuri tuossa hiljattain ja pistin ne nyt tänne: https://github.com/KohaSuomi/Koha-24.05/wiki/SCOUserCSS

Ne kannattaa kuitenkin käydä vielä läpi, koska en ollut kaikista varma, miksi ne on lisätty ja ovatko ne tarpeellisia vielä.

**Comment by AnneliO** [comment]
Nextillä ja tuotannossa on sinänsä samat ulkoasumääritykset, joten en osaa sanoa, miksi kirjautumisrivit asettuvat eri tavalla tuotannossa ja nextillä.

**Comment by emta001** [comment]
> Nextillä ja tuotannossa on sinänsä samat ulkoasumääritykset, joten en osaa sanoa, miksi kirjautumisrivit asettuvat eri tavalla tuotannossa ja nextillä.

Voipi olla miun säädöistä kiinni. Muistelisin, että ne menee tuollee peräkanaa yhteisön versiossa ja päätin antaa niiden olla. Mutta kun suomeksi nuo tekstit on sitten vähän pidempiä, niin ne ei enää mahdu siististi vierekkäin.

**Comment by pirliis** [comment]
Testasin myös OUTIssa: lainaus, palautus ja lainojen uusinta näyttäisi toimivan.

Ainoastaan käännökset vielä puuttuvat palautusboksista:
![image](https://github.com/user-attachments/assets/1d71a7c3-49aa-40ec-898e-2b0683e838c1)


ja palautetun niteen näkymästä: 
![image](https://github.com/user-attachments/assets/4acabf7b-5fcc-4916-9fa7-4d90d034165b)

**Comment by AnneliO** [comment]
Tiketissä #127 voi seurata Koha-Suomen käännösten etenemistä (eivät ihan vielä etene, koska keskeneräisiä ominaisuuksia kuten tiedonhaun näyttöjen xslt:t).

**Comment by AnneliO** [comment]
> Tiketissä [#127](https://github.com/KohaSuomi/Koha-24.05/issues/127) voi seurata Koha-Suomen käännösten etenemistä (eivät ihan vielä etene, koska keskeneräisiä ominaisuuksia kuten tiedonhaun näyttöjen xslt:t).

Käännökset ovat nyt testattavissa.

**Comment by pirliis** [comment]
OUTIn nextin itsepalvelutoiminnossa käännökset näyttäisivät olevan ok.

**Comment by emta001** [comment]
En välttämättä kerkeä säätämään tuon kirjautumislaatikon asetteluita ennen versionvaihtoa, yritän tehdä sen mahdollisimman pian versionvaihdon jälkeen.

**Comment by lmstrand** [comment]
Vaara-nextin SCOuserCSS:iä voi kokeilla, niiden kanssa laatikot näyttävät tältä omassa selaimessani:

![image](https://github.com/user-attachments/assets/dd10e376-7723-4bcf-98d2-13748143cc0b)

**Comment by lmstrand** [comment]
Vaaran SCOUserCSS kokonaisuudessaan:

```
.navbar {
	display: none;
}


/*
#opacheader {
	display: none;
}
*/

/* Lainaus-boksin ulkoasumuutokset */
div#sco_entry_checkout.sco_entry.col {
  background-color: rgb(81, 163, 226);
  margin: 25px 25px 55px 55px;
  padding: 25px 25px 25px 25px;
  -webkit-border-radius: 10px;
-moz-border-radius: 10px;
border-radius: 10px;
-webkit-box-shadow: 5px 5px 7px 0px rgba(0,0,0,0.35); 
box-shadow: 5px 5px 7px 0px rgba(0,0,0,0.35);
}

.sco_entry.col-5 h4 {
 font-size: 25px;
 color: darkslategrey;
}


/* Palautus-boksin ulkoasumuutokset */
div#sco_entry_checkin.sco_entry.col {
  background-color: rgb(179, 222, 122);
  margin: 25px 25px 55px 55px;
  padding: 25px 25px 25px 25px;
  -webkit-border-radius: 10px;
-moz-border-radius: 10px;
border-radius: 10px;
-webkit-box-shadow: 5px 5px 7px 0px rgba(0,0,0,0.35); 
box-shadow: 5px 5px 7px 0px rgba(0,0,0,0.35);
}

.sco_entry.col h4 {
 font-size: 25px;
 color: darkslategrey;
}


/* Lainaa tai uusi nide -boksin ulkoasumuutokset */
#newcheckout {
  background-color: rgb(81, 163, 226);
  max-width: 650px;
  padding: 25px 25px 25px 25px;
  -webkit-border-radius: 5px;
-moz-border-radius: 5px;
border-radius: 5px;
-webkit-box-shadow: 5px 5px 7px 0px rgba(0,0,0,0.35); 
box-shadow: 5px 5px 7px 0px rgba(0,0,0,0.35);
}

/* Lainaa tai uusi nide -boksin otsikon väri ja koko */
.sco_entry h2 {
 font-size: 25px;
 color: darkslategrey;
}

/* Piilota Maksut-välilehti */
#account {
 display: none;
}


/* ? 
label {

  white-space:nowrap;
}
*/

/* ?
#uibarcode {
  			
            width: 116%;
  
        }

*/

/* Olet kirjautunut sisään.. -boksin taustaväri */
.alert.alert-info {
  			background-color:rgb(15, 241, 111);

  
        }

/*  .alert.alert-info::after {content: "  Kirjautumisen jälkeen istunto katkaistaan 40 sekunnin kuluttua. Kirjaudu sisään uudelleen tarvittaessa.";}



/* Piilota Kopioi-, Tulosta- ja CSV-napit */

body#sco_main.sco button.dt-button.buttons-copy.buttons-html5, button.dt-button.buttons-csv.buttons-html5, button.dt-button.buttons-print { display: none; }

```

**Comment by emta001** [comment]
Jesh, kannattanee tosiaan ottaa käyttöön tuo Larin laittama rimpsu.

**Comment by lmstrand** [comment]
Tuossa on mukana Vaaran huomautus 40 sekunnin aikakatkaisusta joka pitää jättää pois/muokata kimpan asetuksen mukaiseksi ainakin.

**Comment by AnneliO** [comment]
Onko tässä tiketissä vielä jotain kesken vai voisiko sen sulkea?

**Comment by pirliis** [comment]
Tämän voi varmaan sulkea. OUTIssa olemme päättäneet, että käytämme meillä ennestään käytössä ollutta CSS-rimpsua. Suljen siis.
