### ISSUE TITLE
KPCPU - koha-plugin-ceepos-integration

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#60]
### Siirrettävä ominaisuus

Koha-Ceepos-liitännäinen.

**Comment by johannaraisa** [comment]
OUTIn nextillä pitäisi olla kaikki valmiina testausta varten yksikölle OUUL, eikun kokeilemaan.

**Comment by pirliis** [comment]
OUTIn nextillä testattu, että maksurajapinta Kohasta Ceeposiin toimii ja maksetun maksun kuittaus Ceeposista Kohaan toimii.

Mutta Maksa maksuja -välilehden Ceeposmaksu-painikkeet näkyvät nextillä tuplana ja Ceeposmaksu-painike ei mene epäaktiiviseksi maksun lähetyksen jälkeen, vaan saman maksun saattoi lähettää Ceeposiin monta kertaa.

![image](https://github.com/user-attachments/assets/0d7bfffb-0e8a-4590-94bd-09b3335cfcd5)

**Comment by johannaraisa** [comment]
Hmm, minulla näkyi vain yksi nappi ja siinä teksti oli "Ceepos-maksu". Tää voi olla välimuisti- tai käännöstiedostojuttu, pitää tutkia. Hyvä kuitenkin, että se maksu meni läpi.

**Comment by pirliis** [comment]
Kun päivitin sivua, niin nyt painikkeet näkyvät nextillä näin eli jotain tapahtui. :)

![image](https://github.com/user-attachments/assets/5a4c680d-fa6b-4188-919e-f5d0fe0ae6bd)

Tuotannossa näkymä näin:

![image](https://github.com/user-attachments/assets/40889d1b-ba23-4413-9ee8-40e8039f3b6b)

**Comment by johannaraisa** [comment]
Minulla näkyy nextillä näin. Kokeilitko sitä ctrl+f5?

![image](https://github.com/user-attachments/assets/8e30ab29-e2ff-478a-9bb6-596d65072a7e)

**Comment by johannaraisa** [comment]
Tuo on siis eri sivu, menin siitä rivin Maksa-napista.

**Comment by pirliis** [comment]
Joo, päivittelin ctrl+f5:lla. 
Mutta tosiaan, sivut ovat erit riippuen mistä menee Maksa maksuja -välilehdelle. 

Jos valitsee maksurivin kohdalta yhden maksun Maksa-painikkeella, menee samaan kuin sinulla, jossa yksi Ceepos-maksu-painike, mutta jos käyttää Maksa valitut -painiketta, Maksa maksuja -välilehdellä on kaksi Ceepos-maksu -painiketta.

Tuotannossa molempien painikkeiden takana yksi Ceeposmaku-painike.

**Comment by johannaraisa** [comment]
Ahh, sinne on piilotettu 24.05 versiossa ylimääräisiä kenttiä, joten tuossa se luo kaksi kertaa sen napin.

**Comment by johannaraisa** [comment]
Nyt se toinen nappi pitäisi olla kadonnut, vaatii sivun latauksen ctrl+f5:llä.

**Comment by pirliis** [comment]
> Nyt se toinen nappi pitäisi olla kadonnut, vaatii sivun latauksen ctrl+f5:llä.

Nyt näkyy vain yksi Ceepos-maksu -painike ja toimii kuin pitääkin.

**Comment by johannaraisa** [comment]
Jees, eiköhän tämä ole kunnossa, suljen tiketin.

**Comment by pirliis** [comment]
Sellainen huomio vielä, kun menee maksurivin kohdalta Maksa-painikkeella maksusivulle ja ei valitse kassaa ennen maksun lähettämistä Ceeposiin, ilmoituksen _Maksu lähetetty, käsittele kassassa!_ kuittauksen jälkeen ohjelma heittää sivulle: 
https://outi-next.koha-suomi.fi/cgi-bin/koha/circ/circulation.pl?borrowernumber=undefined


> Jees, eiköhän tämä ole kunnossa, suljen tiketin.

Ei vielä. Odota, niin raportoin. :)

**Comment by pirliis** [comment]
Kun menee maksurivin kohdalta Maksa-painikkeella maksusivulle, eikä valitse kassaa ennen kuin lähettää maksun Ceeposiin, ilmoituksen "Maksu lähetetty, käsittele kassassa!" kuittauksen jälkeen ohjelma nakkaa sivulle: 
https://outi-next.koha-suomi.fi/cgi-bin/koha/circ/circulation.pl?borrowernumber=undefined

Kun maksusivulle menee Maksa valitut -painikkeen kautta, eikä valitse kassaa, tulee oikein ilmoitus:

![image](https://github.com/user-attachments/assets/c093ce14-405f-47ae-9b8b-ff01dde41f19)

**Comment by johannaraisa** [comment]
Lisäsin korjauksen kokeile nyt, taas ctrl+f5.

**Comment by pirliis** [comment]
Nyt näyttää toimivan kuin pitääkin eli tulee ilmoitus, eikä nakkaa tyhjälle sivulle.

Lisäsin nextille yhden Kassun tekemän intranetusercss-rimpsun, joka piilottaa maksusivulta Poista-linkin, jolla käyttäjä pystyi poistamaan maksun, jonka oli lähettänyt Kohasta Ceeposiin. Piilotus toimii. Sama rimpsu meillä on myös tuotannossa.

**Comment by johannaraisa** [comment]
Voidaanko nyt todeta, että toimii ja suljetaan tiketti? :smile:

**Comment by pirliis** [comment]
Kyllä voidaan ja toivotaan parasta, että toimii myös tuotannossa. :D
