### ISSUE TITLE
KPEDX - koha-plugin-editx

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#65]
### Siirrettävä ominaisuus

EDItX-sanomia käsittelevä liitännäinen.

**Comment by lmstrand** [comment]
Testattu vaara-nextillä (testi4.xml). Toimii. Uutena herjana GetMarcFromKohaField: framework parameter has been obsoleted for long at /home/koha/Koha/C4/Biblio.pm line 1212. Eli jossain versionvaihdossa tuo pitää korvata jollain, kun metodi poistetaan yhteisössä.
