### ISSUE TITLE
KPVLT - koha-plugin-visual-label-tool

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#66]
### Siirrettävä ominaisuus

Tarratyökalu.

**Comment by emta001** [comment]
Kävin vaski-nextillä vilkaisemassa tätä ja liitännäinen vaikuttaisi ainakin käynnistyvän ilman herjoja. En sen tarkemmin kokeillut esim. tarran luomista, mutta tän pitäs olla testattavissa.

**Comment by MikkoLiimatainen** [comment]
En huomannut ongelmia liitännäisen toiminnassa. Tarrat pystyy luomaan ja tulostamaan. Testasin myös tarrapohjan muokkaamista ja sekin onnistui.

**Comment by pirliis** [comment]
OUTIn nextillä tarrapohjien muokkaus ja tulostus näyttäisi toimivan.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
