### ISSUE TITLE
KPBB - koha-plugin-broadcast-biblios

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#68]
### Siirrettävä ominaisuus

Broadcast biblios via REST.

**Comment by johannaraisa** [comment]
Testasin OUTI nextillä ja Täti nextillä valutusta ja tietueet liikkuivat kuten piti. Jätin cronit pyörimään, katselen miten päivityksiä tulee.

**Comment by johannaraisa** [comment]
Testasin Melindaan viennin ja sekin toimii.

**Comment by johannaraisa** [comment]
Tämä on toiminut kuten pitää, suljen tiketin.
