### ISSUE TITLE
Asiakastiedot: huollettavan muokkausnäytöllä ei näy kirjastokortittomasta huoltajasta/takaajasta mitään tietoja  -  ksdev/ks-0021-bug-29768-hidepatronname 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#7]
Hidepatronname-järjestelmäasetus piilottaa takaajan tiedot täysin, jos tällä ei ole kirjastokorttia. Tällä muutoksella tuodaan huoltajan nimi näkyville.

**Comment by emta001** [comment]
Testaussuunnitelemat:

Muokkauksessa:
1. Etsi huollettava jonka takaajalla ei ole kirjastokorttia.
2. Muokkaa huollettavaa.
=> Tarkista, että takaajan nimi näkyy oikein.

Varauksen haku asiakkaalle:
1. Tee asiakkaalle varaus tämän Perustiedot-näytön kautta (paina Hae ja varaa).
2. Tee haku.
3. Avaa "Varaa"-napin kautta aukeava alasvetovalikko.
=> Tarkista, että linkki "Varaa asiakkaalle..." toimii oikein.

**Comment by Kati-Helle** [comment]
Helle-nextissä huollettavan Merikeiju Tassimenyylä muokkausnäytöllä näkyy kirjastokortittoman takaajan nimi oikein
![kuva](https://github.com/KohaSuomi/Koha-24.05/assets/99952449/b2c6dd65-fca1-4d0f-b576-413cb329bcf7)

Asiakastiedon Hae ja varaa -toimintolinkki toimii oikein kirjastokortittoman takaajan huollettavalla tietueen perustiedot näytöllä
![kuva](https://github.com/KohaSuomi/Koha-24.05/assets/99952449/438fe228-1555-495a-b481-741d509fe235)

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii myös vastaava asiakkaan tiedoista aloitettu varaustapa hakutulosnäytön Varaa-painikkeesta, kun hakutuloksesta valitaan varattava/varattavat niteet 
![kuva](https://github.com/KohaSuomi/Koha-24.05/assets/99952449/fc14bdb1-e071-4fb4-b1bc-8e03cef29f9e)

**Comment by atarnus** [comment]
Outi-Nextillä näkyy samalla tavalla kuin Hellessä, mutta minulle jäi kyllä nyt vähän kysymykseksi, että miten tämä asia liittyy tuohon asetukseen? Se on vahingossa piilottanut ylimääräistä? Mutta miten saa näkymään sen virheen, joka tässä on nyt korjattu? Missä versiossa se on tullut?

Ja miten tuo takaajan näkyminen nyt liittyy tähän taattavan varaukseen? Ei kai siinä kuulu takaajaa missään välissä näkyäkään? Oliko sieltäkin kadonnut jotain? Onko tästä toinen tiketti tai keskustelu, jossa bugia on avattu enemmän?

**Comment by emta001** [comment]
> Outi-Nextillä näkyy samalla tavalla kuin Hellessä, mutta minulle jäi kyllä nyt vähän kysymykseksi, että miten tämä asia liittyy tuohon asetukseen? Se on vahingossa piilottanut ylimääräistä? Mutta miten saa näkymään sen virheen, joka tässä on nyt korjattu? Missä versiossa se on tullut?
> 
> Ja miten tuo takaajan näkyminen nyt liittyy tähän taattavan varaukseen? Ei kai siinä kuulu takaajaa missään välissä näkyäkään? Oliko sieltäkin kadonnut jotain? Onko tästä toinen tiketti tai keskustelu, jossa bugia on avattu enemmän?

Tämä siis liittyy tuohon "Varaa asiakkaalle"-toimintoon niin, että korjaus tekee muutoksia patron-title.inciin ja kuinka siellä käytetään parametriä no_html. Tämä aiheuttaa sen, että "Varaa asiakkaalle", joka on oikeastaan vain linkki asiakkaan tietoihin, meni keskeltä poikki. Tästä oli [tiketti](https://github.com/KohaSuomi/Koha-22x/issues/122) jo versioon 22 siirryttäessä, siinä on kuvailtu tarkemmin mitä tuossa tapahtui. Varsinaisesti ongelma ei siis liity takaaja-taattava-skenaarioon ollenkaan, vaan siihen että sen korjaaminen aiheutti sitten toisen bugin :sweat_smile:

**Comment by ajrajala** [comment]
Vaski-nextilläkin toimii testaussuunnitelman mukaisesti.

**Comment by emta001** [comment]
Toimii, siispä suljen tiketin.
