### ISSUE TITLE
KPPDF - koha-plugin-print-pdf-notices

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#72]
### Siirrettävä ominaisuus

Koha plugin for printing notices.

**Comment by emta001** [comment]
Testailin omassa testiympäristössä tätä ja vaikuttaisi toimivan ilman sen kummempia muutoksia. Tätä voi siis testata testeillä:

Tsekkilista tälle:
1. Onko plugin ulkoasu kunnossa?
2. Haetaanko tulostuslistalle oikeat viestit?
3. Suodattuvatko viestit oikein?
4. Onnistuuko viestin avaaminen tulosta-painikkeesta?
5. Onko viestin sisältö oikein?
6. Saako viestin tulostettua?
7. Saako viestin peruttua?

**Comment by Kati-Helle** [comment]
Helle-nextissä testasin noutoilmoituksilla. Toimii!

x    Onko plugin ulkoasu kunnossa?
x    Haetaanko tulostuslistalle oikeat viestit?
x    Suodattuvatko viestit oikein?
x    Onnistuuko viestin avaaminen tulosta-painikkeesta?
x    Onko viestin sisältö oikein?
x    Saako viestin tulostettua?
x    Saako viestin peruttua?

**Comment by ReettaSiili** [comment]
Myös Siili-nextissä tsekkilista kunnossa noutoilmoituksilla. Suodattuvat edelleen asiakkaan kotikirjaston mukaan mutta ainakaan meillä tämä ei ole ongelma. Kahdentumisongelma näyttäisi vaivaavan edelleen [tiketti](https://github.com/KohaSuomi/koha-plugin-print-pdf-notices/issues/3). Myöhästymisilmoitusten croni ei varmaan ole päällä kun ne eivät ole muodostuneet.

**Comment by emta001** [comment]
Testausten perusteella toimii, suljen tiketin.
