### ISSUE TITLE
KPDELC - koha-plugin-delete-biblio-components

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#73]
### Siirrettävä ominaisuus

Osakohteiden poistoliitännäinen.

**Comment by emta001** [comment]
Testailin omilla testeilläni ja vaikuttaisi toimivan kuten pitääkin.

**Comment by piiaseme** [comment]
OUTIssa testattu ja vaikuttaa toimivan oikein.

**Comment by MikkoLiimatainen** [comment]
Vaskissakin testattu ja minusta näyttää toimivan oikein.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii.

**Comment by emta001** [comment]
Toimii siis, suljen tiketin.
