### ISSUE TITLE
KPSMSL - koha-plugin-sms-send-link-mobility-driver 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#74]
### Siirrettävä ominaisuus

Koha plugin for sending SMS messages via Link Mobility.

**Comment by johannaraisa** [comment]
Otan tämä, koska rajapinta muuttuu ja se pitää tehdä uudestaan.

**Comment by johannaraisa** [comment]
Nykyinen versio toimii nextillä, suljen tiketin.
