### ISSUE TITLE
Hyllyvaraukset-raportti - ksdev/ks-0022-K23-12-pendingreserves

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#8]
Koha-Suomen oma versio hyllyvaraus-raportista.

**Comment by lmstrand** [comment]
Testattavana nexteillä. Osassa kimppojen nextejä ei ole holds-to-pull -ajo välttämättä käynnissä.

**Comment by Kati-Helle** [comment]
Helle-nextissä toiminnassa ja toimii. 
![kuva](https://github.com/KohaSuomi/Koha-24.05/assets/99952449/edb62dec-70c2-49b2-a82b-5bf36687423d)

**Comment by MikkoLiimatainen** [comment]
Vaski-nextillä hyllyvarausraportti toimii

**Comment by pknuuti** [comment]
Vaaran nextillä hyllyvarausraportti toimii myös.

**Comment by pirliis** [comment]
OUTIn nextillä holds-to-pull -ajo ei taida olla päällä, kun hyllyvarausraportti ei anna mitään tuloksia.

**Comment by emta001** [comment]
> OUTIn nextillä holds-to-pull -ajo ei taida olla päällä, kun hyllyvarausraportti ei anna mitään tuloksia.

Nyt on päällä.

**Comment by pirliis** [comment]
OUTIn nextillä hyllyvarausraportti näyttäisi muutoin toimivalta, mutta jos tietueessa on useampi kuin yksi voimassa olevia varaus, se katoaa raportilta, kun raportti päivittyy.

Esim. teokset, joista on saatavana olevia niteitä ja voimassa olevia varauksia enempi kuin yksi:
https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2256373
https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2235580
https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2329007
https://outi-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=2328192

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä palauttamalla yhden hyllyvarauksen nimekkeestä, jossa oli useampia varauksia. Kun palasin takaisin hyllyvarauslistalle, edelleen sama nimeke oli listalla. Mutta kun päivitin sivun uudelleen, nimeke ei ollut listalla ja taas uudelleen päivitys, nimeke oli jälleen listalla. Järjestin tietueet nimekkeen mukaan, olisikohan tuolla järjestyksellä ollut jotain tekemistä asian kanssa?

**Comment by pirliis** [comment]
> Testasin Vaaran nextillä palauttamalla yhden hyllyvarauksen nimekkeestä, jossa oli useampia varauksia. Kun palasin takaisin hyllyvarauslistalle, edelleen sama nimeke oli listalla. Mutta kun päivitin sivun uudelleen, nimeke ei ollut listalla ja taas uudelleen päivitys, nimeke oli jälleen listalla. Järjestin tietueet nimekkeen mukaan, olisikohan tuolla järjestyksellä ollut jotain tekemistä asian kanssa?

Kiitos Päivi hoksautuksesta. Raportille tulevat teokset järjestyvät oletuksena (ennen kuin on tehnyt enempi rajauksia) niin, että ensimmäisenä listalle tulevat varaukset, joista on yksi varaus ja listan loppupäähän, jos varauksia on enempi. En hoksannut tuota ja sieltä listan loppupäästä ne teokset löytyvät riippuen kuinka monta varausta niissä on. :) 

Itse oletin, että kaikkien varausten oletusjärjestys on teoksen nimen mukaan aakkosissa riippumatta kuinka monta varausta siinä on kiinni. 

Käytännössä rajauksia tehdään aina useampia, joten luulenpa, ettei tämä ole ongelma. Näin näyttää olevan tuotannossakin.

**Comment by LeenaKinnunen** [comment]
Lapissa hyllyvarauslista toimii ja päivittyy oikein.
