### ISSUE TITLE
HT - host-tools

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#80]
### Siirrettävä ominaisuus

Edustanodejen hallintatyökalut.

**Comment by CodoDerDritte** [comment]
Edustanodejen hallintatyökalut siirrettiin taannoisessa tiedostojärjestelmäremontissa uuteen sijaintiin ja päivitettiin käyttämään uutta OCFS:ää. Linkitykset nodejen /usr/local/(s)bin:issä on päivitetty osoittamaan uuteen sijaintiin lukuunottamatta backup-health-checkiä, joka on muutenkin työn alla.

**Comment by CodoDerDritte** [comment]
Nyt myös pushattu githubiin.
