### ISSUE TITLE
KPAFC - koha-plugin-auto-framework-code

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#84]
### Siirrettävä ominaisuus

Automatically set framework code for a record.

**Comment by piiaseme** [comment]
Voiko tätä vielä testata? OUTIn nextillä tähän mennessä kaikki testaamani tietueet ovat avautuneet nextillä Oletuspohjalle vaikka niiden olisi pitänyt tulla mm. kirjana, lehtenä tai CD-levynä. 

OUTIn nextillä on samat määrittelyt kuin tuotannossa.

**Comment by AnneliO** [comment]
Tämä ei ole vielä testattavissa. Pasi tekee tämän valmiiksi, kun hän palailee lomalta.
