### ISSUE TITLE
IntranetUserJS: KPJSCRL - koha-plugin-intranetjs-checkout-report-link

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#86]
### Siirrettävä ominaisuus

Lisää linkin Lainaukset-raporttiin tietueen Tiedot-näytölle.

**Comment by Rvallim0** [comment]
Vaski nextillä testattu, Lainatilasto-nappi löytyy ja avaa "Tietueen niteiden laina- ja uusintamäärät" raportin tulokset sille tietueelle, eli toimii.

**Comment by pknuuti** [comment]
Vaaran nextilläkin toimii kuten Vaskilla.

**Comment by lmstrand** [comment]
Kiitos testeistä.

**Comment by LeenaKinnunen** [comment]
Lapissa linkki löytyy tietuenäytöltä, mutta ei avaa raporttia. Jos hakee raporttien (raportti id 559) kautta tietueen lainamäärät, raportti kyllä toimii. Testattu nextin tietueella biblionumber=1409334
EDIT: toimii, kun lisäsin määrittelyyn oikean raporttinumeron.

**Comment by lmstrand** [comment]
> Lapissa linkki löytyy tietuenäytöltä, mutta ei avaa raporttia. Jos hakee raporttien (raportti id 559) kautta tietueen lainamäärät, raportti kyllä toimii. Testattu nextin tietueella biblionumber=1409334

Teiltä puuttuu nextiltä pluginin määrittelystä raportin numero, joka pitäisi aukaista.

![image](https://github.com/user-attachments/assets/f9a92845-4a67-42a2-93bc-2b57278f01af)

**Comment by AnneliO** [comment]
Seuranta kimpoista, joissa liitännäinenon otettu käyttöön nextillä. Kommentoi tikettiä, kun asia kunnossa omassa kimpassa.

- [x] Lappi
- [x] OUTI
- [x] Siili
- [x] Vaara
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [x] Lastu
- [x] Vaski

**Comment by Tuomas-Kyyti** [comment]
Kyytin nextillä käytössä.

**Comment by pknuuti** [comment]
Vaaran nextillä käytössä.

**Comment by piiaseme** [comment]
OUTIn nextillä käytössä ja toimii.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii.

**Comment by Rvallim0** [comment]
Vaski nextillä käytössä ja toimii

**Comment by LastuJanneS** [comment]
Lastussa myös käytössä ja toimii.

**Comment by PiaKusmin** [comment]
Lapin nextillä toimii.

**Comment by ElinaUotila** [comment]
Olen näköjään unohtanut kommentoida. Tämä on Kirkesissä kunnossa :)

**Comment by ReettaSiili** [comment]
Myös Siilissä kunnossa.

**Comment by Hanna-Lumme** [comment]
Lumpeissa kunnossa myös.

**Comment by AnneliO** [comment]
Kaikki kimpat ovat kuitanneet, joten suljen tiketin. :)
