### ISSUE TITLE
KPJSHKV - koha-plugin-intranetjs-haku-kenttien-viiveet

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#88]
### Siirrettävä ominaisuus

Pienentää viivettä Kohan hakukentissä.

**Comment by lmstrand** [comment]
Tätä ei ilmeisesti tarvita enää, Taulukkojen Haku-kentissä ei esiinny tökkimistä ja ne toimivat oikein, samoin kuin sarakkeiden filtteröinti. Myöskään Koha-Suomen hyllyvarauslistalla en huomaa tökkimistä, mutta voitaisiin testata tämä useammilla koneilla(kokoonpanoilla/selaimilla?) vielä. Laitan siis statuksen testattavaksi.

**Comment by lmstrand** [comment]
Haku-kentät siis hankinnan puolella vastaanotossa taulukossa, asiakashaussa ja hyllyvarauslistalla https://github.com/KohaSuomi/Koha/issues/826.

**Comment by MikkoLiimatainen** [comment]
Saan nyt nextillä liitännäisiin mennessä virheen "Jotain meni pieleen taulua ladatessa" ja Koha::Plugin::Fi::KohaSuomi::HakuKenttienViiveet-plugarin kohdalla lukee, että liitännäisen lataamisessa tapahtui virhe.

**Comment by lmstrand** [comment]
> Saan nyt nextillä liitännäisiin mennessä virheen "Jotain meni pieleen taulua ladatessa" ja Koha::Plugin::Fi::KohaSuomi::HakuKenttienViiveet-plugarin kohdalla lukee, että liitännäisen lataamisessa tapahtui virhe.

Kävin poistamassa pluginin tietokantaan jääneet tiedot. Nyt ei enää herjaa.

**Comment by MikkoLiimatainen** [comment]
En kyllä huomaa hakukenttien toiminnassa enää ongelmia. En havainnut kirjainten tipahtelua, enkä virheellisiä tuloksia. Tarvitaan varmaan joku nopeampisorminen testaaja vielä.

Jotain hakujen kohdistuksiin liittyviä ongelmia, kuten tietuesivun haun kyvyttömyys hakea kirjaston nimeä, vaikuttaisi tulleen, mutta ne varmaan tarvitsevat oman tikettinsä.

**Comment by ajrajala** [comment]
Kohtalaisen nopeasormisena ja aiemmin herkästi tämän ongelman havainneena testasin tätä ja vaikuttaa nyt tosiaan toimivan hyvin. 👍

**Comment by lmstrand** [comment]
Poistetaan tämä käytöstä ja Githubista. Säilyttelen pluginia vielä omalla koneellani kaiken varalta.
