### ISSUE TITLE
Palautuskehotusmaksun määrittely - ksdev/ks-0023-K23-13-overdue-notice-fines

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#9]
Myöhästymisilmoitusten määrittely -sivulla voi määrittää asiakastyyppikohtaisesti, mikä summa asiakkaalta veloitetaan palautuskehotuksen lähettämisestä. Maksun voi määrittää erikseen 1.-3. ilmoitukselle.

Tämä on riippuvainen overdue_notices.pl cron jobista.

**Comment by emta001** [comment]
Testattavana nexteillä. Tarkistakaa, että palautuskehotusmaksun pystyy määrittelemään ja se tallentuu oikein. Vaatii lisäksi overdue_notices.pl cronin ajamisen, kommentoikaa alle jos haluatte sen päälle testausta varten.

**Comment by ajrajala** [comment]
Maksun saa määritettyä ja se tallentuu. Huomiona ihan kaiken varalta, että desimaaleja käyttäessä erottimena pitää käyttää pistettä, pilkkua käytettäessä tallentuu hinta ilman desimaaleja (1,50 -> 1). Mutta tämä on siis ollut näin aiemminkin.

Voin testata palautuskehotusmaksun muodostumisen, jos laitat vaski-nextille cronin päälle.

**Comment by emta001** [comment]
> Maksun saa määritettyä ja se tallentuu. Huomiona ihan kaiken varalta, että desimaaleja käyttäessä erottimena pitää käyttää pistettä, pilkkua käytettäessä tallentuu hinta ilman desimaaleja (1,50 -> 1). Mutta tämä on siis ollut näin aiemminkin.
> 
> Voin testata palautuskehotusmaksun muodostumisen, jos laitat vaski-nextille cronin päälle.

Se olikin jo näköjään päällä (ehkä edellisen versionvaihdon jäljiltä). Pyörähtää käyntiin aamuisin klo 9.

**Comment by ajrajala** [comment]
Tarkistin maksujen muodostumisen tänään muodostuneista 1. ja 2. palautuskehotuksista ja maksut näyttää muodostuneen asiakkaille oikein. Silloin, kun asiakastyypille maksuksi ei ole määritetty mitään, ei asiakkaalle ole muodostunut maksuriviä ollenkaan.

**Comment by LastuLauriH** [comment]
Ainakin myöhästymismaksujen määrittelyt tallentuvat oikein myös Lastussa.

**Comment by pknuuti** [comment]
Vaaran nextillä toimii myöhästymismaksujen määrittely. Maksut on kokonaisia euroja.

**Comment by pirliis** [comment]
OUTIn nextillä myöhästymismaksujen määrittely asiakastyyppikohtaisesti toimii. Myös palautuskehotusmaksut 1. ja 2. palautuskehotuksille muodostuvat oikein.

**Comment by emta001** [comment]
Todettu toimivaksi, suljen tiketin.
