### ISSUE TITLE
Tietueen Perustiedot-näytöllä niteiden haku ei valmistu

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-24.05#90]
### Mikä vikana?

Tietueen Perustiedot-näytöllä niteiden haku ei valmistu vaan jää Käsitellä-tilaan

![kuva](https://github.com/KohaSuomi/Koha-24.05/assets/99952449/9f76c318-6fbd-4010-81c0-3d06c8c9a257)

**Comment by emta001** [comment]
Tässä on nyt useampi bugi päällekkäin. Jostain syystä Hellessä API-kutsu ei palauta _string-objektissa item_type_id:tä, mutta Siilissä se palautetaan. Toinen ongelma on noItemTypeImages-asetus, jos se on pois päältä selaimeen konsoliin tulee virhe "item_type_description not defined". Tähän löytyi korjaus yhteisöstä ja se on viety nexteille. 

Ekan ongelman voi siis kiertää laittamalla noItemTypeImages-asetuksen pois päältä. Yritetään vielä selvitellä tuota häröilevää API-kutsua.

**Comment by Kati-Helle** [comment]
Kiitos Emmi,  noItemTypeImages-asetuksen muutos Näytä -> Älä näytä auttoi. Asetuksen ei tulisikaan olla Näytä-asennossa kuten ei ole tuotannossakaan.

**Comment by emta001** [comment]
Selvisi tuo alkuperäinen ongelma. Uuteen versioon on tehty muutos, jossa tietueen niteet haetaan API:n kautta. Tällöin niteen nidetyypin kuvausta kutsutaan _string-objektista, jonka sisältö generoidaan perustuen MARC-kuvailupohjien sisältöön. Jos kuvailupohjassa _ei ole_ käytetty 952y-kentässä auktorisoitua arvoa itemtypes, nidetyypin kuvausta ei pystytä lisämään _string-objektiin ja selaimen lokille tulee herja "row._string.item_type_id is undefined". Tämä ei sinäänsä olisi ongelma, ellei meillä olisi joissakin kimpoissa kuvailupohjissa käytössä nidetyypin generointiin tarkoitettu plugari, joka estää auktorisoidun arvon käytön pohjassa.

Purkkaratkaisuna tässä voisi käyttää noItemTypeImages-asetuksen laittamista pois päältä. Mutta tällöin niteen nidetyyppiä ei enää näy 24.05-versiossa, joten tämä tuskin on mitenkään toivottu ratkaisu. Toinen vaihtoehto on yrittää jotenkin kiertää tuo API:n luoma rajoitus. Muutos pitäisi sitten viedä myös yhteisöön ja kyetä perustelemaan sinne, että ei voi olettaa kaikkien käyttävän Kohaa samalla tavalla ja API:n toiminnallisuutta ei voi sitoa tällaiseen ratkaisuun. Kolmas vaihtoehto on luopua nidetyypin generoinnista. Voi tähänä jokin muukin ratkaisu olla, mutta nämä tuli tälleen lonkalta mieleen.

**Comment by MikkoLiimatainen** [comment]
Vaskissa löytyi samanlainen jumi konsolin virheilmoituksella `Uncaught TypeError: row.transfer._strings.from_library_ is undefined`
Virhe on viestin mukaan detail.pl:6984:88 kohdassa ja minusta näyttää, että tuossa from_library on nyt ylimääräinen _-merkki lopussa, joka aiheuttanee ongelman.

Edit: piti laittaa virheviesti koodiksi, kun muuten GitHub näytti poistavan tuon ylimääräisen _-merkin.

**Comment by emta001** [comment]
> Vaskissa löytyi samanlainen jumi konsolin virheilmoituksella `Uncaught TypeError: row.transfer._strings.from_library_ is undefined` Virhe on viestin mukaan detail.pl:6984:88 kohdassa ja minusta näyttää, että tuossa from_library on nyt ylimääräinen _-merkki lopussa, joka aiheuttanee ongelman.
> 
> Edit: piti laittaa virheviesti koodiksi, kun muuten GitHub näytti poistavan tuon ylimääräisen _-merkin.

Ilmeisesti asetuksen päälle laittaminen heittääkin sitten uutta herjaa.

**Comment by emta001** [comment]
> > Vaskissa löytyi samanlainen jumi konsolin virheilmoituksella `Uncaught TypeError: row.transfer._strings.from_library_ is undefined` Virhe on viestin mukaan detail.pl:6984:88 kohdassa ja minusta näyttää, että tuossa from_library on nyt ylimääräinen _-merkki lopussa, joka aiheuttanee ongelman.
> > Edit: piti laittaa virheviesti koodiksi, kun muuten GitHub näytti poistavan tuon ylimääräisen _-merkin.
> 
> Ilmeisesti asetuksen päälle laittaminen heittääkin sitten uutta herjaa.

Nääh, ei ollut uusi herja :smile: Vaskissa on varmaankin kuvailupohjassa 952$y-kentässä authorised value arvo tyhjänä. Siksi sinne tulee tuota.

**Comment by emta001** [comment]
Vein nexteille tähän liittyen vielä korjauksen, jolla noItemTypeImages-asetuksen laittaminen pois päältä ei piilota nidetyyppi-saraketta kokonaan. Tämä tarkoittaa nyt kuitenkin sitä, että nidetyypin generointiin tarkoitettu value builder on laitettava pois käytöstä ja MARC-kuvailupohjassa on sen sijaan käytettävä auktorisoitua arvoa itemtypes.

Eli testailkaa näin:
1. Ota itemtype.pl value builder pois MARC-kuvailupohjan kentästä 952$y ja laita kenttään käyttöön auktorisoitu arvo itemtypes.
2. Laita pois päältä asetus noItemTypeImages.
3. Mene jonkin tietueetn Perustiedot-näytölle.
4. Tarkista, että nidetaulukossa näkyy sarake nidetyyppi ja siinä ei ole kuvaa mukana.

**Comment by Kati-Helle** [comment]
Helle-nextissä testasin Kirja-kuvailupohjaa käyttävällä tietueella biblionumber=1629244. 

Kun noItemTypeImages-asetus on näin
![kuva](https://github.com/user-attachments/assets/62a663ec-3be3-46dc-b5e4-b3adbb474e5b)

Nidetyyppi-saraketta ei ole
![kuva](https://github.com/user-attachments/assets/c055ce69-a3ef-4d36-9f64-8b90fcb725cb)

Kun noItemTypeImages-asetus on näin
![kuva](https://github.com/user-attachments/assets/3a667ce4-24a5-4a63-8392-80e24ef4a66d)

Nidetyyppi-sarake on ja sarakkeessa nidetyypin arvo ilman kuvaketta
![kuva](https://github.com/user-attachments/assets/195866df-4e6e-4652-b772-54323ee2ab25)

**Comment by emta001** [comment]
Nyt pitäs toimia oikein. Asiaahan auttoi se, että oikeasti toinkin sen korjauksen paikalleen enkä vaan kuvittellut tehneeni niin :smile:

**Comment by Kati-Helle** [comment]
Jep, nyt Emmi toimii Helle-nextissä kuvailemaasi tapaan.

kun noItemTypeImages-asetus näin
![kuva](https://github.com/user-attachments/assets/2db5bdc7-4141-44ba-865c-e697405cfbee)

niin Nidetyyppi-sarake näkyy ja sarakkeessa nidetyypin arvo ilman kuvaketta
![kuva](https://github.com/user-attachments/assets/1a1cc8c3-4594-464e-b18c-89d95d77a9f2)

**Comment by MikkoLiimatainen** [comment]
> Vein nexteille tähän liittyen vielä korjauksen, jolla noItemTypeImages-asetuksen laittaminen pois päältä ei piilota nidetyyppi-saraketta kokonaan. Tämä tarkoittaa nyt kuitenkin sitä, että nidetyypin generointiin tarkoitettu value builder on laitettava pois käytöstä ja MARC-kuvailupohjassa on sen sijaan käytettävä auktorisoitua arvoa itemtypes.
> 
> Eli testailkaa näin:
> 
> 1. Ota itemtype.pl value builder pois MARC-kuvailupohjan kentästä 952$y ja laita kenttään käyttöön auktorisoitu arvo itemtypes.
> 2. Laita pois päältä asetus noItemTypeImages.
> 3. Mene jonkin tietueetn Perustiedot-näytölle.
> 4. Tarkista, että nidetaulukossa näkyy sarake nidetyyppi ja siinä ei ole kuvaa mukana.

Mielestäni tein kaiken tämän testiohjeen mukaan ja silti tietueessa https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4298398 nidelistan lataaminen jää jumiin.

1. Otin Kirja kuvailupohjasta pois valuebuilderin ja laitoin käyttöön auktorisoidun arvon itemtypes.
2. Tarkistin, ettei asetus noItemTypeImages ole päällä.
3. Menin tietueen https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4298398 perustiedot näytölle.
4. Valitsin Turku, Pääkirjasto kokoelmat välilehdellä näytettäväksi kaikki niteet.
5. Listan lataaminen ei valmistu ja konsolissa on sama virheilmoitus kuin aiemminkin.

Tosin nyt en pääse samassa tietueessa myöskään niteet näytölle, vaan Koha jää siinäkin lataamaan. Onkohan tässä kyseessä eri ongelma, joka ilmeni vain samalla tavalla?

Ajattelin tuon virheilmoituksen perusteella, ettei jonkin kuljetettavan niteen tiedon lataaminen onnistu. Minusta tuo vaikuttaisi olevan ongelma sellaisen kuljetuksen kanssa, jossa on daterequested, mutta ei datesent-arvoa. Eli kuljetus on pyydetty, mutta ei lähetetty. Silloin nähdäkseni listaan ladataan teksti eri tavalla ja siinä rivissä on ylimääräinen _-merkki lähettävän kirjaston kohdalla
```
row.transfer._strings.from_library_.str
```
Kuljetuksessa, joka on oikeasti lähetetty sama kohta on ilman ylimääräistä _-merkkiä 
```
row.transfer._strings.from_library.str
```

**Comment by emta001** [comment]
> > Vein nexteille tähän liittyen vielä korjauksen, jolla noItemTypeImages-asetuksen laittaminen pois päältä ei piilota nidetyyppi-saraketta kokonaan. Tämä tarkoittaa nyt kuitenkin sitä, että nidetyypin generointiin tarkoitettu value builder on laitettava pois käytöstä ja MARC-kuvailupohjassa on sen sijaan käytettävä auktorisoitua arvoa itemtypes.
> > Eli testailkaa näin:
> > 
> > 1. Ota itemtype.pl value builder pois MARC-kuvailupohjan kentästä 952$y ja laita kenttään käyttöön auktorisoitu arvo itemtypes.
> > 2. Laita pois päältä asetus noItemTypeImages.
> > 3. Mene jonkin tietueetn Perustiedot-näytölle.
> > 4. Tarkista, että nidetaulukossa näkyy sarake nidetyyppi ja siinä ei ole kuvaa mukana.
> 
> Mielestäni tein kaiken tämän testiohjeen mukaan ja silti tietueessa https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4298398 nidelistan lataaminen jää jumiin.
> 
>     1. Otin Kirja kuvailupohjasta pois valuebuilderin ja laitoin käyttöön auktorisoidun arvon itemtypes.
> 
>     2. Tarkistin, ettei asetus noItemTypeImages ole päällä.
> 
>     3. Menin tietueen https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4298398 perustiedot näytölle.
> 
>     4. Valitsin Turku, Pääkirjasto kokoelmat välilehdellä näytettäväksi kaikki niteet.
> 
>     5. Listan lataaminen ei valmistu ja konsolissa on sama virheilmoitus kuin aiemminkin.
> 
> 
> Tosin nyt en pääse samassa tietueessa myöskään niteet näytölle, vaan Koha jää siinäkin lataamaan. Onkohan tässä kyseessä eri ongelma, joka ilmeni vain samalla tavalla?
> 
> Ajattelin tuon virheilmoituksen perusteella, ettei jonkin kuljetettavan niteen tiedon lataaminen onnistu. Minusta tuo vaikuttaisi olevan ongelma sellaisen kuljetuksen kanssa, jossa on daterequested, mutta ei datesent-arvoa. Eli kuljetus on pyydetty, mutta ei lähetetty. Silloin nähdäkseni listaan ladataan teksti eri tavalla ja siinä rivissä on ylimääräinen _-merkki lähettävän kirjaston kohdalla
> 
> ```
> row.transfer._strings.from_library_.str
> ```
> 
> Kuljetuksessa, joka on oikeasti lähetetty sama kohta on ilman ylimääräistä _-merkkiä
> 
> ```
> row.transfer._strings.from_library.str
> ```

Outo, kun meen tuohon tietueseen niin nidelista kyllä latautuu ilman herjoja. Mutta en miekään pääse Niteet-näytölle. Tällä [tietueella](https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4311760&searchid=scs_1721384563986) sekin aukeaa. Pitää hieman tutkia onko tässä kyseessä uusi bugi vai mikä tuossa oikein mättää.

**Comment by emta001** [comment]
Sanoisin, että tää on varmaankin uusi suorituskyky bugi. Kokeilin vielä tämmöstä [tietuetta](https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4177619) jossa on 99 nidettä ja sekään ei aukea. Tai sitten Kohalla on jotain lastenkirjoja vastaan.

**Comment by emta001** [comment]
Testailtiin tuota Niteet-näytön ongelmaa. Siellä varmaan tehdään nyt jokin haku, joka kestää tiettyjen tietueiden kanssa pitkään. Kyllä noissa aukeamisissa kestää testeillä ja tuotannossakin jonkin aikaa, mutta ne sentään valmistuu. Teetko @MikkoLiimatainen tosiaan tästä tiketin, selvitellään asiaa lisää siinä.

**Comment by MikkoLiimatainen** [comment]
> Testailtiin tuota Niteet-näytön ongelmaa. Siellä varmaan tehdään nyt jokin haku, joka kestää tiettyjen tietueiden kanssa pitkään. Kyllä noissa aukeamisissa kestää testeillä ja tuotannossakin jonkin aikaa, mutta ne sentään valmistuu. Teetko @MikkoLiimatainen tosiaan tästä tiketin, selvitellään asiaa lisää siinä.

Tein tiketin tuosta perusnäytön kuljetustilaisten ongelmasta, kun siihen löytyi Bugzillasta korjauskin: https://github.com/KohaSuomi/Koha-24.05/issues/100

Tein niteet-sivun ongelmasta oman tikettinsä, kun se ei näytä liittyvän tuohonkaan ongelmaan: https://github.com/KohaSuomi/Koha-24.05/issues/101

**Comment by emta001** [comment]
Sanoisin, että tämän tiketin alkuperäinen ongelma on korjattu. Uusista ongelmista on luotu tiketit tai ne käsitellään toisessa tiketissä. Tämän voinee sulkea.
