### ISSUE TITLE
Lisää huollettava -monivalintanappi ei toimi

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha-24.05#91]
### Mikä vikana?

Kohan osoiterivillä asiakkaan lisäys operaation nimitys on muuttunut, mikä vaikuttaa monivalintanapin käyttämiin lisäyslinkkeihin. Ennen osoiterivillä luki asiakasta lisätessä op=add, mutta versiossa 24.05 tämä on muuttunut muotoon op=add_form. Lisää huollettava -monivalintanapin skripti tulee siis tältä osin päivittää, mikäli skripti on kimpassa käytössä.

Tässä versiosta 23.11 versioon 24.05 korjattu skripti. Muutoksen voi tehdä kimpan omaan versioon muuttamalla lapsiLinkki, omatoimilapsiLinkki ja muuHuollettavaLinkki -linkkien op=add kohta muotoon op=add_form.
```
/// ALKU ///
/* Lisää huollettava monivalintanappi. Asiakastyyppien tunnisteet pitää tarkistaa ja muuttaa tarvittaessa kimpassa käytettäviin. */
$(document).ready(function() {
  if ( !!document.getElementById("addchild") ){
    var editpatron_url = new URLSearchParams(document.getElementById("editpatron").href);
    var asiakasnumero = editpatron_url.get('borrowernumber');
    var kayttokieli = 'Suomi';

    var lapsiLinkki = "/cgi-bin/koha/members/memberentry.pl?op=add_form&categorycode=LAPSI&guarantor_id=" + asiakasnumero;
    var omatoimilapsiLinkki = "/cgi-bin/koha/members/memberentry.pl?op=add_form&categorycode=LAOMATOIMI&guarantor_id=" + asiakasnumero;
    var muuHuollettavaLinkki = "/cgi-bin/koha/members/memberentry.pl?op=add_form&categorycode=MUUHUOL&guarantor_id=" + asiakasnumero;
    var lisaaHuollettavaNappi = "<div class='btn-group'><button class='btn btn-default dropdown-toggle' data-toggle='dropdown'><i class='fa fa-plus'></i><span id='huollettavaKaannos'> Lisää huollettava.</span> <span class='caret'></span></button><ul class='dropdown-menu'><li><a href=" + lapsiLinkki + ">Lapsiasiakas, omatoimi kielletty</a></li><li><a href=" + omatoimilapsiLinkki + ">Lapsiasiakas, omatoimi sallittu</a></li><li><a href=" + muuHuollettavaLinkki + ">Huollettava, muu kuin lapsi</a></li></ul></div>";

    $( "#editpatron" ).after( lisaaHuollettavaNappi );
    $('#addchild').css('display','none');

    kayttokieli = document.getElementsByClassName('currentlanguage')[0].innerHTML;
    if (kayttokieli == 'Suomi') {
      $("#huollettavaKaannos").text(" Lisää huollettava");
    }
    else if (kayttokieli == 'Svenska') {
      $("#huollettavaKaannos").text(" Lägg till barn");
    }
    else if (kayttokieli == 'English') {
      $("#huollettavaKaannos").text(" Add child");
    }
  }    
});
/// LOPPU ///
```

**Comment by Kati-Helle** [comment]
Tein Helle-nextin rimpsuun Mikon mainitsemat muutostarpeet. 
Lisää huollettava -monivalintanappi on nyt samojen asiakastyyppien Tiedot-välilehdellä kuin tuotannossa. Asiakastiedon tallennus onnistui monivalintanappia käyttäen.

**Comment by atarnus** [comment]
Testasin Outi-nextillä ja uusi rimpsu toimii. (Vanhalla rimpsulla menee tosiaan väärälle sivulle, jossa vanhemman osoitetiedot eivät kopioidu ja varaustunnuksen luonti ei onnistu.)

Onnistuin kuitenkin törmäämään ongelmiin, jotka todennäköisesti eivät liity tähän rimpsuun, vaan tuohon takaajan suhteen valintaan. Jos ei valitse takaajan suhdetta, järjestelmä antaa tallentaa tiedot, mutta tulee error, ja uusi asiakas tallentuu ilman takaajatietoa. Lisää ongelmia tulee sitten jos järjestelmä ehdottaa duplikaattia, niin takaajatieto putoaa kokonaan. Ja jos siinä valitsee 'On tuplatieto. Muokkaa olemassa olevaa asiakasta', niin tulee tällainen virhe:

![image](https://github.com/user-attachments/assets/2659b434-e9bf-4b99-b75f-c40721eede82)

Testillä näitä virheitä ei esiintynyt (paitsi takaajatiedon tippuminen mahd. tuplatapauksessa).

Etsiskelen oliko näistä jo tikettiä tai useampaa.

**Comment by atarnus** [comment]
Yo. virheilmoitus liittyy näköjään ilmoitukseen mahdollisesta duplikaatista, ja tapahtuu riippumatta takaajasuhteista. Tästä tein tiketin: https://github.com/KohaSuomi/Koha-24.05/issues/109

Kun etenee tallentamaan ilman valittua takaajasuhdetta, ja sieltä tulee internal server error: https://github.com/KohaSuomi/Koha-24.05/issues/108

Takaajatiedon tipahtaminen: https://github.com/KohaSuomi/Koha/issues/610

Tämä rimpsu siis ok.

**Comment by LeenaKinnunen** [comment]
Lisäsin Lapille op=add_form-tiedot Mikon ohjeen mukaan, ja osoitetieto kopioitui. Eli toimii.

**Comment by lmstrand** [comment]
Sovimme kehittäjien kanssa, että tätä ei tehdä pluginiksi.
