### ISSUE TITLE
Varaustunnuksen generointi ei toimi

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha-24.05#92]
### Mikä vikana?

Tässä koodissa on sama ongelma muuttuneiden op-arvojen kanssa kuin tiketissä: https://github.com/KohaSuomi/Koha-24.05/issues/91. 

op=add on muuttunut muotoon op=add_form
op=modify on muuttunut muotoon op=edit_form
op=duplicate on säilynyt ennallaan

Korjattu versio 23.11 version pohjalta:
```
//ALKU
// Varaustunnuksen automaattinen generointi. Kentän jälkeen lisätty kolme pistettä, josta muodostus tapahtuu. Uudelle asiakkaalle varaustunnus muodostuu automaattisesti kolmea pistettä painamatta.
// Tarkista oman tietokannan oikea payhdessätron_attr-arvo esim. selaimen Tarkista/Inspect element -toiminnolla.
$(document).ready(function(){
    if (window.location.pathname == '/cgi-bin/koha/members/memberentry.pl' && window.location.search.includes("?op=add_form&") || window.location.search.includes("?op=duplicate&")) {
      var unixepoch = Math.round( (new Date()).getTime() / 10 ).toString();
      var epochdashed = unixepoch.replace( /(....)/g, '$1-').replace(/-$/,'' );
      $('textarea#patron_attr_2').val(epochdashed);
      
	  $( '<a class="buttonDot" href="#" id="generate_holdid" title="Luo varaustunnus" style="vertical-align: top;"> ...</a>' ).insertAfter( "#patron_attr_2");
	  $("#generate_holdid").click(function(event) {
        event.preventDefault();
          unixepoch = Math.round( (new Date()).getTime() / 10 ).toString();
          epochdashed = unixepoch.replace( /(....)/g, '$1-').replace(/-$/,'' );
          $('textarea#patron_attr_2').val(epochdashed);
		  $("#patron_attr_2").trigger('blur');
      });
    }

      if (window.location.pathname == '/cgi-bin/koha/members/memberentry.pl' && window.location.search.includes("?op=edit_form")) {
	  $( '<a class="buttonDot" href="#" id="generate_holdid" title="Luo varaustunnus" style="vertical-align: top;"> ...</a>' ).insertAfter( "#patron_attr_2");
	  $("#generate_holdid").click(function(event) {
        event.preventDefault();
          unixepoch = Math.round( (new Date()).getTime() / 10 ).toString();
          epochdashed = unixepoch.replace( /(....)/g, '$1-').replace(/-$/,'' );
          $('textarea#patron_attr_2').val(epochdashed);
		  $("#patron_attr_2").trigger('blur');
      });
    }
});
//LOPPU
```

**Comment by lmstrand** [comment]
Kiitos Mikko, siirretään tämä pluginiksi.

**Comment by lmstrand** [comment]
Lisätty HOLDID-asiakasmääreen siirtorimpsun kanssa pluginiin IntranetUserJS: HoldID (koha-plugin-intranetjs-holdid).

**Comment by Kati-Helle** [comment]
Jo tallennetun asiakastiedon muokkauksesta puuttuu Varaustunnus-kentän vierestä varaustunnuksen 'muodostamispisteet'
![kuva](https://github.com/KohaSuomi/Koha-24.05/assets/99952449/8ff9b6b1-6626-4b56-9206-c6d011998530)

Uutta asiakastietoa lisätessä varaustunnus-arvo muodostuu automaattisesti Varaustunnus-kenttään. Kentän vieressä olevista 'pisteistä' arvo muuttuu automaattisesti
![kuva](https://github.com/KohaSuomi/Koha-24.05/assets/99952449/93f423a9-952d-4b16-83f6-be84abc4bb3b)

**Comment by lmstrand** [comment]
Onko varaustunnuksen generointimahdollisuus kolmesta pisteestä tarpeen asiakkaan muokkausnäkymässä?

**Comment by MikkoLiimatainen** [comment]
Eiköhän se varmuuden vuoksi ole hyvä siellä olla. Toki muokatessa asiakkaan luulisi valitsevan jonkin helpomman tunnuksen. Ehkä asiakas voi haluta eroon valitsemastaan tunnuksesta, eikä välitä keksiä uutta.

**Comment by lmstrand** [comment]
Lisätty tiketin https://github.com/KohaSuomi/koha-plugin-intranetjs-holdid/issues/1 pluginiin kolmesta pisteestä generointi myös asiakkaan muokkaus-näkymään. Viety nexteille.

> Eiköhän se varmuuden vuoksi ole hyvä siellä olla. Toki muokatessa asiakkaan luulisi valitsevan jonkin helpomman tunnuksen. Ehkä asiakas voi haluta eroon valitsemastaan tunnuksesta, eikä välitä keksiä uutta.

**Comment by Kati-Helle** [comment]
Helle-nextin asiakkaan muokkauksessa varaustunnuksen generointi toimii Varaustunnus-kentän vieressä olevista kolmesta pisteestä.

**Comment by MikkoLiimatainen** [comment]
Vaski-nextillä generointi toimii asiakasta lisätessä, muokatessa ja kopioitaessa. Varaustunnusasiaa voinee tarvittaessa jatkaa tuossa plugarin tiketissä, joten suljen tämän.
