### ISSUE TITLE
Osa niteistä ei valittavissa ja muokattavissa tietueen Perustiedot-näytöllä

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-24.05#95]
### Mikä vikana?

Tietueen Perustiedot-näytöllä puuttuu osalta niteistä valintaruutu sekä Muokkaa-painike eikä näille ainakaan heti tunnu löytyvän mitään yhteistä nimittäjää. Esimerkkinä tarkasteluun voi käyttää vaikkapa [tätä vaski-nextin tietuetta](https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4279901). Kuvakaappauksesta näkyy, että esimerkiksi niteen tila ei ole tapauksissa yhteinen tekijä, sillä esim. toinen lainattu-tilainen nide on muokattavissa ja toinen ei. En huomaa myöskään, että esimerkiksi kirjautuneen käyttäjän kirjaston vaihtaminen vaikuttaisi asiaan vaan samat niteet näyttäisivät äkkiseltään näkyvän ei-muokattavina.

### Jotain muuta?

![kuva](https://github.com/KohaSuomi/Koha-24.05/assets/44638512/087877ad-0812-47a3-833e-b74b0371bba0)

**Comment by emta001** [comment]
Tällä on nyt jotain tekemistä niteen sijaintikirjaston kanssa. Vaihdoin niteelle NVask20230500603 kannasta suoraan sijaintikirjastoksi Turun pääkirjaston, jonka jälkeen nide oli valittavissa ja muokattavissa.

**Comment by ajrajala** [comment]
Sellainen lisähuomio myös, että Niteet-välilehden kautta pääsee muokkaamaan niitäkin niteitä joilta Perustiedot-näytöltä puuttuu Muokkaa-nappi.

**Comment by emta001** [comment]
Jännäähän tässä on myös se, että kaikkien niteiden muokkaamisen pitäisi olla mahdollista superlibrarian käyttäjille. Mutta jokin tässä näyttäisi estävän senkin. 

>Sellainen lisähuomio myös, että Niteet-välilehden kautta pääsee muokkaamaan niitäkin niteitä joilta Perustiedot-näytöltä puuttuu Muokkaa-nappi.

Tämäkin on aika epäloogista. Miksi estää muokkaus yhdessä paikassa ja sallia sitten toisessa.

**Comment by emta001** [comment]
Tätä on tosiaan menty muuttamaan niin, että muokkaus perustuu siihen voiko käyttäjä muokata tietyssä kirjastossa sijaitsevaa nidettä. Aiemmin tämä perustui niteen kotikirjastoon.

Sitä en tiedä miksei tuo toimi myöskään superlibrarian-oikilla, mutta korjataan nyt ainakin tämä sijainti-kotikirjasto ensin. Tästä voisi tehdä myös tiketin yhteisöön, minusta tuo on selkeä virhe siellä päässä.

**Comment by ajrajala** [comment]
Eikö järjestelmäasetuksen IndependentBranches=No pitäisi kuitenkin tehdä se, että käyttäjä voi muokata minkä tahansa kirjaston niteitä?

**Comment by emta001** [comment]
> Eikö järjestelmäasetuksen IndependentBranches=No pitäisi kuitenkin tehdä se, että käyttäjä voi muokata minkä tahansa kirjaston niteitä?

Kyllähän sen pitäisi tehdä, mutta ei sekään näköjään toimi ihan kuten pitäisi. Logiikka tässä näyttäisi tällä hetkellä toimivan seuraavasti:

1. Tutkitaan löytyneiden niteiden kotikirjastot ja tarkistetaan metodilla can_edit_items_from onko käyttäjällä oikeutta muokata nidettä.
2. Lähetetään näistä kirjastoista hash käytettäväksi API:ssa (nidelistaus tulee uudessa versiossa sieltä). Se näyttää esim. tälle:
```
$VAR1 = {
          'SII_VU' => 1,
          'SII_PK' => 1
};
```
3. Tätä hashia vasten tutkitaan, että onko niteen sijaintikirjasto listalla. Jos ei ole, muokkaus ei onnistu.

Töppäys tulee nimenomaan tuon hashin tutkimisessa. Mulla on siis tietueessa niteet, joiden kotikirjastot on SII_VU ja SII_PK. Niistä tehdään tuo hash. Sitten yhden niteen sijainti onkin kirjastossa SII_AU, jota ei löydy tuosta hashista. Koodissa sitten tietysti katsotaan, että eihän tätä SII_AU:ta täällä listalla ole, joten ei tällä käyttäjällä ole oikeutta muokata tätä.

Lisämausteena, tuon hashin pitäisi muodostua kolmen ehdon perusteella:
1. Onko käyttäjä superlibrarian. Jos on, palauta 1.
2. Onko asetus IndependentBranches päällä. Jos on, tutkitaan vastaako käyttäjän kirjasto niteen kotikirjastoa. Jos ei ole, mennään seuraavaan kohtaan.
3. Tutkitaan mitä metodi "can_see_things_from" palauttaa (käytännössä siis onko käyttäjällä oikeus "edit_any_item" päällä).

Tuon IndependentBranches-asetuksen käytön logiikka tässä kohtaa on hieman kyseenalainen, mutta se on varmaan ihan oma buginsa.

**Comment by emta001** [comment]
Yhteisöön tehty tiketti ja ehdotus korjauksesta. Katellaan mimmosta palautetta tulee ja tuodaan sitten meillekin.

**Comment by emta001** [comment]
Korjaus viety nexteille.

**Comment by ajrajala** [comment]
Vaski-nextillä kaikki niteet nyt valittavissa tietueen Perustiedot-näytöllä, testattu sekä ns. normivirkailijatunnuksella sekä superlibrarian-tunnuksella.

**Comment by pknuuti** [comment]
Vaaran nextillä testattu ja toimii kuten Vaskilla.

**Comment by atarnus** [comment]
Minulla ei ollut tiedossa tietueita, joissa olisi näkynyt näitä virheellisiä rivejä, että voisin varmistaa jonkin muuttuneen. Mutta katselin Outi-nextillä läpi lukuisia teoksia, joissa oli paljon niteitä, eikä tullut vastaan yhtään, jota ei olisi voinut muokata. Katsoin muutaman myös "tavallisella" virkailijatunnuksella.

**Comment by emta001** [comment]
Toimii testien perusteella, suljen tiketin.
