### ISSUE TITLE
Nidehaun tulosnäkymän suodatus muuttunut, edellyttää koodien käyttöä

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-24.05#96]
### Mikä vikana?

Nidehaun tulosnäkymän suodatukset ovat muuttuneet. Versiossa 23.11 Kokoelma, Kotikirjasto, Nykyinen kirjasto, Hyllypaikka, Nidetyyppi ja nidetiloihin liittyvien sarakkeiden suodatus tapahtui pudotusvalikon kautta. Nextillä pudotusvalikot on korvattu kentillä, joihin voi kirjoittaa, mutta näihin liittyy sellainen ongelma että suodatuksessa on käytettävä kirjastotunnusta/auktorisoidun arvon koodia eli kuvaustekstillä ei pysty suodattamaan. Käyttäjät eivät kaikkia näitä tunne joten suodatus tällaisenaan ei palvele tavallista käyttäjää.

**Comment by ajrajala** [comment]
Lisähuomiona vielä, että suodatuksessa ei riitä että kirjastotunnuksen/koodin alku on kirjoitettuna suodatuskenttään (esim. TU kotikirjasto-kenttään) vaan tunnus/koodi on kirjoitettava kokonaisuudessaan (esim. TUNU) jotta suodatushaku löytää mitään.

**Comment by emta001** [comment]
Tähän taisikin löytyä korjaus yhteisöstä, bug [37248](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37249). Kokeilen auttaako tuo ja tuon sen sitten nexteille testattavaksi.

**Comment by emta001** [comment]
Ilmeisesti tuo bugi korjaa vain nidenumerolla rajauksen. Ekaa kommenttia lukuunottamatta muista filttereistä ei sitten olekaan puhetta.

**Comment by emta001** [comment]
Löytyi toinen tiketti (johon Anni näköjään ootkin kommentoinut), [37238](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37238). Tuo vaikuttaisi olevan tähän ongelmaan liittyvämpi, mutta se on Failed QA tilassa.

**Comment by ajrajala** [comment]
> Tähän taisikin löytyä korjaus yhteisöstä, bug [37248](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37249). Kokeilen auttaako tuo ja tuon sen sitten nexteille testattavaksi.

Vähän hassusti tuosta tosiaan unohtunut nuo muut suodatusongelmat ekan kommentin jälkeen. Pitäisikö yhteisöön tehdä uusi tiketti näistä jäljellä olevista ongelmista vaikka suodatusongelma tuossa sarakeasetusten lisäämistä koskevassa tiketissä 37238 mainitaankin? Vai miten tämän kanssa on fiksua edetä? 🤔

**Comment by emta001** [comment]
> > Tähän taisikin löytyä korjaus yhteisöstä, bug [37248](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37249). Kokeilen auttaako tuo ja tuon sen sitten nexteille testattavaksi.
> 
> Vähän hassusti tuosta tosiaan unohtunut nuo muut suodatusongelmat ekan kommentin jälkeen. Pitäisikö yhteisöön tehdä uusi tiketti näistä jäljellä olevista ongelmista vaikka suodatusongelma tuossa sarakeasetusten lisäämistä koskevassa tiketissä 37238 mainitaankin? Vai miten tämän kanssa on fiksua edetä? 🤔

Paha mennä sanomaan. Toisaalta Lucas on kommentoinut tuohon 37248 tikettiin näistä ongelmista, mutten tiedä hoksaako kukaan niihin tarttua. Ja onhan ne ihan eri ongelmia kuin mitä tuo tiketti käsittelee. Niin voisi olla ihan aiheellista tehdä uusi tiketti, sulkevat sen sitten jos katsovat tarpeelliseksi.

Teen tuosta nidenumerolla suodattamisesta oman tiketin meille ja tuon korjauksen nexteille. Saadaanpahan edes jotakin tuosta suodatuksesta toimimaan :smile:

**Comment by ajrajala** [comment]
Nyt on yhteisöön tehty tiketti [37369](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37369) nimenomaan koskien koodien käyttöä filttereissä.

**Comment by emta001** [comment]
Laitoin tämä Odottaa-tilaan, odotellaan tulisiko yhtesöstä tähän ratkaisua.

**Comment by emta001** [comment]
Kun vertaa testiä ja nextiä keskenään, testillä esim. nidetyypillä suodattaminen on toiminut aiemmin valikon kautta. Nextillä tuo ominaisuus on siis jostain syystä rikki, vaikka siihen ei ole nähdäkseni tehty minkäänlaista muutosta. Jokin haun siirtymisessä API:n kautta tehtäväksi luultavasti rikkoi sen, mutta sen kun arvaisi että mikä.

**Comment by AnneliO** [comment]
Testillä kaikki ns. auktorisoidut arvot suodatetaan alasvetovalikolla. Nextillä niissäkin on ns. vapaasanahakukenttä. Todennäköisesti testilläkin suodatus tehdään tunnuksella, mutta käyttäjä ei vain näe sitä?

**Comment by emta001** [comment]
> Testillä kaikki ns. auktorisoidut arvot suodatetaan alasvetovalikolla. Nextillä niissäkin on ns. vapaasanahakukenttä. Todennäköisesti testilläkin suodatus tehdään tunnuksella, mutta käyttäjä ei vain näe sitä?

Jeppis, näin se on toiminut. Ilmeisesti koodi vastaanottaa kuvauksen ja kääntää sen pellin alla tunnukseksi, jolla se haku tehdään. Hirveen simppeli homma, en ymmärrä miten se on voinut mennä rikki näin pahasti, kun ei tuohon hakukenttään tule edes alasvetovalikkoa :sweat_smile:

**Comment by emta001** [comment]
Tuossa on muutakin kummaa verrattuna nykyiseen tuotantoon. Ensimmäisessä sarakkeessa ei pitäisi olla minkäänlaista suodatusta, mutta sitä klikatessa siihen ilmestyy hakukenttä.

![image](https://github.com/user-attachments/assets/ef885582-9c02-4193-8d88-f56e5bb21085)

Ja tätä kun vielä testailin niin löytyihän se ongelma. Eli tuon taulukon asetuksissa on käytetty näissä filttereissä asetusta `column` ei `aoColumns`, kuten pitäisi. Siksi nuo toimii hassusti.

**Comment by emta001** [comment]
Ratkaisu tikettiin meni yhteisössä läpi, tuodaan meillekin.

**Comment by emta001** [comment]
Viety nexteille testattavaksi.

**Comment by ajrajala** [comment]
Testattu vaski-nextillä Kokoelmakoodi, Kotikirjasto, Nykyinen kirjasto, Hyllypaikka ja Nidetyyppi sekä eri nidetila-valikoita. Näyttäisi suodatus toimivan oikein + suodatuksen saa pois valitsemalla pudotusvalikkoon takaisin sarakkeen otsikon.

(Kokeilin myös uudelleen tulosnäkymän muita suodatuskenttiä, joihin saa kirjoittaa, nekin toimivat edelleen. Samoin toimii sarakkeiden mukainen järjestäminen.)

**Comment by AnneliO** [comment]
Testasin siili-nextillä samoja, mitä Annikin ja tulokset oli samat. Eli toimi sielläkin. :)

**Comment by emta001** [comment]
Toimii siis, suljen tiketin.
