### ISSUE TITLE
Nidehaun tuloksien suodattaminen nidenumerolla ei toimi

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#97]
### Mikä vikana?

Huomattu tiketin #96 yhteydessä, että nidehaun tuloksien suodattaminen nidenumerolla johtaa 500 erroriin. Korjattu yhteisön tiketissä [37249](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37249). 

### Kuinka toistaa ongelma/asia

1. Tee nidehaku.
2. Yritä suodattaa haun tuloksia nidenumerolla.
3. Hetken päästä näytölle ilmestyy pop-up, jossa lukee "Something went wrong when loading the table. 500: Internal Server Error. "

**Comment by emta001** [comment]
Viety nexteille testattavaksi.

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä ja suodatus toimii. Näkymä on sellainen, että en meinannut tajuta koko suodatusta.

**Comment by pknuuti** [comment]
Näkymä nykyisessä tuotannossa:

![Image](https://github.com/user-attachments/assets/b1b25bf4-2546-48cc-9709-604ec3e0a15f)

näkymä nextillä 

![Image](https://github.com/user-attachments/assets/5b438edc-8428-4603-8222-4b527e256c01)

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii Nidehaun hakutuloksen suodattaminen nidenumerolla. Sekä pienimmästä arvosta suurimpaan että suurimmasta pienimpään.

Kentän nimi englanniksi Item number
![kuva](https://github.com/user-attachments/assets/10f15000-797a-4731-8925-237bcfc0dcb5)

**Comment by ajrajala** [comment]
Vaski-nextillä nidenumerolla suodattaminen kunnossa.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
