### ISSUE TITLE
Asiakastyyppi ja nidetyyppi eivät vaihdu laina- ja maksusääntöä muokatessa

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#98]
### Mikä vikana?

Laina- ja maksusääntöä muokatessa asiakastyyppi ja nidetyyppi eivät aina vaihdu kuten pitää jos sääntöä muokkaa. Näin tapahtuu silloin, kun käyttäjä valitsee ensin muokattavaksi yhden säännön ja sitten vaihtaakin muokattavaa sääntöä. 

### Mitä pitäisi tapahtua

Asiakas- ja nidetyyppi sarakkeiden arvojen tulisi vaihtua muokattavan arvon mukaan.

### Kuinka toistaa ongelma/asia

1. Mene laina- ja maksusäännöt sivulle ja valitse sääntö muokattavaksi.
2. Valitse tämän jälkeen muokattavaksi sellainen sääntö, jonka asiakas- ja nidetyyppi arvot poikkeavat edellisestä säännöstä.
=> Asiakas- ja nidetyyppi sarakkeiden arvot eivät välttämättä vaihdu muokattavan säännön mukaisiksi.
3. Valitse jälleen uusi sääntö.
=> Arvot eivät edelleenkään välttämättä vaihdu.

**Comment by ajrajala** [comment]
Testailin vaihtelemalla eri sääntörivien välillä, joissa oli eri valinnat sekä asiakastyypissä että nidetyypissä. Sarakkeiden arvot vaihtuivat joka kerta oikein.

**Comment by pknuuti** [comment]
Sama havainto Vaaran nextillä kuin Vaskissakin, sarakkeiden arvot vaihtuvat oikein.

**Comment by LeenaKinnunen** [comment]
Samoin Lapissa, sarakkeiden arvot vaihtuvat oikein

**Comment by emta001** [comment]
Toimii, suljen tiketin.
