### ISSUE TITLE
Alasvetovalikoiden arvot eivät nollaudu kun laina- ja maksusääntöjen muokkausrivin tyhjentää

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-24.05#99]
### Mikä vikana?

Kun laina- ja maksusääntöjen muokkausrivillä painaa "Tyhjennä"-painiketta, alasvetovalikoiden arvot eivät nollaudu vaan niihin jäävät aiemmin valitut arvot.

### Mitä pitäisi tapahtua

Alasvetovalikoiden tulisi nollautua.

### Kuinka toistaa ongelma/asia

1. Mene laina- ja maksusäännöt sivulle.
2. Valitse joko olemassa oleva sääntö muokattavaksi tai täytä kenttiin uudet arvot ja valitse alasvetovalikoista muu kuin "oletusarvo" (ensimmäinen arvo listalla).
3. Paina "Tyhjennä".
=> Tekstikentät tyhjenevät, mutta alasvetovalikoihin jää aiemmin valitut arvot.

**Comment by ajrajala** [comment]
Testasin sääntörivillä, jolla kaikkiin pudotusvalikkko-kenttiin oli valittu jokin muu kuin oletusarvo. Kun otti rivin muokkaukseen ja  valitsi Tyhjennä, alasvetovalikoihin palautui oletusarvot. Eli korjaus näyttäisi vaski-nextillä toimivan.

**Comment by pknuuti** [comment]
Myös Vaaran nextillä testattu kuten Vaskissa, toimii samalla tavalla oikein.

**Comment by LeenaKinnunen** [comment]
Lapissa toimii myös oikein.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
